// Tao prompt-n3.json: moi muc tu vung N3 -> prompt Qwen-Image (1 cau tieng Anh) + style chung
// Chay: node build-n3.cjs  (doc thang curriculum/n3/*.json, khong sua file du an)
const fs = require("fs");
const path = require("path");
// ---- PATHS: SENSEI_REPO = goc repo (mac dinh 4 cap tren tep nay); ANH_AI_WORK = thu muc lam viec (ghi vao $ANH_AI_WORK/goc) ----
const REPO = process.env.SENSEI_REPO || path.resolve(__dirname, "..", "..", "..", "..");
const WORKD = path.join(process.env.ANH_AI_WORK || path.join(require("os").homedir(), "anh-ai-work"), "goc");
fs.mkdirSync(WORKD, { recursive: true });
const GOC = path.join(REPO, "curriculum", "n3");
const RA = path.join(WORKD, "prompt-n3.json");

const STYLE = "flat minimal vector illustration, soft rounded shapes, warm muted palette of terracotta #c96442, sage green #6b8a5e, muted gold and cream, thin dark ink #1f1d19 outlines, gentle two-to-three tone shading, one clear subject centered with generous empty margin, plain light warm paper background #f0ebe1, friendly simple faces, Japanese everyday-life context, no text, no letters, no numbers, no watermark, square 1:1 composition";
const NEG_BASE = "text, letters, words, numbers, digits, captions, labels, readable signage, kanji, hiragana, katakana, latin alphabet, watermark, logo, signature, photorealistic, 3d render, glossy plastic look, busy cluttered background, comic panel grid, frame border, dark background, harsh shadows, neon colors, blurry, deformed hands, extra fingers, distorted face";

// Tu dien hinh: slug -> [prompt, negative rieng, loai, kho]
const D = {
  "trust": ["A young woman leaning backwards with closed eyes and a calm smile while her friend stands behind her with open arms ready to catch her in a trust fall.", "falling injury, fear", "vocab", 2],
  "misunderstand": ["A man proudly handing a small gift box to a woman who frowns and turns away offended, while the man looks confused with a puzzled sweat drop, showing a misunderstanding between them.", "romance kiss", "canh", 3],
  "mistaken-identity": ["A cheerful man tapping the shoulder of a stranger from behind thinking it is his friend, the stranger turning around surprised and the man freezing in embarrassment.", "fight, violence", "canh", 2],
  "improve-skill": ["A young student painter standing beside three easels in a row whose paintings of the same apple go from clumsy scribble to rough sketch to a beautiful finished apple, showing clear progress.", "text on canvas", "canh", 2],
  "specialty": ["A young researcher in a white lab coat standing proudly in front of a shelf of thick medical books and a human anatomy model, holding a stethoscope as her field of expertise.", "blood, surgery", "nhanvat", 3],
  "knowledgeable": ["An elderly guide confidently pointing at tiny details on a large unfolded map with a magnifying glass while a young tourist listens amazed, showing deep detailed knowledge.", "readable map labels", "canh", 3],
  "bad-at": ["A young man awkwardly flailing in a swimming pool with a panicked sweaty face while others around him swim easily, showing something he is bad at.", "drowning, danger", "vocab", 2],
  "confidence": ["A young woman standing tall with chest out, hands on hips and a bright self-assured smile, a small glow of confidence around her.", "arrogant sneer", "vocab", 2],
  "experience": ["An elderly sushi chef with calm expert hands showing a nervous young apprentice how to slice fish at a wooden counter, a lifetime of experience in his posture.", "raw blood", "canh", 3],
  "personality": ["Three friends sitting on one bench with clearly different personalities: one laughing loudly with arms wide, one shyly reading a book, one grumpy with crossed arms.", "identical faces", "canh", 3],
  "result": ["A student holding up a graded test sheet covered in big red circle marks with a relieved happy face, the teacher smiling beside her.", "readable writing on paper, numbers on paper", "vocab", 2],
  "coincidence": ["Two old friends turning a street corner from opposite sides and bumping into each other by chance, both with wide surprised delighted eyes.", "collision injury", "canh", 2],
  "good-at": ["A proud boy juggling five balls effortlessly with a confident grin while classmates watch in admiration.", "circus clown", "vocab", 2],
  "join": ["A smiling newcomer stepping into a circle of people holding hands at a community dance, the group opening the circle to welcome him in.", "crowd chaos", "canh", 2],
  "agree": ["A group of colleagues around a table all raising their hands and giving thumbs up in agreement with a smiling presenter.", "angry faces", "canh", 2],
  "record": ["A sprinter bursting through the finish-line tape with a stopwatch icon glowing above and a gold trophy waiting, breaking a record.", "numbers on stopwatch, scoreboard digits", "vocab", 2],
  "regret-pity": ["A family standing at a window in raincoats looking sadly at heavy rain pouring on their packed picnic basket, disappointed that the outing is ruined.", "storm damage", "canh", 2],
  "explain": ["A teacher pointing at a simple diagram of arrows and circles on a whiteboard while explaining to two attentive students.", "writing on whiteboard, formulas", "canh", 2],
  "effort": ["A determined student studying late at night at a desk lamp with a headband, sweat drop on the forehead and a tall stack of textbooks, putting in great effort.", "readable book titles", "vocab", 2],
  "mindful": ["A woman in a supermarket pausing thoughtfully to compare a salad and a greasy burger in her hands, consciously choosing the healthy one.", "brand packaging", "vocab", 3],
  "be-careful": ["A waiter walking very carefully on tiptoe while balancing a tray of brimming full teacups, eyes focused on not spilling.", "spilled mess", "vocab", 2],
  "make-a-point-of": ["A man in a business suit deliberately choosing the stairs beside an escalator, climbing with a small determined smile as his daily habit.", "crowded station", "vocab", 3],
  "exercise": ["A young woman jogging happily along a riverside path in sportswear and sneakers.", "", "vocab", 1],
  "eat": ["A young person eating a bowl of rice with chopsticks at a small table, happily taking a bite.", "", "vocab", 1],
  "sleep": ["A person sleeping peacefully on a futon, tucked under a blanket with eyes closed and a small moon outside the window.", "", "vocab", 1],
  "wake-up": ["A person sitting up in bed stretching arms and yawning as morning sunlight streams through the window and an alarm clock rings.", "numbers on clock", "vocab", 1],
  "health": ["A glowing healthy young man with rosy cheeks flexing an arm happily next to a fresh apple and a glass of water.", "bodybuilder, oiled muscles", "vocab", 2],
  "daily-life": ["A cozy apartment scene showing everyday life: a person cooking breakfast, laundry drying by the window, and a cat on a cushion.", "mess", "canh", 3],
  "habit": ["A woman doing her morning stretches by the window next to a wall calendar grid filled entirely with identical check marks, a daily habit.", "numbers on calendar, writing", "vocab", 3],
  "vegetables": ["A woven basket full of fresh vegetables: carrots, a daikon radish, cabbage, tomatoes and green onions.", "", "vocab", 1],
  "body-weight": ["A person standing on a bathroom scale looking down anxiously at the needle dial.", "numbers on scale", "vocab", 1],
  "sick": ["A sick child lying in bed with a flushed face, a thermometer in the mouth and a cold towel on the forehead.", "blood, hospital gore", "vocab", 1],
  "work": ["An office worker typing busily at a desk with a laptop, documents and a cup of coffee.", "readable screen", "vocab", 1],
  "time": ["A large brass hourglass with flowing sand standing beside a round wall clock with hands but no numerals.", "numbers on clock face", "vocab", 1],
  "body": ["A simple friendly full-body figure of a person standing in a relaxed pose with arms slightly out, like a gentle anatomy chart without labels.", "labels, nudity, organs", "vocab", 1],
  "decide": ["A young woman at a fork in a forest path firmly pointing down one path with a decisive expression.", "readable signposts", "vocab", 2],
  "obey-rules": ["A pedestrian patiently waiting at a crosswalk under a red walking-man traffic signal even though the road is empty.", "", "canh", 2],
  "prohibit": ["A red circle-and-slash prohibition sign over a camera icon mounted on a museum wall beside a framed painting.", "any writing on the sign", "vocab", 1],
  "resolve": ["A young man tying a white headband around his forehead with clenched fist and fiery determined eyes.", "", "vocab", 2],
  "graduate": ["A smiling student in a graduation gown and cap holding a rolled diploma tube under blooming cherry blossoms.", "", "vocab", 1],
  "rules": ["A notice board with a row of simple pictogram icons: a crossed-out cigarette, a crossed-out phone, a trash bin and a quiet finger-to-lips symbol, the rules of a place.", "any writing on the board", "vocab", 3],
  "university": ["A grand university campus building with a clock tower, green lawn and students walking with backpacks.", "numbers on clock", "canh", 1],
  "company": ["A modern mid-size office building with glass windows and office workers in suits walking in through the entrance.", "company logo, sign text", "canh", 1],
  "regulation": ["A thick official bound binder of regulations lying open next to a round red hanko seal stamp and a pen on a desk.", "readable text on pages", "vocab", 3],
  "employee": ["A young office employee in a navy suit with a staff ID badge on a lanyard, holding a briefcase and bowing slightly.", "readable badge", "nhanvat", 1],
  "student": ["A Japanese student with a school backpack and books under the arm walking to school.", "", "nhanvat", 1],
  "school-uniform": ["A Japanese school uniform, a navy sailor-collar blouse and pleated skirt, neatly hung on a hanger next to a boy's black gakuran jacket.", "", "vocab", 1],
  "meeting": ["Several colleagues sitting around a conference table with laptops and documents, one person presenting a simple chart on a screen.", "readable screen", "canh", 1],
  "study-abroad": ["A young student with a big suitcase and backpack stepping out of an airport toward a Japanese city with a torii gate and cherry blossoms, beginning study abroad.", "flags with text", "canh", 2],
  "retire": ["An older office worker leaving the office holding a big bouquet of flowers while colleagues clap and bow to see him off on his last day.", "", "canh", 2],
  "grateful-relief": ["A woman struggling with heavy shopping bags looking relieved and grateful as a kind passerby takes one of the bags to help carry it.", "", "canh", 2],
  "help-rescue": ["A person reaching down and pulling a fallen friend up by the hand from the ground.", "injury, blood", "vocab", 1],
  "success": ["A businesswoman jumping for joy holding a golden trophy high as confetti bursts around her.", "", "vocab", 1],
  "failure": ["A person in an apron staring in dismay at a burnt, collapsed cake smoking on a plate in the kitchen.", "fire, disaster", "vocab", 1],
  "late": ["A panicked student with toast in the mouth running toward a school gate that is closing, a wall clock with hands pointing late above the gate.", "numbers on clock", "canh", 2],
  "forget": ["A man at his front door slapping his forehead as he realizes he forgot his umbrella, which leans against the wall inside.", "", "vocab", 1],
  "blame": ["A boy pointing an accusing finger at his little brother beside a broken vase on the floor, shifting the blame.", "violence", "canh", 3],
  "traffic-jam": ["A long line of cars and a bus bumper to bumper on a city road, drivers looking bored and frustrated in a traffic jam.", "license plate text", "canh", 1],
  "carelessly": ["A person absentmindedly knocking over a cup of tea with an elbow while looking at a phone, with an oops expression.", "", "vocab", 2],
  "teacher": ["A kind Japanese teacher standing in front of a blackboard holding a textbook and a pointer.", "writing on blackboard", "nhanvat", 1],
  "weather": ["A weather presenter pointing at a map of Japan decorated with simple sun, cloud and rain icons.", "text, numbers, temperatures", "vocab", 2],
  "exam": ["Students sitting in neat rows of desks writing an exam silently while a proctor watches.", "readable papers", "canh", 1],
  "accident": ["Two small cars that have bumped into each other at an intersection with dented fronts, drivers stepping out shocked.", "blood, injury, fire", "canh", 1],
  "train": ["A Japanese JR commuter train with a green stripe arriving at a station platform.", "text on train, logo", "vocab", 1],
  "hard-tough": ["A person staggering under an enormous tower of cardboard boxes, sweating and exhausted.", "", "vocab", 2],
  "compare": ["A person holding two different apples, one in each hand, looking back and forth to compare them.", "", "vocab", 1],
  "change": ["A single tree whose leaves shift gradually from fresh green on the left side to red autumn and bare branches on the right, showing change.", "", "vocab", 2],
  "rise": ["A simple upward line chart with a bold terracotta arrow climbing steeply to the top right, a small figure cheering beside it.", "numbers on axes, labels", "vocab", 2],
  "increase": ["Stacks of coins growing taller and taller from left to right, the last stack overflowing.", "numbers, currency symbols", "vocab", 2],
  "decrease": ["Stacks of coins shrinking shorter from left to right with a downward arrow above them, the last stack only one coin.", "numbers, currency symbols", "vocab", 2],
  "environment": ["A small globe covered in green forests, clean blue rivers and tiny animals, cradled by two gentle hands.", "", "vocab", 2],
  "city": ["A busy Japanese city with tall buildings, a crossing full of people and a train passing on an elevated track.", "billboard text", "canh", 1],
  "countryside": ["A peaceful Japanese countryside with green rice paddies, a wooden farmhouse and mountains in the distance.", "", "canh", 1],
  "cost-of-living": ["A shopper at a supermarket checkout staring shocked at a very long receipt while holding a small basket of groceries.", "readable receipt, numbers", "canh", 3],
  "population": ["A map shape of Japan densely filled with many tiny people standing shoulder to shoulder.", "text", "vocab", 2],
  "interest": ["A child leaning forward with sparkling eyes pressing the face to the glass of a museum case holding a dinosaur fossil.", "", "vocab", 2],
  "attitude": ["A shop clerk slouching lazily behind a counter with arms crossed and bored eyes while a customer waits, showing a bad attitude.", "", "canh", 3],
  "opinion": ["A person in a meeting confidently raising a hand to share an idea with a lightbulb above, others turning to listen.", "", "canh", 2],
  "convenient": ["A smiling person easily handling several tasks with one compact multi-tool that has a knife, scissors and a screwdriver unfolded.", "weapon", "vocab", 2],
  "inconvenient": ["A tired person walking a long empty road carrying heavy bags toward a single tiny bus stop far away in the countryside.", "", "canh", 2],
  "long-ago": ["An old Edo-period Japanese village street with thatched-roof houses, people in kimono and a wooden cart.", "", "canh", 2],
  "product": ["Neat rows of colorful packaged products on store shelves with blank price tags.", "text on packaging, brand logos", "vocab", 1],
  "manufactured-goods": ["Shiny manufactured goods like rice cookers and headphones moving along a factory conveyor belt.", "logos", "vocab", 2],
  "sell": ["A shop clerk handing a wrapped product across the counter to a customer who gives money in return.", "", "canh", 1],
  "enterprise": ["A cluster of large corporate skyscrapers with many tiny workers streaming in, representing a big enterprise.", "logos", "canh", 2],
  "factory": ["A factory building with sawtooth roof and chimneys, trucks loading boxes at the gate.", "sign text", "canh", 1],
  "purpose": ["An arrow striking the exact center of a red and cream bullseye target.", "", "vocab", 2],
  "service": ["A polite waiter bowing and serving a steaming dish to a smiling customer in a restaurant.", "", "canh", 1],
  "housewife": ["A cheerful housewife in an apron carrying a shopping basket full of groceries on her arm.", "", "nhanvat", 1],
  "overseas": ["An airplane flying across the ocean from a small island of Japan toward a distant continent on a simple globe.", "map labels", "vocab", 2],
  "child": ["A happy little child with a yellow school hat and red randoseru backpack.", "", "nhanvat", 1],
  "young": ["An energetic young man jumping with a skateboard next to a slow elderly man with a cane who smiles at him, emphasizing youth.", "", "vocab", 2],
  "person": ["A single friendly person standing in a neutral relaxed pose, simple clothes, facing forward.", "crowd", "nhanvat", 1],
  "use": ["A person using a pair of scissors to cut colored paper at a table.", "", "vocab", 1],
  "make": ["A person shaping rice balls with their hands in a kitchen, a plate of finished onigiri beside them.", "", "vocab", 1],
  "new": ["A pair of shiny brand-new sneakers with sparkles next to a pair of old worn-out torn sneakers.", "brand logos", "vocab", 1],
  "cheap": ["A bargain bin overflowing with items marked by bright red blank discount tags, a happy shopper grabbing a deal.", "numbers, percent signs, text on tags", "vocab", 2],
  "period": ["A wall calendar grid without numbers where a block of consecutive days is highlighted by a terracotta bracket from start to end.", "numbers, text, month names", "vocab", 3],
  "nationwide": ["A map of Japan with colorful pins placed in every region from Hokkaido to Okinawa.", "place names, text", "vocab", 2],
  "range-scope": ["An open textbook with a section of pages marked by a colored bracket and sticky tabs, showing the range to study.", "readable text", "vocab", 3],
  "region-area": ["A small neighborhood of houses, a park and a shrine outlined by a dashed boundary line on a simple map.", "place names", "vocab", 3],
  "average": ["A simple bar chart with bars of different heights and a dashed horizontal line running through the middle height.", "numbers, axis labels", "vocab", 3],
  "tournament": ["A big sports tournament stadium with colorful pennant flags, a trophy on a podium and teams lining up.", "text on banners", "canh", 2],
  "rain": ["Rain falling from a gray cloud onto a person holding a red umbrella on a wet street.", "", "vocab", 1],
  "friend": ["Two friends walking side by side laughing with arms around each other's shoulders.", "", "vocab", 1],
  "busy": ["A frazzled office worker juggling a ringing phone, a stack of papers and a laptop with sweat drops flying.", "", "vocab", 1],
  "telephone": ["A smartphone and a classic desk telephone side by side, the smartphone ringing with sound waves.", "screen text", "vocab", 1],
  "information": ["A person surrounded by floating icons of a newspaper, a TV, a smartphone and a radio streaming information toward them.", "readable text", "vocab", 3],
  "held-event": ["A lively festival being held in a town square with a stage, lanterns, food stalls and a crowd gathering.", "text on lanterns", "canh", 3],
  "win-lottery": ["A person jumping for joy holding a winning lottery ticket up high with gold confetti falling around them.", "numbers on ticket", "vocab", 2],
  "pass-exam": ["A student jumping for joy with fists in the air under cherry blossoms, holding an acceptance envelope, after passing an exam.", "text", "vocab", 2],
  "win-championship": ["An athlete standing on the top step of a podium lifting a huge golden championship trophy above the head.", "numbers on podium", "vocab", 1],
  "qualification": ["A proud person holding a framed certificate decorated with a gold seal and ribbon, no writing on it.", "readable text on certificate", "vocab", 2],
  "lottery": ["A small Japanese lottery ticket booth with a person buying a colorful lottery ticket.", "numbers, text", "canh", 2],
  "money": ["A neat pile of Japanese yen coins and banknotes next to a coin purse.", "readable numbers on notes, portraits", "vocab", 1],
  "future-personal": ["A little boy looking up dreamily at a thought bubble showing himself grown up as a doctor, imagining his future.", "", "vocab", 3],
  "half-done": ["A half-eaten sandwich with a big bite missing left abandoned on a plate beside a half-drunk glass of milk.", "", "vocab", 3],
  "absent": ["A classroom full of students at desks with one empty desk and chair in the middle, showing someone is absent.", "writing on board", "canh", 2],
  "fatigue": ["An exhausted office worker slumped over a desk with heavy eyelids and a drooping posture.", "", "vocab", 1],
  "shortage": ["A supermarket shelf that is almost completely empty with only one lonely item left, a worried shopper looking at it.", "text", "vocab", 3],
  "bored": ["A person yawning with a bored flat face resting the chin on a hand in front of a monotonous pile of identical papers.", "", "vocab", 2],
  "nutrition": ["A balanced meal plate with grilled fish, rice, vegetables, miso soup and fruit.", "", "vocab", 2],
  "rest": ["A person relaxing on a park bench with eyes closed and a canned drink, taking a break.", "", "vocab", 1],
  "say": ["A person speaking with an open mouth and a small empty speech bubble coming out.", "text in bubble", "vocab", 1],
  "quit": ["A determined man snapping a cigarette in half and dropping it into a trash can, quitting smoking.", "", "vocab", 2],
  "talent": ["A small child playing the violin brilliantly with sparkles and musical notes flowing around while adults watch amazed.", "", "vocab", 2],
  "complaint": ["An angry customer complaining loudly at a counter, waving a hand at a broken toaster, while a clerk bows apologetically.", "", "canh", 2],
  "discontent": ["A person pouting with arms crossed and a sulky face in front of a tiny portion of food on a large plate.", "", "vocab", 2],
  "poor": ["A family in patched clothes sharing a single small bowl of rice in a bare room with a leaky roof.", "", "canh", 2],
  "excellent": ["A proud student receiving a shiny gold medal on stage while classmates applaud.", "", "vocab", 2],
  "cancel": ["An outdoor sports match called off in heavy rain, a referee crossing both arms in a big X while players walk off the field.", "", "canh", 2],
  "match-game": ["Two soccer teams in different colored jerseys competing for the ball on a green field.", "numbers on jerseys", "canh", 1],
  "envy": ["A boy looking enviously with longing eyes at his friend proudly riding a shiny new bicycle.", "", "canh", 2],
  "frustrated-loss": ["A young athlete kneeling on the field clenching fists and biting the lip with tears after losing a match.", "", "vocab", 2],
  "anxiety": ["A person hugging their knees under a small gray storm cloud with nervous eyes and a trembling mouth.", "", "vocab", 2],
  "painful-hardship": ["A person crying alone at a desk late at night under a lamp, head in hands with a heavy burden of work.", "", "vocab", 2],
  "frightening": ["A person trembling in terror as a huge dark looming shadow with glowing eyes stretches across the wall behind them.", "gore, blood", "vocab", 2],
  "moved": ["A person in a movie theater seat wiping happy tears with a handkerchief, deeply moved by the film.", "screen text", "vocab", 2],
  "tears": ["A close-up of a gentle face with a single large glistening tear rolling down the cheek.", "", "vocab", 1],
  "bothered": ["A woman at her desk distracted, repeatedly glancing over her shoulder at a closed door with a curious worried look.", "", "vocab", 3],
  "worry": ["A mother standing at a window at night with hands clasped anxiously, waiting for her child to come home.", "", "vocab", 2],
  "want-to-meet": ["A young woman holding a framed photo of a distant friend, with a thought bubble of the two of them hugging, longing to see her.", "", "vocab", 3],
  "family": ["A happy Japanese family of grandparents, parents and two children standing together smiling.", "", "canh", 1],
  "hot": ["A person sweating heavily under a blazing summer sun, fanning themselves with a paper uchiwa fan.", "", "vocab", 1],
  "stop": ["A bus coming to a stop at a roadside bus stop with its brake lights on and doors opening.", "text", "vocab", 1],
  "want-to-eat": ["A hungry person pressing their face against a restaurant window, drooling at a steaming bowl of ramen inside.", "text", "vocab", 2],
  "prove": ["A detective holding up a magnified fingerprint card as evidence in front of a surprised crowd, proving the truth.", "text", "canh", 3],
  "confirm-check": ["A person double-checking that the front door is locked by pulling the handle and pointing at the lock.", "", "vocab", 2],
  "culprit": ["A sneaky masked burglar tiptoeing away in a striped shirt carrying a sack of stolen loot.", "weapon", "nhanvat", 1],
  "mistake": ["A person buttoning a shirt into the wrong buttonholes so it hangs lopsided, looking down at the mistake in surprise.", "", "vocab", 2],
  "crime-scene": ["A scene cordoned off with yellow police tape where investigators in gloves examine footprints on the ground.", "text on tape", "canh", 2],
  "investigate": ["A police detective in a trench coat crouching with a magnifying glass to examine footprints and clues.", "", "vocab", 2],
  "wallet": ["A brown leather wallet slightly open showing yen banknotes and cards inside.", "numbers, text", "vocab", 1],
  "key": ["A single brass door key on a small key ring.", "", "vocab", 1],
  "lost-item": ["A folded umbrella and a bag left behind on an empty train seat after passengers have left.", "text", "vocab", 2],
  "dog": ["A friendly Shiba Inu dog sitting with its curled tail.", "", "vocab", 1],
  "arrive": ["A traveler with a suitcase stepping off a train onto the platform with a happy relieved face, arriving at the destination.", "station name text", "vocab", 2],
  "he": ["A friendly young man pointed at by a hand from the side of the frame, presenting him as that guy.", "", "nhanvat", 1],
  "thing": ["An assorted group of everyday objects on a table: a cup, a book, a pair of glasses, a pen and a small plant.", "", "vocab", 2],
  "understand": ["A person nodding with a bright lightbulb shining above the head and a happy aha expression.", "", "vocab", 2],
  "imagine": ["A dreamy child sitting on the grass with a big thought bubble showing a flying castle among clouds.", "", "vocab", 2],
  "predict": ["A person looking up at gathering clouds and confidently opening an umbrella just before the first raindrops fall, predicting rain.", "", "vocab", 3],
  "future": ["A futuristic city with sleek round towers, flying cars and robots helping people.", "text", "canh", 2],
  "earthquake": ["A room shaking in an earthquake with a lamp swinging, books falling off shelves and a person crouching under a table.", "injury", "canh", 1],
  "danger": ["A person stepping dangerously close to a crumbling cliff edge beside a yellow triangle warning sign with an exclamation mark.", "text", "vocab", 2],
  "safe": ["A child in a yellow helmet crossing the street safely at a crosswalk, guided by a crossing guard holding a flag.", "text", "vocab", 2],
  "machine": ["A big industrial machine with interlocking gears, levers and pipes working steadily.", "", "vocab", 1],
  "problem": ["A person scratching their head in confusion in front of a huge tangled knot of rope.", "", "vocab", 3],
  "unemployment": ["A man in a suit sitting dejected on a park bench holding a cardboard box of his office belongings.", "", "canh", 2],
  "technological-progress": ["A row showing the evolution of telephones from an old rotary dial phone to a flip phone to a modern smartphone, with an arrow of progress.", "numbers on dial", "vocab", 2],
  "expand": ["A tiny food stall on the left growing into a bigger shop and then a large store on the right, with an arrow showing expansion.", "shop sign text", "vocab", 3],
  "develop": ["A small village of wooden houses on the left growing into a modern skyline of tall buildings on the right, showing development.", "", "canh", 3],
  "economy": ["Coins, a factory, a shopping cart and a rising chart arrow circling around a globe, representing the economy.", "numbers", "vocab", 3],
  "bad": ["A person grimacing with a thumbs down at a rotten brown apple with flies, next to a fresh shiny apple for contrast.", "", "vocab", 2],
  "gain-weight": ["A person looking shocked as their belt strains and a shirt button pops off from their round belly.", "", "vocab", 1],
  "keep-going": ["A tired marathon runner pushing on with determination, still running forward despite heavy sweat.", "numbers on bib", "vocab", 2],
  "manners": ["A young person bowing politely at a deep angle to greet an elderly guest at the entrance of a Japanese home.", "", "vocab", 2],
  "knowledge": ["A person sitting on a tall stack of books with a glowing lightbulb and small icons of a globe, an atom and a leaf around their head.", "readable book titles", "vocab", 3],
  "ability": ["A confident person surrounded by floating icons of a hammer, a paintbrush, a laptop and a chef's knife, showing many abilities.", "", "vocab", 3],
  "housework": ["A person vacuuming the floor while laundry dries on a line and dishes sit in a drying rack at home.", "", "canh", 1],
  "cooking": ["A person in an apron stir-frying vegetables in a pan on a stove with steam rising.", "", "vocab", 1],
  "skilful": ["A painter confidently brushing a beautiful landscape on a canvas with praised sparkles around it.", "", "vocab", 2],
  "can-speak": ["A young Asian person chatting fluently and cheerfully with a foreign tourist, both laughing with empty speech bubbles.", "text in bubbles", "canh", 3],
  "tall-high": ["A very tall slender tower beside a small low house, a tiny person looking up at the tower.", "", "vocab", 1],
  "she": ["A friendly young woman pointed at by a hand from the side of the frame, presenting her as that woman.", "", "nhanvat", 1],
  "good": ["A smiling person giving a big thumbs up with a sparkle.", "", "vocab", 1],
  "head": ["A side view of a person's head with the head clearly highlighted in terracotta, a hand gently touching the top of it.", "brain, organs", "vocab", 1],
  "correct": ["A student pointing at the right answer on a board marked with a big red circle while a wrong one beside it has a red cross.", "writing, numbers", "vocab", 3],
  "representative": ["One person stepping forward from a group to speak on behalf of everyone, the group standing behind nodding.", "", "canh", 2],
  "proxy": ["A young deputy sitting in the boss's big chair and signing a document on his behalf while the empty coat rack shows the boss is away.", "readable document", "canh", 3],
  "in-charge": ["A staff member at a help desk pointing to herself with a smile as the person in charge, wearing a lanyard badge.", "readable badge", "nhanvat", 3],
  "pay": ["A customer handing yen banknotes to a cashier at a register in a shop.", "numbers on notes", "canh", 1],
  "signature": ["A hand signing a document with a fountain pen, drawing a flowing abstract squiggle line.", "letters, readable writing", "vocab", 2],
  "department-manager": ["A middle-aged manager in a suit and tie standing in front of a team of desks, holding a folder and directing staff.", "", "nhanvat", 2],
  "company-president": ["A senior company president in a fine suit sitting behind a large wooden desk in a spacious office with a city view.", "nameplate text", "nhanvat", 2],
  "attend": ["A participant signing in at a reception desk and taking a seat at a meeting where all chairs are filled.", "text", "canh", 2],
  "contact": ["A person sending a message on a smartphone as small envelope icons fly toward a friend's phone.", "readable text", "vocab", 2],
  "tomorrow-skip": ["", "", "vocab", 1],
  "debate": ["Two people across a table debating passionately with raised hands and gestures while a moderator listens.", "", "canh", 2],
  "present-announce": ["A person presenting at a podium with a simple chart on a screen behind them, the audience listening.", "readable screen", "canh", 2],
  "report": ["An employee handing a report folder to a boss who reviews it at a desk.", "readable document", "canh", 2],
  "culture": ["A Japanese tea ceremony with a woman in kimono whisking matcha on tatami mats beside an ikebana arrangement.", "", "canh", 2],
  "history": ["An ancient Japanese castle beside a samurai armor, an old scroll and a clay haniwa figure, representing history.", "text on scroll", "vocab", 3],
  "survey": ["A surveyor with a clipboard interviewing a passerby on the street, marking a checklist.", "readable text", "canh", 2],
  "politics": ["Politicians in suits debating in a parliament chamber in front of a domed government building.", "text", "canh", 2],
  "question": ["A curious student raising a hand in class with a speech bubble containing only a big question mark.", "letters", "vocab", 1],
  "japan": ["Mount Fuji with a red torii gate and cherry blossoms in the foreground.", "", "vocab", 1],
  "listen": ["A person cupping a hand behind their ear and leaning in to listen carefully.", "", "vocab", 1],
  "write": ["A hand holding a pencil writing on lined paper with only wavy scribble lines.", "letters, readable writing", "vocab", 1],
  "notice": ["A smartphone screen showing a notification bell icon and a sealed envelope icon popping up.", "text", "vocab", 2],
  "postpone": ["A hand moving a sticky note with a meeting icon from one square to a later square on a wall calendar without numbers, with a curved arrow.", "numbers, text", "vocab", 3],
  "reschedule": ["A person rearranging colorful sticky notes on a weekly planner board, swapping their places.", "text on notes", "vocab", 2],
  "approve": ["A manager pressing a red hanko seal stamp onto a document with a satisfied nod.", "readable text", "vocab", 2],
  "command": ["A stern boss pointing forward and giving an order to a worker who stands straight and salutes.", "military weapon", "canh", 2],
  "plan": ["A person drawing a plan on a large sheet with boxes connected by arrows and a small map route.", "text", "vocab", 2],
  "prepare": ["A person packing a suitcase with folded clothes, a passport and toiletries on the bed, preparing for a trip.", "text", "vocab", 1],
  "end": ["A stage curtain closing at the end of a play while the actors take a final bow.", "text", "canh", 2],
  "obey-follow": ["A line of tourists following a guide's raised flag in orderly single file.", "text on flag", "canh", 2],
  "responsibility": ["A ship captain firmly holding the wheel in a storm while the crew behind relies on him, bearing responsibility.", "", "canh", 3],
  "protect": ["A parent shielding a small child under a big umbrella from heavy rain.", "", "vocab", 1],
  "respect": ["A young person listening attentively and nodding respectfully to an elderly person who is speaking.", "", "vocab", 3],
  "nuisance": ["A man talking loudly on a phone in a quiet train carriage while other passengers frown and cover their ears.", "text", "canh", 2],
  "promise": ["Two hands linking pinky fingers in a pinky promise.", "", "vocab", 1],
  "think": ["A person with a hand on the chin looking up thoughtfully with small swirls of thought above.", "", "vocab", 1],
  "i-me": ["A young person smiling and pointing to their own chest to indicate themselves.", "", "nhanvat", 1],
  "everyone": ["A diverse group of people of all ages standing together smiling and waving.", "", "nhanvat", 1],
  "hang": ["A person hanging a coat on a wall hook in a genkan entryway.", "", "vocab", 2],
  "improve": ["A wilted drooping plant on the left and the same plant standing tall and blooming on the right after being cared for with a watering can.", "", "vocab", 3],
  "reflect": ["A person sitting quietly with bowed head and folded hands, reflecting on a mistake shown by a spilled cup beside them.", "", "vocab", 3],
  "evaluate": ["A panel of three judges holding up cards with star symbols while a performer waits on stage.", "numbers on cards", "canh", 3],
  "goal": ["A hiker climbing toward a red flag planted on the peak of a mountain.", "text on flag", "vocab", 2],
  "team": ["A sports team in matching jerseys huddling together with hands stacked in the center.", "numbers on jerseys", "canh", 1]
};

// Ban do id -> slug, hoac "!ly do" de bo qua (giu SVG)
const G = "!Tu chuc nang/ngu phap, khong co hinh anh day duoc nghia";
const T = "!Tu chi thoi gian/truu tuong, anh khong phan biet duoc voi tu gan nghia (khong duoc dung chu/so)";
const L = "!Ten ngon ngu: muon day nghia phai ve chu viet, ma anh cam chu";
const M = {
  "1-1":"trust","1-2":"misunderstand","1-3":"mistaken-identity","1-4":"improve-skill","1-5":"specialty","1-6":"specialty",
  "1-7":"knowledgeable","1-8":"bad-at","1-9":"confidence","1-10":"experience","1-11":"personality",
  "1-12":"!Danh tu truu tuong (ly do), khong co vat the nao day nghia ro","1-13":"result","1-14":"coincidence","1-15":"good-at",
  "1-16":"join","1-17":"agree","1-18":"record","1-19":"regret-pity","1-20":"explain",
  "2-1":"effort","2-2":"mindful","2-3":"be-careful","2-4":"make-a-point-of","2-5":"exercise","2-6":"eat","2-7":"sleep","2-8":"wake-up",
  "2-9":"health","2-10":"daily-life","2-11":"habit","2-12":"vegetables","2-13":"body-weight","2-14":"mindful","2-15":"effort",
  "2-16":"sick","2-17":"work","2-18":"time","2-19":"body","2-20":"!Pho tu tan suat (moi ngay), anh khong the hien duoc lap lai ma khong dung so/chu",
  "3-1":"decide","3-2":"decide","3-3":"obey-rules","3-4":"prohibit","3-5":"resolve","3-6":"graduate","3-7":"rules","3-8":"rules",
  "3-9":"!Danh tu truu tuong (nghia vu), khong co hinh day nghia ro","3-10":"resolve","3-11":"university","3-12":"company","3-13":"regulation",
  "3-14":"employee","3-15":"student","3-16":"school-uniform","3-17":"meeting","3-18":"!Pho tu tan suat (moi tuan), anh khong the hien duoc lap lai ma khong dung so/chu",
  "3-19":"study-abroad","3-20":"retire",
  "4-1":"grateful-relief","4-2":"success","4-3":"failure","4-4":"late","4-5":"forget","4-6":"help-rescue",
  "4-7":"!Danh tu ngu phap (おかげ = nho co), chi co nghia trong cau","4-8":"blame","4-9":"success","4-10":"failure","4-11":"traffic-jam",
  "4-12":"late","4-13":"carelessly","4-14":"effort","4-15":"teacher","4-16":"weather","4-17":"exam","4-18":"accident","4-19":"train","4-20":"hard-tough",
  "5-1":"compare","5-2":G,"5-3":"change","5-4":"rise","5-5":"decrease",
  "5-6":T,"5-7":T,"5-8":"environment","5-9":"city","5-10":"countryside","5-11":"cost-of-living","5-12":"population",
  "5-13":"interest","5-14":"attitude","5-15":"opinion","5-16":"convenient","5-17":"inconvenient","5-18":"long-ago","5-19":"daily-life","5-20":"!Danh tu truu tuong (xa hoi), anh quang truong de hieu nham thanh 'thi tran'",
  "6-1":"!Hau to ngu phap (向け = danh cho), nghia nam o danh tu di kem","6-2":"!Dong tu goc cua mau ngu phap (向けます), nghia truu tuong 'huong ve'",
  "6-3":"!Danh tu truu tuong (doi tuong nghien cuu/dich vu), anh de bi hieu nham thanh 'nham ban'","6-4":"product","6-5":"manufactured-goods","6-6":"sell","6-7":"enterprise","6-8":"factory",
  "6-9":"purpose","6-10":"service","6-11":"housewife","6-12":"overseas","6-13":"child","6-14":"company","6-15":"young","6-16":"person",
  "6-17":"use","6-18":"make","6-19":"new","6-20":"cheap",
  "7-1":G,"7-2":"!Dong tu goc cua mau ngu phap (通します), nghia 'cho di qua/xuyen suot' qua truu tuong","7-3":G,"7-4":G,
  "7-5":"!Dong tu truu tuong (gioi han), anh de hieu nham thanh 'cam' hoac 'rao chan'","7-6":"period","7-7":"nationwide",
  "7-8":"!Danh tu truu tuong (toan the), khong co hinh day nghia ro","7-9":"range-scope","7-10":"!Pho tu so luong (tat ca), khong co hinh day nghia ro",
  "7-11":"region-area","7-12":"average","7-13":"tournament","7-14":"rain","7-15":"friend","7-16":"busy","7-17":"telephone","7-18":"information",
  "7-19":"!Dong tu truu tuong (keo dai), anh mua keo dai de hieu nham thanh 'mua'","7-20":"held-event",
  "8-1":"!Danh tu truu tuong (dieu kien), khong co hinh day nghia ro","8-2":"success","8-3":"win-lottery","8-4":"!Danh tu truu tuong (gia dinh), khong co hinh day nghia ro",
  "8-5":"pass-exam","8-6":"effort","8-7":G,"8-8":"study-abroad","8-9":"win-championship","8-10":"!Danh tu truu tuong (co hoi), hinh canh cua sang de hieu nham thanh 'cua'/'anh sang'","8-11":"qualification","8-12":"lottery",
  "8-13":"failure","8-14":"exam","8-15":"money","8-16":"time","8-17":"effort","8-18":"decide","8-19":"future-personal","8-20":G,
  "9-1":G,"9-2":G,"9-3":"half-done","9-4":"absent","9-5":"health","9-6":"late","9-7":"fatigue","9-8":"!Danh tu truu tuong (xu huong), khong co hinh day nghia ro",
  "9-9":"shortage","9-10":"sleep","9-11":"bored","9-12":"nutrition","9-13":"rest","9-14":"forget","9-15":"busy","9-16":"eat","9-17":"say","9-18":"quit",
  "9-19":T,"9-20":"sick",
  "10-1":"talent","10-2":"complaint","10-3":"discontent","10-4":"poor","10-5":"join","10-6":"excellent","10-7":"cancel","10-8":"attitude","10-9":"effort",
  "10-10":"match-game","10-11":"rain","10-12":"child","10-13":"say","10-14":"tournament","10-15":"effort","10-16":"money","10-17":"young","10-18":"company",
  "10-19":"work","10-20":"busy",
  "11-1":"envy","11-2":"frustrated-loss","11-3":"anxiety","11-4":"painful-hardship","11-5":"frightening","11-6":"moved","11-7":"tears","11-8":"bothered",
  "11-9":"worry","11-10":"want-to-meet","11-11":"family","11-12":"hot","11-13":"train","11-14":"stop","11-15":"work","11-16":"busy","11-17":"match-game",
  "11-18":"want-to-eat","11-19":"person","11-20":"future-personal",
  "12-1":"prove","12-2":"confirm-check","12-3":"culprit","12-4":"mistake","12-5":"crime-scene","12-6":"investigate","12-7":"wallet","12-8":"key",
  "12-9":"lost-item","12-10":"dog","12-11":"arrive","12-12":"result","12-13":"be-careful","12-14":"person","12-15":"he",
  "12-16":"!Pho tu tan suat (luon luon), khong co hinh day nghia ro","12-17":"thing","12-18":"!Dai tu chi dinh (cai nay), SVG chi tay hien tai ro hon",
  "12-19":"!Tu chi dinh (kia/do), SVG chi tay hien tai ro hon","12-20":"understand",
  "13-1":"!Danh tu truu tuong (tinh huong), khong co hinh day nghia ro","13-2":"imagine","13-3":"predict","13-4":"future",
  "13-5":"!Tinh tu truu tuong (kha thi), khong co hinh day nghia ro","13-6":"!Dong tu truu tuong (xay ra), nghia phu thuoc chu ngu",
  "13-7":"change","13-8":"accident","13-9":"earthquake","13-10":"danger","13-11":"safe","13-12":"!Dong tu kha nang (co the lam duoc), khong co hinh day nghia ro",
  "13-13":"!Da co hinh 'say'/'debate' gan nghia; 話します (noi chuyen) giu anh hoi thoai rieng", "13-14":"machine","13-15":"problem","13-16":"say","13-17":"future-personal",
  "13-18":L,"13-19":"he","13-20":"!Tu nghi van (loai nao), khong co hinh day nghia ro",
  "14-1":"increase","14-2":"unemployment","14-3":"technological-progress","14-4":"expand","14-5":"develop","14-6":"decrease","14-7":"increase","14-8":"decrease",
  "14-9":"population","14-10":"cost-of-living","14-11":"environment","14-12":"economy","14-13":"bad","14-14":"gain-weight","14-15":"keep-going","14-16":"rise",
  "14-17":"company","14-18":"!Danh tu truu tuong (tinh huong), khong co hinh day nghia ro","14-19":"problem","14-20":"!Dong tu truu tuong (tro thanh), khong co hinh day nghia ro",
  "15-1":"personality","15-2":"manners","15-3":"knowledge","15-4":"ability","15-5":"housework","15-6":"experience","15-7":"cooking","15-8":L,
  "15-9":"skilful","15-10":L,"15-11":L,"15-12":"can-speak","15-13":"tall-high","15-14":"!Pho tu phu dinh (hoan toan khong), khong co hinh day nghia ro",
  "15-15":"she","15-16":"good","15-17":"head","15-18":"!Pho tu muc do (hoan toan), khong co hinh day nghia ro","15-19":"!Pho tu nhan manh (that su), khong co hinh day nghia ro",
  "15-20":"correct",
  "16-1":"representative","16-2":"proxy","16-3":"in-charge","16-4":"pay","16-5":"signature","16-6":"pay","16-7":"department-manager","16-8":"company-president",
  "16-9":"meeting","16-10":"attend","16-11":"telephone","16-12":"contact","16-13":"money","16-14":"company","16-15":"work","16-16":"rest",
  "16-17":T,"16-18":T,"16-19":"explain","16-20":"say",
  "17-1":"debate","17-2":"present-announce","17-3":"report","17-4":"culture","17-5":"history","17-6":"survey","17-7":"opinion","17-8":"politics","17-9":"economy",
  "17-10":"environment","17-11":"meeting","17-12":"question","17-13":"japan","17-14":"!Danh tu truu tuong (xa hoi), anh quang truong de hieu nham thanh 'thi tran'","17-15":"university","17-16":"student","17-17":"teacher",
  "17-18":"talk","17-19":"listen","17-20":"write",
  "18-1":"notice","18-2":"postpone","18-3":"decide","18-4":"reschedule","18-5":"approve","18-6":"command","18-7":"cancel","18-8":"meeting","18-9":"plan",
  "18-10":"prepare","18-11":"!Tinh tu truu tuong (can thiet), khong co hinh day nghia ro","18-12":"end","18-13":"company-president","18-14":T,"18-15":T,
  "18-16":"telephone","18-17":"contact","18-18":"decide","18-19":"!Pho tu (van chua), khong co hinh day nghia ro","18-20":"problem",
  "19-1":"obey-follow","19-2":"responsibility","19-3":"!Danh tu truu tuong (nghia vu), khong co hinh day nghia ro","19-4":"!Danh tu truu tuong (quyen loi), anh de bi hieu nham thanh 'bo phieu'",
  "19-5":"protect","19-6":"respect","19-7":"nuisance","19-8":"rules","19-9":"rules","19-10":"promise","19-11":"think","19-12":"!Pho tu (som), anh van phong luc binh minh khong phan biet voi 'buoi sang'","19-13":"decide",
  "19-14":"person","19-15":"i-me","19-16":"everyone","19-17":"!Danh tu truu tuong (xa hoi), anh quang truong de hieu nham thanh 'thi tran'","19-18":"problem","19-19":"!Dong tu chung chung (lam), khong co hinh day nghia ro","19-20":"hang",
  "20-1":"improve","20-2":"reflect","20-3":"evaluate","20-4":"goal","20-5":"team","20-6":"effort","20-7":"prepare","20-8":"result","20-9":"meeting",
  "20-10":"responsibility","20-11":"rules","20-12":"!Danh tu truu tuong (tinh huong), khong co hinh day nghia ro","20-13":"problem","20-14":"success",
  "20-15":"failure","20-16":"plan","20-17":T,"20-18":"company","20-19":"everyone","20-20":"talk"
};
// 話します: dung chung slug "talk" (13-13 cung la 話します)
M["13-13"] = "talk";
D["talk"] = ["Two people sitting face to face at a cafe table chatting happily, one gesturing with an empty speech bubble.", "text in bubble", "vocab", 1];
delete D["tomorrow-skip"];

// Doc giao trinh truc tiep
const muc = [];
for (let i = 1; i <= 20; i++) {
  const j = JSON.parse(fs.readFileSync(`${GOC}/${i}.json`, "utf8"));
  for (const v of j.vocabList || []) muc.push(v);
}

const items = [], skipped = [], daDung = new Set(), loi = [];
for (const v of muc) {
  const k = v.id.replace("voc-n3-", "");
  const s = M[k];
  if (!s) { loi.push("thieu map " + v.id); continue; }
  if (s.startsWith("!")) {
    skipped.push({ id: v.id, word: v.kanji || v.word, meaningVi: v.meaningVi, reason: s.slice(1) });
    continue;
  }
  const d = D[s];
  if (!d) { loi.push("thieu slug " + s + " cho " + v.id); continue; }
  const it = { id: v.id, word: v.kanji || v.word, meaningVi: v.meaningVi, ten: s, prompt: d[0], negative: d[1], loai: d[2], kho: d[3] };
  if (daDung.has(s)) it.dungLai = s; else daDung.add(s);
  items.push(it);
}
// Slug khong dung toi
for (const s of Object.keys(D)) if (!daDung.has(s)) loi.push("slug thua " + s);
// Kiem tra prompt khong xin chu Nhat
for (const s of Object.keys(D)) if (/[\u3040-\u30ff\u4e00-\u9fff]/.test(D[s][0])) loi.push("prompt co chu Nhat " + s);
if (loi.length) { console.error(loi.join("\n")); process.exit(1); }

const out = {
  level: "n3",
  nguon: "curriculum/n3/{1..20}.json vocabList[]",
  style: STYLE,
  negativeBase: NEG_BASE,
  cachGhep: "prompt_cuoi = item.prompt + ' ' + style; negative_cuoi = negativeBase + (item.negative ? ', ' + item.negative : ''). Chi sinh 1 anh cho moi 'ten'; muc co dungLai dung lai anh cua ten do.",
  thongKe: { tong: muc.length, coAnh: items.length, anhDuyNhat: daDung.size, dungLai: items.filter(x => x.dungLai).length, boQua: skipped.length },
  items, skipped
};
fs.writeFileSync(RA, JSON.stringify(out, null, 1), "utf8");
console.log(JSON.stringify(out.thongKe));
