# -*- coding: utf-8 -*-
"""N1 — Bai 5: Dien bien tieu cuc & Ket cuc — に至る (dan den mot ket qua nghiem
trong sau qua trinh), に至っては (neu bat truong hop CUC DOAN nhat trong so sanh),
という始末だ (ket luan che trach sau chuoi su viec xau).

Tu vung minh hoa TU CHON tu pool mo data/jlpt-vocab/n1.csv (xem NOTICE.md).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from n1_lib import v, k, t, ex, slide, line, q, lesson, merge
from jlpt_pool import Pool

L = 5
pool = Pool("n1")

VOCAB = [
    v(1,  "いたります", "至ります", "いたります", "itarimasu", "verb", "Đạt đến, dẫn đến (một trạng thái)", "倒産するに 至ります = dẫn đến mức phá sản.", L),
    v(2,  "あっかします", "悪化します", "あっかします", "akka shimasu", "verb", "Xấu đi, ác hóa", "けいえいが 悪化します = kinh doanh xấu đi.", L),
    v(3,  "じたい", "事態", "じたい", "jitai", "noun", "Tình thế, tình huống (nghiêm trọng)", "深刻な 事態 = tình huống nghiêm trọng.", L),
    v(4,  "しんこく", "深刻", "しんこく", "shinkoku", "adjective", "Nghiêm trọng", "事態が 深刻だ = tình huống nghiêm trọng.", L),
    v(5,  "とうさん", "倒産", "とうさん", "tousan", "noun", "Phá sản", "会社が 倒産します = công ty phá sản.", L),
    v(6,  "ほうちします", "放置します", "ほうちします", "houchi shimasu", "verb", "Bỏ mặc, để yên không xử lý", "もんだいを 放置します = bỏ mặc vấn đề không giải quyết.", L),
    v(7,  "いいわけ", "言い訳", "いいわけ", "iiwake", "noun", "Lời biện minh, bào chữa", "言い訳を 続けます = cứ tiếp tục biện minh.", L),
    v(8,  "うそ", "嘘", "うそ", "uso", "noun", "Lời nói dối", "嘘を つきます = nói dối.", L),
    v(9,  "しまつ", "始末", "しまつ", "shimatsu", "noun", "Kết cục, hậu quả (thường xấu, đáng chê trách)", "という 始末だ = rốt cuộc lại ra nông nỗi...", L),
    v(10, "しゃいん", "社員", "しゃいん", "shain", "noun", "Nhân viên", "Đã gặp N5 bài 1.", L),
    v(11, "しゃちょう", "社長", "しゃちょう", "shachou", "noun", "Giám đốc", "Đã gặp N4 bài 41.", L),
    v(12, "まじめ", "真面目", "まじめ", "majime", "adjective", "Nghiêm túc, chăm chỉ", "Đã gặp N4 bài 36.", L),
    v(13, "もんだい", "問題", "もんだい", "mondai", "noun", "Vấn đề", "Đã gặp N3 bài 13.", L),
    v(14, "つづけます", "続けます", "つづけます", "tsuzukemasu", "verb", "Tiếp tục làm gì", "Đã gặp N4 bài 28.", L),
    v(15, "しんじます", "信じます", "しんじます", "shinjimasu", "verb", "Tin tưởng", "Đã gặp N3 bài 1.", L),
    v(16, "けいえい", "経営", "けいえい", "keiei", "noun", "Kinh doanh, quản lý (doanh nghiệp)", "Đã gặp N2 bài 15.", L),
    v(17, "かいしゃ", "会社", "かいしゃ", "kaisha", "noun", "Công ty", "Đã gặp N5 bài 3.", L),
    v(18, "せきにん", "責任", "せきにん", "sekinin", "noun", "Trách nhiệm", "Đã gặp N3 bài 19.", L),
    v(19, "わるい", "悪い", "わるい", "warui", "adjective", "Xấu", "Đã gặp N5 bài 8.", L),
    v(20, "ゆるします", "許します", "ゆるします", "yurushimasu", "verb", "Tha thứ, cho phép", "Đã gặp N2 bài 14.", L),
]

KANJI = [
    k(1, "至", "CHÍ", 6, ["シ (shi)"], ["いた(る)"], "Đến, đạt đến.",
      [("至ります", "いたります", "Đạt đến"), ("至急", "しきゅう", "Khẩn cấp, gấp")], L),
    k(2, "悪", "Á/ÁC", 11, ["アク (aku)", "オ (o)"], ["わる(い)"], "Xấu, ác, tệ.",
      [("悪化", "あっか", "Xấu đi"), ("悪い", "わるい", "Xấu")], L),
    k(3, "倒", "ĐẢO", 10, ["トウ (tou)"], ["たお(れる)", "たお(す)"], "Đổ, ngã, sụp.",
      [("倒産", "とうさん", "Phá sản"), ("倒れます", "たおれます", "Bị đổ, ngã xuống")], L),
    k(4, "始", "THỦY", 8, ["シ (shi)"], ["はじ(める)", "はじ(まる)"], "Bắt đầu.",
      [("始末", "しまつ", "Kết cục"), ("始めます", "はじめます", "Bắt đầu")], L),
    k(5, "末", "MẠT", 5, ["マツ (matsu)", "バツ (batsu)"], ["すえ"], "Cuối, ngọn, phần sau.",
      [("始末", "しまつ", "Kết cục"), ("週末", "しゅうまつ", "Cuối tuần")], L),
]

SLIDES = [
    slide(L, 1,
        "1. Cuối cùng đã đi đến mức... (kết cục nghiêm trọng sau một quá trình): Vる/N + に至る",
        "V(thể từ điển)/N + に至る",
        "に至る diễn tả một QUÁ TRÌNH (thường tiêu cực, kéo dài) cuối cùng đã DẪN ĐẾN một kết quả "
        "NGHIÊM TRỌNG. Văn phong TRANG TRỌNG, hay gặp trong tin tức, báo cáo, văn bản pháp lý.",
        [
            ex(L, 1, 1, [t("t-l5s1-1", "けいえい", "経営", "けいえい", key=True), t("t-l5s1-2", "が"),
                         t("t-l5s1-3", "あっかし", "悪化し", "あっかし", key=True), t("t-l5s1-4", "、"),
                         t("t-l5s1-5", "とうさん", "倒産", "とうさん", key=True), t("t-l5s1-6", "する"),
                         t("t-l5s1-7", "に"), t("t-l5s1-8", "いたりました", "至りました", "いたりました", key=True)],
               "Kinh doanh xấu đi, cuối cùng đã dẫn đến mức phá sản."),
            ex(L, 1, 2, [t("t-l5s1-9", "ちいさい", "小さい", "ちいさい"), t("t-l5s1-10", "もんだい", "問題", "もんだい", key=True),
                         t("t-l5s1-11", "が"), t("t-l5s1-12", "、"), t("t-l5s1-13", "しんこくな", "深刻な", "しんこくな", key=True),
                         t("t-l5s1-14", "じたい", "事態", "じたい", key=True), t("t-l5s1-15", "に"),
                         t("t-l5s1-16", "いたりました", "至りました", "いたりました", key=True)],
               "Vấn đề nhỏ, cuối cùng đã dẫn đến tình huống nghiêm trọng."),
        ],
        tips="に至る luôn đi cùng một QUÁ TRÌNH đứng trước (thường có 悪化/末に/ついに) — không dùng cho một sự việc xảy ra đột ngột, tức thời.",
        culture="Tin tức thời sự Nhật hay dùng に至る để tổng kết diễn biến một vụ việc: '〜が続き、ついに逮捕に至った' (... tiếp diễn, cuối cùng đã dẫn đến việc bị bắt giữ)."),

    slide(L, 2,
        "2. Còn nói riêng đến... thì... (nêu bật trường hợp cực đoan nhất): Aは〜が、Bに至っては",
        "A(bình thường)は〜が、B(trường hợp cực đoan nhất)に至っては、…",
        "に至っては dùng để SO SÁNH nhiều đối tượng/trường hợp, rồi NÊU BẬT một trường hợp CỰC ĐOAN "
        "NHẤT (thường tệ hơn hẳn các trường hợp còn lại đã nêu) — 'còn RIÊNG đến... thì...'.",
        [
            ex(L, 2, 1, [t("t-l5s2-1", "しゃいん", "社員", "しゃいん", key=True), t("t-l5s2-2", "は"),
                         t("t-l5s2-3", "まじめに", "真面目に", "まじめに"), t("t-l5s2-4", "はたらきました", "働きました", "はたらきました"),
                         t("t-l5s2-5", "が"), t("t-l5s2-6", "、"), t("t-l5s2-7", "しゃちょう", "社長", "しゃちょう", key=True),
                         t("t-l5s2-8", "に"), t("t-l5s2-9", "いたっては", "至っては", "いたっては", key=True), t("t-l5s2-10", "、"),
                         t("t-l5s2-11", "もんだい", "問題", "もんだい", key=True), t("t-l5s2-12", "を"),
                         t("t-l5s2-13", "ほうちしました", "放置しました", "ほうちしました")],
               "Nhân viên thì làm việc nghiêm túc, nhưng còn riêng giám đốc thì bỏ mặc vấn đề."),
            ex(L, 2, 2, [t("t-l5s2-14", "しゃいん", "社員", "しゃいん", key=True), t("t-l5s2-15", "は"),
                         t("t-l5s2-16", "うそ", "嘘", "うそ", key=True), t("t-l5s2-17", "を"),
                         t("t-l5s2-18", "つきません", "付きません", "つきません"), t("t-l5s2-19", "でした"),
                         t("t-l5s2-20", "が"), t("t-l5s2-21", "、"), t("t-l5s2-22", "しゃちょう", "社長", "しゃちょう", key=True),
                         t("t-l5s2-23", "に"), t("t-l5s2-24", "いたっては", "至っては", "いたっては", key=True), t("t-l5s2-25", "、"),
                         t("t-l5s2-26", "うそ", "嘘", "うそ", key=True), t("t-l5s2-27", "を"),
                         t("t-l5s2-28", "つきつづけました", "付き続けました", "つきつづけました")],
               "Nhân viên thì không nói dối, nhưng còn riêng giám đốc thì cứ tiếp tục nói dối."),
        ],
        tips="Khác に至る (diễn tả QUÁ TRÌNH → kết quả), に至っては dùng để SO SÁNH nhiều đối tượng rồi nhấn vào MỘT trường hợp tệ nhất.",
        culture="Văn phong phê phán trên báo Nhật hay dùng に至っては để nhấn mạnh người có TRÁCH NHIỆM CAO NHẤT lại là người tệ nhất trong vụ việc — tạo hiệu ứng châm biếm mạnh."),

    slide(L, 3,
        "3. Kết cục be bét là... (kết luận chê trách sau chuỗi sự việc xấu): 〜という始末だ",
        "[chuỗi hành động/sự việc xấu]、〜という始末だ",
        "という始末だ đặt ở CUỐI CÂU, sau khi liệt kê một chuỗi hành động/sự việc TIÊU CỰC, để "
        "KẾT LUẬN bằng một KẾT CỤC XẤU — mang sắc thái CHÊ TRÁCH, THẤT VỌNG hoặc BẤT LỰC rõ rệt của người nói.",
        [
            ex(L, 3, 1, [t("t-l5s3-1", "しゃちょう", "社長", "しゃちょう", key=True), t("t-l5s3-2", "は"),
                         t("t-l5s3-3", "うそ", "嘘", "うそ", key=True), t("t-l5s3-4", "を"),
                         t("t-l5s3-5", "つきつづけ", "付き続け", "つきつづけ"), t("t-l5s3-6", "、"),
                         t("t-l5s3-7", "だれも", "誰も", "だれも"), t("t-l5s3-8", "しんじない", "信じない", "しんじない"),
                         t("t-l5s3-9", "という"), t("t-l5s3-10", "しまつだ", "始末だ", "しまつだ", key=True)],
               "Giám đốc cứ tiếp tục nói dối, rốt cuộc đến mức chẳng ai còn tin nữa."),
            ex(L, 3, 2, [t("t-l5s3-11", "かいしゃ", "会社", "かいしゃ", key=True), t("t-l5s3-12", "は"),
                         t("t-l5s3-13", "もんだい", "問題", "もんだい", key=True), t("t-l5s3-14", "を"),
                         t("t-l5s3-15", "ほうちし", "放置し", "ほうちし"), t("t-l5s3-16", "、"),
                         t("t-l5s3-17", "とうさん", "倒産", "とうさん", key=True), t("t-l5s3-18", "する"),
                         t("t-l5s3-19", "という"), t("t-l5s3-20", "しまつだ", "始末だ", "しまつだ", key=True)],
               "Công ty cứ bỏ mặc vấn đề, rốt cuộc đến mức phá sản."),
        ],
        tips="という始末だ luôn mang giọng CHÊ TRÁCH — không dùng để kể một kết quả trung tính hay tích cực.",
        culture="始末 vốn nghĩa là 'thu dọn hậu quả' — thường thấy trong câu 'この始末をどうしてくれるんだ' (Anh định xử lý cái hậu quả này thế nào đây?), thể hiện sự tức giận trước một kết cục do người khác gây ra."),

    slide(L, 4,
        "4. Kết hợp trong một câu chuyện khủng hoảng hoàn chỉnh",
        "に至る (quá trình → kết quả) + に至っては (nêu bật trường hợp tệ nhất) + という始末だ (kết luận chê trách)",
        "Trong một bài tường thuật hoàn chỉnh về một vụ khủng hoảng, thường dùng に至る để nêu DIỄN "
        "BIẾN dẫn đến kết quả xấu, rồi に至っては để chỉ ra AI là người đáng trách nhất, và kết bằng "
        "という始末だ để THẲNG THẮN chê trách kết cục cuối cùng.",
        [
            ex(L, 4, 1, [t("t-l5s4-1", "かいしゃ", "会社", "かいしゃ", key=True), t("t-l5s4-2", "の"),
                         t("t-l5s4-3", "けいえい", "経営", "けいえい", key=True), t("t-l5s4-4", "は"),
                         t("t-l5s4-5", "あっかし", "悪化し", "あっかし"), t("t-l5s4-6", "、"),
                         t("t-l5s4-7", "とうさん", "倒産", "とうさん", key=True), t("t-l5s4-8", "に"),
                         t("t-l5s4-9", "いたりました", "至りました", "いたりました", key=True)],
               "Kinh doanh của công ty xấu đi, đã dẫn đến mức phá sản."),
            ex(L, 4, 2, [t("t-l5s4-10", "しゃいん", "社員", "しゃいん", key=True), t("t-l5s4-11", "は"),
                         t("t-l5s4-12", "ゆるしました", "許しました", "ゆるしました"), t("t-l5s4-13", "が"),
                         t("t-l5s4-14", "、"), t("t-l5s4-15", "しゃちょう", "社長", "しゃちょう", key=True),
                         t("t-l5s4-16", "に"), t("t-l5s4-17", "いたっては", "至っては", "いたっては", key=True), t("t-l5s4-18", "、"),
                         t("t-l5s4-19", "だれも", "誰も", "だれも"), t("t-l5s4-20", "ゆるさない", "許さない", "ゆるさない"),
                         t("t-l5s4-21", "という"), t("t-l5s4-22", "しまつです", "始末です", "しまつです", key=True)],
               "Nhân viên thì đã tha thứ, nhưng còn riêng giám đốc thì rốt cuộc đến mức chẳng ai tha thứ."),
        ],
        tips="Ba ngữ pháp này cùng nhóm văn phong TRANG TRỌNG, CHÊ TRÁCH — rất hợp khi kể lại một vụ bê bối, khủng hoảng theo trình tự thời gian.",
        culture="Cấu trúc tường thuật kinh điển trên báo Nhật: nêu quá trình xấu đi (に至る) → chỉ đích danh người đáng trách nhất (に至っては) → kết luận gay gắt (という始末だ)."),
]

DIALOGUE = [
    line(L, 1, "田中", "Người dẫn chương trình",
         [t("d5-1", "きょう", "今日", "きょう"), t("d5-2", "は"), t("d5-3", "かいしゃ", "会社", "かいしゃ", key=True),
          t("d5-4", "の"), t("d5-5", "じたい", "事態", "じたい", key=True), t("d5-6", "について"), t("d5-7", "はなします", "話します", "はなします")],
         "Hôm nay chúng ta nói về tình huống của công ty."),
    line(L, 2, "山本", "Chuyên gia kinh tế",
         [t("d5-8", "けいえい", "経営", "けいえい", key=True), t("d5-9", "が"), t("d5-10", "あっかし", "悪化し", "あっかし", key=True),
          t("d5-11", "、"), t("d5-12", "とうさん", "倒産", "とうさん", key=True), t("d5-13", "する"), t("d5-14", "に"),
          t("d5-15", "いたりました", "至りました", "いたりました", key=True)],
         "Kinh doanh xấu đi, đã dẫn đến mức phá sản."),
    line(L, 3, "田中", "Người dẫn chương trình",
         [t("d5-16", "しゃいん", "社員", "しゃいん", key=True), t("d5-17", "は"), t("d5-18", "どうでしたか")],
         "Nhân viên thì sao?"),
    line(L, 4, "山本", "Chuyên gia kinh tế",
         [t("d5-19", "しゃいん", "社員", "しゃいん", key=True), t("d5-20", "は"), t("d5-21", "まじめに", "真面目に", "まじめに"),
          t("d5-22", "はたらきました", "働きました", "はたらきました"), t("d5-23", "が"), t("d5-24", "、"),
          t("d5-25", "しゃちょう", "社長", "しゃちょう", key=True), t("d5-26", "に"), t("d5-27", "いたっては", "至っては", "いたっては", key=True),
          t("d5-28", "、"), t("d5-29", "もんだい", "問題", "もんだい", key=True), t("d5-30", "を"),
          t("d5-31", "ほうちしました", "放置しました", "ほうちしました")],
         "Nhân viên thì làm việc nghiêm túc, nhưng còn riêng giám đốc thì bỏ mặc vấn đề."),
    line(L, 5, "田中", "Người dẫn chương trình",
         [t("d5-32", "しゃちょう", "社長", "しゃちょう", key=True), t("d5-33", "は"), t("d5-34", "なんと", "何と", "なんと"),
          t("d5-35", "いいましたか", "言いましたか", "いいましたか")],
         "Giám đốc đã nói gì?"),
    line(L, 6, "山本", "Chuyên gia kinh tế",
         [t("d5-36", "いいわけ", "言い訳", "いいわけ", key=True), t("d5-37", "を"),
          t("d5-38", "つづけました", "続けました", "つづけました", key=True)],
         "Ông ấy cứ tiếp tục biện minh."),
    line(L, 7, "田中", "Người dẫn chương trình",
         [t("d5-39", "しゃいん", "社員", "しゃいん", key=True), t("d5-40", "は"), t("d5-41", "しゃちょう", "社長", "しゃちょう", key=True),
          t("d5-42", "を"), t("d5-43", "しんじましたか", "信じましたか", "しんじましたか")],
         "Nhân viên có tin giám đốc không?"),
    line(L, 8, "山本", "Chuyên gia kinh tế",
         [t("d5-44", "いいえ"), t("d5-45", "。"), t("d5-46", "うそ", "嘘", "うそ", key=True), t("d5-47", "を"),
          t("d5-48", "つきつづけ", "付き続け", "つきつづけ"), t("d5-49", "、"), t("d5-50", "だれも", "誰も", "だれも"),
          t("d5-51", "しんじない", "信じない", "しんじない"), t("d5-52", "という"), t("d5-53", "しまつです", "始末です", "しまつです", key=True)],
         "Không. Ông ấy cứ nói dối liên tục, rốt cuộc đến mức chẳng ai tin nữa."),
    line(L, 9, "田中", "Người dẫn chương trình",
         [t("d5-54", "しゃいん", "社員", "しゃいん", key=True), t("d5-55", "は"), t("d5-56", "しゃちょう", "社長", "しゃちょう", key=True),
          t("d5-57", "を"), t("d5-58", "ゆるしましたか", "許しましたか", "ゆるしましたか")],
         "Nhân viên có tha thứ cho giám đốc không?"),
    line(L, 10, "山本", "Chuyên gia kinh tế",
         [t("d5-59", "しゃちょう", "社長", "しゃちょう", key=True), t("d5-60", "に"), t("d5-61", "いたっては", "至っては", "いたっては", key=True),
          t("d5-62", "、"), t("d5-63", "だれも", "誰も", "だれも"), t("d5-64", "ゆるさない", "許さない", "ゆるさない"),
          t("d5-65", "という"), t("d5-66", "しまつです", "始末です", "しまつです", key=True)],
         "Còn riêng giám đốc thì, rốt cuộc đến mức chẳng ai tha thứ."),
]

EXERCISES = [
    q(L, 1, "「経営が悪化し、倒産するに至った」 — に至る diễn tả điều gì?",
      ["Một quá trình cuối cùng đã dẫn đến một kết quả nghiêm trọng",
       "Một sự việc xảy ra đột ngột, bất ngờ", "Sự cho phép làm việc gì đó",
       "Sự nghi ngờ về khả năng"], 0,
      "に至る diễn tả một QUÁ TRÌNH (thường tiêu cực) cuối cùng dẫn đến một kết quả nghiêm trọng, không dùng cho việc đột ngột.",
      "Xem cấu trúc に至る ở slide 1."),
    q(L, 2, "「社員は真面目に働いたが、社長に至っては、問題を放置した」 — に至っては dùng để làm gì?",
      ["So sánh nhiều đối tượng rồi nêu bật trường hợp CỰC ĐOAN NHẤT",
       "Diễn tả một quá trình dẫn đến kết quả", "Xin phép làm việc gì đó",
       "Đưa ra lời khuyên nhẹ nhàng"], 0,
      "に至っては dùng để so sánh, rồi nhấn mạnh vào MỘT trường hợp tệ hơn hẳn các trường hợp còn lại.",
      "Xem cấu trúc に至っては ở slide 2."),
    q(L, 3, "「社長は嘘をつき続け、誰も信じないという始末だ」 — という始末だ mang sắc thái gì?",
      ["Chê trách, thất vọng về một kết cục xấu sau chuỗi sự việc tiêu cực",
       "Khen ngợi một kết quả tốt đẹp", "Sự cho phép", "Sự nghi ngờ nhẹ nhàng"], 0,
      "という始末だ luôn mang giọng CHÊ TRÁCH, đặt sau một chuỗi hành động/sự việc xấu.",
      "Xem cấu trúc という始末だ ở slide 3."),
    q(L, 4, "Sự khác biệt cốt lõi giữa に至る và に至っては là gì?",
      ["に至る là QUÁ TRÌNH dẫn đến kết quả; に至っては là SO SÁNH để nêu bật trường hợp tệ nhất",
       "Hoàn toàn giống nhau, dùng thay thế được cho nhau",
       "に至る chỉ dùng cho câu hỏi", "に至っては chỉ dùng cho câu khẳng định"], 0,
      "に至る miêu tả một tiến trình dẫn tới kết quả; に至っては dùng để so sánh và nhấn vào trường hợp cực đoan nhất.",
      "Xem bảng phân biệt ở slide 4."),
    q(L, 5, "「小さい問題が、深刻な事態に至りました」 nghĩa là:",
      ["Vấn đề nhỏ, cuối cùng đã dẫn đến tình huống nghiêm trọng",
       "Vấn đề nhỏ đã được giải quyết hoàn toàn", "Không có vấn đề gì xảy ra",
       "Tình huống đã trở nên tốt hơn"], 0,
      "に至りました ở đây nhấn mạnh việc vấn đề nhỏ đã LEO THANG thành tình huống nghiêm trọng.",
      "Áp dụng cấu trúc に至る cho ngữ cảnh vấn đề leo thang."),
    q(L, 6, "Tại sao に至る, に至っては và という始末だ thường xuất hiện CÙNG NHAU trong một bài tường thuật?",
      ["Để kể diễn biến (に至る) → chỉ người đáng trách nhất (に至っては) → kết luận chê trách (という始末だ)",
       "Vì chúng có nghĩa giống hệt nhau nên dùng thay phiên", "Không có lý do đặc biệt",
       "Vì quy tắc ngữ pháp bắt buộc phải dùng chung"], 0,
      "Ba cấu trúc tạo thành một khung tường thuật hoàn chỉnh: diễn biến → ai đáng trách nhất → kết cục đáng chê trách.",
      "Xem kỹ thuật tường thuật ở slide 4."),
    q(L, 7, "「社員は嘘をつかなかったが、社長に至っては、嘘をつき続けた」 nghĩa là:",
      ["Nhân viên không nói dối, nhưng còn riêng giám đốc thì cứ tiếp tục nói dối",
       "Cả nhân viên và giám đốc đều không nói dối", "Cả nhân viên và giám đốc đều nói dối liên tục",
       "Chỉ nhân viên nói dối, giám đốc thì không"], 0,
      "に至っては ở đây nêu bật giám đốc là trường hợp TỆ HƠN HẲN so với nhân viên (đã không nói dối).",
      "Áp dụng cấu trúc に至っては cho ngữ cảnh so sánh nhân viên/giám đốc."),
    q(L, 8, "Theo hội thoại, giám đốc đã làm gì khi bị hỏi về vấn đề?",
      ["Cứ tiếp tục biện minh (言い訳を続けました)", "Xin lỗi ngay lập tức",
       "Từ chức ngay lập tức", "Không nói gì cả"], 0,
      "Chuyên gia nói 「言い訳を続けました」.",
      "Xem câu thoại thứ 6."),
    q(L, 9, "Theo hội thoại, kết cục của việc giám đốc nói dối liên tục là gì?",
      ["Rốt cuộc chẳng ai còn tin ông ấy nữa (誰も信じないという始末)",
       "Mọi người vẫn tin tưởng ông ấy", "Ông ấy đã sửa chữa được lỗi lầm",
       "Không được đề cập trong hội thoại"], 0,
      "Chuyên gia nói 「誰も信じないという始末です」.",
      "Xem câu thoại thứ 8."),
    q(L, 10, "Theo hội thoại, nhân viên có tha thứ cho giám đốc không?",
      ["Riêng giám đốc thì rốt cuộc chẳng ai tha thứ (社長に至っては、誰も許さないという始末)",
       "Tất cả đều đã tha thứ cho giám đốc", "Không được đề cập trong hội thoại",
       "Giám đốc đã tự tha thứ cho mình"], 0,
      "Chuyên gia nói 「社長に至っては、誰も許さないという始末です」.",
      "Xem câu thoại thứ 10."),
]

LESSON = lesson(
    L,
    "Bài 5: Diễn biến tiêu cực & Kết cục (に至る & に至っては & 始末だ)",
    "に至る diễn tả một QUÁ TRÌNH (thường tiêu cực) cuối cùng đã DẪN ĐẾN một kết quả nghiêm trọng; "
    "に至っては dùng để SO SÁNH nhiều đối tượng rồi NÊU BẬT trường hợp CỰC ĐOAN NHẤT; という始末だ đặt "
    "cuối câu để KẾT LUẬN một KẾT CỤC XẤU sau chuỗi sự việc tiêu cực, mang giọng CHÊ TRÁCH — ba cấu "
    "trúc thường kết hợp trong một bài tường thuật hoàn chỉnh về một vụ khủng hoảng.",
    VOCAB, KANJI, SLIDES, DIALOGUE, EXERCISES,
)

if __name__ == "__main__":
    pool.mark_used([w["word"] for w in VOCAB if w["word"]], lesson=L)
    merge([LESSON])
