# -*- coding: utf-8 -*-
"""N1 — Bai 3: Bat ke であれ〜であれ (doi lap, khong phan biet truong hop) va Du la といい〜といい
(cung chu the, nhan xet toan dien).

Tu vung minh hoa TU CHON tu pool mo data/jlpt-vocab/n1.csv (xem NOTICE.md).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from n1_lib import v, k, t, ex, slide, line, q, lesson, merge
from jlpt_pool import Pool

L = 3
pool = Pool("n1")

VOCAB = [
    v(1,  "あじわい", "味わい", "あじわい", "ajiwai", "noun", "Hương vị", "味わいと 品質 = hương vị và chất lượng.", L),
    v(2,  "ひんしつ", "品質", "ひんしつ", "hinshitsu", "noun", "Chất lượng", "品質が いい = chất lượng tốt.", L),
    v(3,  "みかく", "味覚", "みかく", "mikaku", "noun", "Vị giác", "味覚が するどい = vị giác nhạy bén.", L),
    v(4,  "とみ", "富", "とみ", "tomi", "noun", "Của cải, tài sản", "富を きずきます = xây dựng tài sản.", L),
    v(5,  "ふごう", "富豪", "ふごう", "fugou", "noun", "Người giàu có, triệu phú", "富豪であれ = dù là người giàu có.", L),
    v(6,  "きのう", "機能", "きのう", "kinou", "noun", "Chức năng", "機能が すぐれて います = chức năng vượt trội.", L),
    v(7,  "かんぺき", "完璧", "かんぺき", "kanpeki", "adjective", "Hoàn hảo", "完璧な せいひん = sản phẩm hoàn hảo.", L),
    v(8,  "せいじか", "政治家", "せいじか", "seijika", "noun", "Chính trị gia", "政治家であれ = dù là chính trị gia.", L),
    v(9,  "かいしゃいん", "会社員", "かいしゃいん", "kaishain", "noun", "Nhân viên công ty", "会社員であれ = dù là nhân viên công ty.", L),
    v(10, "すばらしい", "素晴らしい", "すばらしい", "subarashii", "adjective", "Tuyệt vời", "Đã gặp N4 bài 26.", L),
    v(11, "まずしい", "貧しい", "まずしい", "mazushii", "adjective", "Nghèo", "Đã gặp N3 bài 4.", L),
    v(12, "たちば", "立場", "たちば", "tachiba", "noun", "Lập trường", "Đã gặp N2 bài 8.", L),
    v(13, "みぶん", "身分", "みぶん", "mibun", "noun", "Thân phận, địa vị", "Đã gặp N4 bài 33.", L),
    v(14, "かのうせい", "可能性", "かのうせい", "kanousei", "noun", "Khả năng", "Đã gặp N3 bài 13.", L),
    v(15, "しょうひん", "商品", "しょうひん", "shouhin", "noun", "Hàng hóa", "Đã gặp N3 bài 6.", L),
    v(16, "びょうき", "病気", "びょうき", "byouki", "noun", "Bệnh", "Đã gặp N4 bài 26.", L),
    v(17, "ほうりつ", "法律", "ほうりつ", "houritsu", "noun", "Pháp luật", "Đã gặp N2 bài 2.", L),
    v(18, "まもります", "守ります", "まもります", "mamorimasu", "verb", "Tuân thủ, bảo vệ", "Đã gặp N3 bài 19.", L),
    v(19, "おなじ", "同じ", "おなじ", "onaji", "adjective", "Giống nhau", "Đã gặp N4 bài 26.", L),
    v(20, "せいひん", "製品", "せいひん", "seihin", "noun", "Sản phẩm", "Đã gặp N3 bài 6.", L),
]

KANJI = [
    k(1, "富", "PHÚ", 12, ["フ (fu)"], ["と(み)", "と(む)"], "Giàu có, phong phú.",
      [("富", "とみ", "Của cải"), ("富豪", "ふごう", "Người giàu có")], L),
    k(2, "豪", "HÀO", 14, ["ゴウ (gou)"], [], "Hào kiệt, mạnh mẽ.",
      [("富豪", "ふごう", "Triệu phú"), ("豪華", "ごうか", "Sang trọng")], L),
    k(3, "完", "HOÀN", 7, ["カン (kan)"], [], "Hoàn thành, đầy đủ.",
      [("完璧", "かんぺき", "Hoàn hảo"), ("完成", "かんせい", "Hoàn thành")], L),
    k(4, "璧", "BÍCH", 18, ["ヘキ (heki)"], [], "Ngọc bích, hoàn mỹ.",
      [("完璧", "かんぺき", "Hoàn hảo")], L),
    k(5, "覚", "GIÁC", 12, ["カク (kaku)"], ["おぼ(える)"], "Cảm giác, ghi nhớ.",
      [("味覚", "みかく", "Vị giác"), ("覚えます", "おぼえます", "Ghi nhớ")], L),
]

SLIDES = [
    slide(L, 1,
        "1. Bất kể, dù là... hay là... (đối lập): N1であれ、N2であれ",
        "N1であれ、N2であれ、[kết quả/nguyên tắc không đổi]",
        "であれ〜であれ liệt kê HAI (hoặc nhiều) khả năng ĐỐI LẬP để nhấn mạnh KHÔNG PHÂN BIỆT "
        "trường hợp nào xảy ra, kết quả/nguyên tắc vẫn GIỮ NGUYÊN — trang trọng, dùng trong quy tắc phổ quát.",
        [
            ex(L, 1, 1, [t("t-l3s1-1", "ふごう", "富豪", "ふごう", key=True), t("t-l3s1-2", "であれ", key=True),
                         t("t-l3s1-3", "、"), t("t-l3s1-4", "まずしい", "貧しい", "まずしい", key=True), t("t-l3s1-5", "ひと", "人", "ひと"),
                         t("t-l3s1-6", "であれ", key=True), t("t-l3s1-7", "、"), t("t-l3s1-8", "びょうき", "病気", "びょうき", key=True),
                         t("t-l3s1-9", "に"), t("t-l3s1-10", "なる"), t("t-l3s1-11", "かのうせい", "可能性", "かのうせい", key=True),
                         t("t-l3s1-12", "は"), t("t-l3s1-13", "おなじ", "同じ", "おなじ", key=True), t("t-l3s1-14", "です")],
               "Dù là người giàu có hay người nghèo, khả năng bị bệnh đều như nhau."),
            ex(L, 1, 2, [t("t-l3s1-15", "せいじか", "政治家", "せいじか", key=True), t("t-l3s1-16", "であれ", key=True),
                         t("t-l3s1-17", "、"), t("t-l3s1-18", "かいしゃいん", "会社員", "かいしゃいん", key=True), t("t-l3s1-19", "であれ", key=True),
                         t("t-l3s1-20", "、"), t("t-l3s1-21", "ほうりつ", "法律", "ほうりつ", key=True), t("t-l3s1-22", "を"),
                         t("t-l3s1-23", "まもらなければ", "守らなければ", "まもらなければ", key=True), t("t-l3s1-24", "なりません")],
               "Dù là chính trị gia hay nhân viên công ty, đều phải tuân theo pháp luật."),
        ],
        tips="であれ dùng được cho cả DANH TỪ (như ví dụ trên) — không cần V/A, thích hợp để liệt kê các NHÓM NGƯỜI/vai trò khác nhau.",
        culture="Hiến pháp, quy định pháp lý Nhật hay viết: '国籍であれ、性別であれ、平等に扱われる' (dù quốc tịch hay giới tính nào, đều được đối xử bình đẳng)."),

    slide(L, 2,
        "2. Cả... lẫn... (cùng một chủ thể, khen toàn diện): N1といい、N2といい",
        "N1といい、N2といい、[nhận xét chung, thường khen ngợi]",
        "といい〜といい liệt kê HAI KHÍA CẠNH của CÙNG MỘT CHỦ THỂ (không phải hai lựa chọn đối "
        "lập như であれ) để đưa ra một NHẬN XÉT TOÀN DIỆN — thường mang tính KHEN NGỢI (đôi khi chê).",
        [
            ex(L, 2, 1, [t("t-l3s2-1", "あじわい", "味わい", "あじわい", key=True), t("t-l3s2-2", "と"),
                         t("t-l3s2-3", "いい", key=True), t("t-l3s2-4", "、"), t("t-l3s2-5", "ひんしつ", "品質", "ひんしつ", key=True),
                         t("t-l3s2-6", "と"), t("t-l3s2-7", "いい", key=True), t("t-l3s2-8", "、"),
                         t("t-l3s2-9", "この"), t("t-l3s2-10", "しょうひん", "商品", "しょうひん", key=True), t("t-l3s2-11", "は"),
                         t("t-l3s2-12", "かんぺき", "完璧", "かんぺき", key=True), t("t-l3s2-13", "です")],
               "Cả về hương vị lẫn chất lượng, sản phẩm này đều hoàn hảo."),
            ex(L, 2, 2, [t("t-l3s2-14", "たちば", "立場", "たちば", key=True), t("t-l3s2-15", "と"),
                         t("t-l3s2-16", "いい", key=True), t("t-l3s2-17", "、"), t("t-l3s2-18", "みぶん", "身分", "みぶん", key=True),
                         t("t-l3s2-19", "と"), t("t-l3s2-20", "いい", key=True), t("t-l3s2-21", "、"),
                         t("t-l3s2-22", "かれ", "彼", "かれ"), t("t-l3s2-23", "は"), t("t-l3s2-24", "すばらしい", "素晴らしい", "すばらしい", key=True),
                         t("t-l3s2-25", "ひと", "人", "ひと"), t("t-l3s2-26", "です")],
               "Cả về lập trường lẫn địa vị, anh ấy đều là người tuyệt vời."),
        ],
        tips="といい〜といい KHÁC であれ〜であれ ở chỗ: hai vế trong といい luôn là hai KHÍA CẠNH của CÙNG một sự vật/người, không phải hai LỰA CHỌN riêng biệt.",
        culture="Quảng cáo sản phẩm Nhật hay dùng: '味といい、価格といい、お客様に満足していただけます' (cả về hương vị lẫn giá cả, đều làm hài lòng quý khách)."),

    slide(L, 3,
        "3. So sánh であれ〜であれ và といい〜といい",
        "であれ〜であれ: hai LỰA CHỌN đối lập, không phân biệt trường hợp nào　vs　といい〜といい: hai KHÍA CẠNH của CÙNG một chủ thể, nhận xét toàn diện",
        "であれ〜であれ liệt kê hai khả năng KHÁC NHAU/ĐỐI LẬP (ví dụ: giàu HAY nghèo) để nói kết "
        "quả không đổi; といい〜といい liệt kê hai MẶT của MỘT chủ thể duy nhất (ví dụ: hương vị VÀ "
        "chất lượng của CÙNG một sản phẩm) để đưa ra nhận xét tổng thể.",
        [
            ex(L, 3, 1, [t("t-l3s3-1", "ふごう", "富豪", "ふごう", key=True), t("t-l3s3-2", "であれ", key=True),
                         t("t-l3s3-3", "、"), t("t-l3s3-4", "せいじか", "政治家", "せいじか", key=True), t("t-l3s3-5", "であれ", key=True),
                         t("t-l3s3-6", "、"), t("t-l3s3-7", "きそく", "規則", "きそく"), t("t-l3s3-8", "は"),
                         t("t-l3s3-9", "おなじ", "同じ", "おなじ", key=True), t("t-l3s3-10", "です")],
               "Dù là triệu phú hay chính trị gia, quy tắc đều như nhau. (2 lựa chọn đối lập)"),
            ex(L, 3, 2, [t("t-l3s3-11", "きのう", "機能", "きのう", key=True), t("t-l3s3-12", "と"),
                         t("t-l3s3-13", "いい", key=True), t("t-l3s3-14", "、"), t("t-l3s3-15", "みかく", "味覚", "みかく", key=True),
                         t("t-l3s3-16", "の"), t("t-l3s3-17", "たのしみ", "楽しみ", "たのしみ"), t("t-l3s3-18", "と"),
                         t("t-l3s3-19", "いい", key=True), t("t-l3s3-20", "、"), t("t-l3s3-21", "この"),
                         t("t-l3s3-22", "せいひん", "製品", "せいひん", key=True), t("t-l3s3-23", "は"),
                         t("t-l3s3-24", "かんぺき", "完璧", "かんぺき", key=True), t("t-l3s3-25", "です")],
               "Cả về chức năng lẫn niềm vui vị giác, sản phẩm này đều hoàn hảo. (2 khía cạnh của 1 chủ thể)"),
        ],
        tips="Mẹo: nếu hai vế là hai LỰA CHỌN KHÁC NHAU (A hay B) → であれ; nếu hai vế là hai MẶT của CÙNG MỘT thứ (A và B của C) → といい.",
        culture="Cả hai đều là ngữ pháp N1 trọng điểm — nhầm lẫn giữa 'lựa chọn đối lập' và 'khía cạnh của cùng một vật' là lỗi phổ biến của người học."),

    slide(L, 4,
        "4. であれ dùng độc lập (chỉ một vế): N + であれ",
        "N + であれ、[kết quả/nguyên tắc không đổi]",
        "であれ có thể dùng ĐỘC LẬP (không cần lặp lại であれ lần hai) khi chỉ có MỘT trường hợp "
        "cần nhấn mạnh 'DÙ LÀ...' vẫn không làm thay đổi kết quả/nguyên tắc.",
        [
            ex(L, 4, 1, [t("t-l3s4-1", "しゃちょう", "社長", "しゃちょう"), t("t-l3s4-2", "であれ", key=True),
                         t("t-l3s4-3", "、"), t("t-l3s4-4", "きそく", "規則", "きそく"), t("t-l3s4-5", "を"),
                         t("t-l3s4-6", "まもらなければ", "守らなければ", "まもらなければ", key=True), t("t-l3s4-7", "なりません")],
               "Dù là giám đốc, cũng phải tuân theo quy tắc."),
            ex(L, 4, 2, [t("t-l3s4-8", "ふごう", "富豪", "ふごう", key=True), t("t-l3s4-9", "であれ", key=True),
                         t("t-l3s4-10", "、"), t("t-l3s4-11", "びょうき", "病気", "びょうき", key=True), t("t-l3s4-12", "に"),
                         t("t-l3s4-13", "なる"), t("t-l3s4-14", "かのうせい", "可能性", "かのうせい"), t("t-l3s4-15", "が"),
                         t("t-l3s4-16", "あります", "有ります", "あります")],
               "Dù là người giàu có, vẫn có khả năng bị bệnh."),
        ],
        tips="Dạng độc lập であれ gần giống でも thông thường nhưng TRANG TRỌNG hơn nhiều, thường thấy trong quy định, phát biểu chính thức.",
        culture="Thông báo nội quy công ty Nhật hay viết: '新入社員であれ、規則を守る義務がある' (dù là nhân viên mới, cũng có nghĩa vụ tuân thủ quy tắc)."),
]

DIALOGUE = [
    line(L, 1, "田中", "Nhà báo",
         [t("d3-1", "この"), t("d3-2", "しょうひん", "商品", "しょうひん", key=True), t("d3-3", "は"),
          t("d3-4", "どうですか")],
         "Sản phẩm này thế nào?"),
    line(L, 2, "サントス", "Nhà sản xuất",
         [t("d3-5", "あじわい", "味わい", "あじわい", key=True), t("d3-6", "と"), t("d3-7", "いい", key=True),
          t("d3-8", "、"), t("d3-9", "ひんしつ", "品質", "ひんしつ", key=True), t("d3-10", "と"),
          t("d3-11", "いい", key=True), t("d3-12", "、"), t("d3-13", "かんぺき", "完璧", "かんぺき", key=True),
          t("d3-14", "です")],
         "Cả về hương vị lẫn chất lượng đều hoàn hảo."),
    line(L, 3, "田中", "Nhà báo",
         [t("d3-15", "きのう", "機能", "きのう", key=True), t("d3-16", "は"), t("d3-17", "どうですか")],
         "Chức năng thì sao?"),
    line(L, 4, "サントス", "Nhà sản xuất",
         [t("d3-18", "みかく", "味覚", "みかく", key=True), t("d3-19", "と"), t("d3-20", "いい", key=True),
          t("d3-21", "、"), t("d3-22", "きのう", "機能", "きのう", key=True), t("d3-23", "と"), t("d3-24", "いい", key=True),
          t("d3-25", "、"), t("d3-26", "すばらしい", "素晴らしい", "すばらしい", key=True), t("d3-27", "せいひん", "製品", "せいひん", key=True),
          t("d3-28", "です")],
         "Cả về vị giác lẫn chức năng, đều là sản phẩm tuyệt vời."),
    line(L, 5, "田中", "Nhà báo",
         [t("d3-29", "ふごう", "富豪", "ふごう", key=True), t("d3-30", "であれ", key=True), t("d3-31", "、"),
          t("d3-32", "まずしい", "貧しい", "まずしい", key=True), t("d3-33", "ひと", "人", "ひと"), t("d3-34", "であれ", key=True),
          t("d3-35", "、"), t("d3-36", "だれ", "誰", "だれ"), t("d3-37", "でも"), t("d3-38", "つかえます", "使えます", "つかえます"),
          t("d3-39", "か")],
         "Dù là người giàu hay người nghèo, ai cũng dùng được chứ?"),
    line(L, 6, "サントス", "Nhà sản xuất",
         [t("d3-40", "はい"), t("d3-41", "。"), t("d3-42", "みぶん", "身分", "みぶん", key=True), t("d3-43", "であれ", key=True),
          t("d3-44", "、"), t("d3-45", "たちば", "立場", "たちば", key=True), t("d3-46", "であれ", key=True),
          t("d3-47", "、"), t("d3-48", "だれ", "誰", "だれ"), t("d3-49", "でも"), t("d3-50", "つかえます", "使えます", "つかえます")],
         "Vâng. Dù là địa vị hay lập trường nào, ai cũng dùng được."),
    line(L, 7, "田中", "Nhà báo",
         [t("d3-51", "せいじか", "政治家", "せいじか", key=True), t("d3-52", "であれ", key=True), t("d3-53", "、"),
          t("d3-54", "かいしゃいん", "会社員", "かいしゃいん", key=True), t("d3-55", "であれ", key=True), t("d3-56", "、"),
          t("d3-57", "みんな"), t("d3-58", "こうにゅう", "購入", "こうにゅう"), t("d3-59", "できます", "出来ます", "できます"),
          t("d3-60", "か")],
         "Dù là chính trị gia hay nhân viên công ty, mọi người đều mua được chứ?"),
    line(L, 8, "サントス", "Nhà sản xuất",
         [t("d3-61", "はい"), t("d3-62", "。"), t("d3-63", "しゃちょう", "社長", "しゃちょう"), t("d3-64", "であれ", key=True),
          t("d3-65", "、"), t("d3-66", "きそく", "規則", "きそく"), t("d3-67", "は"), t("d3-68", "おなじ", "同じ", "おなじ", key=True),
          t("d3-69", "です")],
         "Vâng. Dù là giám đốc, quy tắc vẫn giống nhau."),
    line(L, 9, "田中", "Nhà báo",
         [t("d3-70", "とみ", "富", "とみ", key=True), t("d3-71", "が"), t("d3-72", "あって", "有って", "あって"),
          t("d3-73", "も"), t("d3-74", "びょうき", "病気", "びょうき", key=True), t("d3-75", "に"), t("d3-76", "なる"),
          t("d3-77", "かのうせい", "可能性", "かのうせい", key=True), t("d3-78", "は"), t("d3-79", "おなじ", "同じ", "おなじ"),
          t("d3-80", "です", "です", "です"), t("d3-81", "か")],
         "Dù có tài sản, khả năng bị bệnh vẫn giống nhau chứ?"),
    line(L, 10, "サントス", "Nhà sản xuất",
         [t("d3-82", "はい"), t("d3-83", "。"), t("d3-84", "ふごう", "富豪", "ふごう", key=True), t("d3-85", "であれ", key=True),
          t("d3-86", "、"), t("d3-87", "びょうき", "病気", "びょうき", key=True), t("d3-88", "に"), t("d3-89", "なる"),
          t("d3-90", "かのうせい", "可能性", "かのうせい", key=True), t("d3-91", "が"), t("d3-92", "あります", "有ります", "あります")],
         "Vâng. Dù là người giàu, vẫn có khả năng bị bệnh."),
]

EXERCISES = [
    q(L, 1, "「富豪であれ、貧しい人であれ、病気になる可能性は同じです」 — であれ〜であれ diễn tả điều gì?",
      ["Liệt kê hai lựa chọn đối lập để nhấn mạnh không phân biệt trường hợp nào, kết quả vẫn giữ nguyên",
       "Liệt kê hai khía cạnh của cùng một chủ thể để khen ngợi", "Sự khẳng định chắc chắn",
       "Sự từ chối lịch sự"], 0,
      "であれ〜であれ liệt kê hai khả năng ĐỐI LẬP (giàu/nghèo) để nhấn mạnh kết quả không đổi.",
      "Xem cấu trúc であれ〜であれ ở slide 1."),
    q(L, 2, "「味わいといい、品質といい、この商品は完璧です」 — といい〜といい khác であれ〜であれ ở điểm nào?",
      ["といい〜といい liệt kê hai KHÍA CẠNH của CÙNG một chủ thể, không phải hai lựa chọn đối lập",
       "Hoàn toàn giống nhau, dùng thay thế được cho nhau",
       "といい chỉ dùng cho câu hỏi", "であれ chỉ dùng cho phủ định"], 0,
      "といい〜といい liệt kê hai mặt (hương vị, chất lượng) của CÙNG một sản phẩm, khác であれ là hai lựa chọn khác nhau.",
      "Xem giải thích といい〜といい ở slide 2."),
    q(L, 3, "Có thể dùng であれ〜であれ để nói về 'hương vị và chất lượng của cùng một sản phẩm' không?",
      ["Không tự nhiên — であれ dành cho hai LỰA CHỌN đối lập, nên dùng といい〜といい mới đúng",
       "Có, hoàn toàn tự nhiên", "Chỉ đúng trong văn viết trang trọng",
       "Chỉ đúng khi nói về sản phẩm đắt tiền"], 0,
      "であれ〜であれ dành cho hai lựa chọn KHÁC NHAU/đối lập, không phù hợp khi nói về hai khía cạnh của MỘT chủ thể.",
      "Xem mẹo phân biệt ở slide 3."),
    q(L, 4, "「社長であれ、規則を守らなければなりません」 — であれ ở đây dùng như thế nào?",
      ["Dùng ĐỘC LẬP (chỉ một vế) để nhấn mạnh 'dù là...' vẫn không đổi nguyên tắc",
       "Phải luôn dùng lặp lại hai lần であれ〜であれ", "Đây là lỗi ngữ pháp",
       "Chỉ dùng được cho câu hỏi"], 0,
      "であれ có thể dùng ĐỘC LẬP (một vế) khi chỉ cần nhấn mạnh một trường hợp cụ thể.",
      "Xem cấu trúc độc lập ở slide 4."),
    q(L, 5, "「政治家であれ、会社員であれ、法律を守らなければなりません」 nghĩa là:",
      ["Dù là chính trị gia hay nhân viên công ty, đều phải tuân theo pháp luật",
       "Chỉ chính trị gia mới cần tuân theo pháp luật", "Không ai cần tuân theo pháp luật",
       "Chỉ nhân viên công ty mới cần tuân theo pháp luật"], 0,
      "であれ〜であれ ở đây liệt kê hai vai trò khác nhau (chính trị gia/nhân viên) để nói nghĩa vụ không đổi với ai.",
      "Áp dụng cấu trúc N1であれ、N2であれ."),
    q(L, 6, "「機能といい、味覚の楽しみといい、この製品は完璧です」 nghĩa là:",
      ["Cả về chức năng lẫn niềm vui vị giác, sản phẩm này đều hoàn hảo",
       "Chỉ chức năng là tốt, vị giác thì không", "Sản phẩm này không có chức năng gì",
       "Chỉ vị giác là tốt, chức năng thì không"], 0,
      "といい〜といい ở đây khen ngợi TOÀN DIỆN cả hai khía cạnh (chức năng và vị giác) của cùng sản phẩm.",
      "Áp dụng cấu trúc N1といい、N2といい."),
    q(L, 7, "Xếp であれ〜であれ và といい〜といい theo tiêu chí phân biệt chính:",
      ["であれ = hai lựa chọn KHÁC NHAU; といい = hai khía cạnh của CÙNG một chủ thể",
       "であれ = trang trọng; といい = thân mật (không có khác biệt về nghĩa)",
       "Cả hai hoàn toàn giống nhau", "であれ chỉ dùng cho người; といい chỉ dùng cho vật"], 0,
      "Tiêu chí phân biệt chính là: であれ cho lựa chọn đối lập; といい cho khía cạnh của cùng một thứ.",
      "Xem bảng so sánh ở slide 3."),
    q(L, 8, "Theo hội thoại, sản phẩm được đánh giá thế nào về hương vị và chất lượng?",
      ["Hoàn hảo cả hai (味わいといい、品質といい、完璧です)", "Chỉ hương vị tốt",
       "Chỉ chất lượng tốt", "Cả hai đều không tốt"], 0,
      "Santos nói 「味わいといい、品質といい、完璧です」.",
      "Xem câu thoại thứ 2."),
    q(L, 9, "Theo hội thoại, ai có thể sử dụng sản phẩm này?",
      ["Bất kể địa vị hay lập trường nào, ai cũng dùng được (身分であれ、立場であれ、誰でも使えます)",
       "Chỉ người giàu mới dùng được", "Chỉ chính trị gia mới dùng được",
       "Không ai dùng được"], 0,
      "Santos nói 「身分であれ、立場であれ、誰でも使えます」.",
      "Xem câu thoại thứ 6."),
    q(L, 10, "Khả năng bị bệnh có giống nhau giữa người giàu và người nghèo không theo hội thoại?",
      ["Có, dù giàu vẫn có khả năng bị bệnh (富豪であれ、病気になる可能性があります)",
       "Không, người giàu không bao giờ bị bệnh", "Chỉ người nghèo mới bị bệnh",
       "Không được đề cập trong hội thoại"], 0,
      "Santos xác nhận 「富豪であれ、病気になる可能性があります」.",
      "Xem câu thoại cuối cùng."),
]

LESSON = lesson(
    L,
    "Bài 3: Bất kể & Dù là (であれ〜であれ & といい〜といい)",
    "であれ〜であれ liệt kê HAI LỰA CHỌN ĐỐI LẬP (giàu hay nghèo, chính trị gia hay nhân viên) để "
    "nhấn mạnh KHÔNG PHÂN BIỆT trường hợp nào, kết quả/nguyên tắc vẫn không đổi — có thể dùng ĐỘC "
    "LẬP (một vế); といい〜といい liệt kê HAI KHÍA CẠNH của CÙNG MỘT chủ thể để đưa ra NHẬN XÉT "
    "TOÀN DIỆN, thường mang tính khen ngợi.",
    VOCAB, KANJI, SLIDES, DIALOGUE, EXERCISES,
)

if __name__ == "__main__":
    pool.mark_used([w["word"] for w in VOCAB if w["word"]], lesson=L)
    merge([LESSON])
