# -*- coding: utf-8 -*-
"""N2 — Bai 6: Khoi diem を契機に (buoc ngoat ca nhan) va を皮切りに (khoi dau chuoi su kien).

Tu vung minh hoa TU CHON tu pool mo data/jlpt-vocab/n2.csv (xem NOTICE.md).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from n2_lib import v, k, t, ex, slide, line, q, lesson, merge
from jlpt_pool import Pool

L = 6
pool = Pool("n2")

VOCAB = [
    v(1,  "けいき", "契機", "けいき", "keiki", "noun", "Cơ hội, động lực (bước ngoặt)", "留学を 契機に = lấy việc du học làm cơ hội.", L),
    v(2,  "かわきり", "皮切り", "かわきり", "kawakiri", "noun", "Khởi đầu, mở màn", "東京を 皮切りに = bắt đầu từ Tokyo.", L),
    v(3,  "きっかけ", "きっかけ", "きっかけ", "kikkake", "noun", "Cơ hội, động lực (thân mật)", "きっかけを つかみます = nắm bắt cơ hội.", L),
    v(4,  "しんろ", "進路", "しんろ", "shinro", "noun", "Con đường sự nghiệp/tương lai", "進路を 変えます = thay đổi con đường sự nghiệp.", L),
    v(5,  "できごと", "出来事", "できごと", "dekigoto", "noun", "Sự kiện, sự việc", "大きな 出来事 = sự kiện lớn.", L),
    v(6,  "してん", "支店", "してん", "shiten", "noun", "Chi nhánh", "支店を 開きます = mở chi nhánh.", L),
    v(7,  "かつどうします", "活動します", "かつどうします", "katsudou shimasu", "verb", "Hoạt động", "全国で 活動します = hoạt động trên toàn quốc.", L),
    v(8,  "りゅうがくします", "留学します", "りゅうがくします", "ryuugaku shimasu", "verb", "Du học", "Đã gặp N4 bài 26.", L),
    v(9,  "かいがい", "海外", "かいがい", "kaigai", "noun", "Nước ngoài", "Đã gặp N5 bài 25.", L),
    v(10, "かいしゃ", "会社", "かいしゃ", "kaisha", "noun", "Công ty", "Đã gặp N4 bài 26.", L),
    v(11, "はじめます", "始めます", "はじめます", "hajimemasu", "verb", "Bắt đầu", "Đã gặp N4 bài 26.", L),
    v(12, "つづけます", "続けます", "つづけます", "tsuzukemasu", "verb", "Tiếp tục", "Đã gặp N4 bài 28.", L),
    v(13, "ぜんこく", "全国", "ぜんこく", "zenkoku", "noun", "Toàn quốc", "Đã gặp N3 bài 7.", L),
    v(14, "かいぎ", "会議", "かいぎ", "kaigi", "noun", "Cuộc họp", "Đã gặp N4 bài 30.", L),
    v(15, "とうきょう", "東京", "とうきょう", "toukyou", "noun", "Tokyo", "Đã gặp N4 bài 26.", L),
    v(16, "しごと", "仕事", "しごと", "shigoto", "noun", "Công việc", "Đã gặp N4 bài 26.", L),
    v(17, "かわります", "変わります", "かわります", "kawarimasu", "verb", "Thay đổi", "Đã gặp N2 bài 5.", L),
    v(18, "つよく", "強く", "つよく", "tsuyoku", "adverb", "Mạnh mẽ", "Đã gặp N2 bài 5.", L),
    v(19, "けいけん", "経験", "けいけん", "keiken", "noun", "Kinh nghiệm", "Đã gặp N4 bài 26.", L),
    v(20, "けいざい", "経済", "けいざい", "keizai", "noun", "Kinh tế", "Đã gặp N3 bài 14.", L),
]

KANJI = [
    k(1, "契", "KHẾ", 9, ["ケイ (kei)"], ["ちぎ(る)"], "Giao ước, khế ước.",
      [("契機", "けいき", "Cơ hội, động lực"), ("契約", "けいやく", "Hợp đồng")], L),
    k(2, "機", "CƠ", 16, ["キ (ki)"], [], "Cơ hội, máy móc.",
      [("契機", "けいき", "Cơ hội, động lực"), ("機械", "きかい", "Máy móc")], L),
    k(3, "皮", "BÌ", 5, ["ヒ (hi)"], ["かわ"], "Da, vỏ.",
      [("皮切り", "かわきり", "Khởi đầu, mở màn"), ("皮膚", "ひふ", "Làn da")], L),
    k(4, "支", "CHI", 4, ["シ (shi)"], ["ささ(える)"], "Chi nhánh, hỗ trợ.",
      [("支店", "してん", "Chi nhánh"), ("支える", "ささえる", "Hỗ trợ, nâng đỡ")], L),
    k(5, "路", "LỘ", 13, ["ロ (ro)"], ["じ"], "Con đường.",
      [("進路", "しんろ", "Con đường sự nghiệp"), ("道路", "どうろ", "Đường xá")], L),
]

SLIDES = [
    slide(L, 1,
        "1. Lấy làm cơ hội/động lực (bước ngoặt cá nhân): N + を契機に",
        "N(sự kiện có ý nghĩa) + を契機に、[thay đổi/hành động mới]",
        "を契機に diễn tả việc LẤY một sự kiện làm CƠ HỘI/ĐỘNG LỰC để bắt đầu một THAY ĐỔI TÍCH "
        "CỰC — thường dùng cho sự kiện có Ý NGHĨA CÁ NHÂN, mang tính CHỌN LỰA/QUYẾT TÂM của chủ thể.",
        [
            ex(L, 1, 1, [t("t-l6s1-1", "りゅうがく", "留学", "りゅうがく", key=True), t("t-l6s1-2", "を"),
                         t("t-l6s1-3", "けいき", "契機", "けいき", key=True), t("t-l6s1-4", "に"),
                         t("t-l6s1-5", "、"), t("t-l6s1-6", "しんろ", "進路", "しんろ", key=True), t("t-l6s1-7", "を"),
                         t("t-l6s1-8", "かえました", "変えました", "かえました")],
               "Lấy việc du học làm cơ hội, tôi đã thay đổi con đường sự nghiệp."),
            ex(L, 1, 2, [t("t-l6s1-9", "この"), t("t-l6s1-10", "できごと", "出来事", "できごと", key=True),
                         t("t-l6s1-11", "を"), t("t-l6s1-12", "けいき", "契機", "けいき", key=True), t("t-l6s1-13", "に"),
                         t("t-l6s1-14", "、"), t("t-l6s1-15", "かいしゃ", "会社", "かいしゃ", key=True), t("t-l6s1-16", "を"),
                         t("t-l6s1-17", "はじめました", "始めました", "はじめました")],
               "Lấy sự kiện này làm động lực, tôi đã bắt đầu công ty."),
        ],
        tips="を契機に thường dùng cho MỘT sự kiện DUY NHẤT trở thành bước ngoặt của một cá nhân — mang văn phong trang trọng, thường thấy trong tiểu sử, phỏng vấn.",
        culture="Câu phỏng vấn kinh điển ở Nhật: '何をきっかけに/契機に、この仕事を選びましたか' (bạn đã chọn công việc này nhân cơ hội/động lực nào)."),

    slide(L, 2,
        "2. Bắt đầu từ... (khởi đầu một chuỗi sự kiện): N + を皮切りに",
        "N(điểm khởi đầu) + を皮切りに、[chuỗi sự kiện/hoạt động tiếp theo]",
        "を皮切りに diễn tả việc BẮT ĐẦU TỪ một điểm mốc rồi TIẾP TỤC MỞ RỘNG thành một CHUỖI/"
        "LOẠT sự kiện khác — nhấn mạnh SỰ KHỞI ĐẦU của một quá trình liên tiếp, thường dùng khi nói về mở rộng kinh doanh.",
        [
            ex(L, 2, 1, [t("t-l6s2-1", "とうきょう", "東京", "とうきょう", key=True), t("t-l6s2-2", "を"),
                         t("t-l6s2-3", "かわきり", "皮切り", "かわきり", key=True), t("t-l6s2-4", "に"),
                         t("t-l6s2-5", "、"), t("t-l6s2-6", "ぜんこく", "全国", "ぜんこく", key=True), t("t-l6s2-7", "で"),
                         t("t-l6s2-8", "かつどう", "活動", "かつどう", key=True), t("t-l6s2-9", "を"),
                         t("t-l6s2-10", "つづけます", "続けます", "つづけます")],
               "Bắt đầu từ Tokyo, chúng tôi sẽ tiếp tục hoạt động trên toàn quốc."),
            ex(L, 2, 2, [t("t-l6s2-11", "この"), t("t-l6s2-12", "してん", "支店", "してん", key=True), t("t-l6s2-13", "を"),
                         t("t-l6s2-14", "かわきり", "皮切り", "かわきり", key=True), t("t-l6s2-15", "に"),
                         t("t-l6s2-16", "、"), t("t-l6s2-17", "いくつか"), t("t-l6s2-18", "の"),
                         t("t-l6s2-19", "してん", "支店", "してん", key=True), t("t-l6s2-20", "が"),
                         t("t-l6s2-21", "つづきます", "続きます", "つづきます")],
               "Bắt đầu từ chi nhánh này, sẽ có một loạt chi nhánh khác tiếp diễn."),
        ],
        tips="を皮切りに luôn ngụ ý SẼ CÓ THÊM nhiều sự kiện/hoạt động tương tự tiếp theo — không dùng cho một sự kiện đơn lẻ, kết thúc.",
        culture="Thông cáo báo chí doanh nghiệp Nhật hay dùng: '大阪店を皮切りに、全国に10店舗を出店する予定です' (bắt đầu từ cửa hàng Osaka, dự kiến sẽ mở 10 cửa hàng trên toàn quốc)."),

    slide(L, 3,
        "3. So sánh を契機に và を皮切りに",
        "を契機に: BƯỚC NGOẶT cá nhân (một sự kiện duy nhất)　vs　を皮切りに: KHỞI ĐẦU của một CHUỖI sự kiện tiếp diễn",
        "を契機に nhấn Ý NGHĨA CỦA SỰ THAY ĐỔI (một sự kiện làm động lực để chuyển hướng); を皮切り"
        "に nhấn TRÌNH TỰ THỜI GIAN của một LOẠT hoạt động sẽ tiếp diễn sau điểm khởi đầu đó.",
        [
            ex(L, 3, 1, [t("t-l6s3-1", "かいがい", "海外", "かいがい", key=True), t("t-l6s3-2", "の"),
                         t("t-l6s3-3", "けいけん", "経験", "けいけん", key=True), t("t-l6s3-4", "を"),
                         t("t-l6s3-5", "けいき", "契機", "けいき", key=True), t("t-l6s3-6", "に"),
                         t("t-l6s3-7", "、"), t("t-l6s3-8", "しんろ", "進路", "しんろ", key=True), t("t-l6s3-9", "を"),
                         t("t-l6s3-10", "かえました", "変えました", "かえました")],
               "Lấy kinh nghiệm ở nước ngoài làm động lực, tôi đã thay đổi con đường sự nghiệp. (bước ngoặt cá nhân)"),
            ex(L, 3, 2, [t("t-l6s3-11", "この"), t("t-l6s3-12", "かいぎ", "会議", "かいぎ", key=True), t("t-l6s3-13", "を"),
                         t("t-l6s3-14", "かわきり", "皮切り", "かわきり", key=True), t("t-l6s3-15", "に"),
                         t("t-l6s3-16", "、"), t("t-l6s3-17", "けいざい", "経済", "けいざい", key=True), t("t-l6s3-18", "の"),
                         t("t-l6s3-19", "かいぎ", "会議", "かいぎ", key=True), t("t-l6s3-20", "が"),
                         t("t-l6s3-21", "つづきます", "続きます", "つづきます")],
               "Bắt đầu từ cuộc họp này, sẽ có một loạt cuộc họp kinh tế tiếp diễn. (khởi đầu chuỗi)"),
        ],
        tips="Mẹo: nếu câu chỉ nói về SỰ THAY ĐỔI của MỘT NGƯỜI/tổ chức → を契機に; nếu câu nói về MỘT LOẠT sự kiện nối tiếp nhau → を皮切りに.",
        culture="Cả hai đều là ngữ pháp N2 trọng điểm, thường thấy trong bài đọc hiểu về tiểu sử doanh nhân, lịch sử phát triển công ty."),

    slide(L, 4,
        "4. Dạng thân mật: きっかけ (thay cho を契機に)",
        "N/[thể thường]+のを+きっかけに　　hoặc　　どんなきっかけで〜",
        "きっかけ là từ THUẦN NHẬT, THÂN MẬT hơn 契機 (từ Hán-Nhật, trang trọng) — cả hai cùng "
        "nghĩa 'cơ hội/động lực', nhưng きっかけ dùng được trong hội thoại đời thường, phỏng vấn thân mật.",
        [
            ex(L, 4, 1, [t("t-l6s4-1", "なに", "何", "なに"), t("t-l6s4-2", "が"), t("t-l6s4-3", "きっかけ", "きっかけ", "きっかけ", key=True),
                         t("t-l6s4-4", "で"), t("t-l6s4-5", "、"), t("t-l6s4-6", "にほんご", "日本語", "にほんご"),
                         t("t-l6s4-7", "を"), t("t-l6s4-8", "べんきょう", "勉強", "べんきょう"), t("t-l6s4-9", "しました", "為ました", "しました"),
                         t("t-l6s4-10", "か")],
               "Nhờ động lực gì mà bạn đã học tiếng Nhật vậy?"),
            ex(L, 4, 2, [t("t-l6s4-11", "りゅうがく", "留学", "りゅうがく", key=True), t("t-l6s4-12", "が"),
                         t("t-l6s4-13", "きっかけ", "きっかけ", "きっかけ", key=True), t("t-l6s4-14", "で"),
                         t("t-l6s4-15", "、"), t("t-l6s4-16", "しんろ", "進路", "しんろ", key=True), t("t-l6s4-17", "を"),
                         t("t-l6s4-18", "かえました", "変えました", "かえました")],
               "Nhờ động lực từ việc du học, tôi đã thay đổi con đường sự nghiệp."),
        ],
        tips="Nを契機に ≈ Nがきっかけで — có thể hoán đổi trong nhiều ngữ cảnh, chỉ khác mức độ trang trọng.",
        culture="Trong phỏng vấn tuyển dụng thân mật, người Nhật hay hỏi 'きっかけは何ですか' thay vì '契機は何ですか' để tạo không khí gần gũi hơn."),
]

DIALOGUE = [
    line(L, 1, "田中", "Phóng viên",
         [t("d6-1", "なに", "何", "なに"), t("d6-2", "が"), t("d6-3", "きっかけ", "きっかけ", "きっかけ", key=True),
          t("d6-4", "で"), t("d6-5", "、"), t("d6-6", "かいしゃ", "会社", "かいしゃ", key=True), t("d6-7", "を"),
          t("d6-8", "はじめました", "始めました", "はじめました"), t("d6-9", "か")],
         "Nhờ động lực gì mà anh đã bắt đầu công ty?"),
    line(L, 2, "サントス", "Doanh nhân",
         [t("d6-10", "かいがい", "海外", "かいがい", key=True), t("d6-11", "りゅうがく", "留学", "りゅうがく", key=True),
          t("d6-12", "を"), t("d6-13", "けいき", "契機", "けいき", key=True), t("d6-14", "に"), t("d6-15", "、"),
          t("d6-16", "しんろ", "進路", "しんろ", key=True), t("d6-17", "を"), t("d6-18", "かえました", "変えました", "かえました")],
         "Lấy việc du học nước ngoài làm động lực, tôi đã thay đổi con đường sự nghiệp."),
    line(L, 3, "田中", "Phóng viên",
         [t("d6-19", "かいしゃ", "会社", "かいしゃ", key=True), t("d6-20", "は"), t("d6-21", "どこで"),
          t("d6-22", "はじまりました", "始まりました", "はじまりました"), t("d6-23", "か")],
         "Công ty bắt đầu ở đâu vậy?"),
    line(L, 4, "サントス", "Doanh nhân",
         [t("d6-24", "とうきょう", "東京", "とうきょう", key=True), t("d6-25", "を"), t("d6-26", "かわきり", "皮切り", "かわきり", key=True),
          t("d6-27", "に"), t("d6-28", "、"), t("d6-29", "ぜんこく", "全国", "ぜんこく", key=True), t("d6-30", "で"),
          t("d6-31", "かつどう", "活動", "かつどう", key=True), t("d6-32", "を"), t("d6-33", "つづけました", "続けました", "つづけました")],
         "Bắt đầu từ Tokyo, chúng tôi đã tiếp tục hoạt động trên toàn quốc."),
    line(L, 5, "田中", "Phóng viên",
         [t("d6-34", "してん", "支店", "してん", key=True), t("d6-35", "は"), t("d6-36", "いくつ"),
          t("d6-37", "あります", "有ります", "あります"), t("d6-38", "か")],
         "Có bao nhiêu chi nhánh?"),
    line(L, 6, "サントス", "Doanh nhân",
         [t("d6-39", "この"), t("d6-40", "してん", "支店", "してん", key=True), t("d6-41", "を"),
          t("d6-42", "かわきり", "皮切り", "かわきり", key=True), t("d6-43", "に"), t("d6-44", "、"),
          t("d6-45", "いくつか"), t("d6-46", "の"), t("d6-47", "してん", "支店", "してん", key=True),
          t("d6-48", "が"), t("d6-49", "つづきました", "続きました", "つづきました")],
         "Bắt đầu từ chi nhánh này, đã có một loạt chi nhánh khác tiếp diễn."),
    line(L, 7, "田中", "Phóng viên",
         [t("d6-50", "どんな"), t("d6-51", "できごと", "出来事", "できごと", key=True), t("d6-52", "が"),
          t("d6-53", "いちばん"), t("d6-54", "たいへん"), t("d6-55", "でした", "でした", "でした"), t("d6-56", "か")],
         "Sự kiện nào là khó khăn nhất?"),
    line(L, 8, "サントス", "Doanh nhân",
         [t("d6-57", "けいざい", "経済", "けいざい", key=True), t("d6-58", "が"), t("d6-59", "わるく"),
          t("d6-60", "なった"), t("d6-61", "とき", "時", "とき"), t("d6-62", "です", "です", "です")],
         "Là lúc kinh tế trở nên xấu đi."),
    line(L, 9, "田中", "Phóng viên",
         [t("d6-63", "つよく", "強く", "つよく", key=True), t("d6-64", "なりました", "成りました", "なりました"), t("d6-65", "ね")],
         "Anh đã trở nên mạnh mẽ hơn nhỉ."),
    line(L, 10, "サントス", "Doanh nhân",
         [t("d6-66", "はい"), t("d6-67", "。"), t("d6-68", "けいけん", "経験", "けいけん", key=True), t("d6-69", "が"),
          t("d6-70", "しごと", "仕事", "しごと", key=True), t("d6-71", "に"), t("d6-72", "やくだちました", "役立ちました", "やくだちました")],
         "Vâng. Kinh nghiệm đã có ích cho công việc."),
]

EXERCISES = [
    q(L, 1, "「留学を契機に、進路を変えました」 — を契機に diễn tả điều gì?",
      ["Lấy một sự kiện làm cơ hội/động lực để bắt đầu thay đổi tích cực (bước ngoặt cá nhân)",
       "Khởi đầu của một chuỗi sự kiện tiếp diễn", "Sự khẳng định chắc chắn",
       "Sự từ chối lịch sự"], 0,
      "を契機に diễn tả việc lấy một sự kiện làm ĐỘNG LỰC để bắt đầu một thay đổi tích cực trong cuộc sống/sự nghiệp.",
      "Xem cấu trúc を契機に ở slide 1."),
    q(L, 2, "「東京を皮切りに、全国で活動を続けます」 — を皮切りに khác を契機に ở điểm nào?",
      ["を皮切りに nhấn khởi đầu của một CHUỖI sự kiện tiếp diễn, không chỉ một bước ngoặt cá nhân",
       "Hoàn toàn giống nhau, dùng thay thế được cho nhau",
       "を皮切りに chỉ dùng cho câu hỏi", "を契機に chỉ dùng cho phủ định"], 0,
      "を皮切りに nhấn TRÌNH TỰ của một LOẠT sự kiện/hoạt động sẽ tiếp diễn sau điểm khởi đầu.",
      "Xem giải thích を皮切りに ở slide 2."),
    q(L, 3, "を皮切りに có thể dùng cho một sự kiện đơn lẻ, không có tiếp diễn gì sau đó không?",
      ["Không, を皮切りに luôn ngụ ý sẽ có THÊM nhiều sự kiện/hoạt động tương tự tiếp theo",
       "Có, dùng được cho sự kiện đơn lẻ", "Chỉ dùng được trong câu hỏi",
       "Chỉ dùng được trong quá khứ"], 0,
      "を皮切りに luôn hàm ý MỞ RỘNG thành chuỗi hoạt động tiếp theo, không dùng cho sự kiện kết thúc, đơn lẻ.",
      "Xem lưu ý ngữ pháp ở slide 2."),
    q(L, 4, "きっかけ khác 契機 ở điểm nào?",
      ["きっかけ là từ thuần Nhật, THÂN MẬT hơn; 契機 là từ Hán-Nhật, TRANG TRỌNG hơn",
       "Hoàn toàn khác nghĩa nhau", "きっかけ chỉ dùng cho phủ định",
       "契機 chỉ dùng cho câu hỏi"], 0,
      "Cả hai cùng nghĩa 'cơ hội/động lực', nhưng きっかけ thân mật hơn, dùng trong hội thoại đời thường; 契機 trang trọng hơn.",
      "Xem so sánh ở slide 4."),
    q(L, 5, "「この支店を皮切りに、いくつかの支店が続きました」 nghĩa là:",
      ["Bắt đầu từ chi nhánh này, một loạt chi nhánh khác đã tiếp diễn",
       "Chi nhánh này là chi nhánh cuối cùng", "Không có chi nhánh nào khác được mở",
       "Chi nhánh này đã đóng cửa"], 0,
      "を皮切りに ở đây nhấn việc chi nhánh này là ĐIỂM KHỞI ĐẦU cho một loạt chi nhánh khác ra đời sau đó.",
      "Áp dụng cấu trúc Nを皮切りに."),
    q(L, 6, "Sự khác biệt cốt lõi giữa を契機に và を皮切りに là gì?",
      ["を契機に nhấn Ý NGHĨA của sự thay đổi cá nhân; を皮切りに nhấn TRÌNH TỰ của chuỗi sự kiện",
       "Không có gì khác nhau cả", "を契機に chỉ dùng cho công ty",
       "を皮切りに chỉ dùng cho cá nhân"], 0,
      "を契機に tập trung vào Ý NGHĨA/ĐỘNG LỰC thay đổi; を皮切りに tập trung vào TRÌNH TỰ THỜI GIAN của chuỗi sự kiện.",
      "Xem bảng so sánh ở slide 3."),
    q(L, 7, "「海外の経験を契機に、進路を変えました」 nghĩa là:",
      ["Lấy kinh nghiệm ở nước ngoài làm động lực, đã thay đổi con đường sự nghiệp",
       "Kinh nghiệm ở nước ngoài không có ảnh hưởng gì", "Đã từ bỏ việc thay đổi",
       "Chưa từng có kinh nghiệm ở nước ngoài"], 0,
      "を契機に ở đây nhấn kinh nghiệm nước ngoài là ĐỘNG LỰC dẫn đến quyết định thay đổi con đường sự nghiệp.",
      "Áp dụng cấu trúc Nを契機に cho ngữ cảnh câu."),
    q(L, 8, "Theo hội thoại, công ty của Santos bắt đầu ở đâu?",
      ["Tokyo (東京を皮切りに)", "Osaka", "Nước ngoài", "Không được đề cập trong hội thoại"], 0,
      "Santos nói 「東京を皮切りに、全国で活動を続けました」.",
      "Xem câu thoại thứ 4."),
    q(L, 9, "Sự kiện nào khó khăn nhất đối với Santos?",
      ["Lúc kinh tế trở nên xấu đi (経済が悪くなった時)", "Lúc mở công ty",
       "Lúc du học nước ngoài", "Không có sự kiện nào khó khăn"], 0,
      "Santos trả lời 「経済が悪くなった時です」.",
      "Xem câu thoại thứ 8."),
    q(L, 10, "Kinh nghiệm của Santos đã giúp ích cho điều gì?",
      ["Công việc (経験が仕事に役立ちました)", "Không có tác dụng gì",
       "Chỉ có ích cho việc học", "Đã bị lãng phí hoàn toàn"], 0,
      "Santos nói 「経験が仕事に役立ちました」.",
      "Xem câu thoại cuối cùng."),
]

LESSON = lesson(
    L,
    "Bài 6: Khởi điểm & Cột mốc (を契機に & を皮切りに)",
    "を契機に diễn tả việc lấy một sự kiện làm CƠ HỘI/ĐỘNG LỰC để bắt đầu một THAY ĐỔI TÍCH CỰC "
    "(bước ngoặt cá nhân, một sự kiện duy nhất); を皮切りに diễn tả việc BẮT ĐẦU TỪ một điểm mốc "
    "rồi tiếp tục mở rộng thành một CHUỖI sự kiện khác (nhấn trình tự thời gian); きっかけ là dạng "
    "thuần Nhật, thân mật hơn của 契機.",
    VOCAB, KANJI, SLIDES, DIALOGUE, EXERCISES,
)

if __name__ == "__main__":
    pool.mark_used([w["word"] for w in VOCAB if w["word"]], lesson=L)
    merge([LESSON])
