# -*- coding: utf-8 -*-
"""N2 — Bai 1: Thoi diem & nghi thuc trang trong に際して (vao dip) va に先立って (truoc khi).

Tu vung minh hoa TU CHON tu pool mo data/jlpt-vocab/n2.csv (xem NOTICE.md).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from n2_lib import v, k, t, ex, slide, line, q, lesson, merge
from jlpt_pool import Pool

L = 1
pool = Pool("n2")

VOCAB = [
    v(1,  "しゅうにんします", "就任します", "しゅうにんします", "shuunin shimasu", "verb", "Nhậm chức", "しゃちょうに 就任します = nhậm chức giám đốc.", L),
    v(2,  "かいかいします", "開会します", "かいかいします", "kaikai shimasu", "verb", "Khai mạc", "しきを 開会します = khai mạc buổi lễ.", L),
    v(3,  "へいかいします", "閉会します", "へいかいします", "heikai shimasu", "verb", "Bế mạc", "かいぎを 閉会します = bế mạc cuộc họp.", L),
    v(4,  "しゅうりょうします", "終了します", "しゅうりょうします", "shuuryou shimasu", "verb", "Kết thúc, hoàn tất", "じゅんびが 終了します = việc chuẩn bị hoàn tất.", L),
    v(5,  "ぎしき", "儀式", "ぎしき", "gishiki", "noun", "Nghi lễ, nghi thức", "しゅうにんの 儀式 = nghi lễ nhậm chức.", L),
    v(6,  "けいしき", "形式", "けいしき", "keishiki", "noun", "Hình thức", "こうしきの 形式 = hình thức chính thức.", L),
    v(7,  "こうしき", "公式", "こうしき", "koushiki", "adjective", "Chính thức", "公式の ぎしき = nghi lễ chính thức.", L),
    v(8,  "あいさつ", "挨拶", "あいさつ", "aisatsu", "noun", "Lời chào, phát biểu chào hỏi", "ごあいさつ もうしあげます = tôi xin có đôi lời phát biểu.", L),
    v(9,  "おれい", "お礼", "おれい", "orei", "noun", "Lời cảm ơn", "Đã gặp N4 bài 33.", L),
    v(10, "みなさま", "皆様", "みなさま", "minasama", "pronoun", "Quý vị", "Đã gặp N3 bài 12.", L),
    v(11, "けいけん", "経験", "けいけん", "keiken", "noun", "Kinh nghiệm", "Đã gặp N4 bài 26.", L),
    v(12, "かいしゃ", "会社", "かいしゃ", "kaisha", "noun", "Công ty", "Đã gặp N4 bài 26.", L),
    v(13, "しゃちょう", "社長", "しゃちょう", "shachou", "noun", "Giám đốc", "Đã gặp N4 bài 41.", L),
    v(14, "じゅんび", "準備", "じゅんび", "junbi", "noun", "Sự chuẩn bị", "Đã gặp N4 bài 26.", L),
    v(15, "もうします", "申します", "もうします", "moushimasu", "verb", "Nói, thưa (khiêm nhường ngữ)", "Đã gặp N4 bài 50.", L),
    v(16, "ひとこと", "一言", "ひとこと", "hitokoto", "noun", "Đôi lời, một lời", "Đã gặp N3 bài 11.", L),
    v(17, "いたします", "致します", "いたします", "itashimasu", "verb", "Làm (khiêm nhường ngữ)", "Đã gặp N4 bài 50.", L),
    v(18, "ほうこくします", "報告します", "ほうこくします", "houkoku shimasu", "verb", "Báo cáo", "Đã gặp N3 bài 17.", L),
    v(19, "はじめます", "始めます", "はじめます", "hajimemasu", "verb", "Bắt đầu", "Đã gặp N4 bài 26.", L),
    v(20, "おわります", "終わります", "おわります", "owarimasu", "verb", "Kết thúc", "Đã gặp N4 bài 26.", L),
]

KANJI = [
    k(1, "際", "TẾ", 14, ["サイ (sai)"], ["きわ"], "Khi, dịp, ranh giới.",
      [("に際して", "にさいして", "Vào dịp"), ("国際", "こくさい", "Quốc tế")], L),
    k(2, "就", "TỰU", 12, ["シュウ (shuu)"], ["つ(く)"], "Đảm nhận, tựu chức.",
      [("就任", "しゅうにん", "Nhậm chức"), ("就職", "しゅうしょく", "Xin việc")], L),
    k(3, "任", "NHIỆM", 6, ["ニン (nin)"], ["まか(せる)"], "Nhiệm vụ, đảm nhiệm.",
      [("就任", "しゅうにん", "Nhậm chức"), ("責任", "せきにん", "Trách nhiệm")], L),
    k(4, "儀", "NGHI", 15, ["ギ (gi)"], [], "Nghi thức, nghi lễ.",
      [("儀式", "ぎしき", "Nghi lễ"), ("礼儀", "れいぎ", "Lễ nghi")], L),
    k(5, "式", "THỨC", 6, ["シキ (shiki)"], [], "Nghi thức, hình thức, công thức.",
      [("形式", "けいしき", "Hình thức"), ("公式", "こうしき", "Chính thức")], L),
]

SLIDES = [
    slide(L, 1,
        "1. Vào dịp, nhân lúc (trang trọng): N + に際して",
        "N(sự kiện quan trọng)/V(từ điển) + に際して、[phát biểu/hành động]",
        "に際して dùng để nói 'VÀO DỊP/NHÂN LÚC' một sự kiện quan trọng, trang trọng đang diễn ra "
        "— thường dùng để MỞ ĐẦU bài phát biểu, thông báo chính thức, mức độ trang trọng cao hơn hẳn とき thông thường.",
        [
            ex(L, 1, 1, [t("t-l1s1-1", "しゅうにん", "就任", "しゅうにん", key=True), t("t-l1s1-2", "に", key=True),
                         t("t-l1s1-3", "さいして", "際して", "さいして", key=True), t("t-l1s1-4", "、"),
                         t("t-l1s1-5", "ひとこと", "一言", "ひとこと", key=True), t("t-l1s1-6", "ご"), t("t-l1s1-7", "あいさつ", "挨拶", "あいさつ", key=True),
                         t("t-l1s1-8", "もうしあげます", "申し上げます", "もうしあげます")],
               "Nhân dịp nhậm chức, tôi xin có đôi lời phát biểu."),
            ex(L, 1, 2, [t("t-l1s1-9", "かいかい", "開会", "かいかい", key=True), t("t-l1s1-10", "に", key=True),
                         t("t-l1s1-11", "さいして", "際して", "さいして", key=True), t("t-l1s1-12", "、"),
                         t("t-l1s1-13", "みなさま", "皆様", "みなさま", key=True), t("t-l1s1-14", "に"),
                         t("t-l1s1-15", "おれい", "お礼", "おれい", key=True), t("t-l1s1-16", "を"),
                         t("t-l1s1-17", "もうしあげます", "申し上げます", "もうしあげます")],
               "Nhân dịp khai mạc, tôi xin gửi lời cảm ơn đến quý vị."),
        ],
        tips="に際しまして (dạng ます trang trọng hơn nữa) thường thấy trong văn bản mời, thư chúc mừng chính thức.",
        culture="Diễn văn khai mạc hội nghị Nhật luôn mở đầu bằng cụm cố định: '本日の開会に際しまして、一言ご挨拶申し上げます'."),

    slide(L, 2,
        "2. Trước khi (chuẩn bị trước một sự kiện): N + に先立って",
        "N(sự kiện quan trọng) + に先立って、[hành động chuẩn bị/thông báo trước]",
        "に先立って diễn tả một hành động xảy ra TRƯỚC một sự kiện quan trọng khác — nhấn mạnh "
        "TRÌNH TỰ THỜI GIAN rõ ràng (việc A hoàn thành trước, rồi B mới diễn ra), dùng trong ngữ cảnh trang trọng.",
        [
            ex(L, 2, 1, [t("t-l1s2-1", "かいかい", "開会", "かいかい", key=True), t("t-l1s2-2", "に", key=True),
                         t("t-l1s2-3", "さきだって", "先立って", "さきだって", key=True), t("t-l1s2-4", "、"),
                         t("t-l1s2-5", "じゅんび", "準備", "じゅんび", key=True), t("t-l1s2-6", "を"), t("t-l1s2-7", "します")],
               "Trước khi khai mạc, chúng tôi tiến hành chuẩn bị."),
            ex(L, 2, 2, [t("t-l1s2-8", "しゅうにん", "就任", "しゅうにん", key=True), t("t-l1s2-9", "に", key=True),
                         t("t-l1s2-10", "さきだって", "先立って", "さきだって", key=True), t("t-l1s2-11", "、"),
                         t("t-l1s2-12", "けいけん", "経験", "けいけん", key=True), t("t-l1s2-13", "を"),
                         t("t-l1s2-14", "つみました", "積みました", "つみました")],
               "Trước khi nhậm chức, tôi đã tích lũy kinh nghiệm."),
        ],
        tips="に先立ち (bỏ って) là dạng trung tính hơn, thường thấy trong văn bản viết, tin tức: '式典に先立ち、記者会見が行われた'.",
        culture="Trước lễ khai trương ở Nhật, doanh nghiệp thường tổ chức 'お祓い' (lễ cầu an) — một hành động điển hình 'に先立って' trước sự kiện chính."),

    slide(L, 3,
        "3. So sánh に際して và に先立って",
        "に際して: VÀO ĐÚNG LÚC/DỊP sự kiện (đồng thời)　vs　に先立って: TRƯỚC KHI sự kiện xảy ra (có trình tự thời gian)",
        "に際して nhấn 'nhân dịp/vào lúc' sự kiện đang diễn ra — dùng để MỞ ĐẦU phát biểu ngay "
        "trong thời điểm đó; に先立って nhấn một hành động XẢY RA TRƯỚC sự kiện, với trình tự A → B rõ ràng.",
        [
            ex(L, 3, 1, [t("t-l1s3-1", "かいかい", "開会", "かいかい", key=True), t("t-l1s3-2", "に", key=True),
                         t("t-l1s3-3", "さいして", "際して", "さいして", key=True), t("t-l1s3-4", "、"),
                         t("t-l1s3-5", "しゃちょう", "社長", "しゃちょう", key=True), t("t-l1s3-6", "が"),
                         t("t-l1s3-7", "あいさつ", "挨拶", "あいさつ", key=True), t("t-l1s3-8", "しました")],
               "Vào dịp khai mạc, giám đốc đã phát biểu. (đồng thời)"),
            ex(L, 3, 2, [t("t-l1s3-9", "かいかい", "開会", "かいかい", key=True), t("t-l1s3-10", "に", key=True),
                         t("t-l1s3-11", "さきだって", "先立って", "さきだって", key=True), t("t-l1s3-12", "、"),
                         t("t-l1s3-13", "しゃちょう", "社長", "しゃちょう", key=True), t("t-l1s3-14", "が"),
                         t("t-l1s3-15", "じゅんび", "準備", "じゅんび", key=True), t("t-l1s3-16", "を"),
                         t("t-l1s3-17", "かくにんしました", "確認しました", "かくにんしました")],
               "Trước khi khai mạc, giám đốc đã xác nhận việc chuẩn bị. (trước đó)"),
        ],
        tips="Mẹo: nếu hành động XẢY RA CÙNG LÚC với sự kiện → に際して; nếu hành động XẢY RA TRƯỚC sự kiện → に先立って.",
        culture="Cả hai đều là ngữ pháp N2 trọng điểm, hay xuất hiện trong đề đọc hiểu về thông báo sự kiện, hội nghị, lễ tân trang trọng."),

    slide(L, 4,
        "4. Dạng cực kỳ trang trọng trong bài phát biểu: に際しまして / に先立ちまして",
        "N + に際しまして、[phát biểu khiêm nhường]　　N + に先立ちまして、[phát biểu khiêm nhường]",
        "Trong văn phong CỰC KỲ trang trọng (phát biểu khai mạc, lễ tân chính thức), thường dùng "
        "dạng ましょう/まして thay vì して/って: に際しまして, に先立ちまして — kết hợp cùng khiêm nhường ngữ もうしあげます/いたします.",
        [
            ex(L, 4, 1, [t("t-l1s4-1", "へいかい", "閉会", "へいかい", key=True), t("t-l1s4-2", "に", key=True),
                         t("t-l1s4-3", "さいしまして", "際しまして", "さいしまして", key=True), t("t-l1s4-4", "、"),
                         t("t-l1s4-5", "ひとこと", "一言", "ひとこと", key=True), t("t-l1s4-6", "ご"),
                         t("t-l1s4-7", "あいさつ", "挨拶", "あいさつ", key=True), t("t-l1s4-8", "もうしあげます", "申し上げます", "もうしあげます")],
               "Nhân dịp bế mạc, tôi xin có đôi lời phát biểu."),
            ex(L, 4, 2, [t("t-l1s4-9", "ぎしき", "儀式", "ぎしき", key=True), t("t-l1s4-10", "に", key=True),
                         t("t-l1s4-11", "さきだちまして", "先立ちまして", "さきだちまして", key=True), t("t-l1s4-12", "、"),
                         t("t-l1s4-13", "しゅうりょう", "終了", "しゅうりょう", key=True), t("t-l1s4-14", "の"),
                         t("t-l1s4-15", "ほうこく", "報告", "ほうこく", key=True), t("t-l1s4-16", "を"),
                         t("t-l1s4-17", "いたします", "致します", "いたします", key=True)],
               "Trước khi diễn ra nghi lễ, tôi xin báo cáo về việc kết thúc (công tác chuẩn bị)."),
        ],
        tips="に際しまして/に先立ちまして + もうしあげます/いたします là bộ khung câu CHUẨN cho mọi bài phát biểu khai mạc/bế mạc trang trọng ở Nhật.",
        culture="Đây là mẫu câu bắt buộc phải thuộc lòng nếu làm việc trong môi trường công sở Nhật, đặc biệt khi phải phát biểu tại các buổi lễ chính thức (式典)."),
]

DIALOGUE = [
    line(L, 1, "田中", "MC buổi lễ",
         [t("d1-1", "それでは"), t("d1-2", "、"), t("d1-3", "かいかい", "開会", "かいかい", key=True),
          t("d1-4", "に", key=True), t("d1-5", "さいしまして", "際しまして", "さいしまして", key=True), t("d1-6", "、"),
          t("d1-7", "しゃちょう", "社長", "しゃちょう", key=True), t("d1-8", "から"), t("d1-9", "ひとこと", "一言", "ひとこと", key=True),
          t("d1-10", "お願いします")],
         "Vậy thì, nhân dịp khai mạc, xin mời giám đốc phát biểu đôi lời."),
    line(L, 2, "サントス", "Giám đốc mới nhậm chức",
         [t("d1-11", "しゃちょう", "社長", "しゃちょう", key=True), t("d1-12", "に"), t("d1-13", "しゅうにん", "就任", "しゅうにん", key=True),
          t("d1-14", "する", key=True), t("d1-15", "サントス", "サントス", "サントス"), t("d1-16", "と"),
          t("d1-17", "もうします", "申します", "もうします")],
         "Tôi tên là Santos, người sẽ nhậm chức giám đốc."),
    line(L, 3, "田中", "MC buổi lễ",
         [t("d1-18", "しゅうにん", "就任", "しゅうにん", key=True), t("d1-19", "に", key=True),
          t("d1-20", "さきだって", "先立って", "さきだって", key=True), t("d1-21", "、"),
          t("d1-22", "どんな"), t("d1-23", "けいけん", "経験", "けいけん", key=True), t("d1-24", "を"),
          t("d1-25", "つみました", "積みました", "つみました"), t("d1-26", "か")],
         "Trước khi nhậm chức, ông đã tích lũy kinh nghiệm gì?"),
    line(L, 4, "サントス", "Giám đốc mới nhậm chức",
         [t("d1-27", "がいこく", "外国", "がいこく"), t("d1-28", "の"), t("d1-29", "かいしゃ", "会社", "かいしゃ", key=True),
          t("d1-30", "で"), t("d1-31", "けいけん", "経験", "けいけん", key=True), t("d1-32", "を"),
          t("d1-33", "つみました", "積みました", "つみました")],
         "Tôi đã tích lũy kinh nghiệm ở công ty nước ngoài."),
    line(L, 5, "田中", "MC buổi lễ",
         [t("d1-34", "こんかい", "今回", "こんかい"), t("d1-35", "の"), t("d1-36", "ぎしき", "儀式", "ぎしき", key=True),
          t("d1-37", "は"), t("d1-38", "こうしき", "公式", "こうしき", key=True), t("d1-39", "な"),
          t("d1-40", "けいしき", "形式", "けいしき", key=True), t("d1-41", "です", "です", "です"), t("d1-42", "ね")],
         "Nghi lễ lần này theo hình thức chính thức nhỉ."),
    line(L, 6, "サントス", "Giám đốc mới nhậm chức",
         [t("d1-43", "はい"), t("d1-44", "。"), t("d1-45", "じゅんび", "準備", "じゅんび", key=True), t("d1-46", "が"),
          t("d1-47", "しゅうりょう", "終了", "しゅうりょう", key=True), t("d1-48", "しました")],
         "Vâng. Việc chuẩn bị đã hoàn tất."),
    line(L, 7, "田中", "MC buổi lễ",
         [t("d1-49", "それでは"), t("d1-50", "、"), t("d1-51", "かいかい", "開会", "かいかい", key=True),
          t("d1-52", "を"), t("d1-53", "はじめます", "始めます", "はじめます", key=True)],
         "Vậy thì, chúng ta bắt đầu khai mạc."),
    line(L, 8, "サントス", "Giám đốc mới nhậm chức",
         [t("d1-54", "みなさま", "皆様", "みなさま", key=True), t("d1-55", "、"), t("d1-56", "ほんじつ", "本日", "ほんじつ"),
          t("d1-57", "は"), t("d1-58", "ありがとうございます", "ありがとうございます", "ありがとうございます")],
         "Kính thưa quý vị, hôm nay xin cảm ơn."),
    line(L, 9, "田中", "MC buổi lễ",
         [t("d1-59", "へいかい", "閉会", "へいかい", key=True), t("d1-60", "に", key=True),
          t("d1-61", "さいしまして", "際しまして", "さいしまして", key=True), t("d1-62", "、"),
          t("d1-63", "また", "又", "また"), t("d1-64", "ひとこと", "一言", "ひとこと", key=True), t("d1-65", "お願いします")],
         "Nhân dịp bế mạc, xin ông có thêm đôi lời."),
    line(L, 10, "サントス", "Giám đốc mới nhậm chức",
         [t("d1-66", "みなさま", "皆様", "みなさま", key=True), t("d1-67", "、"), t("d1-68", "ほんじつ", "本日", "ほんじつ"),
          t("d1-69", "は"), t("d1-70", "これで"), t("d1-71", "おわります", "終わります", "おわります", key=True),
          t("d1-72", "。"), t("d1-73", "ありがとうございました", "ありがとうございました", "ありがとうございました")],
         "Kính thưa quý vị, hôm nay xin kết thúc tại đây. Xin cảm ơn."),
]

EXERCISES = [
    q(L, 1, "「就任に際して、一言ご挨拶申し上げます」 — に際して diễn tả điều gì?",
      ["Vào dịp/nhân lúc một sự kiện quan trọng đang diễn ra (trang trọng)",
       "Trước khi một sự kiện xảy ra", "Sau khi một sự kiện kết thúc",
       "Phủ định việc phát biểu"], 0,
      "に際して dùng để nói 'nhân dịp' một sự kiện quan trọng đang diễn ra, thường mở đầu bài phát biểu.",
      "Xem cấu trúc に際して ở slide 1."),
    q(L, 2, "「開会に先立って、準備をします」 — に先立って khác に際して ở điểm nào?",
      ["に先立って nhấn hành động xảy ra TRƯỚC sự kiện (trình tự thời gian rõ ràng)",
       "Hoàn toàn giống nhau, không khác gì cả", "に先立って chỉ dùng cho câu hỏi",
       "に際して chỉ dùng trong quá khứ"], 0,
      "に先立って nhấn TRÌNH TỰ THỜI GIAN: hành động A (chuẩn bị) xảy ra TRƯỚC sự kiện B (khai mạc).",
      "Xem giải thích に先立って ở slide 2."),
    q(L, 3, "「開会に際して、社長が挨拶しました」 và 「開会に先立って、社長が準備を確認しました」 khác nhau ở đâu?",
      ["Câu đầu: hành động ĐỒNG THỜI với sự kiện; câu sau: hành động TRƯỚC sự kiện",
       "Không có gì khác nhau cả", "Câu đầu là quá khứ, câu sau là hiện tại",
       "Câu sau là phủ định của câu đầu"], 0,
      "に際して=đồng thời với sự kiện (giám đốc phát biểu NGAY LÚC khai mạc); に先立って=trước sự kiện (xác nhận chuẩn bị TRƯỚC khi khai mạc).",
      "So sánh hai câu ở slide 3."),
    q(L, 4, "Dạng trang trọng hơn của に際して/に先立って trong bài phát biểu chính thức là gì?",
      ["に際しまして / に先立ちまして", "に際してだ / に先立ってだ",
       "に際してよ / に先立ってよ", "Không có dạng trang trọng hơn"], 0,
      "Trong văn phong cực kỳ trang trọng, dùng dạng ましょう/まして: に際しまして, に先立ちまして.",
      "Xem dạng trang trọng ở slide 4."),
    q(L, 5, "Cấu trúc nào thường kết hợp với に際しまして/に先立ちまして trong phát biểu chính thức?",
      ["もうしあげます/いたします (khiêm nhường ngữ)", "たべます/のみます (ăn uống thông thường)",
       "あそびます/ねます (chơi/ngủ thông thường)", "Không cần kết hợp với động từ nào"], 0,
      "に際しまして/に先立ちまして thường đi kèm khiêm nhường ngữ もうしあげます/いたします để tạo văn phong trang trọng, lịch sự.",
      "Xem mẫu câu chuẩn ở slide 4."),
    q(L, 6, "「就任に先立って、経験を積みました」 nghĩa là:",
      ["Trước khi nhậm chức, đã tích lũy kinh nghiệm", "Sau khi nhậm chức mới tích lũy kinh nghiệm",
       "Không có kinh nghiệm gì trước khi nhậm chức", "Đã từ chối nhậm chức"], 0,
      "に先立って ở đây nhấn hành động tích lũy kinh nghiệm xảy ra TRƯỚC việc nhậm chức.",
      "Áp dụng cấu trúc Nに先立って."),
    q(L, 7, "Trong hội thoại, nghi lễ được tổ chức theo hình thức nào?",
      ["Hình thức chính thức (公式な形式です)", "Hình thức không trang trọng",
       "Không có hình thức cụ thể", "Hình thức bí mật"], 0,
      "田中 nói 「今回の儀式は公式な形式ですね」.",
      "Xem câu thoại thứ 5."),
    q(L, 8, "Santos đã tích lũy kinh nghiệm ở đâu trước khi nhậm chức?",
      ["Ở công ty nước ngoài (外国の会社で経験を積みました)", "Ở trường đại học",
       "Không có kinh nghiệm gì", "Ở công ty hiện tại"], 0,
      "Santos trả lời 「外国の会社で経験を積みました」.",
      "Xem câu thoại thứ 4."),
    q(L, 9, "Việc chuẩn bị cho buổi lễ đã hoàn tất chưa theo hội thoại?",
      ["Đã hoàn tất (準備が終了しました)", "Chưa hoàn tất", "Không cần chuẩn bị gì",
       "Không được đề cập trong hội thoại"], 0,
      "Santos nói 「準備が終了しました」.",
      "Xem câu thoại thứ 6."),
    q(L, 10, "Santos đã phát biểu gì nhân dịp bế mạc?",
      ["Cảm ơn quý vị và tuyên bố kết thúc (これで終わります。ありがとうございました)",
       "Tiếp tục kéo dài buổi lễ", "Không phát biểu gì cả",
       "Hủy bỏ buổi lễ"], 0,
      "Santos nói 「本日はこれで終わります。ありがとうございました」.",
      "Xem câu thoại cuối cùng."),
]

LESSON = lesson(
    L,
    "Bài 1: Thời điểm & Nghi thức trang trọng (に際して & に先立って)",
    "に際して diễn tả 'vào dịp/nhân lúc' một sự kiện quan trọng ĐANG diễn ra (trang trọng, dùng "
    "mở đầu phát biểu); に先立って diễn tả một hành động xảy ra TRƯỚC sự kiện đó (trình tự thời "
    "gian rõ ràng); dạng trang trọng nhất に際しまして/に先立ちまして kết hợp khiêm nhường ngữ là "
    "khung câu chuẩn cho phát biểu khai mạc/bế mạc chính thức.",
    VOCAB, KANJI, SLIDES, DIALOGUE, EXERCISES,
)

if __name__ == "__main__":
    pool.mark_used([w["word"] for w in VOCAB if w["word"]], lesson=L)
    merge([LESSON])
