# -*- coding: utf-8 -*-
"""N2 — Bai 8: Xoay quanh mot van de tranh cai をめぐって (cuoi cau/truoc dong tu) va を巡る (bo
nghia danh tu).

Tu vung minh hoa TU CHON tu pool mo data/jlpt-vocab/n2.csv (xem NOTICE.md).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from n2_lib import v, k, t, ex, slide, line, q, lesson, merge
from jlpt_pool import Pool

L = 8
pool = Pool("n2")

VOCAB = [
    v(1,  "たいりつします", "対立します", "たいりつします", "tairitsu shimasu", "verb", "Đối lập, đối đầu", "いけんが 対立します = ý kiến đối lập nhau.", L),
    v(2,  "とち", "土地", "とち", "tochi", "noun", "Đất đai", "土地の 問題 = vấn đề đất đai.", L),
    v(3,  "かいけつします", "解決します", "かいけつします", "kaiketsu shimasu", "verb", "Giải quyết", "Đã gặp N3 bài 13.", L),
    v(4,  "ぎろんします", "議論します", "ぎろんします", "giron shimasu", "verb", "Tranh luận", "Đã gặp N3 bài 17.", L),
    v(5,  "さんせい", "賛成", "さんせい", "sansei", "noun", "Tán thành", "Đã gặp N3 bài 20.", L),
    v(6,  "はんたい", "反対", "はんたい", "hantai", "noun", "Phản đối", "Đã gặp N3 bài 20.", L),
    v(7,  "もんだい", "問題", "もんだい", "mondai", "noun", "Vấn đề", "Đã gặp N5 bài 22.", L),
    v(8,  "けいかく", "計画", "けいかく", "keikaku", "noun", "Kế hoạch", "Đã gặp N4 bài 26.", L),
    v(9,  "かいしゃ", "会社", "かいしゃ", "kaisha", "noun", "Công ty", "Đã gặp N4 bài 26.", L),
    v(10, "いけん", "意見", "いけん", "iken", "noun", "Ý kiến", "Đã gặp N4 bài 26.", L),
    v(11, "つづきます", "続きます", "つづきます", "tsuzukimasu", "verb", "Tiếp diễn", "Đã gặp N3 bài 9.", L),
    v(12, "なります", "成ります", "なります", "narimasu", "verb", "Trở thành", "Đã gặp N5 bài 8.", L),
    v(13, "まだ", "まだ", "まだ", "mada", "adverb", "Vẫn chưa", "Đã gặp N4 bài 26.", L),
    v(14, "ひと", "人", "ひと", "hito", "noun", "Người", "Đã gặp N5 bài 1.", L),
    v(15, "せいじ", "政治", "せいじ", "seiji", "noun", "Chính trị", "Đã gặp N4 bài 40.", L),
    v(16, "しゃかい", "社会", "しゃかい", "shakai", "noun", "Xã hội", "Đã gặp N3 bài 5.", L),
    v(17, "かんきょう", "環境", "かんきょう", "kankyou", "noun", "Môi trường", "Đã gặp N3 bài 5.", L),
    v(18, "かいぎ", "会議", "かいぎ", "kaigi", "noun", "Cuộc họp", "Đã gặp N4 bài 30.", L),
    v(19, "くに", "国", "くに", "kuni", "noun", "Quốc gia", "Đã gặp N4 bài 26.", L),
    v(20, "とうきょう", "東京", "とうきょう", "toukyou", "noun", "Tokyo", "Đã gặp N2 bài 6.", L),
]

KANJI = [
    k(1, "対", "ĐỐI", 7, ["タイ (tai)"], [], "Đối lập, đối diện.",
      [("対立", "たいりつ", "Đối lập"), ("反対", "はんたい", "Phản đối")], L),
    k(2, "立", "LẬP", 5, ["リツ (ritsu)"], ["た(つ)"], "Đứng, thành lập.",
      [("対立", "たいりつ", "Đối lập"), ("立場", "たちば", "Lập trường")], L),
    k(3, "巡", "TUẦN", 6, ["ジュン (jun)"], ["めぐ(る)"], "Đi vòng quanh, tuần hoàn.",
      [("巡る", "めぐる", "Xoay quanh"), ("巡回", "じゅんかい", "Tuần tra")], L),
    k(4, "土", "THỔ", 3, ["ド (do)"], ["つち"], "Đất, thổ nhưỡng.",
      [("土地", "とち", "Đất đai"), ("土曜日", "どようび", "Thứ bảy")], L),
    k(5, "地", "ĐỊA", 6, ["チ (chi)"], [], "Đất, địa điểm.",
      [("土地", "とち", "Đất đai"), ("地震", "じしん", "Động đất")], L),
]

SLIDES = [
    slide(L, 1,
        "1. Xoay quanh (trước động từ tranh luận): N + をめぐって",
        "N(vấn đề tranh cãi) + をめぐって、[tranh luận/đối lập/xảy ra]",
        "をめぐって diễn tả 'XOAY QUANH' một VẤN ĐỀ TRANH CÃI — thường theo sau bởi động từ chỉ "
        "sự TRANH LUẬN/ĐỐI LẬP (議論する, 対立する, 争う), dùng khi mô tả một cuộc tranh cãi có NHIỀU BÊN liên quan.",
        [
            ex(L, 1, 1, [t("t-l8s1-1", "とち", "土地", "とち", key=True), t("t-l8s1-2", "の"),
                         t("t-l8s1-3", "もんだい", "問題", "もんだい", key=True), t("t-l8s1-4", "を"),
                         t("t-l8s1-5", "めぐって", key=True), t("t-l8s1-6", "、"), t("t-l8s1-7", "たいりつ", "対立", "たいりつ", key=True),
                         t("t-l8s1-8", "が"), t("t-l8s1-9", "つづいて", "続いて", "つづいて"), t("t-l8s1-10", "います", "居ます", "います")],
               "Xoay quanh vấn đề đất đai, sự đối lập vẫn tiếp diễn."),
            ex(L, 1, 2, [t("t-l8s1-11", "けいかく", "計画", "けいかく", key=True), t("t-l8s1-12", "を"),
                         t("t-l8s1-13", "めぐって", key=True), t("t-l8s1-14", "、"), t("t-l8s1-15", "ぎろん", "議論", "ぎろん", key=True),
                         t("t-l8s1-16", "が"), t("t-l8s1-17", "おこなわれました", "行われました", "おこなわれました")],
               "Xoay quanh kế hoạch, đã diễn ra tranh luận."),
        ],
        tips="をめぐって luôn ngụ ý có NHIỀU BÊN với QUAN ĐIỂM KHÁC NHAU về cùng một vấn đề — không dùng cho vấn đề đã có sự đồng thuận.",
        culture="Bản tin thời sự Nhật hay dùng: '新しい法律をめぐって、国会で議論が続いている' (xoay quanh luật mới, tranh luận vẫn tiếp diễn ở quốc hội)."),

    slide(L, 2,
        "2. Dạng bổ nghĩa danh từ: N1 + を巡る + N2",
        "N1(vấn đề tranh cãi) + を巡る + N2(vấn đề/tranh luận/đối lập)",
        "を巡る là DẠNG BỔ NGHĨA DANH TỪ của をめぐって — dùng khi 'vấn đề xoay quanh N1' cần bổ "
        "nghĩa trực tiếp cho một DANH TỪ khác (N2) như 問題, 議論, 対立, đứng NGAY TRƯỚC danh từ đó.",
        [
            ex(L, 2, 1, [t("t-l8s2-1", "とち", "土地", "とち", key=True), t("t-l8s2-2", "を"),
                         t("t-l8s2-3", "めぐる", key=True), t("t-l8s2-4", "もんだい", "問題", "もんだい", key=True),
                         t("t-l8s2-5", "は"), t("t-l8s2-6", "まだ"), t("t-l8s2-7", "かいけつ", "解決", "かいけつ", key=True),
                         t("t-l8s2-8", "して", key=True), t("t-l8s2-9", "いません", key=True)],
               "Vấn đề xoay quanh đất đai vẫn chưa được giải quyết."),
            ex(L, 2, 2, [t("t-l8s2-10", "けいかく", "計画", "けいかく", key=True), t("t-l8s2-11", "を"),
                         t("t-l8s2-12", "めぐる", key=True), t("t-l8s2-13", "ぎろん", "議論", "ぎろん", key=True),
                         t("t-l8s2-14", "は"), t("t-l8s2-15", "つづいて", "続いて", "つづいて"), t("t-l8s2-16", "います", "居ます", "います")],
               "Cuộc tranh luận xoay quanh kế hoạch vẫn đang tiếp diễn."),
        ],
        tips="Nを巡るN2 ≈ N2をめぐって (cùng ý nghĩa, khác vị trí cú pháp) — chọn dạng nào tùy vào N2 đứng trước hay sau trong câu.",
        culture="Tiêu đề báo Nhật thường dùng を巡る để súc tích hóa câu: '環境問題を巡る国際会議' (hội nghị quốc tế xoay quanh vấn đề môi trường)."),

    slide(L, 3,
        "3. So sánh vị trí cú pháp của をめぐって và を巡る",
        "Nをめぐって、[động từ ở CUỐI câu]　vs　Nを巡るN2 (N2 là danh từ theo SAU ngay lập tức)",
        "Hai dạng CÙNG Ý NGHĨA nhưng khác VỊ TRÍ CÚ PHÁP: をめぐって đặt TRƯỚC MỆNH ĐỀ (có động từ "
        "ở cuối câu); を巡る đặt TRỰC TIẾP TRƯỚC DANH TỪ mà nó bổ nghĩa — cần chọn đúng dạng theo cấu trúc câu.",
        [
            ex(L, 3, 1, [t("t-l8s3-1", "せいじ", "政治", "せいじ", key=True), t("t-l8s3-2", "を"),
                         t("t-l8s3-3", "めぐって", key=True), t("t-l8s3-4", "、"), t("t-l8s3-5", "ひと", "人", "ひと", key=True),
                         t("t-l8s3-6", "びと"), t("t-l8s3-7", "の"), t("t-l8s3-8", "いけん", "意見", "いけん", key=True),
                         t("t-l8s3-9", "が"), t("t-l8s3-10", "わかれます", "分かれます", "わかれます")],
               "Xoay quanh chính trị, ý kiến của mọi người bị chia rẽ. (をめぐって + động từ cuối câu)"),
            ex(L, 3, 2, [t("t-l8s3-11", "せいじ", "政治", "せいじ", key=True), t("t-l8s3-12", "を"),
                         t("t-l8s3-13", "めぐる", key=True), t("t-l8s3-14", "いけん", "意見", "いけん", key=True),
                         t("t-l8s3-15", "の"), t("t-l8s3-16", "ちがい", "違い", "ちがい"), t("t-l8s3-17", "は"),
                         t("t-l8s3-18", "おおきい", "大きい", "おおきい")],
               "Sự khác biệt ý kiến xoay quanh chính trị là rất lớn. (を巡る + danh từ theo sau)"),
        ],
        tips="Mẹo: nếu câu KẾT THÚC bằng động từ → dùng をめぐって; nếu cần một CỤM DANH TỪ (làm chủ ngữ/tân ngữ) → dùng を巡る.",
        culture="Cả hai đều là ngữ pháp N2 trọng điểm, hay xuất hiện trong đề đọc hiểu về tin tức chính trị, xã hội, tranh chấp kinh doanh."),

    slide(L, 4,
        "4. Kết hợp với 賛成/反対 để mô tả hai phe tranh luận",
        "Nをめぐって、賛成する人と反対する人が対立します",
        "をめぐって/を巡る thường kết hợp với 賛成 (tán thành) và 反対 (phản đối) để mô tả một vấn "
        "đề có HAI PHE Ý KIẾN TRÁI NGƯỢC — cấu trúc điển hình khi tường thuật một cuộc tranh luận xã hội.",
        [
            ex(L, 4, 1, [t("t-l8s4-1", "この"), t("t-l8s4-2", "けいかく", "計画", "けいかく", key=True), t("t-l8s4-3", "を"),
                         t("t-l8s4-4", "めぐって", key=True), t("t-l8s4-5", "、"), t("t-l8s4-6", "さんせい", "賛成", "さんせい", key=True),
                         t("t-l8s4-7", "する"), t("t-l8s4-8", "ひと", "人", "ひと"), t("t-l8s4-9", "と"),
                         t("t-l8s4-10", "はんたい", "反対", "はんたい", key=True), t("t-l8s4-11", "する"), t("t-l8s4-12", "ひと", "人", "ひと"),
                         t("t-l8s4-13", "が"), t("t-l8s4-14", "たいりつ", "対立", "たいりつ", key=True), t("t-l8s4-15", "して", key=True),
                         t("t-l8s4-16", "います", "居ます", "います")],
               "Xoay quanh kế hoạch này, người tán thành và người phản đối đang đối lập nhau."),
            ex(L, 4, 2, [t("t-l8s4-17", "とち", "土地", "とち", key=True), t("t-l8s4-18", "を"),
                         t("t-l8s4-19", "めぐる", key=True), t("t-l8s4-20", "かいぎ", "会議", "かいぎ", key=True), t("t-l8s4-21", "は"),
                         t("t-l8s4-22", "まだ"), t("t-l8s4-23", "つづいて", "続いて", "つづいて"), t("t-l8s4-24", "います", "居ます", "います")],
               "Cuộc họp xoay quanh đất đai vẫn đang tiếp diễn."),
        ],
        tips="賛成派/反対派 (phe tán thành/phe phản đối) là cách gọi phổ biến trong tin tức khi tường thuật các cuộc tranh luận をめぐって.",
        culture="Bài báo về chính sách công ở Nhật thường có cấu trúc: '[vấn đề]をめぐって、賛成派と反対派が対立している'."),
]

DIALOGUE = [
    line(L, 1, "田中", "Đồng nghiệp",
         [t("d8-1", "とち", "土地", "とち", key=True), t("d8-2", "の"), t("d8-3", "もんだい", "問題", "もんだい", key=True),
          t("d8-4", "を"), t("d8-5", "めぐって", key=True), t("d8-6", "、"), t("d8-7", "たいりつ", "対立", "たいりつ", key=True),
          t("d8-8", "が"), t("d8-9", "つづいて", "続いて", "つづいて"), t("d8-10", "います", "居ます", "います"), t("d8-11", "ね")],
         "Xoay quanh vấn đề đất đai, sự đối lập vẫn tiếp diễn nhỉ."),
    line(L, 2, "サントス", "Đồng nghiệp",
         [t("d8-12", "はい"), t("d8-13", "。"), t("d8-14", "とち", "土地", "とち", key=True), t("d8-15", "を"),
          t("d8-16", "めぐる", key=True), t("d8-17", "もんだい", "問題", "もんだい", key=True), t("d8-18", "は"),
          t("d8-19", "まだ", "まだ", "まだ", key=True), t("d8-20", "かいけつ", "解決", "かいけつ", key=True), t("d8-21", "して", key=True),
          t("d8-22", "いません", key=True)],
         "Vâng. Vấn đề xoay quanh đất đai vẫn chưa được giải quyết."),
    line(L, 3, "田中", "Đồng nghiệp",
         [t("d8-23", "けいかく", "計画", "けいかく", key=True), t("d8-24", "を"), t("d8-25", "めぐって", key=True),
          t("d8-26", "、"), t("d8-27", "かいしゃ", "会社", "かいしゃ", key=True), t("d8-28", "で"),
          t("d8-29", "ぎろん", "議論", "ぎろん", key=True), t("d8-30", "が"), t("d8-31", "おこなわれました", "行われました", "おこなわれました")],
         "Xoay quanh kế hoạch, đã có tranh luận diễn ra ở công ty."),
    line(L, 4, "サントス", "Đồng nghiệp",
         [t("d8-32", "さんせい", "賛成", "さんせい", key=True), t("d8-33", "する"), t("d8-34", "ひと", "人", "ひと", key=True),
          t("d8-35", "は"), t("d8-36", "おおいです", "多いです", "おおいです"), t("d8-37", "か")],
         "Có nhiều người tán thành không?"),
    line(L, 5, "田中", "Đồng nghiệp",
         [t("d8-38", "はんたい", "反対", "はんたい", key=True), t("d8-39", "する"), t("d8-40", "ひと", "人", "ひと", key=True),
          t("d8-41", "と"), t("d8-42", "たいりつ", "対立", "たいりつ", key=True), t("d8-43", "して", key=True),
          t("d8-44", "います", "居ます", "います")],
         "Đang đối lập với những người phản đối."),
    line(L, 6, "サントス", "Đồng nghiệp",
         [t("d8-45", "せいじ", "政治", "せいじ", key=True), t("d8-46", "を"), t("d8-47", "めぐる", key=True),
          t("d8-48", "いけん", "意見", "いけん", key=True), t("d8-49", "の"), t("d8-50", "ちがい", "違い", "ちがい"),
          t("d8-51", "も"), t("d8-52", "おおきい", "大きい", "おおきい"), t("d8-53", "です", "です", "です"), t("d8-54", "ね")],
         "Sự khác biệt ý kiến xoay quanh chính trị cũng lớn nhỉ."),
    line(L, 7, "田中", "Đồng nghiệp",
         [t("d8-55", "かんきょう", "環境", "かんきょう", key=True), t("d8-56", "を"), t("d8-57", "めぐって", key=True),
          t("d8-58", "も"), t("d8-59", "しゃかい", "社会", "しゃかい", key=True), t("d8-60", "で"), t("d8-61", "ぎろん", "議論", "ぎろん", key=True),
          t("d8-62", "が"), t("d8-63", "あります", "有ります", "あります")],
         "Xoay quanh môi trường cũng có tranh luận trong xã hội."),
    line(L, 8, "サントス", "Đồng nghiệp",
         [t("d8-64", "くに", "国", "くに", key=True), t("d8-65", "ぜんたい", "全体", "ぜんたい"), t("d8-66", "が"),
          t("d8-67", "かんけい", "関係", "かんけい"), t("d8-68", "しますか")],
         "Toàn quốc gia có liên quan không?"),
    line(L, 9, "田中", "Đồng nghiệp",
         [t("d8-69", "はい"), t("d8-70", "。"), t("d8-71", "とうきょう", "東京", "とうきょう", key=True), t("d8-72", "の"),
          t("d8-73", "かいぎ", "会議", "かいぎ", key=True), t("d8-74", "も"), t("d8-75", "つづいて", "続いて", "つづいて"),
          t("d8-76", "います", "居ます", "います")],
         "Vâng. Cuộc họp ở Tokyo cũng đang tiếp diễn."),
    line(L, 10, "サントス", "Đồng nghiệp",
         [t("d8-77", "はやく"), t("d8-78", "かいけつ", "解決", "かいけつ", key=True), t("d8-79", "して", key=True),
          t("d8-80", "ほしい", "欲しい", "ほしい"), t("d8-81", "です", "です", "です"), t("d8-82", "ね")],
         "Mong sẽ sớm được giải quyết nhỉ."),
]

EXERCISES = [
    q(L, 1, "「土地の問題をめぐって、対立が続いています」 — をめぐって diễn tả điều gì?",
      ["Xoay quanh một vấn đề tranh cãi, thường có nhiều bên với quan điểm khác nhau",
       "Sự khẳng định chắc chắn một điều gì đó", "Sự từ chối lịch sự",
       "Phủ định hoàn toàn vấn đề"], 0,
      "をめぐって diễn tả việc xoay quanh một vấn đề TRANH CÃI có nhiều bên quan điểm khác nhau.",
      "Xem cấu trúc をめぐって ở slide 1."),
    q(L, 2, "「土地を巡る問題」 — を巡る khác をめぐって ở điểm nào?",
      ["を巡る là dạng bổ nghĩa danh từ, đứng TRỰC TIẾP trước danh từ nó bổ nghĩa",
       "Hoàn toàn khác nghĩa nhau", "を巡る chỉ dùng cho câu hỏi",
       "をめぐって chỉ dùng cho phủ định"], 0,
      "を巡る là dạng bổ nghĩa danh từ của をめぐって, đứng ngay trước danh từ (như 問題, 議論).",
      "Xem giải thích を巡る ở slide 2."),
    q(L, 3, "Khi nào nên dùng をめぐって thay vì を巡る?",
      ["Khi câu kết thúc bằng một động từ (mệnh đề hoàn chỉnh)",
       "Khi cần một cụm danh từ làm chủ ngữ/tân ngữ", "Không có sự khác biệt nào",
       "Chỉ dùng được trong câu hỏi"], 0,
      "をめぐって dùng khi câu có động từ ở CUỐI câu; を巡る dùng khi cần tạo CỤM DANH TỪ.",
      "Xem mẹo phân biệt ở slide 3."),
    q(L, 4, "「政治を巡る意見の違いは大きい」 nghĩa là:",
      ["Sự khác biệt ý kiến xoay quanh chính trị là rất lớn",
       "Không có sự khác biệt ý kiến nào về chính trị", "Chính trị đã được giải quyết hoàn toàn",
       "Mọi người đều đồng ý về chính trị"], 0,
      "を巡る ở đây bổ nghĩa cho 意見の違い (sự khác biệt ý kiến), nghĩa là sự khác biệt XOAY QUANH chính trị.",
      "Áp dụng cấu trúc Nを巡るN2."),
    q(L, 5, "をめぐって/を巡る thường kết hợp với cặp từ nào để mô tả hai phe tranh luận?",
      ["賛成 (tán thành) và 反対 (phản đối)", "上手 (giỏi) và 下手 (kém)",
       "忙しい (bận) và 暇 (rảnh)", "高い (cao) và 安い (rẻ)"], 0,
      "賛成/反対 là cặp từ điển hình mô tả hai phe ý kiến trái ngược khi dùng をめぐって/を巡る.",
      "Xem cấu trúc kết hợp ở slide 4."),
    q(L, 6, "「この計画をめぐって、賛成する人と反対する人が対立しています」 nghĩa là:",
      ["Xoay quanh kế hoạch này, người tán thành và người phản đối đang đối lập nhau",
       "Mọi người đều tán thành kế hoạch này", "Mọi người đều phản đối kế hoạch này",
       "Kế hoạch này đã bị hủy bỏ"], 0,
      "Câu này mô tả HAI PHE (tán thành và phản đối) đang đối lập nhau xoay quanh kế hoạch.",
      "Áp dụng cấu trúc kết hợp をめぐって + 賛成/反対."),
    q(L, 7, "「環境をめぐって、社会で議論があります」 nghĩa là:",
      ["Xoay quanh môi trường, có tranh luận trong xã hội", "Môi trường đã được cải thiện hoàn toàn",
       "Không ai quan tâm đến môi trường", "Xã hội đã đồng thuận về môi trường"], 0,
      "をめぐって ở đây chỉ ra rằng vấn đề môi trường đang là chủ đề TRANH LUẬN trong xã hội.",
      "Áp dụng cấu trúc Nをめぐって cho ngữ cảnh câu."),
    q(L, 8, "Theo hội thoại, vấn đề đất đai đã được giải quyết chưa?",
      ["Chưa, vẫn chưa được giải quyết (まだ解決していません)", "Đã được giải quyết hoàn toàn",
       "Không cần giải quyết", "Không được đề cập trong hội thoại"], 0,
      "Santos nói 「土地を巡る問題はまだ解決していません」.",
      "Xem câu thoại thứ 2."),
    q(L, 9, "Ai đang đối lập với nhau trong hội thoại về kế hoạch của công ty?",
      ["Người phản đối và người tán thành (反対する人と対立しています)",
       "Chỉ có một phe duy nhất", "Không ai đối lập cả",
       "Giám đốc và trưởng phòng"], 0,
      "田中 nói 「反対する人と対立しています」.",
      "Xem câu thoại thứ 5."),
    q(L, 10, "Santos mong muốn điều gì ở cuối hội thoại?",
      ["Vấn đề sẽ sớm được giải quyết (早く解決してほしいです)",
       "Vấn đề sẽ kéo dài mãi mãi", "Cuộc họp sẽ bị hủy",
       "Không mong muốn gì cả"], 0,
      "Santos nói 「早く解決してほしいですね」.",
      "Xem câu thoại cuối cùng."),
]

LESSON = lesson(
    L,
    "Bài 8: Tranh cãi & Vấn đề xoay quanh (をめぐって & を巡る)",
    "をめぐって diễn tả 'xoay quanh' một VẤN ĐỀ TRANH CÃI có nhiều bên quan điểm khác nhau, "
    "thường theo sau bởi động từ tranh luận/đối lập, dùng khi câu kết thúc bằng động từ; を巡る là "
    "dạng bổ nghĩa danh từ tương ứng, đứng trực tiếp trước danh từ nó bổ nghĩa; thường kết hợp với "
    "賛成/反対 để mô tả hai phe ý kiến trái ngược.",
    VOCAB, KANJI, SLIDES, DIALOGUE, EXERCISES,
)

if __name__ == "__main__":
    pool.mark_used([w["word"] for w in VOCAB if w["word"]], lesson=L)
    merge([LESSON])
