# -*- coding: utf-8 -*-
"""N2 — Bai 5: Ti le thuan にしたがって (theo quy luat/tuan theo) va につれて (song song tu nhien),
on lai 一方だ (N3 bai 14).

Tu vung minh hoa TU CHON tu pool mo data/jlpt-vocab/n2.csv (xem NOTICE.md).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from n2_lib import v, k, t, ex, slide, line, q, lesson, merge
from jlpt_pool import Pool

L = 5
pool = Pool("n2")

VOCAB = [
    v(1,  "きょうかします", "強化します", "きょうかします", "kyouka shimasu", "verb", "Tăng cường", "きそくを 強化します = tăng cường quy tắc.", L),
    v(2,  "みなれます", "見慣れます", "みなれます", "minaremasu", "verb", "Quen mắt (khi nhìn nhiều lần)", "みなれた けしき = phong cảnh đã quen mắt.", L),
    v(3,  "じしん", "自信", "じしん", "jishin", "noun", "Sự tự tin", "自信が つきます = có được sự tự tin.", L),
    v(4,  "ねんれい", "年齢", "ねんれい", "nenrei", "noun", "Độ tuổi", "年齢が あがるに したがって = theo độ tuổi tăng lên.", L),
    v(5,  "かわります", "変わります", "かわります", "kawarimasu", "verb", "Thay đổi", "きせつが かわります = mùa thay đổi.", L),
    v(6,  "たちます", "経ちます", "たちます", "tachimasu", "verb", "Trôi qua (thời gian)", "じかんが たちます = thời gian trôi qua.", L),
    v(7,  "つよい", "強い", "つよい", "tsuyoi", "adjective", "Mạnh", "かぜが つよく なります = gió trở nên mạnh.", L),
    v(8,  "ちかづきます", "近づきます", "ちかづきます", "chikazukimasu", "verb", "Đến gần", "たいふうが ちかづきます = bão đến gần.", L),
    v(9,  "なれます", "慣れます", "なれます", "naremasu", "verb", "Quen thuộc, làm quen", "Đã gặp N4 bài 26.", L),
    v(10, "きせつ", "季節", "きせつ", "kisetsu", "noun", "Mùa", "Đã gặp N5 bài 25.", L),
    v(11, "きおん", "気温", "きおん", "kion", "noun", "Nhiệt độ", "Đã gặp N3 bài 5.", L),
    v(12, "とし", "年", "とし", "toshi", "noun", "Năm, tuổi", "Đã gặp N4 bài 26.", L),
    v(13, "にほんご", "日本語", "にほんご", "nihongo", "noun", "Tiếng Nhật", "Đã gặp N4 bài 26.", L),
    v(14, "じょうず", "上手", "じょうず", "jouzu", "adjective", "Giỏi", "Đã gặp N4 bài 26.", L),
    v(15, "じかん", "時間", "じかん", "jikan", "noun", "Thời gian", "Đã gặp N4 bài 26.", L),
    v(16, "かぜ", "風", "かぜ", "kaze", "noun", "Gió", "Đã gặp N4 bài 34.", L),
    v(17, "たいふう", "台風", "たいふう", "taifuu", "noun", "Bão", "Đã gặp N4 bài 34.", L),
    v(18, "きそく", "規則", "きそく", "kisoku", "noun", "Quy tắc", "Đã gặp N4 bài 33.", L),
    v(19, "したがいます", "従います", "したがいます", "shitagaimasu", "verb", "Tuân theo", "Đã gặp N3 bài 19.", L),
    v(20, "わすれます", "忘れます", "わすれます", "wasuremasu", "verb", "Quên", "Đã gặp N4 bài 38.", L),
]

KANJI = [
    k(1, "強", "CƯỜNG", 11, ["キョウ (kyou)"], ["つよ(い)"], "Mạnh, cường tráng.",
      [("強化", "きょうか", "Tăng cường"), ("強い", "つよい", "Mạnh")], L),
    k(2, "慣", "QUÁN", 14, ["カン (kan)"], ["な(れる)"], "Quen thuộc, thói quen.",
      [("慣れます", "なれます", "Quen thuộc"), ("見慣れる", "みなれる", "Quen mắt")], L),
    k(3, "齢", "LINH", 17, ["レイ (rei)"], [], "Tuổi tác.",
      [("年齢", "ねんれい", "Độ tuổi"), ("高齢", "こうれい", "Cao tuổi")], L),
    k(4, "近", "CẬN", 7, ["キン (kin)"], ["ちか(い)", "ちか(づく)"], "Gần, lân cận.",
      [("近づきます", "ちかづきます", "Đến gần"), ("近く", "ちかく", "Gần đây")], L),
    k(5, "変", "BIẾN", 9, ["ヘン (hen)"], ["か(わる)"], "Thay đổi, biến hóa.",
      [("変わります", "かわります", "Thay đổi"), ("変化", "へんか", "Sự thay đổi")], L),
]

SLIDES = [
    slide(L, 1,
        "1. Theo sự thay đổi tỉ lệ thuận (có tính quy luật): V(từ điển)/N + にしたがって",
        "V(thể từ điển)/N + にしたがって、[thay đổi tương ứng]",
        "にしたがって diễn tả 'THEO' sự thay đổi của A thì B cũng thay đổi TƯƠNG ỨNG — mang tính "
        "QUY LUẬT/LOGIC hơn hẳn につれて, và còn có thể mang nghĩa 'TUÂN THEO' khi đi với danh từ chỉ quy tắc.",
        [
            ex(L, 1, 1, [t("t-l5s1-1", "にほんご", "日本語", "にほんご", key=True), t("t-l5s1-2", "が"),
                         t("t-l5s1-3", "じょうず", "上手", "じょうず", key=True), t("t-l5s1-4", "に"),
                         t("t-l5s1-5", "なる"), t("t-l5s1-6", "に", key=True), t("t-l5s1-7", "したがって", "従って", "したがって", key=True),
                         t("t-l5s1-8", "、"), t("t-l5s1-9", "じしん", "自信", "じしん", key=True), t("t-l5s1-10", "が"),
                         t("t-l5s1-11", "つきます", "付きます", "つきます")],
               "Theo việc tiếng Nhật giỏi lên, sự tự tin cũng tăng theo."),
            ex(L, 1, 2, [t("t-l5s1-12", "きそく", "規則", "きそく", key=True), t("t-l5s1-13", "に", key=True),
                         t("t-l5s1-14", "したがって", "従って", "したがって", key=True), t("t-l5s1-15", "、"),
                         t("t-l5s1-16", "こうどう", "行動", "こうどう"), t("t-l5s1-17", "して", key=True), t("t-l5s1-18", "ください")],
               "Hãy hành động theo quy tắc. (nghĩa 'tuân theo')"),
        ],
        tips="にしたがって có 2 nghĩa: (1) tỉ lệ thuận theo thay đổi, (2) tuân theo quy tắc/mệnh lệnh — につれて KHÔNG có nghĩa (2).",
        culture="Văn bản hướng dẫn, quy định công ty Nhật hay dùng nghĩa 'tuân theo': '規則にしたがって、行動してください'."),

    slide(L, 2,
        "2. Cùng với, theo đà (song song tự nhiên): V(từ điển)/N + につれて",
        "V(thể từ điển)/N + につれて、[thay đổi tương ứng]",
        "につれて diễn tả 'CÙNG VỚI' việc A thay đổi thì B cũng thay đổi theo — chỉ mô tả sự thay "
        "đổi SONG SONG TỰ NHIÊN, KHÔNG mang nghĩa 'tuân theo quy tắc' như にしたがって.",
        [
            ex(L, 2, 1, [t("t-l5s2-1", "じかん", "時間", "じかん", key=True), t("t-l5s2-2", "が"),
                         t("t-l5s2-3", "たつ", "経つ", "たつ", key=True), t("t-l5s2-4", "に", key=True),
                         t("t-l5s2-5", "つれて", key=True), t("t-l5s2-6", "、"), t("t-l5s2-7", "わすれて", "忘れて", "わすれて", key=True),
                         t("t-l5s2-8", "いきます", "行きます", "いきます")],
               "Theo thời gian trôi qua, dần dần quên đi."),
            ex(L, 2, 2, [t("t-l5s2-9", "たいふう", "台風", "たいふう", key=True), t("t-l5s2-10", "が"),
                         t("t-l5s2-11", "ちかづく", "近づく", "ちかづく", key=True), t("t-l5s2-12", "に", key=True),
                         t("t-l5s2-13", "つれて", key=True), t("t-l5s2-14", "、"), t("t-l5s2-15", "かぜ", "風", "かぜ", key=True),
                         t("t-l5s2-16", "が"), t("t-l5s2-17", "つよく", "強く", "つよく", key=True), t("t-l5s2-18", "なります", "成ります", "なります")],
               "Khi bão đến gần, gió trở nên mạnh hơn."),
        ],
        tips="につれて thường dùng cho hiện tượng TỰ NHIÊN (thời gian, thời tiết, tuổi tác) — không dùng cho mệnh lệnh/quy tắc.",
        culture="Câu miêu tả tự nhiên trong văn học Nhật: '季節が変わるにつれて、気温も下がっていく' (theo mùa thay đổi, nhiệt độ cũng giảm dần)."),

    slide(L, 3,
        "3. So sánh にしたがって và につれて",
        "にしたがって: có thể mang nghĩa TUÂN THEO + tỉ lệ thuận　vs　につれて: CHỈ tỉ lệ thuận song song tự nhiên",
        "にしたがって RỘNG NGHĨA hơn (dùng được cho cả 'tuân theo mệnh lệnh' lẫn 'tỉ lệ thuận'); "
        "につれて CHỈ dùng cho sự thay đổi TỰ NHIÊN, không có sắc thái mệnh lệnh — trong nhiều "
        "trường hợp tỉ lệ thuận cả hai có thể thay thế nhau.",
        [
            ex(L, 3, 1, [t("t-l5s3-1", "ねんれい", "年齢", "ねんれい", key=True), t("t-l5s3-2", "が"),
                         t("t-l5s3-3", "あがる", "上がる", "あがる"), t("t-l5s3-4", "に", key=True),
                         t("t-l5s3-5", "したがって", "従って", "したがって", key=True), t("t-l5s3-6", "、"),
                         t("t-l5s3-7", "みなれた", "見慣れた", "みなれた", key=True), t("t-l5s3-8", "けしき", "景色", "けしき"),
                         t("t-l5s3-9", "が"), t("t-l5s3-10", "かわります", "変わります", "かわります", key=True)],
               "Theo độ tuổi tăng lên, phong cảnh đã quen mắt cũng thay đổi. (có thể thay bằng につれて)"),
            ex(L, 3, 2, [t("t-l5s3-11", "きそく", "規則", "きそく", key=True), t("t-l5s3-12", "に", key=True),
                         t("t-l5s3-13", "したがって", "従って", "したがって", key=True), t("t-l5s3-14", "、"),
                         t("t-l5s3-15", "したがいます", "従います", "したがいます")],
               "Tuân theo quy tắc. (KHÔNG thể thay bằng につれて vì đây là nghĩa 'tuân theo')"),
        ],
        tips="Mẹo: nếu câu có ý MỆNH LỆNH/QUY TẮC → chỉ dùng にしたがって; nếu chỉ là hai HIỆN TƯỢNG thay đổi song song → cả hai đều dùng được.",
        culture="Đây là điểm ngữ pháp N2 hay gây nhầm lẫn nhất vì cả hai đều dịch là 'theo/cùng với' — cần nhớ につれて hẹp nghĩa hơn."),

    slide(L, 4,
        "4. Kết hợp với 一方だ (ôn N3 bài 14): mô tả xu hướng liên tục",
        "Nにつれて/にしたがって、[thay đổi A]一方だ",
        "Kết hợp につれて/にしたがって với 一方だ (đã học N3 bài 14 — xu hướng MỘT CHIỀU liên tục) "
        "để nhấn mạnh một QUÁ TRÌNH THAY ĐỔI DÀI HẠN, không ngừng lại, thường dùng trong báo cáo, phân tích xu hướng.",
        [
            ex(L, 4, 1, [t("t-l5s4-1", "きおん", "気温", "きおん", key=True), t("t-l5s4-2", "が"),
                         t("t-l5s4-3", "あがる", "上がる", "あがる"), t("t-l5s4-4", "に", key=True),
                         t("t-l5s4-5", "つれて", key=True), t("t-l5s4-6", "、"), t("t-l5s4-7", "きせつ", "季節", "きせつ", key=True),
                         t("t-l5s4-8", "は"), t("t-l5s4-9", "かわる", "変わる", "かわる"), t("t-l5s4-10", "いっぽう", "一方", "いっぽう", key=True),
                         t("t-l5s4-11", "だ")],
               "Theo đà nhiệt độ tăng, mùa cứ thay đổi liên tục."),
            ex(L, 4, 2, [t("t-l5s4-12", "とし", "年", "とし", key=True), t("t-l5s4-13", "を"),
                         t("t-l5s4-14", "とる", "取る", "とる"), t("t-l5s4-15", "に", key=True), t("t-l5s4-16", "したがって", "従って", "したがって", key=True),
                         t("t-l5s4-17", "、"), t("t-l5s4-18", "きょうか", "強化", "きょうか", key=True), t("t-l5s4-19", "する"),
                         t("t-l5s4-20", "いっぽう", "一方", "いっぽう", key=True), t("t-l5s4-21", "だ")],
               "Theo tuổi tác tăng lên, việc tăng cường (sức khỏe) chỉ ngày càng cần thiết."),
        ],
        tips="Cấu trúc につれて/にしたがって + 一方だ thường xuất hiện trong tiêu đề báo cáo xã hội học, kinh tế học phân tích xu hướng dài hạn.",
        culture="Đây là cách kết hợp ngữ pháp N2+N3 điển hình mà đề thi đọc hiểu JLPT hay lồng ghép để kiểm tra khả năng nắm bắt ngữ pháp tổng hợp."),
]

DIALOGUE = [
    line(L, 1, "田中", "Bạn học tiếng Nhật",
         [t("d5-1", "にほんご", "日本語", "にほんご", key=True), t("d5-2", "が"), t("d5-3", "じょうず", "上手", "じょうず", key=True),
          t("d5-4", "に"), t("d5-5", "なりました", "成りました", "なりました"), t("d5-6", "ね")],
         "Tiếng Nhật của bạn giỏi lên rồi nhỉ."),
    line(L, 2, "サントス", "Bạn học tiếng Nhật",
         [t("d5-7", "はい"), t("d5-8", "。"), t("d5-9", "じょうず", "上手", "じょうず", key=True), t("d5-10", "に"),
          t("d5-11", "なる"), t("d5-12", "に", key=True), t("d5-13", "したがって", "従って", "したがって", key=True),
          t("d5-14", "、"), t("d5-15", "じしん", "自信", "じしん", key=True), t("d5-16", "が"),
          t("d5-17", "つきました", "付きました", "つきました")],
         "Vâng. Theo việc giỏi lên, sự tự tin cũng tăng theo."),
    line(L, 3, "田中", "Bạn học tiếng Nhật",
         [t("d5-18", "じかん", "時間", "じかん", key=True), t("d5-19", "が"), t("d5-20", "たつ", "経つ", "たつ", key=True),
          t("d5-21", "に", key=True), t("d5-22", "つれて", key=True), t("d5-23", "、"), t("d5-24", "べんきょう", "勉強", "べんきょう"),
          t("d5-25", "が"), t("d5-26", "らくに"), t("d5-27", "なりました", "成りました", "なりました"), t("d5-28", "か")],
         "Theo thời gian trôi qua, việc học có trở nên dễ dàng hơn không?"),
    line(L, 4, "サントス", "Bạn học tiếng Nhật",
         [t("d5-29", "はい"), t("d5-30", "。"), t("d5-31", "きそく", "規則", "きそく", key=True), t("d5-32", "に", key=True),
          t("d5-33", "したがって", "従って", "したがって", key=True), t("d5-34", "、"), t("d5-35", "まいにち", "毎日", "まいにち"),
          t("d5-36", "べんきょう", "勉強", "べんきょう"), t("d5-37", "しました")],
         "Vâng. Tôi đã học mỗi ngày theo đúng quy tắc (kỷ luật của bản thân)."),
    line(L, 5, "田中", "Bạn học tiếng Nhật",
         [t("d5-38", "たのもしい", "頼もしい", "たのもしい"), t("d5-39", "です", "です", "です"), t("d5-40", "ね")],
         "Bạn thật đáng tin cậy nhỉ."),
    line(L, 6, "サントス", "Bạn học tiếng Nhật",
         [t("d5-41", "ねんれい", "年齢", "ねんれい", key=True), t("d5-42", "が"), t("d5-43", "あがる", "上がる", "あがる"),
          t("d5-44", "に", key=True), t("d5-45", "したがって", "従って", "したがって", key=True), t("d5-46", "、"),
          t("d5-47", "みなれた", "見慣れた", "みなれた", key=True), t("d5-48", "けしき", "景色", "けしき"),
          t("d5-49", "も"), t("d5-50", "かわりました", "変わりました", "かわりました", key=True)],
         "Theo độ tuổi tăng lên, phong cảnh đã quen mắt cũng thay đổi."),
    line(L, 7, "田中", "Bạn học tiếng Nhật",
         [t("d5-51", "たいふう", "台風", "たいふう", key=True), t("d5-52", "が"), t("d5-53", "ちかづく", "近づく", "ちかづく", key=True),
          t("d5-54", "に", key=True), t("d5-55", "つれて", key=True), t("d5-56", "、"), t("d5-57", "かぜ", "風", "かぜ", key=True),
          t("d5-58", "が"), t("d5-59", "つよく", "強く", "つよく", key=True), t("d5-60", "なりました", "成りました", "なりました")],
         "Khi bão đến gần, gió trở nên mạnh hơn."),
    line(L, 8, "サントス", "Bạn học tiếng Nhật",
         [t("d5-61", "きおん", "気温", "きおん", key=True), t("d5-62", "も"), t("d5-63", "さがる", "下がる", "さがる"),
          t("d5-64", "いっぽう", "一方", "いっぽう", key=True), t("d5-65", "です")],
         "Nhiệt độ cũng chỉ ngày càng giảm."),
    line(L, 9, "田中", "Bạn học tiếng Nhật",
         [t("d5-66", "きせつ", "季節", "きせつ", key=True), t("d5-67", "が"), t("d5-68", "かわる", "変わる", "かわる"),
          t("d5-69", "いっぽう", "一方", "いっぽう", key=True), t("d5-70", "です", "です", "です"), t("d5-71", "ね")],
         "Mùa cứ thay đổi liên tục nhỉ."),
    line(L, 10, "サントス", "Bạn học tiếng Nhật",
         [t("d5-72", "そうですね"), t("d5-73", "。"), t("d5-74", "からだ", "体", "からだ"), t("d5-75", "を"),
          t("d5-76", "きょうか", "強化", "きょうか", key=True), t("d5-77", "した"), t("d5-78", "ほうが"),
          t("d5-79", "いいです")],
         "Đúng vậy nhỉ. Nên tăng cường sức khỏe cơ thể."),
]

EXERCISES = [
    q(L, 1, "「日本語が上手になるにしたがって、自信がつきます」 — にしたがって diễn tả điều gì?",
      ["Theo sự thay đổi của A thì B cũng thay đổi tương ứng (mang tính quy luật)",
       "Tuân theo mệnh lệnh một cách máy móc", "So sánh hai điều kiện",
       "Phủ định việc tự tin"], 0,
      "にしたがって diễn tả sự thay đổi tỉ lệ thuận có tính quy luật giữa hai vế của câu.",
      "Xem cấu trúc にしたがって ở slide 1."),
    q(L, 2, "「規則にしたがって、行動してください」 — にしたがって ở đây mang nghĩa gì?",
      ["Tuân theo (quy tắc) — nghĩa thứ hai của にしたがって",
       "Tỉ lệ thuận về thời gian", "Phủ định việc hành động",
       "So sánh hai quy tắc khác nhau"], 0,
      "にしたがって có 2 nghĩa: tỉ lệ thuận VÀ tuân theo quy tắc — ở đây là nghĩa tuân theo.",
      "Xem nghĩa thứ hai ở slide 1."),
    q(L, 3, "につれて có thể dùng để diễn tả nghĩa 'tuân theo mệnh lệnh' không?",
      ["Không, につれて CHỈ diễn tả sự thay đổi song song tự nhiên",
       "Có, hoàn toàn giống にしたがって", "Chỉ dùng được trong câu hỏi",
       "Chỉ dùng được trong câu phủ định"], 0,
      "につれて hẹp nghĩa hơn にしたがって — KHÔNG có nghĩa 'tuân theo', chỉ mô tả thay đổi song song tự nhiên.",
      "Xem giải thích につれて ở slide 2."),
    q(L, 4, "「時間が経つにつれて、忘れていきます」 nghĩa là:",
      ["Theo thời gian trôi qua, dần dần quên đi", "Ngay lập tức quên hết mọi thứ",
       "Không bao giờ quên", "Thời gian đã dừng lại"], 0,
      "につれて ở đây mô tả sự thay đổi song song tự nhiên: thời gian trôi qua → dần dần quên đi.",
      "Áp dụng cấu trúc につれて cho ngữ cảnh câu."),
    q(L, 5, "Trường hợp nào KHÔNG THỂ thay にしたがって bằng につれて?",
      ["Khi câu mang nghĩa 'tuân theo quy tắc/mệnh lệnh'",
       "Khi câu mô tả sự thay đổi song song tự nhiên", "Không có trường hợp nào cả",
       "Chỉ khi câu là câu hỏi"], 0,
      "につれて không có nghĩa 'tuân theo', nên câu như 規則にしたがって (tuân theo quy tắc) không thể đổi thành 規則につれて.",
      "Xem mẹo phân biệt ở slide 3."),
    q(L, 6, "「気温が上がるにつれて、季節は変わる一方だ」 — kết hợp につれて và 一方だ để làm gì?",
      ["Nhấn mạnh một quá trình thay đổi dài hạn, liên tục không ngừng lại",
       "Phủ định sự thay đổi", "So sánh hai mùa khác nhau",
       "Chỉ ra một sự kiện xảy ra một lần duy nhất"], 0,
      "Kết hợp につれて (song song) với 一方だ (một chiều liên tục, đã học N3) nhấn mạnh xu hướng thay đổi dài hạn.",
      "Xem cấu trúc kết hợp ở slide 4."),
    q(L, 7, "「年を取るにしたがって、強化する一方だ」 nghĩa là:",
      ["Theo tuổi tác tăng lên, việc tăng cường (sức khỏe) chỉ ngày càng cần thiết",
       "Tuổi tác không ảnh hưởng gì đến sức khỏe", "Không cần tăng cường gì cả",
       "Tuổi tác giảm dần theo thời gian"], 0,
      "にしたがって+一方だ nhấn mạnh mối liên hệ tỉ lệ thuận liên tục giữa tuổi tác và nhu cầu tăng cường sức khỏe.",
      "Áp dụng cấu trúc kết hợp ở slide 4."),
    q(L, 8, "Theo hội thoại, Santos đã học tiếng Nhật như thế nào?",
      ["Học mỗi ngày theo quy tắc/kỷ luật của bản thân (規則にしたがって、毎日勉強しました)",
       "Chỉ học khi có thời gian rảnh", "Không học đều đặn",
       "Chỉ học vào cuối tuần"], 0,
      "Santos nói 「規則にしたがって、毎日勉強しました」.",
      "Xem câu thoại thứ 4."),
    q(L, 9, "Điều gì xảy ra khi bão đến gần theo hội thoại?",
      ["Gió trở nên mạnh hơn (風が強くなりました)", "Gió trở nên yếu đi",
       "Không có gì thay đổi", "Trời trở nên nắng đẹp"], 0,
      "田中 nói 「台風が近づくにつれて、風が強くなりました」.",
      "Xem câu thoại thứ 7."),
    q(L, 10, "Santos đề xuất điều gì ở cuối hội thoại?",
      ["Nên tăng cường sức khỏe cơ thể (体を強化したほうがいいです)",
       "Nên đi du lịch", "Nên nghỉ học tiếng Nhật", "Không đề xuất gì cả"], 0,
      "Santos nói 「体を強化したほうがいいです」.",
      "Xem câu thoại cuối cùng."),
]

LESSON = lesson(
    L,
    "Bài 5: Tỉ lệ thuận & Càng ngày càng (にしたがって & につれて & 一方だ)",
    "にしたがって diễn tả sự thay đổi tỉ lệ thuận CÓ TÍNH QUY LUẬT, và còn mang thêm nghĩa 'TUÂN "
    "THEO' quy tắc/mệnh lệnh; につれて hẹp nghĩa hơn, CHỈ mô tả sự thay đổi SONG SONG TỰ NHIÊN "
    "(không có nghĩa tuân theo); kết hợp với 一方だ (ôn N3 bài 14) để nhấn mạnh xu hướng thay đổi dài hạn, liên tục.",
    VOCAB, KANJI, SLIDES, DIALOGUE, EXERCISES,
)

if __name__ == "__main__":
    pool.mark_used([w["word"] for w in VOCAB if w["word"]], lesson=L)
    merge([LESSON])
