# -*- coding: utf-8 -*-
"""N2 — Bai 13: Vuot ngoai gioi han にとどまらず (khong chi dung lai o mot pham vi hep).

Tu vung minh hoa TU CHON tu pool mo data/jlpt-vocab/n2.csv (xem NOTICE.md).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from n2_lib import v, k, t, ex, slide, line, q, lesson, merge
from jlpt_pool import Pool

L = 13
pool = Pool("n2")

VOCAB = [
    v(1,  "とどまります", "留まります", "とどまります", "todomarimasu", "verb", "Dừng lại, ở lại (trong một phạm vi)", "この まちに 留まります = ở lại thị trấn này.", L),
    v(2,  "かくちょうします", "拡張します", "かくちょうします", "kakuchou shimasu", "verb", "Mở rộng", "じぎょうを 拡張します = mở rộng sự nghiệp.", L),
    v(3,  "たんに", "単に", "たんに", "tan ni", "adverb", "Chỉ đơn thuần", "単に 問題だけでなく = không chỉ đơn thuần là vấn đề.", L),
    v(4,  "ぶんや", "分野", "ぶんや", "bun-ya", "noun", "Lĩnh vực", "Đã gặp N3 bài 6.", L),
    v(5,  "えいきょう", "影響", "えいきょう", "eikyou", "noun", "Ảnh hưởng", "Đã gặp N2 bài 7.", L),
    v(6,  "せかい", "世界", "せかい", "sekai", "noun", "Thế giới", "Đã gặp N4 bài 26.", L),
    v(7,  "かいしゃ", "会社", "かいしゃ", "kaisha", "noun", "Công ty", "Đã gặp N4 bài 26.", L),
    v(8,  "けいざい", "経済", "けいざい", "keizai", "noun", "Kinh tế", "Đã gặp N3 bài 14.", L),
    v(9,  "かんきょう", "環境", "かんきょう", "kankyou", "noun", "Môi trường", "Đã gặp N3 bài 5.", L),
    v(10, "もんだい", "問題", "もんだい", "mondai", "noun", "Vấn đề", "Đã gặp N5 bài 22.", L),
    v(11, "ふきゅうします", "普及します", "ふきゅうします", "fukyuu shimasu", "verb", "Phổ biến, lan rộng", "Đã gặp N2 bài 7.", L),
    v(12, "にほん", "日本", "にほん", "nihon", "noun", "Nhật Bản", "Đã gặp N4 bài 26.", L),
    v(13, "せかいじゅう", "世界中", "せかいじゅう", "sekaijuu", "noun", "Khắp thế giới", "Đã gặp N4 bài 26.", L),
    v(14, "かつどうします", "活動します", "かつどうします", "katsudou shimasu", "verb", "Hoạt động", "Đã gặp N2 bài 6.", L),
    v(15, "はってんします", "発展します", "はってんします", "hatten shimasu", "verb", "Phát triển", "Đã gặp N3 bài 14.", L),
    v(16, "ぎじゅつ", "技術", "ぎじゅつ", "gijutsu", "noun", "Kỹ thuật", "Đã gặp N3 bài 14.", L),
    v(17, "しゃかい", "社会", "しゃかい", "shakai", "noun", "Xã hội", "Đã gặp N3 bài 5.", L),
    v(18, "だけでなく", "だけでなく", "だけでなく", "dake de naku", "expression", "Không chỉ (trung tính)", "Đã gặp N3 bài 15.", L),
    v(19, "のみならず", "のみならず", "のみならず", "nomi narazu", "expression", "Không những (cực trang trọng)", "Đã gặp N2 bài 7.", L),
    v(20, "ばかりか", "ばかりか", "ばかりか", "bakari ka", "expression", "Không những (nhấn mạnh)", "Đã gặp N3 bài 15.", L),
]

KANJI = [
    k(1, "留", "LƯU", 10, ["リュウ (ryuu)"], ["と(まる)", "と(どまる)"], "Ở lại, dừng lại.",
      [("留まる", "とどまる", "Dừng lại, ở lại"), ("留学", "りゅうがく", "Du học")], L),
    k(2, "張", "TRƯƠNG", 11, ["チョウ (chou)"], ["は(る)"], "Căng ra, mở rộng.",
      [("拡張", "かくちょう", "Mở rộng"), ("主張", "しゅちょう", "Chủ trương")], L),
    k(3, "単", "ĐƠN", 9, ["タン (tan)"], [], "Đơn giản, đơn lẻ.",
      [("単に", "たんに", "Chỉ đơn thuần"), ("単語", "たんご", "Từ vựng")], L),
    k(4, "拡", "KHOÁCH", 8, ["カク (kaku)"], [], "Mở rộng.",
      [("拡張", "かくちょう", "Mở rộng"), ("拡大", "かくだい", "Mở rộng")], L),
    k(5, "世", "THẾ", 5, ["セイ (sei)", "セ (se)"], ["よ"], "Đời, thế giới.",
      [("世界", "せかい", "Thế giới"), ("世界中", "せかいじゅう", "Khắp thế giới")], L),
]

SLIDES = [
    slide(L, 1,
        "1. Không chỉ dừng lại ở... (vượt ra phạm vi hẹp): N + にとどまらず",
        "N/[thể thường] + にとどまらず、[phạm vi mở rộng hơn]も/まで",
        "にとどまらず (từ động từ gốc 留まる - dừng lại/ở lại) diễn tả việc VƯỢT RA KHỎI một PHẠM "
        "VI/GIỚI HẠN ban đầu để mở rộng SANG một phạm vi RỘNG HƠN — văn phong TRANG TRỌNG, học thuật.",
        [
            ex(L, 1, 1, [t("t-l13s1-1", "この"), t("t-l13s1-2", "もんだい", "問題", "もんだい", key=True), t("t-l13s1-3", "は"),
                         t("t-l13s1-4", "かんきょう", "環境", "かんきょう", key=True), t("t-l13s1-5", "に", key=True),
                         t("t-l13s1-6", "とどまらず", key=True), t("t-l13s1-7", "、"), t("t-l13s1-8", "けいざい", "経済", "けいざい", key=True),
                         t("t-l13s1-9", "にも"), t("t-l13s1-10", "えいきょう", "影響", "えいきょう", key=True), t("t-l13s1-11", "します")],
               "Vấn đề này không chỉ dừng lại ở môi trường mà còn ảnh hưởng đến cả kinh tế."),
            ex(L, 1, 2, [t("t-l13s1-12", "かいしゃ", "会社", "かいしゃ", key=True), t("t-l13s1-13", "の"),
                         t("t-l13s1-14", "かつどう", "活動", "かつどう", key=True), t("t-l13s1-15", "は"),
                         t("t-l13s1-16", "にほん", "日本", "にほん", key=True), t("t-l13s1-17", "に", key=True),
                         t("t-l13s1-18", "とどまらず", key=True), t("t-l13s1-19", "、"), t("t-l13s1-20", "せかいじゅう", "世界中", "せかいじゅう", key=True),
                         t("t-l13s1-21", "に"), t("t-l13s1-22", "ふきゅう", "普及", "ふきゅう", key=True), t("t-l13s1-23", "して", key=True),
                         t("t-l13s1-24", "います", "居ます", "います")],
               "Hoạt động của công ty không chỉ dừng lại ở Nhật Bản mà còn phổ biến khắp thế giới."),
        ],
        tips="にとどまらず gần với のみならず về mức độ trang trọng, nhưng nhấn mạnh Ý NGHĨA 'VƯỢT QUA GIỚI HẠN' rõ hơn nhờ nguồn gốc động từ 留まる.",
        culture="Báo cáo nghiên cứu Nhật hay viết: 'この技術の影響は一つの分野にとどまらない' (ảnh hưởng của công nghệ này không chỉ dừng lại ở một lĩnh vực)."),

    slide(L, 2,
        "2. Kết hợp với 単に để nhấn mạnh phạm vi ban đầu quá hẹp",
        "単に + N + にとどまらず、[phạm vi rộng hơn]",
        "単に (chỉ đơn thuần) thường đứng TRƯỚC にとどまらず để NHẤN MẠNH rằng phạm vi ban đầu "
        "chỉ là một phần NHỎ/ĐƠN GIẢN so với phạm vi THỰC SỰ của vấn đề.",
        [
            ex(L, 2, 1, [t("t-l13s2-1", "たんに", "単に", "たんに", key=True), t("t-l13s2-2", "ぎじゅつ", "技術", "ぎじゅつ", key=True),
                         t("t-l13s2-3", "の"), t("t-l13s2-4", "ぶんや", "分野", "ぶんや", key=True), t("t-l13s2-5", "に", key=True),
                         t("t-l13s2-6", "とどまらず", key=True), t("t-l13s2-7", "、"), t("t-l13s2-8", "しゃかい", "社会", "しゃかい", key=True),
                         t("t-l13s2-9", "ぜんたい", "全体", "ぜんたい"), t("t-l13s2-10", "に"), t("t-l13s2-11", "えいきょう", "影響", "えいきょう", key=True),
                         t("t-l13s2-12", "します")],
               "Không chỉ đơn thuần dừng lại ở lĩnh vực kỹ thuật, mà còn ảnh hưởng đến toàn xã hội."),
            ex(L, 2, 2, [t("t-l13s2-13", "たんに", "単に", "たんに", key=True), t("t-l13s2-14", "かいしゃ", "会社", "かいしゃ", key=True),
                         t("t-l13s2-15", "の"), t("t-l13s2-16", "もんだい", "問題", "もんだい", key=True), t("t-l13s2-17", "に", key=True),
                         t("t-l13s2-18", "とどまらず", key=True), t("t-l13s2-19", "、"), t("t-l13s2-20", "しゃかい", "社会", "しゃかい", key=True),
                         t("t-l13s2-21", "の"), t("t-l13s2-22", "もんだい", "問題", "もんだい", key=True), t("t-l13s2-23", "にも"),
                         t("t-l13s2-24", "なりました", "成りました", "なりました")],
               "Không chỉ đơn thuần dừng lại ở vấn đề công ty, mà còn trở thành vấn đề xã hội."),
        ],
        tips="単に〜にとどまらず là cụm CỐ ĐỊNH cực kỳ phổ biến trong văn bản học thuật để mở đầu luận điểm về PHẠM VI RỘNG của một vấn đề.",
        culture="Luận văn khoa học xã hội Nhật thường mở đầu bằng: '単に経済問題にとどまらず、社会問題でもある' (không chỉ đơn thuần là vấn đề kinh tế, mà còn là vấn đề xã hội)."),

    slide(L, 3,
        "3. So sánh にとどまらず với だけでなく/のみならず/ばかりか",
        "Cả 4 đều nghĩa 'không chỉ... mà còn...' nhưng にとどまらず nhấn PHẠM VI BAN ĐẦU quá HẸP so với thực tế",
        "だけでなく (N3, trung tính) < ばかりか (N3, nhấn mạnh) ≈ のみならず (N2, cực trang trọng) "
        "≈ にとどまらず (N2, cực trang trọng, nhấn GIỚI HẠN ban đầu qua hình ảnh 'dừng lại/ở lại') "
        "— にとどまらず thường dùng khi phạm vi thực tế LỚN HƠN NHIỀU so với những gì người ta tưởng.",
        [
            ex(L, 3, 1, [t("t-l13s3-1", "にほん", "日本", "にほん", key=True), t("t-l13s3-2", "だけでなく", key=True),
                         t("t-l13s3-3", "、"), t("t-l13s3-4", "せかいじゅう", "世界中", "せかいじゅう", key=True), t("t-l13s3-5", "にも")],
               "Không chỉ Nhật Bản mà còn khắp thế giới nữa. (trung tính, phổ biến)"),
            ex(L, 3, 2, [t("t-l13s3-6", "にほん", "日本", "にほん", key=True), t("t-l13s3-7", "に", key=True),
                         t("t-l13s3-8", "とどまらず", key=True), t("t-l13s3-9", "、"), t("t-l13s3-10", "せかいじゅう", "世界中", "せかいじゅう", key=True),
                         t("t-l13s3-11", "に"), t("t-l13s3-12", "ふきゅう", "普及", "ふきゅう", key=True), t("t-l13s3-13", "して", key=True),
                         t("t-l13s3-14", "います", "居ます", "います")],
               "Không chỉ dừng lại ở Nhật Bản mà còn phổ biến khắp thế giới. (nhấn mạnh phạm vi vượt xa)"),
        ],
        tips="Mẹo: bốn cấu trúc gần như thay thế được cho nhau về nghĩa, nhưng にとどまらず tạo ẤN TƯỢNG MẠNH NHẤT về việc 'phạm vi thực tế lớn hơn nhiều so với tưởng tượng'.",
        culture="Trong đề thi JLPT N2, にとどまらず thường xuất hiện trong đoạn văn mở đầu để giới thiệu QUY MÔ/TẦM QUAN TRỌNG của chủ đề bài đọc."),

    slide(L, 4,
        "4. Dạng bổ nghĩa danh từ: N + にとどまらない + N2",
        "N + にとどまらない + N2",
        "Khi cần bổ nghĩa TRỰC TIẾP cho một danh từ, にとどまらず đổi thành にとどまらない (thể "
        "phủ định thông thường của とどまる), đứng NGAY TRƯỚC danh từ mà nó bổ nghĩa.",
        [
            ex(L, 4, 1, [t("t-l13s4-1", "にほん", "日本", "にほん", key=True), t("t-l13s4-2", "に", key=True),
                         t("t-l13s4-3", "とどまらない", key=True), t("t-l13s4-4", "かつどう", "活動", "かつどう", key=True),
                         t("t-l13s4-5", "を"), t("t-l13s4-6", "して", key=True), t("t-l13s4-7", "います", "居ます", "います")],
               "Đang thực hiện hoạt động không chỉ dừng lại ở Nhật Bản."),
            ex(L, 4, 2, [t("t-l13s4-8", "いち", "一"), t("t-l13s4-9", "ぶんや", "分野", "ぶんや", key=True), t("t-l13s4-10", "に", key=True),
                         t("t-l13s4-11", "とどまらない", key=True), t("t-l13s4-12", "はってん", "発展", "はってん", key=True),
                         t("t-l13s4-13", "を"), t("t-l13s4-14", "とげました", "遂げました", "とげました")],
               "Đã đạt được sự phát triển không chỉ dừng lại ở một lĩnh vực."),
        ],
        tips="にとどまらないN2 rất phổ biến trong tiêu đề sách/báo cáo để nhấn TẦM ẢNH HƯỞNG RỘNG LỚN của một chủ thể.",
        culture="Tựa sách công nghệ Nhật thường viết: '一分野にとどまらない技術革新' (sự đổi mới công nghệ không chỉ dừng lại ở một lĩnh vực)."),
]

DIALOGUE = [
    line(L, 1, "田中", "Nhà nghiên cứu",
         [t("d13-1", "この"), t("d13-2", "もんだい", "問題", "もんだい", key=True), t("d13-3", "は"),
          t("d13-4", "どこまで"), t("d13-5", "えいきょう", "影響", "えいきょう", key=True), t("d13-6", "しますか")],
         "Vấn đề này ảnh hưởng đến đâu?"),
    line(L, 2, "サントス", "Nhà nghiên cứu",
         [t("d13-7", "かんきょう", "環境", "かんきょう", key=True), t("d13-8", "に", key=True), t("d13-9", "とどまらず", key=True),
          t("d13-10", "、"), t("d13-11", "けいざい", "経済", "けいざい", key=True), t("d13-12", "にも"),
          t("d13-13", "えいきょう", "影響", "えいきょう", key=True), t("d13-14", "します")],
         "Không chỉ dừng lại ở môi trường mà còn ảnh hưởng đến cả kinh tế."),
    line(L, 3, "田中", "Nhà nghiên cứu",
         [t("d13-15", "かいしゃ", "会社", "かいしゃ", key=True), t("d13-16", "の"), t("d13-17", "かつどう", "活動", "かつどう", key=True),
          t("d13-18", "は"), t("d13-19", "にほん", "日本", "にほん", key=True), t("d13-20", "だけ"), t("d13-21", "です", "です", "です"),
          t("d13-22", "か")],
         "Hoạt động của công ty chỉ ở Nhật Bản thôi à?"),
    line(L, 4, "サントス", "Nhà nghiên cứu",
         [t("d13-23", "いいえ"), t("d13-24", "、"), t("d13-25", "にほん", "日本", "にほん", key=True), t("d13-26", "に", key=True),
          t("d13-27", "とどまらず", key=True), t("d13-28", "、"), t("d13-29", "せかいじゅう", "世界中", "せかいじゅう", key=True),
          t("d13-30", "に"), t("d13-31", "ふきゅう", "普及", "ふきゅう", key=True), t("d13-32", "して", key=True), t("d13-33", "います", "居ます", "います")],
         "Không, không chỉ dừng lại ở Nhật Bản mà còn phổ biến khắp thế giới."),
    line(L, 5, "田中", "Nhà nghiên cứu",
         [t("d13-34", "ぎじゅつ", "技術", "ぎじゅつ", key=True), t("d13-35", "の"), t("d13-36", "ぶんや", "分野", "ぶんや", key=True),
          t("d13-37", "だけ"), t("d13-38", "です", "です", "です"), t("d13-39", "か")],
         "Chỉ trong lĩnh vực kỹ thuật thôi à?"),
    line(L, 6, "サントス", "Nhà nghiên cứu",
         [t("d13-40", "たんに", "単に", "たんに", key=True), t("d13-41", "ぎじゅつ", "技術", "ぎじゅつ", key=True), t("d13-42", "の"),
          t("d13-43", "ぶんや", "分野", "ぶんや", key=True), t("d13-44", "に", key=True), t("d13-45", "とどまらず", key=True),
          t("d13-46", "、"), t("d13-47", "しゃかい", "社会", "しゃかい", key=True), t("d13-48", "ぜんたい", "全体", "ぜんたい"),
          t("d13-49", "に"), t("d13-50", "えいきょう", "影響", "えいきょう", key=True), t("d13-51", "します")],
         "Không chỉ đơn thuần dừng lại ở lĩnh vực kỹ thuật mà còn ảnh hưởng đến toàn xã hội."),
    line(L, 7, "田中", "Nhà nghiên cứu",
         [t("d13-52", "かいしゃ", "会社", "かいしゃ", key=True), t("d13-53", "は"), t("d13-54", "はってん", "発展", "はってん", key=True),
          t("d13-55", "しますか")],
         "Công ty có phát triển không?"),
    line(L, 8, "サントス", "Nhà nghiên cứu",
         [t("d13-56", "はい"), t("d13-57", "。"), t("d13-58", "いち"), t("d13-59", "ぶんや", "分野", "ぶんや", key=True),
          t("d13-60", "に", key=True), t("d13-61", "とどまらない", key=True), t("d13-62", "はってん", "発展", "はってん", key=True),
          t("d13-63", "です")],
         "Vâng. Đó là sự phát triển không chỉ dừng lại ở một lĩnh vực."),
    line(L, 9, "田中", "Nhà nghiên cứu",
         [t("d13-64", "かくちょう", "拡張", "かくちょう", key=True), t("d13-65", "の"), t("d13-66", "けいかく", "計画", "けいかく"),
          t("d13-67", "は"), t("d13-68", "ありますか")],
         "Có kế hoạch mở rộng không?"),
    line(L, 10, "サントス", "Nhà nghiên cứu",
         [t("d13-69", "はい"), t("d13-70", "。"), t("d13-71", "せかいじゅう", "世界中", "せかいじゅう", key=True), t("d13-72", "に"),
          t("d13-73", "かくちょう", "拡張", "かくちょう", key=True), t("d13-74", "する"), t("d13-75", "けいかく", "計画", "けいかく"),
          t("d13-76", "です")],
         "Vâng. Là kế hoạch mở rộng ra khắp thế giới."),
]

EXERCISES = [
    q(L, 1, "「この問題は環境にとどまらず、経済にも影響します」 — にとどまらず diễn tả điều gì?",
      ["Vượt ra khỏi một phạm vi/giới hạn ban đầu để mở rộng sang phạm vi rộng hơn",
       "Sự khẳng định chắc chắn tuyệt đối", "Sự từ chối lịch sự",
       "Phủ định hoàn toàn ảnh hưởng"], 0,
      "にとどまらず diễn tả việc vượt ra khỏi phạm vi hẹp ban đầu (môi trường) để ảnh hưởng đến phạm vi rộng hơn (kinh tế).",
      "Xem cấu trúc にとどまらず ở slide 1."),
    q(L, 2, "「単に技術の分野にとどまらず、社会全体に影響します」 — 単に đóng vai trò gì?",
      ["Nhấn mạnh rằng phạm vi ban đầu chỉ là một phần nhỏ/đơn giản so với thực tế",
       "Phủ định hoàn toàn câu", "Không có vai trò ngữ pháp nào",
       "Chỉ dùng cho câu hỏi"], 0,
      "単に đứng trước にとどまらず để nhấn mạnh phạm vi ban đầu (kỹ thuật) chỉ là phần nhỏ so với phạm vi thực (toàn xã hội).",
      "Xem cấu trúc kết hợp ở slide 2."),
    q(L, 3, "にとどまらず có nguồn gốc từ động từ nào?",
      ["留まる (とどまる - dừng lại, ở lại)", "止まる (とまる - dừng hẳn)",
       "泊まる (とまる - ở trọ)", "始まる (はじまる - bắt đầu)"], 0,
      "にとどまらず bắt nguồn từ 留まる (とどまる), nghĩa gốc là 'dừng lại/ở lại trong một phạm vi'.",
      "Xem giải thích nguồn gốc ở slide 1."),
    q(L, 4, "Dạng bổ nghĩa danh từ của にとどまらず là gì?",
      ["にとどまらない (thể phủ định thông thường của とどまる)", "にとどまらずの",
       "にとどまっての", "Không có dạng bổ nghĩa danh từ"], 0,
      "にとどまらず khi bổ nghĩa danh từ đổi thành にとどまらない: 一分野にとどまらない発展.",
      "Xem quy tắc ở slide 4."),
    q(L, 5, "にとどまらず khác gì so với だけでなく về mức độ trang trọng?",
      ["にとどまらず trang trọng hơn nhiều, gần với のみならず, thường dùng trong văn học thuật",
       "Hoàn toàn giống nhau về mức độ trang trọng", "だけでなく trang trọng hơn にとどまらず",
       "Không có sự khác biệt nào"], 0,
      "にとどまらず (N2) trang trọng hơn だけでなく (N3, trung tính), gần với mức độ của のみならず.",
      "Xem bảng so sánh ở slide 3."),
    q(L, 6, "「日本にとどまらず、世界中に普及しています」 nhấn mạnh điều gì?",
      ["Phạm vi thực tế (khắp thế giới) lớn hơn nhiều so với những gì người ta có thể nghĩ (chỉ Nhật Bản)",
       "Chỉ phổ biến ở Nhật Bản, không có gì khác", "Không phổ biến ở đâu cả",
       "Nhật Bản đã ngừng sử dụng công nghệ này"], 0,
      "にとどまらず tạo ấn tượng mạnh về việc phạm vi thực tế (thế giới) vượt xa những gì ban đầu tưởng (chỉ Nhật Bản).",
      "Xem mẹo ghi nhớ ở slide 3."),
    q(L, 7, "「一分野にとどまらない発展を遂げました」 nghĩa là:",
      ["Đã đạt được sự phát triển không chỉ dừng lại ở một lĩnh vực",
       "Chỉ phát triển trong một lĩnh vực duy nhất", "Không có sự phát triển nào",
       "Đã ngừng phát triển hoàn toàn"], 0,
      "にとどまらない ở đây bổ nghĩa cho 発展 (phát triển), nghĩa là sự phát triển vượt ra khỏi một lĩnh vực duy nhất.",
      "Áp dụng cấu trúc Nにとどまらない+N2."),
    q(L, 8, "Theo hội thoại, hoạt động của công ty chỉ giới hạn ở Nhật Bản không?",
      ["Không, không chỉ dừng lại ở Nhật Bản mà còn phổ biến khắp thế giới",
       "Có, chỉ hoạt động ở Nhật Bản", "Công ty đã ngừng hoạt động",
       "Không được đề cập trong hội thoại"], 0,
      "Santos nói 「日本にとどまらず、世界中に普及しています」.",
      "Xem câu thoại thứ 4."),
    q(L, 9, "Ảnh hưởng của công nghệ có chỉ giới hạn ở lĩnh vực kỹ thuật không?",
      ["Không, còn ảnh hưởng đến toàn xã hội (単に技術の分野にとどまらず、社会全体に影響します)",
       "Có, chỉ giới hạn ở kỹ thuật", "Không có ảnh hưởng gì cả",
       "Chỉ ảnh hưởng đến một công ty"], 0,
      "Santos nói 「単に技術の分野にとどまらず、社会全体に影響します」.",
      "Xem câu thoại thứ 6."),
    q(L, 10, "Kế hoạch mở rộng của công ty là gì?",
      ["Mở rộng ra khắp thế giới (世界中に拡張する計画です)", "Chỉ mở rộng trong nước",
       "Không có kế hoạch mở rộng nào", "Thu hẹp quy mô hoạt động"], 0,
      "Santos nói 「世界中に拡張する計画です」.",
      "Xem câu thoại cuối cùng."),
]

LESSON = lesson(
    L,
    "Bài 13: Vượt ngoài giới hạn (にとどまらず)",
    "にとどまらず (từ động từ gốc 留まる - dừng lại) diễn tả việc VƯỢT RA KHỎI một PHẠM VI/GIỚI "
    "HẠN ban đầu để mở rộng sang phạm vi RỘNG HƠN — trang trọng, gần với mức độ của のみならず; "
    "thường kết hợp với 単に ở vế trước để nhấn mạnh phạm vi ban đầu quá hẹp; dạng bổ nghĩa danh "
    "từ: にとどまらない (thể phủ định thông thường của とどまる).",
    VOCAB, KANJI, SLIDES, DIALOGUE, EXERCISES,
)

if __name__ == "__main__":
    pool.mark_used([w["word"] for w in VOCAB if w["word"]], lesson=L)
    merge([LESSON])
