# -*- coding: utf-8 -*-
"""N3 — Bai 16: Thay the 代わりに (chung chung) va に代わって (trang trong, thay mat/dai dien).

Tu vung minh hoa TU CHON tu pool mo data/jlpt-vocab/n3.csv (xem NOTICE.md).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from n3_lib import v, k, t, ex, slide, line, q, lesson, merge
from jlpt_pool import Pool

L = 16
pool = Pool("n3")

VOCAB = [
    v(1,  "だいひょう", "代表", "だいひょう", "daihyou", "noun", "Đại diện", "会社の 代表 = đại diện công ty.", L),
    v(2,  "だいり", "代理", "だいり", "dairi", "noun", "Thay mặt, ủy quyền", "社長の 代理 = người được ủy quyền của giám đốc.", L),
    v(3,  "たんとう", "担当", "たんとう", "tantou", "noun", "Phụ trách", "担当の 人 = người phụ trách.", L),
    v(4,  "しはらいます", "支払います", "しはらいます", "shiharaimasu", "verb", "Thanh toán, chi trả", "代金を 支払います = thanh toán tiền hàng.", L),
    v(5,  "しょめい", "署名", "しょめい", "shomei", "noun", "Chữ ký, việc ký tên", "書類に 署名します = ký tên vào tài liệu.", L),
    v(6,  "だいきん", "代金", "だいきん", "daikin", "noun", "Tiền hàng, giá tiền", "代金を 払います = trả tiền hàng.", L),
    v(7,  "ぶちょう", "部長", "ぶちょう", "buchou", "noun", "Trưởng phòng", "Đã gặp N4 bài 41.", L),
    v(8,  "しゃちょう", "社長", "しゃちょう", "shachou", "noun", "Giám đốc", "Đã gặp N4 bài 41.", L),
    v(9,  "かいぎ", "会議", "かいぎ", "kaigi", "noun", "Cuộc họp", "Đã gặp N4 bài 30.", L),
    v(10, "しゅっせきします", "出席します", "しゅっせきします", "shusseki shimasu", "verb", "Tham dự", "Đã gặp N3 bài 5.", L),
    v(11, "でんわ", "電話", "でんわ", "denwa", "noun", "Điện thoại", "Đã gặp N4 bài 34.", L),
    v(12, "れんらくします", "連絡します", "れんらくします", "renraku shimasu", "verb", "Liên lạc", "Đã gặp N4 bài 41.", L),
    v(13, "おかね", "お金", "おかね", "okane", "noun", "Tiền", "Đã gặp N4 bài 26.", L),
    v(14, "かいしゃ", "会社", "かいしゃ", "kaisha", "noun", "Công ty", "Đã gặp N4 bài 26.", L),
    v(15, "しごと", "仕事", "しごと", "shigoto", "noun", "Công việc", "Đã gặp N4 bài 26.", L),
    v(16, "やすみます", "休みます", "やすみます", "yasumimasu", "verb", "Nghỉ", "Đã gặp N5 bài 1.", L),
    v(17, "きょう", "今日", "きょう", "kyou", "noun", "Hôm nay", "Đã gặp N5 bài 1.", L),
    v(18, "あした", "明日", "あした", "ashita", "noun", "Ngày mai", "Đã gặp N5 bài 1.", L),
    v(19, "せつめいします", "説明します", "せつめいします", "setsumei shimasu", "verb", "Giải thích", "Đã gặp N4 bài 26.", L),
    v(20, "いいます", "言います", "いいます", "iimasu", "verb", "Nói", "Đã gặp N5 bài 6.", L),
]

KANJI = [
    k(1, "代", "ĐẠI", 5, ["ダイ (dai)"], ["か(わる)", "か(える)"], "Thay thế, thế hệ.",
      [("代わり", "かわり", "Sự thay thế"), ("代表", "だいひょう", "Đại diện")], L),
    k(2, "表", "BIỂU", 8, ["ヒョウ (hyou)"], ["おもて", "あらわ(す)"], "Bề mặt, biểu thị.",
      [("代表", "だいひょう", "Đại diện"), ("表現", "ひょうげん", "Biểu hiện")], L),
    k(3, "理", "LÝ", 11, ["リ (ri)"], [], "Lý lẽ, xử lý.",
      [("代理", "だいり", "Thay mặt, ủy quyền"), ("料理", "りょうり", "Nấu ăn")], L),
    k(4, "担", "ĐẢM", 8, ["タン (tan)"], ["にな(う)"], "Đảm nhận, gánh vác.",
      [("担当", "たんとう", "Phụ trách"), ("負担", "ふたん", "Gánh nặng")], L),
    k(5, "払", "PHẤT", 5, ["フツ (futsu)"], ["はら(う)"], "Trả, thanh toán.",
      [("支払う", "しはらう", "Thanh toán"), ("払います", "はらいます", "Trả tiền")], L),
]

SLIDES = [
    slide(L, 1,
        "1. Thay vì, thay cho (chung chung): N+の代わりに / V+代わりに",
        "N+の代わりに / V(từ điển)+代わりに、[hành động thay thế]",
        "代わりに diễn tả 'THAY VÌ' một điều gì đó, chuyển sang làm một việc khác — dùng PHỔ BIẾN "
        "trong cả hội thoại lẫn văn viết, không đòi hỏi tính chính thức, dùng được cho cả người lẫn việc.",
        [
            ex(L, 1, 1, [t("t-l16s1-1", "しゃちょう", "社長", "しゃちょう", key=True), t("t-l16s1-2", "の"),
                         t("t-l16s1-3", "かわりに", "代わりに", "かわりに", key=True), t("t-l16s1-4", "、"),
                         t("t-l16s1-5", "ぶちょう", "部長", "ぶちょう", key=True), t("t-l16s1-6", "が"),
                         t("t-l16s1-7", "かいぎ", "会議", "かいぎ", key=True), t("t-l16s1-8", "に"),
                         t("t-l16s1-9", "しゅっせき", "出席", "しゅっせき"), t("t-l16s1-10", "します")],
               "Thay vì giám đốc, trưởng phòng sẽ tham dự cuộc họp."),
            ex(L, 1, 2, [t("t-l16s1-11", "かいぎ", "会議", "かいぎ"), t("t-l16s1-12", "に"), t("t-l16s1-13", "いく", "行く", "いく"),
                         t("t-l16s1-14", "かわりに", "代わりに", "かわりに", key=True), t("t-l16s1-15", "、"),
                         t("t-l16s1-16", "でんわ", "電話", "でんわ", key=True), t("t-l16s1-17", "で"),
                         t("t-l16s1-18", "はなします", "話します", "はなします")],
               "Thay vì đi họp, tôi sẽ nói chuyện qua điện thoại."),
        ],
        tips="代わりに có thể dùng cho cả NGƯỜI (thay cho ai) lẫn VIỆC (thay vì làm gì) — phạm vi sử dụng rộng.",
        culture="Câu quen thuộc trong công sở Nhật: 'メールの代わりに電話で連絡します' (thay vì email, tôi sẽ liên lạc qua điện thoại)."),

    slide(L, 2,
        "2. Thay mặt, đại diện cho (trang trọng): N + に代わって",
        "N(người/tổ chức) + に代わって、[hành động thay mặt/đại diện]",
        "に代わって diễn tả một người/tổ chức CHÍNH THỨC đảm nhận VAI TRÒ/NHIỆM VỤ của người/tổ "
        "chức khác — trang trọng hơn 代わりに, thường dùng trong ngữ cảnh công việc, nghi lễ, văn bản.",
        [
            ex(L, 2, 1, [t("t-l16s2-1", "しゃちょう", "社長", "しゃちょう", key=True), t("t-l16s2-2", "に"),
                         t("t-l16s2-3", "かわって", "代わって", "かわって", key=True), t("t-l16s2-4", "、"),
                         t("t-l16s2-5", "ぶちょう", "部長", "ぶちょう", key=True), t("t-l16s2-6", "が"),
                         t("t-l16s2-7", "かいぎ", "会議", "かいぎ"), t("t-l16s2-8", "に"), t("t-l16s2-9", "しゅっせき", "出席", "しゅっせき"),
                         t("t-l16s2-10", "します")],
               "Thay mặt giám đốc, trưởng phòng sẽ tham dự cuộc họp."),
            ex(L, 2, 2, [t("t-l16s2-11", "たんとうしゃ", "担当者", "たんとうしゃ", key=True), t("t-l16s2-12", "に"),
                         t("t-l16s2-13", "かわって", "代わって", "かわって", key=True), t("t-l16s2-14", "、"),
                         t("t-l16s2-15", "わたし", "私", "わたし"), t("t-l16s2-16", "が"), t("t-l16s2-17", "だいきん", "代金", "だいきん", key=True),
                         t("t-l16s2-18", "を"), t("t-l16s2-19", "しはらいます", "支払います", "しはらいます", key=True)],
               "Thay mặt người phụ trách, tôi sẽ thanh toán tiền hàng."),
        ],
        tips="に代わって KHÔNG dùng để nói 'thay vì làm việc A, làm việc B' — chỉ dùng khi N là NGƯỜI/TỔ CHỨC được thay thế vai trò.",
        culture="Trong thư từ công vụ Nhật: '部長に代わってご連絡いたします' (tôi xin thay mặt trưởng phòng liên lạc) là mẫu câu lịch sự chuẩn mực."),

    slide(L, 3,
        "3. So sánh 代わりに và に代わって",
        "代わりに: rộng, dùng cho cả NGƯỜI và VIỆC　vs　に代わって: CHỈ dùng cho NGƯỜI/TỔ CHỨC, luôn trang trọng",
        "代わりに có phạm vi RỘNG HƠN, dùng được cho cả sự việc (thay vì làm A, làm B) lẫn con "
        "người; に代わって CHỈ dùng khi thay thế VAI TRÒ của một NGƯỜI/TỔ CHỨC cụ thể, mang tính CHÍNH THỨC.",
        [
            ex(L, 3, 1, [t("t-l16s3-1", "いつも"), t("t-l16s3-2", "の"), t("t-l16s3-3", "みせ", "店", "みせ"),
                         t("t-l16s3-4", "の"), t("t-l16s3-5", "かわりに", "代わりに", "かわりに", key=True), t("t-l16s3-6", "、"),
                         t("t-l16s3-7", "あたらしい", "新しい", "あたらしい"), t("t-l16s3-8", "みせ", "店", "みせ"),
                         t("t-l16s3-9", "で"), t("t-l16s3-10", "かいます", "買います", "かいます")],
               "Thay vì cửa hàng thường lệ, tôi mua ở cửa hàng mới. (代わりに cho VIỆC/NƠI CHỐN)"),
            ex(L, 3, 2, [t("t-l16s3-11", "だいひょう", "代表", "だいひょう", key=True), t("t-l16s3-12", "に"),
                         t("t-l16s3-13", "かわって", "代わって", "かわって", key=True), t("t-l16s3-14", "、"),
                         t("t-l16s3-15", "わたし", "私", "わたし"), t("t-l16s3-16", "が"), t("t-l16s3-17", "しょめい", "署名", "しょめい", key=True),
                         t("t-l16s3-18", "します")],
               "Thay mặt đại diện, tôi sẽ ký tên. (に代わって CHỈ cho NGƯỜI)"),
        ],
        tips="Mẹo: nếu vế trước là ĐỊA ĐIỂM/SỰ VIỆC → dùng 代わりに; nếu vế trước là NGƯỜI/TỔ CHỨC được thay thế vai trò → cả hai đều được, nhưng に代わって trang trọng hơn.",
        culture="Trong đơn từ, hợp đồng, giấy tờ chính thức của Nhật, に代わって luôn được ưu tiên hơn 代わりに để đảm bảo tính pháp lý."),

    slide(L, 4,
        "4. Kết hợp với 代理/代表 để nhấn tính chính thức",
        "N の代理として、Nに代わって + [hành động]",
        "Khi người thay thế có CHỨC DANH CHÍNH THỨC (代理 - người được ủy quyền, 代表 - người đại "
        "diện), thường kết hợp cùng に代わって để nhấn mạnh tính HỢP PHÁP/CHÍNH THỨC của việc thay thế.",
        [
            ex(L, 4, 1, [t("t-l16s4-1", "しゃちょう", "社長", "しゃちょう", key=True), t("t-l16s4-2", "の"),
                         t("t-l16s4-3", "だいり", "代理", "だいり", key=True), t("t-l16s4-4", "として"),
                         t("t-l16s4-5", "、"), t("t-l16s4-6", "ぶちょう", "部長", "ぶちょう"), t("t-l16s4-7", "に"),
                         t("t-l16s4-8", "かわって", "代わって", "かわって", key=True), t("t-l16s4-9", "しょめい", "署名", "しょめい"),
                         t("t-l16s4-10", "します")],
               "Với tư cách người được ủy quyền của giám đốc, trưởng phòng sẽ ký tên thay."),
            ex(L, 4, 2, [t("t-l16s4-11", "たんとうしゃ", "担当者", "たんとうしゃ", key=True), t("t-l16s4-12", "に"),
                         t("t-l16s4-13", "かわって", "代わって", "かわって", key=True), t("t-l16s4-14", "、"),
                         t("t-l16s4-15", "だいひょう", "代表", "だいひょう", key=True), t("t-l16s4-16", "が"),
                         t("t-l16s4-17", "せつめい", "説明", "せつめい"), t("t-l16s4-18", "します")],
               "Thay mặt người phụ trách, đại diện sẽ giải thích."),
        ],
        tips="Cấu trúc 「Nの代理として、Nに代わって」thường thấy trong VĂN BẢN HÀNH CHÍNH, hợp đồng — thể hiện chuỗi ủy quyền rõ ràng.",
        culture="Trong công ty Nhật, khi cấp trên vắng mặt, việc dùng đúng 代理/代表/に代わって thể hiện sự tôn trọng thứ bậc và quy trình làm việc."),
]

DIALOGUE = [
    line(L, 1, "田中", "Đồng nghiệp",
         [t("d16-1", "きょう", "今日", "きょう", key=True), t("d16-2", "の"), t("d16-3", "かいぎ", "会議", "かいぎ", key=True),
          t("d16-4", "は"), t("d16-5", "だれ", "誰", "だれ"), t("d16-6", "が"), t("d16-7", "しゅっせき", "出席", "しゅっせき"),
          t("d16-8", "します", "為ます", "します"), t("d16-9", "か")],
         "Cuộc họp hôm nay ai sẽ tham dự?"),
    line(L, 2, "サントス", "Đồng nghiệp",
         [t("d16-10", "しゃちょう", "社長", "しゃちょう", key=True), t("d16-11", "の"), t("d16-12", "かわりに", "代わりに", "かわりに", key=True),
          t("d16-13", "、"), t("d16-14", "ぶちょう", "部長", "ぶちょう", key=True), t("d16-15", "が"),
          t("d16-16", "しゅっせき", "出席", "しゅっせき"), t("d16-17", "します", "為ます", "します")],
         "Thay vì giám đốc, trưởng phòng sẽ tham dự."),
    line(L, 3, "田中", "Đồng nghiệp",
         [t("d16-18", "ぶちょう", "部長", "ぶちょう", key=True), t("d16-19", "は"), t("d16-20", "しゃちょう", "社長", "しゃちょう", key=True),
          t("d16-21", "に"), t("d16-22", "かわって", "代わって", "かわって", key=True), t("d16-23", "あいさつ"),
          t("d16-24", "しますか")],
         "Trưởng phòng sẽ thay mặt giám đốc phát biểu chào hỏi chứ?"),
    line(L, 4, "サントス", "Đồng nghiệp",
         [t("d16-25", "はい"), t("d16-26", "、"), t("d16-27", "そう"), t("d16-28", "です", "です", "です")],
         "Vâng, đúng vậy."),
    line(L, 5, "田中", "Đồng nghiệp",
         [t("d16-29", "だいきん", "代金", "だいきん", key=True), t("d16-30", "は"), t("d16-31", "だれ", "誰", "だれ"),
          t("d16-32", "が"), t("d16-33", "しはらいます", "支払います", "しはらいます", key=True), t("d16-34", "か")],
         "Ai sẽ thanh toán tiền hàng?"),
    line(L, 6, "サントス", "Đồng nghiệp",
         [t("d16-35", "たんとうしゃ", "担当者", "たんとうしゃ", key=True), t("d16-36", "に"), t("d16-37", "かわって", "代わって", "かわって", key=True),
          t("d16-38", "、"), t("d16-39", "わたし", "私", "わたし"), t("d16-40", "が"), t("d16-41", "しはらいます", "支払います", "しはらいます", key=True)],
         "Thay mặt người phụ trách, tôi sẽ thanh toán."),
    line(L, 7, "田中", "Đồng nghiệp",
         [t("d16-42", "しょるい", "書類", "しょるい"), t("d16-43", "に"), t("d16-44", "しょめい", "署名", "しょめい", key=True),
          t("d16-45", "が"), t("d16-46", "ひつよう", "必要", "ひつよう"), t("d16-47", "です", "です", "です"), t("d16-48", "ね")],
         "Cần chữ ký vào tài liệu nhỉ."),
    line(L, 8, "サントス", "Đồng nghiệp",
         [t("d16-49", "だいひょう", "代表", "だいひょう", key=True), t("d16-50", "に"), t("d16-51", "かわって", "代わって", "かわって", key=True),
          t("d16-52", "、"), t("d16-53", "わたし", "私", "わたし"), t("d16-54", "が"), t("d16-55", "しょめい", "署名", "しょめい", key=True),
          t("d16-56", "します")],
         "Thay mặt người đại diện, tôi sẽ ký tên."),
    line(L, 9, "田中", "Đồng nghiệp",
         [t("d16-57", "あした", "明日", "あした", key=True), t("d16-58", "の"), t("d16-59", "かいぎ", "会議", "かいぎ"),
          t("d16-60", "は"), t("d16-61", "やすみます", "休みます", "やすみます", key=True), t("d16-62", "か")],
         "Cuộc họp ngày mai bạn sẽ nghỉ à?"),
    line(L, 10, "サントス", "Đồng nghiệp",
         [t("d16-63", "いいえ"), t("d16-64", "。"), t("d16-65", "だいり", "代理", "だいり", key=True), t("d16-66", "として"),
          t("d16-67", "、"), t("d16-68", "せつめい", "説明", "せつめい", key=True), t("d16-69", "します")],
         "Không. Với tư cách người được ủy quyền, tôi sẽ giải thích."),
]

EXERCISES = [
    q(L, 1, "「社長の代わりに、部長が会議に出席します」 — 代わりに diễn tả điều gì?",
      ["Thay vì một người/việc, chuyển sang làm bằng người/việc khác (dùng phổ biến)",
       "Thay mặt chính thức, mang tính pháp lý", "So sánh hai người",
       "Phủ định việc tham dự"], 0,
      "代わりに diễn tả 'thay vì' một cách phổ biến, dùng được cho cả người và việc.",
      "Xem cấu trúc 代わりに ở slide 1."),
    q(L, 2, "「社長に代わって、部長が会議に出席します」 — に代わって khác 代わりに ở điểm nào?",
      ["に代わって trang trọng hơn, chỉ dùng khi thay thế VAI TRÒ của người/tổ chức",
       "Hoàn toàn giống nhau, dùng thay thế được cho nhau luôn",
       "に代わって chỉ dùng cho việc, không dùng cho người", "代わりに chỉ dùng trong văn viết"], 0,
      "に代わって trang trọng hơn 代わりに, và CHỈ dùng khi N là người/tổ chức được thay thế vai trò.",
      "Xem giải thích に代わって ở slide 2."),
    q(L, 3, "Có thể dùng に代わって để nói 'thay vì đi họp, tôi gọi điện' không?",
      ["Không, vì 会議に行くこと (việc đi họp) không phải là người/tổ chức — phải dùng 代わりに",
       "Có, hoàn toàn tự nhiên và đúng ngữ pháp", "Chỉ đúng trong văn nói thân mật",
       "Chỉ đúng khi nói về công ty"], 0,
      "に代わって CHỈ dùng cho người/tổ chức được thay thế vai trò, không dùng cho hành động/sự việc.",
      "Xem lưu ý quan trọng ở slide 3."),
    q(L, 4, "「担当者に代わって、私が代金を支払います」 nghĩa là:",
      ["Thay mặt người phụ trách, tôi sẽ thanh toán tiền hàng",
       "Người phụ trách sẽ thanh toán thay tôi", "Không ai thanh toán tiền hàng cả",
       "Tôi từ chối thanh toán tiền hàng"], 0,
      "に代わって ở đây nghĩa là 'thay mặt' người phụ trách — người nói (私) đảm nhận việc thanh toán thay.",
      "Áp dụng cấu trúc Nに代わって."),
    q(L, 5, "Cấu trúc 代理として、〜に代わって thường xuất hiện ở đâu?",
      ["Văn bản hành chính, hợp đồng, ngữ cảnh công việc chính thức",
       "Chỉ trong thơ ca", "Chỉ trong tin nhắn thân mật giữa bạn bè",
       "Không bao giờ được sử dụng"], 0,
      "Cấu trúc kết hợp 代理/代表 với に代わって thể hiện chuỗi ủy quyền rõ ràng, thường thấy trong văn bản hành chính.",
      "Xem ví dụ ở slide 4."),
    q(L, 6, "「いつもの店の代わりに、新しい店で買います」 — vì sao không dùng に代わって ở đây?",
      ["Vì 店 (cửa hàng) là một địa điểm/sự việc, không phải người/tổ chức cần thay thế vai trò",
       "Vì câu này sai ngữ pháp hoàn toàn", "Vì に代わって không tồn tại trong tiếng Nhật",
       "Vì cả hai đều đúng như nhau"], 0,
      "に代わって chỉ dùng cho người/tổ chức; ở đây 店 (cửa hàng) là địa điểm nên dùng 代わりに mới đúng.",
      "Xem so sánh ở slide 3."),
    q(L, 7, "「代表に代わって、私が署名します」 nghĩa là:",
      ["Thay mặt người đại diện, tôi sẽ ký tên", "Người đại diện sẽ ký tên thay tôi",
       "Không ai ký tên cả", "Tôi là người đại diện chính thức"], 0,
      "に代わって ở đây nghĩa 'thay mặt' người đại diện (代表) — người nói đảm nhận việc ký tên thay.",
      "Áp dụng cấu trúc Nに代わって cho ngữ cảnh ký tên."),
    q(L, 8, "Theo hội thoại, ai sẽ tham dự cuộc họp hôm nay?",
      ["Trưởng phòng, thay vì giám đốc (部長が出席します)", "Giám đốc sẽ tự tham dự",
       "Không ai tham dự cả", "Cuộc họp bị hủy"], 0,
      "Santos nói 「社長の代わりに、部長が出席します」.",
      "Xem câu thoại thứ 2."),
    q(L, 9, "Ai sẽ thanh toán tiền hàng theo hội thoại?",
      ["Santos, thay mặt người phụ trách (担当者に代わって、私が支払います)",
       "Người phụ trách sẽ tự thanh toán", "Giám đốc sẽ thanh toán",
       "Không ai thanh toán"], 0,
      "Santos nói 「担当者に代わって、私が支払います」.",
      "Xem câu thoại thứ 6."),
    q(L, 10, "Santos sẽ làm gì vào cuộc họp ngày mai?",
      ["Giải thích với tư cách người được ủy quyền (代理として、説明します)",
       "Nghỉ không tham dự", "Không làm gì cả", "Hủy cuộc họp"], 0,
      "Santos nói 「代理として、説明します」.",
      "Xem câu thoại cuối cùng."),
]

LESSON = lesson(
    L,
    "Bài 16: Thay thế (代わりに & に代わって)",
    "代わりに diễn tả 'thay vì' một cách PHỔ BIẾN, dùng được cho cả người và việc; に代わって trang "
    "trọng hơn, CHỈ dùng khi một người/tổ chức CHÍNH THỨC đảm nhận vai trò của người/tổ chức khác "
    "(công việc, nghi lễ, văn bản); kết hợp với 代理/代表 để nhấn tính hợp pháp của việc thay thế.",
    VOCAB, KANJI, SLIDES, DIALOGUE, EXERCISES,
)

if __name__ == "__main__":
    pool.mark_used([w["word"] for w in VOCAB if w["word"]], lesson=L)
    merge([LESSON])
