# -*- coding: utf-8 -*-
"""N3 — Bai 12: Danh gia chac chan に違いない (dua tren bang chung), はずだ (dua tren logic),
はずがない (phu dinh manh cua はずだ).

Tu vung minh hoa TU CHON tu pool mo data/jlpt-vocab/n3.csv (xem NOTICE.md).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from n3_lib import v, k, t, ex, slide, line, q, lesson, merge
from jlpt_pool import Pool

L = 12
pool = Pool("n3")

VOCAB = [
    v(1,  "しょうめいします", "証明します", "しょうめいします", "shoumei shimasu", "verb", "Chứng minh", "うそを 証明します = chứng minh lời nói dối.", L),
    v(2,  "たしかめます", "確かめます", "たしかめます", "tashikamemasu", "verb", "Xác nhận, kiểm chứng", "じじつを 確かめます = xác nhận sự thật.", L),
    v(3,  "はんにん", "犯人", "はんにん", "hannin", "noun", "Thủ phạm, tội phạm", "犯人は あの 人です = thủ phạm là người đó.", L),
    v(4,  "まちがい", "間違い", "まちがい", "machigai", "noun", "Sai lầm, lỗi", "間違いが あります = có sai sót.", L),
    v(5,  "げんば", "現場", "げんば", "genba", "noun", "Hiện trường", "現場を 調べます = điều tra hiện trường.", L),
    v(6,  "そうさします", "捜査します", "そうさします", "sousa shimasu", "verb", "Điều tra (hình sự)", "けいさつが 捜査します = cảnh sát điều tra.", L),
    v(7,  "さいふ", "財布", "さいふ", "saifu", "noun", "Ví tiền", "Đã gặp N4 bài 44.", L),
    v(8,  "かぎ", "鍵", "かぎ", "kagi", "noun", "Chìa khóa", "Đã gặp N5 bài 15.", L),
    v(9,  "わすれもの", "忘れ物", "わすれもの", "wasuremono", "noun", "Đồ bỏ quên", "Đã gặp N5 bài 19.", L),
    v(10, "いぬ", "犬", "いぬ", "inu", "noun", "Chó", "Đã gặp N4 bài 29.", L),
    v(11, "つきます", "着きます", "つきます", "tsukimasu", "verb", "Đến nơi", "Đã gặp N4 bài 34.", L),
    v(12, "けっか", "結果", "けっか", "kekka", "noun", "Kết quả", "Đã gặp N4 bài 39.", L),
    v(13, "きをつけます", "気を付けます", "きをつけます", "ki wo tsukemasu", "expression", "Cẩn thận, chú ý", "Đã gặp N4 bài 33.", L),
    v(14, "ひと", "人", "ひと", "hito", "noun", "Người", "Đã gặp N5 bài 1.", L),
    v(15, "かれ", "彼", "かれ", "kare", "noun", "Anh ấy", "Đã gặp N5 bài 6.", L),
    v(16, "いつも", "何時も", "いつも", "itsumo", "adverb", "Luôn luôn", "Đã gặp N5 bài 6.", L),
    v(17, "もの", "物", "もの", "mono", "noun", "Vật, đồ vật", "Đã gặp N4 bài 38.", L),
    v(18, "これ", "これ", "これ", "kore", "pronoun", "Cái này", "Đã gặp N5 bài 1.", L),
    v(19, "あの", "あの", "あの", "ano", "determiner", "Kia, đó", "Đã gặp N5 bài 1.", L),
    v(20, "わかります", "分かります", "わかります", "wakarimasu", "verb", "Hiểu, biết", "Đã gặp N4 bài 38.", L),
]

KANJI = [
    k(1, "証", "CHỨNG", 12, ["ショウ (shou)"], [], "Chứng cứ, chứng minh.",
      [("証明", "しょうめい", "Chứng minh"), ("証拠", "しょうこ", "Bằng chứng")], L),
    k(2, "犯", "PHẠM", 5, ["ハン (han)"], ["おか(す)"], "Phạm tội, xâm phạm.",
      [("犯人", "はんにん", "Thủ phạm"), ("犯罪", "はんざい", "Tội phạm")], L),
    k(3, "違", "VI", 13, ["イ (i)"], ["ちが(う)"], "Khác biệt, sai khác.",
      [("間違い", "まちがい", "Sai lầm"), ("違います", "ちがいます", "Khác, sai")], L),
    k(4, "捜", "SƯU", 10, ["ソウ (sou)"], ["さが(す)"], "Tìm kiếm, điều tra.",
      [("捜査", "そうさ", "Điều tra"), ("捜す", "さがす", "Tìm kiếm")], L),
    k(5, "現", "HIỆN", 11, ["ゲン (gen)"], ["あらわ(れる)"], "Hiện tại, xuất hiện.",
      [("現場", "げんば", "Hiện trường"), ("現在", "げんざい", "Hiện tại")], L),
]

SLIDES = [
    slide(L, 1,
        "1. Chắc chắn là (dựa trên bằng chứng): [thể thường] に違いない",
        "[Thể thường/N] + に違いない",
        "に違いない diễn tả sự SUY LUẬN MẠNH MẼ dựa trên BẰNG CHỨNG CỤ THỂ đã quan sát được — mức "
        "độ tin tưởng RẤT CAO, gần như khẳng định chắc chắn, thường dùng trong suy luận, phá án.",
        [
            ex(L, 1, 1, [t("t-l12s1-1", "これ", "これ", "これ", key=True), t("t-l12s1-2", "は"),
                         t("t-l12s1-3", "かれ", "彼", "かれ"), t("t-l12s1-4", "の"), t("t-l12s1-5", "さいふ", "財布", "さいふ", key=True),
                         t("t-l12s1-6", "に"), t("t-l12s1-7", "ちがいない", "違いない", "ちがいない", key=True)],
               "Đây chắc chắn là ví của anh ấy."),
            ex(L, 1, 2, [t("t-l12s1-8", "げんば", "現場", "げんば", key=True), t("t-l12s1-9", "の"),
                         t("t-l12s1-10", "もの", "物", "もの"), t("t-l12s1-11", "から"), t("t-l12s1-12", "、"),
                         t("t-l12s1-13", "はんにん", "犯人", "はんにん", key=True), t("t-l12s1-14", "は"),
                         t("t-l12s1-15", "あの"), t("t-l12s1-16", "ひと", "人", "ひと"), t("t-l12s1-17", "に"),
                         t("t-l12s1-18", "ちがいない", "違いない", "ちがいない", key=True)],
               "Từ vật ở hiện trường, thủ phạm chắc chắn là người đó."),
        ],
        tips="に違いない mang tính CHỦ QUAN, cảm tính hơn はずだ một chút — thường dùng khi người nói rất tự tin vào suy luận của mình.",
        culture="Trong tiểu thuyết trinh thám Nhật, thám tử hay nói: '犯人は彼に違いない' (thủ phạm chắc chắn là hắn) khi đã tìm đủ manh mối."),

    slide(L, 2,
        "2. Lẽ ra phải, chắc là (dựa trên logic): [thể thường] はずだ",
        "[Thể thường/N+の] + はずだ",
        "はずだ diễn tả sự SUY LUẬN dựa trên THÔNG TIN/LOGIC đã biết (lịch trình, quy luật, lời "
        "hứa...) — khách quan hơn に違いない, nhấn 'theo lý thì phải như vậy'.",
        [
            ex(L, 2, 1, [t("t-l12s2-1", "かぎ", "鍵", "かぎ", key=True), t("t-l12s2-2", "は"),
                         t("t-l12s2-3", "ここに"), t("t-l12s2-4", "ある"), t("t-l12s2-5", "はず", key=True),
                         t("t-l12s2-6", "です")],
               "Chìa khóa lẽ ra phải ở đây."),
            ex(L, 2, 2, [t("t-l12s2-7", "かれ", "彼", "かれ", key=True), t("t-l12s2-8", "は"),
                         t("t-l12s2-9", "もう"), t("t-l12s2-10", "ついた", "着いた", "ついた"), t("t-l12s2-11", "はず", key=True),
                         t("t-l12s2-12", "です")],
               "Anh ấy lẽ ra đã đến nơi rồi."),
        ],
        tips="はずだ dựa trên CĂN CỨ KHÁCH QUAN (lịch trình, quy luật) trong khi に違いない dựa trên BẰNG CHỨNG/linh cảm chủ quan của người nói.",
        culture="Nhân viên Nhật hay dùng はずです khi trả lời khách hàng dựa trên quy định công ty: '来週には届くはずです' (theo lịch thì tuần sau sẽ đến nơi)."),

    slide(L, 3,
        "3. Không thể nào (phủ định mạnh): [thể thường] はずがない",
        "[Thể thường/N+の] + はずがない",
        "はずがない là PHỦ ĐỊNH MẠNH của はずだ, khẳng định một điều gì đó KHÔNG THỂ xảy ra dựa "
        "trên logic/lý lẽ vững chắc — mức độ chắc chắn cao, dùng để bác bỏ một khả năng.",
        [
            ex(L, 3, 1, [t("t-l12s3-1", "あの"), t("t-l12s3-2", "ひと", "人", "ひと"), t("t-l12s3-3", "が"),
                         t("t-l12s3-4", "はんにん", "犯人", "はんにん", key=True), t("t-l12s3-5", "の"),
                         t("t-l12s3-6", "はずが", key=True), t("t-l12s3-7", "ない", key=True)],
               "Người đó không thể nào là thủ phạm."),
            ex(L, 3, 2, [t("t-l12s3-8", "かれ", "彼", "かれ", key=True), t("t-l12s3-9", "が"),
                         t("t-l12s3-10", "わすれもの", "忘れ物", "わすれもの", key=True), t("t-l12s3-11", "を"),
                         t("t-l12s3-12", "する"), t("t-l12s3-13", "はずが", key=True), t("t-l12s3-14", "ない", key=True),
                         t("t-l12s3-15", "です", "です", "です"), t("t-l12s3-16", "。"), t("t-l12s3-17", "いつも"),
                         t("t-l12s3-18", "きをつけて", "気を付けて", "きをつけて"), t("t-l12s3-19", "います", "居ます", "います")],
               "Không thể nào anh ấy bỏ quên đồ, vì anh ấy luôn cẩn thận."),
        ],
        tips="Phân biệt: ないはずだ (lẽ ra là không...) khác はずがない (không thể nào, phủ định mạnh hơn nhiều).",
        culture="Câu bào chữa quen thuộc trong phim trinh thám Nhật: '彼が犯人のはずがない！' (không thể nào anh ấy là thủ phạm được!)."),

    slide(L, 4,
        "4. So sánh に違いない, はずだ, はずがない",
        "に違いない: chắc chắn (bằng chứng, chủ quan)　vs　はずだ: lẽ ra phải (logic, khách quan)　vs　はずがない: không thể nào (phủ định mạnh)",
        "Ba cấu trúc đều diễn tả mức độ TIN TƯỞNG CAO trong suy luận, nhưng khác NGUỒN GỐC căn cứ: "
        "に違いない từ BẰNG CHỨNG quan sát được; はずだ từ LOGIC/thông tin đã biết; はずがない là "
        "PHỦ ĐỊNH của はずだ, bác bỏ hoàn toàn một khả năng.",
        [
            ex(L, 4, 1, [t("t-l12s4-1", "しょうめい", "証明", "しょうめい", key=True), t("t-l12s4-2", "された"),
                         t("t-l12s4-3", "こと", "事", "こと"), t("t-l12s4-4", "から"), t("t-l12s4-5", "、"),
                         t("t-l12s4-6", "かれ", "彼", "かれ"), t("t-l12s4-7", "が"), t("t-l12s4-8", "はんにん", "犯人", "はんにん", key=True),
                         t("t-l12s4-9", "に"), t("t-l12s4-10", "ちがいない", "違いない", "ちがいない", key=True)],
               "Từ điều đã được chứng minh, chắc chắn anh ấy là thủ phạm."),
            ex(L, 4, 2, [t("t-l12s4-11", "たしかめて", "確かめて", "たしかめて", key=True), t("t-l12s4-12", "みたら"),
                         t("t-l12s4-13", "、"), t("t-l12s4-14", "まちがい", "間違い", "まちがい", key=True), t("t-l12s4-15", "の"),
                         t("t-l12s4-16", "はずが", key=True), t("t-l12s4-17", "ない", key=True), t("t-l12s4-18", "と"),
                         t("t-l12s4-19", "わかりました", "分かりました", "わかりました")],
               "Khi xác nhận thử, tôi đã biết rằng không thể nào có sai sót."),
        ],
        tips="Mẹo ghi nhớ: に違いない='chắc chắn' (linh cảm+bằng chứng); はずだ='lẽ ra' (logic); はずがない='không thể nào' (phủ định mạnh của はずだ).",
        culture="Cả ba đều là ngữ pháp N3 trọng điểm, hay xuất hiện trong đề đọc hiểu về suy luận, lập luận logic."),
]

DIALOGUE = [
    line(L, 1, "田中", "Đồng nghiệp (điều tra vụ mất đồ)",
         [t("d12-1", "だれ", "誰", "だれ"), t("d12-2", "か"), t("d12-3", "が"), t("d12-4", "さいふ", "財布", "さいふ", key=True),
          t("d12-5", "を"), t("d12-6", "とりました", "取りました", "とりました")],
         "Ai đó đã lấy ví tiền."),
    line(L, 2, "サントス", "Đồng nghiệp (điều tra vụ mất đồ)",
         [t("d12-7", "げんば", "現場", "げんば", key=True), t("d12-8", "に"), t("d12-9", "いぬ", "犬", "いぬ", key=True),
          t("d12-10", "が"), t("d12-11", "いました", "居ました", "いました"), t("d12-12", "。"),
          t("d12-13", "はんにん", "犯人", "はんにん", key=True), t("d12-14", "は"), t("d12-15", "あの"),
          t("d12-16", "ひと", "人", "ひと"), t("d12-17", "に"), t("d12-18", "ちがいありません", "違いありません", "ちがいありません", key=True)],
         "Có một con chó ở hiện trường. Thủ phạm chắc chắn là người đó."),
    line(L, 3, "田中", "Đồng nghiệp (điều tra vụ mất đồ)",
         [t("d12-19", "たしかめました", "確かめました", "たしかめました", key=True), t("d12-20", "か")],
         "Bạn đã xác nhận chưa?"),
    line(L, 4, "サントス", "Đồng nghiệp (điều tra vụ mất đồ)",
         [t("d12-21", "まだです"), t("d12-22", "。"), t("d12-23", "でも"), t("d12-24", "かぎ", "鍵", "かぎ", key=True),
          t("d12-25", "は"), t("d12-26", "ここに"), t("d12-27", "ある"), t("d12-28", "はず", key=True),
          t("d12-29", "です")],
         "Chưa. Nhưng chìa khóa lẽ ra phải ở đây."),
    line(L, 5, "田中", "Đồng nghiệp (điều tra vụ mất đồ)",
         [t("d12-30", "あの"), t("d12-31", "ひと", "人", "ひと"), t("d12-32", "は"), t("d12-33", "いつも"),
          t("d12-34", "きをつけて", "気を付けて", "きをつけて"), t("d12-35", "います", "居ます", "います"), t("d12-36", "。"),
          t("d12-37", "はんにん", "犯人", "はんにん", key=True), t("d12-38", "の"), t("d12-39", "はずが", key=True),
          t("d12-40", "ない", key=True), t("d12-41", "です", "です", "です")],
         "Người đó luôn cẩn thận. Không thể nào là thủ phạm được."),
    line(L, 6, "サントス", "Đồng nghiệp (điều tra vụ mất đồ)",
         [t("d12-42", "そうさ", "捜査", "そうさ", key=True), t("d12-43", "の"), t("d12-44", "けっか", "結果", "けっか", key=True),
          t("d12-45", "を"), t("d12-46", "みましょう", "見ましょう", "みましょう")],
         "Vậy hãy xem kết quả điều tra."),
    line(L, 7, "田中", "Đồng nghiệp (điều tra vụ mất đồ)",
         [t("d12-47", "げんば", "現場", "げんば", key=True), t("d12-48", "に"), t("d12-49", "あった"),
          t("d12-50", "わすれもの", "忘れ物", "わすれもの", key=True), t("d12-51", "を"), t("d12-52", "しょうめい", "証明", "しょうめい", key=True),
          t("d12-53", "しました")],
         "Chúng tôi đã chứng minh được đồ bỏ quên ở hiện trường."),
    line(L, 8, "サントス", "Đồng nghiệp (điều tra vụ mất đồ)",
         [t("d12-54", "それ"), t("d12-55", "は"), t("d12-56", "まちがい", "間違い", "まちがい", key=True),
          t("d12-57", "です", "です", "です"), t("d12-58", "か")],
         "Vậy đó có phải là sai lầm không?"),
    line(L, 9, "田中", "Đồng nghiệp (điều tra vụ mất đồ)",
         [t("d12-59", "いいえ"), t("d12-60", "、"), t("d12-61", "まちがい", "間違い", "まちがい", key=True),
          t("d12-62", "の"), t("d12-63", "はずが", key=True), t("d12-64", "ない", key=True), t("d12-65", "と"),
          t("d12-66", "わかりました", "分かりました", "わかりました")],
         "Không, chúng tôi đã biết rằng không thể nào là sai sót."),
    line(L, 10, "サントス", "Đồng nghiệp (điều tra vụ mất đồ)",
         [t("d12-67", "では"), t("d12-68", "、"), t("d12-69", "かれ", "彼", "かれ", key=True), t("d12-70", "が"),
          t("d12-71", "はんにん", "犯人", "はんにん", key=True), t("d12-72", "に"), t("d12-73", "ちがいない", "違いない", "ちがいない", key=True),
          t("d12-74", "です", "です", "です"), t("d12-75", "ね")],
         "Vậy thì, chắc chắn anh ấy là thủ phạm nhỉ."),
]

EXERCISES = [
    q(L, 1, "「これは彼の財布に違いない」 — に違いない diễn tả điều gì?",
      ["Suy luận mạnh mẽ dựa trên bằng chứng, mức độ tin tưởng rất cao",
       "Sự bất lực, đành chấp nhận", "Phủ định hoàn toàn một khả năng",
       "So sánh hai đồ vật"], 0,
      "に違いない diễn tả suy luận CHẮC CHẮN dựa trên bằng chứng quan sát được, mức tin tưởng rất cao.",
      "Xem cấu trúc に違いない ở slide 1."),
    q(L, 2, "「鍵はここにあるはずです」 — はずだ dựa trên điều gì?",
      ["Logic/thông tin đã biết (lẽ ra phải như vậy theo lý)", "Cảm tính chủ quan không căn cứ",
       "Sự phủ định hoàn toàn", "Cảm xúc mãnh liệt"], 0,
      "はずだ diễn tả suy luận dựa trên CĂN CỨ LOGIC/thông tin đã biết, khách quan hơn に違いない.",
      "Xem cấu trúc はずだ ở slide 2."),
    q(L, 3, "「あの人が犯人のはずがない」 nghĩa là:",
      ["Không thể nào người đó là thủ phạm (phủ định mạnh, dựa trên logic)",
       "Người đó chắc chắn là thủ phạm", "Người đó có thể là thủ phạm",
       "Không rõ người đó có phải thủ phạm không"], 0,
      "はずがない là phủ định MẠNH của はずだ, khẳng định điều gì đó KHÔNG THỂ xảy ra.",
      "Xem cấu trúc はずがない ở slide 3."),
    q(L, 4, "Sự khác biệt cốt lõi giữa に違いない và はずだ là gì?",
      ["に違いない dựa trên BẰNG CHỨNG cụ thể/chủ quan; はずだ dựa trên LOGIC/thông tin khách quan",
       "Hoàn toàn giống nhau, dùng thay thế được", "に違いない chỉ dùng cho phủ định",
       "はずだ chỉ dùng cho câu hỏi"], 0,
      "に違いない thiên về bằng chứng/linh cảm; はずだ thiên về suy luận logic từ thông tin đã biết.",
      "Xem so sánh ở slide 4."),
    q(L, 5, "はずがない có quan hệ như thế nào với はずだ?",
      ["Là dạng phủ định mạnh của はずだ", "Là dạng lịch sự của はずだ",
       "Không có liên quan gì đến nhau", "Là dạng quá khứ của はずだ"], 0,
      "はずがない = phủ định của はずだ, dùng để bác bỏ hoàn toàn một khả năng dựa trên logic.",
      "Xem giải thích はずがない ở slide 3."),
    q(L, 6, "「証明されたことから、彼が犯人に違いない」 nghĩa là:",
      ["Từ điều đã được chứng minh, chắc chắn anh ấy là thủ phạm",
       "Không có gì được chứng minh cả", "Anh ấy không thể là thủ phạm",
       "Cần chứng minh thêm mới biết được"], 0,
      "Câu này dùng に違いない sau khi có bằng chứng (証明されたこと) để khẳng định mạnh mẽ.",
      "Áp dụng cấu trúc に違いない dựa trên bằng chứng."),
    q(L, 7, "「確かめてみたら、間違いのはずがないと分かりました」 nghĩa là:",
      ["Khi xác nhận thử, đã biết rằng không thể nào có sai sót",
       "Khi xác nhận thử, phát hiện có rất nhiều sai sót", "Không cần xác nhận vì đã biết trước",
       "Việc xác nhận đã thất bại"], 0,
      "はずがない ở đây phủ định khả năng có sai sót (間違い), sau khi đã xác nhận (確かめてみたら).",
      "Áp dụng cấu trúc はずがない cho danh từ 間違い."),
    q(L, 8, "Theo hội thoại, vì sao Santos nghĩ người kia không phải thủ phạm?",
      ["Vì người đó luôn cẩn thận (いつも気を付けています)", "Vì người đó đã thú nhận",
       "Vì không có bằng chứng nào cả", "Không được đề cập trong hội thoại"], 0,
      "田中 nói 「あの人はいつも気を付けています。犯人のはずがないです」.",
      "Xem câu thoại thứ 5."),
    q(L, 9, "Kết quả điều tra trong hội thoại chứng minh điều gì?",
      ["Đồ bỏ quên ở hiện trường (現場にあった忘れ物を証明しました)",
       "Không tìm thấy bằng chứng nào", "Vụ việc là một sai lầm hoàn toàn",
       "Cảnh sát đã từ bỏ điều tra"], 0,
      "田中 nói 「現場にあった忘れ物を証明しました」.",
      "Xem câu thoại thứ 7."),
    q(L, 10, "Kết luận cuối cùng của hội thoại là gì?",
      ["Chắc chắn anh ấy là thủ phạm (彼が犯人に違いないですね)",
       "Không ai là thủ phạm cả", "Cần điều tra thêm nữa",
       "Vụ việc đã được giải quyết sai"], 0,
      "サントス kết luận 「彼が犯人に違いないですね」.",
      "Xem câu thoại cuối cùng."),
]

LESSON = lesson(
    L,
    "Bài 12: Đánh giá chắc chắn (に違いない & はずだ & はずがない)",
    "に違いない diễn tả suy luận CHẮC CHẮN dựa trên BẰNG CHỨNG cụ thể (chủ quan, mức tin tưởng rất "
    "cao); はずだ diễn tả suy luận dựa trên LOGIC/thông tin đã biết (khách quan hơn); はずがない là "
    "PHỦ ĐỊNH MẠNH của はずだ, khẳng định điều gì đó KHÔNG THỂ xảy ra dựa trên logic vững chắc.",
    VOCAB, KANJI, SLIDES, DIALOGUE, EXERCISES,
)

if __name__ == "__main__":
    pool.mark_used([w["word"] for w in VOCAB if w["word"]], lesson=L)
    merge([LESSON])
