# -*- coding: utf-8 -*-
"""N3 — Bai 15: Mo rong pham vi だけでなく (trung tinh) va ばかりか (manh hon, gay ngac nhien).

Tu vung minh hoa TU CHON tu pool mo data/jlpt-vocab/n3.csv (xem NOTICE.md).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from n3_lib import v, k, t, ex, slide, line, q, lesson, merge
from jlpt_pool import Pool

L = 15
pool = Pool("n3")

VOCAB = [
    v(1,  "せいかく", "性格", "せいかく", "seikaku", "noun", "Tính cách", "性格が いいです = tính cách tốt.", L),
    v(2,  "れいぎ", "礼儀", "れいぎ", "reigi", "noun", "Lễ nghi, phép tắc", "礼儀が ただしいです = lễ nghi đúng mực.", L),
    v(3,  "ちしき", "知識", "ちしき", "chishiki", "noun", "Kiến thức", "知識が あります = có kiến thức.", L),
    v(4,  "のうりょく", "能力", "のうりょく", "nouryoku", "noun", "Năng lực", "能力が たかいです = năng lực cao.", L),
    v(5,  "かじ", "家事", "かじ", "kaji", "noun", "Việc nhà", "家事が じょうずです = giỏi việc nhà.", L),
    v(6,  "けいけん", "経験", "けいけん", "keiken", "noun", "Kinh nghiệm", "Đã gặp N4 bài 26.", L),
    v(7,  "りょうり", "料理", "りょうり", "ryouri", "noun", "Nấu ăn, món ăn", "Đã gặp N4 bài 26.", L),
    v(8,  "がいこくご", "外国語", "がいこくご", "gaikokugo", "noun", "Ngoại ngữ", "Đã gặp N4 bài 26.", L),
    v(9,  "じょうず", "上手", "じょうず", "jouzu", "adjective", "Giỏi", "Đã gặp N4 bài 26.", L),
    v(10, "にほんご", "日本語", "にほんご", "nihongo", "noun", "Tiếng Nhật", "Đã gặp N4 bài 26.", L),
    v(11, "えいご", "英語", "えいご", "eigo", "noun", "Tiếng Anh", "Đã gặp N4 bài 26.", L),
    v(12, "はなせます", "話せます", "はなせます", "hanasemasu", "verb", "Có thể nói (chuyện)", "Đã gặp N4 bài 27.", L),
    v(13, "たかい", "高い", "たかい", "takai", "adjective", "Cao", "Đã gặp N4 bài 34.", L),
    v(14, "ぜんぜん", "全然", "ぜんぜん", "zenzen", "adverb", "Hoàn toàn không", "Đã gặp N5 bài 25.", L),
    v(15, "かのじょ", "彼女", "かのじょ", "kanojo", "noun", "Cô ấy", "Đã gặp N3 bài 3.", L),
    v(16, "いい", "いい", "いい", "ii", "adjective", "Tốt", "Đã gặp N5 bài 8.", L),
    v(17, "あたま", "頭", "あたま", "atama", "noun", "Đầu, đầu óc", "Đã gặp N4 bài 33.", L),
    v(18, "まったく", "全く", "まったく", "mattaku", "adverb", "Hoàn toàn", "Đã gặp N3 bài 4.", L),
    v(19, "ほんとうに", "本当に", "ほんとうに", "hontou ni", "adverb", "Thật sự", "Đã gặp N5 bài 21.", L),
    v(20, "ただしい", "正しい", "ただしい", "tadashii", "adjective", "Đúng đắn, đúng mực", "礼儀が 正しいです = lễ nghi đúng mực.", L),
]

KANJI = [
    k(1, "性", "TÍNH", 8, ["セイ (sei)"], [], "Tính chất, giới tính.",
      [("性格", "せいかく", "Tính cách"), ("女性", "じょせい", "Phụ nữ")], L),
    k(2, "礼", "LỄ", 5, ["レイ (rei)"], [], "Lễ nghi, lễ phép.",
      [("礼儀", "れいぎ", "Lễ nghi"), ("お礼", "おれい", "Lời cảm ơn")], L),
    k(3, "儀", "NGHI", 15, ["ギ (gi)"], [], "Nghi thức, phép tắc.",
      [("礼儀", "れいぎ", "Lễ nghi")], L),
    k(4, "識", "THỨC", 19, ["シキ (shiki)"], [], "Nhận thức, kiến thức.",
      [("知識", "ちしき", "Kiến thức"), ("意識", "いしき", "Ý thức")], L),
    k(5, "能", "NĂNG", 10, ["ノウ (nou)"], [], "Năng lực, khả năng.",
      [("能力", "のうりょく", "Năng lực"), ("可能", "かのう", "Khả thi")], L),
]

SLIDES = [
    slide(L, 1,
        "1. Mở rộng phạm vi (trung tính): N1だけでなく、N2も",
        "N1(+だ) + だけでなく、N2 + も   /   [Thể thường] + だけでなく、〜も",
        "だけでなく mở rộng phạm vi, thêm một điều NGOÀI điều đã nêu — cấu trúc phổ biến, TRUNG "
        "TÍNH, không mang sắc thái ngạc nhiên đặc biệt, thường đi kèm も ở vế sau.",
        [
            ex(L, 1, 1, [t("t-l15s1-1", "かのじょ", "彼女", "かのじょ", key=True), t("t-l15s1-2", "は"),
                         t("t-l15s1-3", "にほんご", "日本語", "にほんご"), t("t-l15s1-4", "だけでなく", key=True),
                         t("t-l15s1-5", "、"), t("t-l15s1-6", "えいご", "英語", "えいご"), t("t-l15s1-7", "も"),
                         t("t-l15s1-8", "はなせます", "話せます", "はなせます")],
               "Cô ấy không chỉ nói được tiếng Nhật mà còn nói được cả tiếng Anh."),
            ex(L, 1, 2, [t("t-l15s1-9", "りょうり", "料理", "りょうり", key=True), t("t-l15s1-10", "だけでなく", key=True),
                         t("t-l15s1-11", "、"), t("t-l15s1-12", "かじ", "家事", "かじ", key=True), t("t-l15s1-13", "も"),
                         t("t-l15s1-14", "じょうず", "上手", "じょうず"), t("t-l15s1-15", "です")],
               "Không chỉ nấu ăn mà việc nhà cũng giỏi."),
        ],
        tips="だけでなく có thể đứng sau N, Aい/な, hoặc V thể thường — vế sau luôn cần も hoặc さえ để nhấn 'thêm nữa'.",
        culture="Trong CV/hồ sơ xin việc ở Nhật, ứng viên hay viết: '日本語だけでなく、英語も話せます' để thể hiện năng lực đa dạng."),

    slide(L, 2,
        "2. Không những... mà còn... (mạnh hơn, gây ngạc nhiên): ばかりか",
        "N(+である)/[Thể thường] + ばかりか、〜も/さえ",
        "ばかりか cũng nghĩa 'không những... mà còn...' nhưng MẠNH HƠN だけでなく, thường nhấn "
        "mạnh điều THỨ HAI VƯỢT XA KỲ VỌNG hoặc gây NGẠC NHIÊN (có thể theo hướng tích cực hoặc tiêu cực).",
        [
            ex(L, 2, 1, [t("t-l15s2-1", "かのじょ", "彼女", "かのじょ", key=True), t("t-l15s2-2", "は"),
                         t("t-l15s2-3", "せいかく", "性格", "せいかく", key=True), t("t-l15s2-4", "が"),
                         t("t-l15s2-5", "いい"), t("t-l15s2-6", "ばかりか", key=True), t("t-l15s2-7", "、"),
                         t("t-l15s2-8", "のうりょく", "能力", "のうりょく", key=True), t("t-l15s2-9", "も"),
                         t("t-l15s2-10", "たかい", "高い", "たかい"), t("t-l15s2-11", "です")],
               "Cô ấy không những tính cách tốt mà năng lực còn cao."),
            ex(L, 2, 2, [t("t-l15s2-12", "けいけん", "経験", "けいけん", key=True), t("t-l15s2-13", "が"),
                         t("t-l15s2-14", "ない"), t("t-l15s2-15", "ばかりか", key=True), t("t-l15s2-16", "、"),
                         t("t-l15s2-17", "ちしき", "知識", "ちしき", key=True), t("t-l15s2-18", "も"),
                         t("t-l15s2-19", "ぜんぜん", "全然", "ぜんぜん"), t("t-l15s2-20", "ありません", "有りません", "ありません")],
               "Không những không có kinh nghiệm mà kiến thức cũng hoàn toàn không có."),
        ],
        tips="ばかりか dùng được cho cả hai chiều: khen ngợi vượt kỳ vọng (tích cực) hoặc chê trách nặng nề hơn (tiêu cực).",
        culture="Trong bài phê bình/khen ngợi trang trọng, ばかりか thường tạo hiệu ứng NHẤN MẠNH mạnh hơn だけでなく nhiều."),

    slide(L, 3,
        "3. So sánh だけでなく và ばかりか",
        "だけでなく: TRUNG TÍNH, phổ biến　vs　ばかりか: MẠNH HƠN, gây NGẠC NHIÊN, trang trọng hơn",
        "Cả hai đều nghĩa 'không chỉ... mà còn...', nhưng だけでなく chỉ đơn thuần THÔNG BÁO có "
        "thêm một điều nữa; ばかりか nhấn thêm sắc thái BẤT NGỜ — điều thứ hai vượt xa những gì người nghe mong đợi.",
        [
            ex(L, 3, 1, [t("t-l15s3-1", "あたま", "頭", "あたま", key=True), t("t-l15s3-2", "が"),
                         t("t-l15s3-3", "いい"), t("t-l15s3-4", "だけでなく", key=True), t("t-l15s3-5", "、"),
                         t("t-l15s3-6", "れいぎ", "礼儀", "れいぎ", key=True), t("t-l15s3-7", "も"),
                         t("t-l15s3-8", "いいです", "いいです", "いいです")],
               "Không chỉ thông minh mà lễ nghi cũng tốt. (thông báo trung tính)"),
            ex(L, 3, 2, [t("t-l15s3-9", "あたま", "頭", "あたま", key=True), t("t-l15s3-10", "が"),
                         t("t-l15s3-11", "いい"), t("t-l15s3-12", "ばかりか", key=True), t("t-l15s3-13", "、"),
                         t("t-l15s3-14", "がいこくご", "外国語", "がいこくご", key=True), t("t-l15s3-15", "が"),
                         t("t-l15s3-16", "ほんとうに", "本当に", "ほんとうに", key=True), t("t-l15s3-17", "じょうず", "上手", "じょうず"),
                         t("t-l15s3-18", "です")],
               "Không những thông minh mà ngoại ngữ còn thật sự giỏi. (nhấn mạnh, ngạc nhiên)"),
        ],
        tips="Mẹo chọn: nếu chỉ muốn LIỆT KÊ thêm thông tin → だけでなく; nếu muốn NHẤN MẠNH sự vượt trội bất ngờ → ばかりか.",
        culture="Bài phỏng vấn tuyển dụng ở Nhật hay dùng ばかりか khi khen ứng viên: '経験があるばかりか、リーダーシップもあります' (không những có kinh nghiệm mà còn có khả năng lãnh đạo)."),

    slide(L, 4,
        "4. Kết hợp với さえ để nhấn cực độ: 〜ばかりか、〜さえ",
        "[Thể thường] + ばかりか、〜さえ + [động từ/tính từ]",
        "Khi kết hợp ばかりか với さえ (thậm chí, đã học ở bài さえ〜ば), câu văn nhấn mạnh mức độ "
        "CỰC ĐOAN của điều thứ hai — thường dùng trong văn viết trang trọng để gây ấn tượng mạnh.",
        [
            ex(L, 4, 1, [t("t-l15s4-1", "かのじょ", "彼女", "かのじょ", key=True), t("t-l15s4-2", "は"),
                         t("t-l15s4-3", "のうりょく", "能力", "のうりょく", key=True), t("t-l15s4-4", "が"),
                         t("t-l15s4-5", "たかい", "高い", "たかい"), t("t-l15s4-6", "ばかりか", key=True), t("t-l15s4-7", "、"),
                         t("t-l15s4-8", "れいぎ", "礼儀", "れいぎ", key=True), t("t-l15s4-9", "さえ", key=True),
                         t("t-l15s4-10", "ただしい", "正しい", "ただしい")],
               "Cô ấy không những năng lực cao mà thậm chí lễ nghi cũng đúng mực."),
            ex(L, 4, 2, [t("t-l15s4-11", "ちしき", "知識", "ちしき", key=True), t("t-l15s4-12", "が"),
                         t("t-l15s4-13", "ない"), t("t-l15s4-14", "ばかりか", key=True), t("t-l15s4-15", "、"),
                         t("t-l15s4-16", "れいぎ", "礼儀", "れいぎ", key=True), t("t-l15s4-17", "さえ", key=True),
                         t("t-l15s4-18", "まったく", "全く", "まったく"), t("t-l15s4-19", "ありません", "有りません", "ありません")],
               "Không những không có kiến thức mà thậm chí lễ nghi cũng hoàn toàn không có."),
        ],
        tips="ばかりか〜さえ tạo hiệu ứng NHẤN MẠNH GẤP ĐÔI — thường thấy trong văn phê bình, bài phỏng vấn, bài luận đánh giá.",
        culture="Cấu trúc này khá nâng cao, thường xuất hiện trong đề đọc hiểu N3-N2 khi văn bản muốn nhấn mạnh một đặc điểm vượt trội hoặc yếu kém rõ rệt."),
]

DIALOGUE = [
    line(L, 1, "田中", "Phỏng vấn nhân sự",
         [t("d15-1", "あたらしい", "新しい", "あたらしい"), t("d15-2", "ひと", "人", "ひと"), t("d15-3", "は"),
          t("d15-4", "どうですか")],
         "Người mới thế nào?"),
    line(L, 2, "サントス", "Phỏng vấn nhân sự",
         [t("d15-5", "にほんご", "日本語", "にほんご"), t("d15-6", "だけでなく", key=True), t("d15-7", "、"),
          t("d15-8", "えいご", "英語", "えいご"), t("d15-9", "も"), t("d15-10", "はなせます", "話せます", "はなせます")],
         "Không chỉ nói được tiếng Nhật mà còn nói được cả tiếng Anh."),
    line(L, 3, "田中", "Phỏng vấn nhân sự",
         [t("d15-11", "せいかく", "性格", "せいかく", key=True), t("d15-12", "は"), t("d15-13", "どうですか")],
         "Tính cách thế nào?"),
    line(L, 4, "サントス", "Phỏng vấn nhân sự",
         [t("d15-14", "せいかく", "性格", "せいかく", key=True), t("d15-15", "が"), t("d15-16", "いい"),
          t("d15-17", "ばかりか", key=True), t("d15-18", "、"), t("d15-19", "のうりょく", "能力", "のうりょく", key=True),
          t("d15-20", "も"), t("d15-21", "たかい", "高い", "たかい"), t("d15-22", "です")],
         "Không những tính cách tốt mà năng lực còn cao."),
    line(L, 5, "田中", "Phỏng vấn nhân sự",
         [t("d15-23", "けいけん", "経験", "けいけん", key=True), t("d15-24", "は"), t("d15-25", "ありますか")],
         "Có kinh nghiệm không?"),
    line(L, 6, "サントス", "Phỏng vấn nhân sự",
         [t("d15-26", "けいけん", "経験", "けいけん", key=True), t("d15-27", "が"), t("d15-28", "ない"),
          t("d15-29", "ばかりか", key=True), t("d15-30", "、"), t("d15-31", "ちしき", "知識", "ちしき", key=True),
          t("d15-32", "も"), t("d15-33", "ぜんぜん", "全然", "ぜんぜん"), t("d15-34", "ありません", "有りません", "ありません")],
         "Không những không có kinh nghiệm mà kiến thức cũng hoàn toàn không có."),
    line(L, 7, "田中", "Phỏng vấn nhân sự",
         [t("d15-35", "それは"), t("d15-36", "こまります", "困ります", "こまります"), t("d15-37", "ね")],
         "Vậy thì khó xử nhỉ."),
    line(L, 8, "サントス", "Phỏng vấn nhân sự",
         [t("d15-38", "でも"), t("d15-39", "、"), t("d15-40", "りょうり", "料理", "りょうり", key=True),
          t("d15-41", "だけでなく", key=True), t("d15-42", "、"), t("d15-43", "かじ", "家事", "かじ", key=True),
          t("d15-44", "も"), t("d15-45", "じょうず", "上手", "じょうず"), t("d15-46", "です")],
         "Nhưng không chỉ nấu ăn mà việc nhà cũng giỏi."),
    line(L, 9, "田中", "Phỏng vấn nhân sự",
         [t("d15-47", "あたま", "頭", "あたま", key=True), t("d15-48", "が"), t("d15-49", "いい"),
          t("d15-50", "ばかりか", key=True), t("d15-51", "、"), t("d15-52", "れいぎ", "礼儀", "れいぎ", key=True),
          t("d15-53", "さえ", key=True), t("d15-54", "ただしい", "正しい", "ただしい"), t("d15-55", "ひと", "人", "ひと"),
          t("d15-56", "です", "です", "です"), t("d15-57", "か")],
         "Có phải người không những thông minh mà thậm chí lễ nghi cũng đúng mực không?"),
    line(L, 10, "サントス", "Phỏng vấn nhân sự",
         [t("d15-58", "はい"), t("d15-59", "。"), t("d15-60", "ほんとうに", "本当に", "ほんとうに", key=True),
          t("d15-61", "いい"), t("d15-62", "ひと", "人", "ひと"), t("d15-63", "です", "です", "です")],
         "Vâng. Là một người thật sự tốt."),
]

EXERCISES = [
    q(L, 1, "「彼女は日本語だけでなく、英語も話せます」 — だけでなく diễn tả điều gì?",
      ["Mở rộng phạm vi, thêm một điều ngoài điều đã nêu (trung tính)",
       "Sự bất ngờ, vượt xa kỳ vọng", "Phủ định hoàn toàn", "So sánh hai ngôn ngữ"], 0,
      "だけでなく mở rộng phạm vi thông tin một cách TRUNG TÍNH, không mang sắc thái ngạc nhiên đặc biệt.",
      "Xem cấu trúc だけでなく ở slide 1."),
    q(L, 2, "「性格がいいばかりか、能力も高いです」 — ばかりか khác だけでなく ở điểm nào?",
      ["ばかりか mạnh hơn, nhấn mạnh sắc thái vượt xa kỳ vọng/ngạc nhiên",
       "Hoàn toàn giống nhau, không khác gì cả", "ばかりか chỉ dùng cho câu hỏi",
       "だけでなく chỉ dùng cho phủ định"], 0,
      "ばかりか nhấn mạnh điều thứ hai VƯỢT XA những gì người nghe mong đợi, mạnh hơn だけでなく.",
      "Xem giải thích ばかりか ở slide 2."),
    q(L, 3, "ばかりか có thể dùng cho cả hướng tích cực lẫn tiêu cực không?",
      ["Có, ばかりか dùng được cho cả khen ngợi vượt kỳ vọng lẫn chê trách nặng nề hơn",
       "Không, chỉ dùng được cho hướng tích cực", "Chỉ dùng được cho hướng tiêu cực",
       "Chỉ dùng được trong câu hỏi"], 0,
      "ばかりか dùng được cho cả hai chiều: khen ngợi vượt kỳ vọng hoặc chê trách nặng nề hơn.",
      "Xem ví dụ về kinh nghiệm/kiến thức ở slide 2."),
    q(L, 4, "「経験がないばかりか、知識も全然ありません」 nghĩa là:",
      ["Không những không có kinh nghiệm mà kiến thức cũng hoàn toàn không có",
       "Có kinh nghiệm và kiến thức đầy đủ", "Chỉ thiếu kinh nghiệm, kiến thức thì đủ",
       "Chỉ thiếu kiến thức, kinh nghiệm thì đủ"], 0,
      "ばかりか ở đây nhấn mạnh CẢ HAI đều thiếu (kinh nghiệm VÀ kiến thức), mức độ nghiêm trọng hơn.",
      "Áp dụng cấu trúc ばかりか cho ngữ cảnh tiêu cực."),
    q(L, 5, "Cấu trúc ばかりか〜さえ dùng để làm gì?",
      ["Nhấn mạnh mức độ cực đoan của điều thứ hai (nhấn mạnh gấp đôi)",
       "Giảm nhẹ mức độ của câu nói", "Phủ định toàn bộ câu",
       "Chỉ dùng được trong câu hỏi"], 0,
      "Kết hợp ばかりか với さえ (thậm chí) tạo hiệu ứng nhấn mạnh GẤP ĐÔI mức độ cực đoan.",
      "Xem cấu trúc ばかりか〜さえ ở slide 4."),
    q(L, 6, "「頭がいいだけでなく、礼儀もいいです」 và 「頭がいいばかりか、外国語が本当に上手です」 khác nhau ở đâu?",
      ["Câu thứ nhất trung tính (thông báo), câu thứ hai nhấn mạnh sự ngạc nhiên/vượt trội",
       "Không có gì khác nhau cả", "Câu thứ nhất là phủ định",
       "Câu thứ hai không đúng ngữ pháp"], 0,
      "だけでなく chỉ thông báo trung tính; ばかりか thêm sắc thái ngạc nhiên, vượt xa kỳ vọng.",
      "So sánh hai câu ở slide 3."),
    q(L, 7, "Trong CV/hồ sơ xin việc, cấu trúc nào thường được dùng để liệt kê kỹ năng một cách trung tính?",
      ["だけでなく", "ばかりか", "てならない", "としたら"], 0,
      "だけでなく phù hợp để liệt kê thêm thông tin/kỹ năng một cách trung tính, phổ biến trong hồ sơ xin việc.",
      "Xem ví dụ văn hóa ở slide 1."),
    q(L, 8, "Theo hội thoại, ứng viên có kinh nghiệm và kiến thức không?",
      ["Không, cả kinh nghiệm và kiến thức đều thiếu (経験がないばかりか、知識も全然ありません)",
       "Có đầy đủ cả hai", "Chỉ có kinh nghiệm, thiếu kiến thức",
       "Chỉ có kiến thức, thiếu kinh nghiệm"], 0,
      "Santos trả lời 「経験がないばかりか、知識も全然ありません」.",
      "Xem câu thoại thứ 6."),
    q(L, 9, "Ứng viên trong hội thoại giỏi những gì?",
      ["Không chỉ nấu ăn mà việc nhà cũng giỏi (料理だけでなく、家事も上手です)",
       "Chỉ giỏi nấu ăn, không giỏi việc nhà", "Không giỏi gì cả",
       "Chỉ giỏi việc nhà, không giỏi nấu ăn"], 0,
      "Santos nói 「料理だけでなく、家事も上手です」.",
      "Xem câu thoại thứ 8."),
    q(L, 10, "Santos đánh giá thế nào về ứng viên ở cuối hội thoại?",
      ["Là một người thật sự tốt (本当にいい人です)", "Là một người không tốt",
       "Không đưa ra đánh giá nào", "Cần phỏng vấn thêm lần nữa"], 0,
      "Santos kết luận 「本当にいい人です」.",
      "Xem câu thoại cuối cùng."),
]

LESSON = lesson(
    L,
    "Bài 15: Mở rộng phạm vi (だけでなく & ばかりか)",
    "だけでなく mở rộng phạm vi, thêm một điều ngoài điều đã nêu một cách TRUNG TÍNH, phổ biến; "
    "ばかりか cũng nghĩa 'không những... mà còn...' nhưng MẠNH HƠN, nhấn mạnh điều thứ hai VƯỢT "
    "XA KỲ VỌNG (tích cực hoặc tiêu cực); kết hợp ばかりか〜さえ để nhấn mức độ cực đoan gấp đôi.",
    VOCAB, KANJI, SLIDES, DIALOGUE, EXERCISES,
)

if __name__ == "__main__":
    pool.mark_used([w["word"] for w in VOCAB if w["word"]], lesson=L)
    merge([LESSON])
