# -*- coding: utf-8 -*-
"""N3 — Bai 1 (bai mo dau N3): Phan doan chac chan わけがない,
phu dinh gian tiep わけではない.

Tu vung minh hoa TU CHON tu pool mo data/jlpt-vocab/n3.csv (xem NOTICE.md).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from n3_lib import v, k, t, ex, slide, line, q, lesson, merge
from jlpt_pool import Pool

L = 1
pool = Pool("n3")

VOCAB = [
    v(1,  "しんじます", "信じます", "しんじます", "shinjimasu", "verb", "Tin tưởng", "そんな こと 信じられません = tôi không thể tin chuyện đó.", L),
    v(2,  "ごかいします", "誤解します", "ごかいします", "gokai shimasu", "verb", "Hiểu lầm", "誤解しないで ください = xin đừng hiểu lầm.", L),
    v(3,  "かんちがいします", "勘違いします", "かんちがいします", "kanchigai shimasu", "verb", "Nhầm lẫn, hiểu sai", "何か 勘違いして いるようです = có vẻ (bạn) đang nhầm lẫn điều gì đó.", L),
    v(4,  "じょうたつします", "上達します", "じょうたつします", "joutatsu shimasu", "verb", "Tiến bộ, tiến triển", "日本語が 上達しました = tiếng Nhật đã tiến bộ.", L),
    v(5,  "せんもんです", "専門です", "せんもんです", "senmon desu", "phrase", "Là chuyên môn (thể thông thường: 専門だ)", "彼の 専門だ から = vì đó là chuyên môn của anh ấy.", L),
    v(6,  "せんもん", "専門", "せんもん", "senmon", "noun", "Chuyên môn, ngành học", "医学が 専門です = chuyên môn là y học.", L),
    v(7,  "くわしい", "詳しい", "くわしい", "kuwashii", "adjective", "Rành, tường tận, chi tiết", "この分野に 詳しい 人 = người rành lĩnh vực này.", L),
    v(8,  "にがて", "苦手", "にがて", "nigate", "adjective", "Kém, không giỏi (tính từ な)", "Đã gặp N4 bài 38.", L),
    v(9,  "じしん", "自信", "じしん", "jishin", "noun", "Sự tự tin", "自信が ある わけではありません = không phải là (tôi) có tự tin.", L),
    v(10, "けいけん", "経験", "けいけん", "keiken", "noun", "Kinh nghiệm, trải nghiệm", "Đã gặp N5 bài 19.", L),
    v(11, "せいかく", "性格", "せいかく", "seikaku", "noun", "Tính cách", "彼は そういう 性格じゃない = anh ấy không phải kiểu tính cách đó.", L),
    v(12, "りゆう", "理由", "りゆう", "riyuu", "noun", "Lý do", "Đã gặp bài 26 (N4).", L),
    v(13, "けっか", "結果", "けっか", "kekka", "noun", "Kết quả", "この 結果は 偶然の わけがない = kết quả này không thể nào là ngẫu nhiên được.", L),
    v(14, "ぐうぜん", "偶然", "ぐうぜん", "guuzen", "adjective", "Ngẫu nhiên, tình cờ (danh từ/tính từ な)", "偶然じゃない = không phải ngẫu nhiên.", L),
    v(15, "とくい", "得意", "とくい", "tokui", "adjective", "Giỏi, sở trường", "彼は 数学が 得意な わけではありません = không phải anh ấy giỏi toán.", L),
    v(16, "さんか", "参加", "さんか", "sanka", "noun", "Sự tham gia", "パーティーに 参加する わけには いきません = không thể nào tham gia bữa tiệc được (chưa học đủ, chỉ minh họa từ vựng).", L),
    v(17, "さんせい", "賛成", "さんせい", "sansei", "noun", "Sự tán thành, đồng ý", "みんなが 賛成した わけではありません = không phải mọi người đều tán thành.", L),
    v(18, "きろく", "記録", "きろく", "kiroku", "noun", "Kỷ lục, ghi chép", "彼が この 記録を 破った わけがない = không thể nào anh ấy phá được kỷ lục này.", L),
    v(19, "ざんねん", "残念", "ざんねん", "zannen", "adjective", "Đáng tiếc, tiếc nuối", "Đã gặp N4 bài 27.", L),
    v(20, "せつめい", "説明", "せつめい", "setsumei", "noun", "Lời giải thích", "Đã gặp N4 bài 34.", L),
]

KANJI = [
    k(1, "信", "TÍN", 9, ["シン (shin)"], ["しん(じる)"], "Tin tưởng, đáng tin.",
      [("信じます", "しんじます", "Tin tưởng"), ("自信", "じしん", "Tự tin"), ("信号", "しんごう", "Đèn tín hiệu")], L),
    k(2, "誤", "NGỘ", 14, ["ゴ (go)"], ["あやま(る)"], "Sai lầm, nhầm lẫn.",
      [("誤解", "ごかい", "Hiểu lầm"), ("誤り", "あやまり", "Sai sót")], L),
    k(3, "専", "CHUYÊN", 9, ["セン (sen)"], ["もっぱ(ら)"], "Chuyên môn, chuyên nhất.",
      [("専門", "せんもん", "Chuyên môn"), ("専門家", "せんもんか", "Chuyên gia")], L),
    k(4, "偶", "NGẪU", 11, ["グウ (guu)"], [], "Ngẫu nhiên, tình cờ.",
      [("偶然", "ぐうぜん", "Ngẫu nhiên"), ("偶数", "ぐうすう", "Số chẵn")], L),
    k(5, "録", "LỤC", 16, ["ロク (roku)"], [], "Ghi chép, ghi lại.",
      [("記録", "きろく", "Kỷ lục, ghi chép"), ("録音", "ろくおん", "Ghi âm")], L),
]

SLIDES = [
    slide(L, 1,
        "1. Khẳng định chắc chắn KHÔNG THỂ: [Thể thông thường] わけがない",
        "V/A(thể thông thường) + わけがない　　N/な-adj + な + わけがない",
        "わけがない (nghĩa đen: 'không có lý do/cách nào') diễn tả sự PHỦ ĐỊNH MẠNH MẼ dựa trên "
        "SUY LUẬN LOGIC của người nói — 'không đời nào, không thể nào' — mạnh hơn hẳn ないでしょう.",
        [
            ex(L, 1, 1, [t("t-l1s1-1", "かれ", "彼", "かれ"), t("t-l1s1-2", "が"),
                         t("t-l1s1-3", "この"), t("t-l1s1-4", "きろく", "記録", "きろく", key=True), t("t-l1s1-5", "を"),
                         t("t-l1s1-6", "やぶった", "破った", "やぶった"), t("t-l1s1-7", "わけが", key=True),
                         t("t-l1s1-8", "ない", key=True)],
               "Không thể nào anh ấy phá được kỷ lục này."),
            ex(L, 1, 2, [t("t-l1s1-9", "そんな"), t("t-l1s1-10", "こと"), t("t-l1s1-11", "、"),
                         t("t-l1s1-12", "しんじられる", "信じられる", "しんじられる"), t("t-l1s1-13", "わけが", key=True),
                         t("t-l1s1-14", "ありません", key=True)],
               "Không thể nào tin được chuyện như vậy."),
        ],
        tips="わけがない mang tính CHỦ QUAN mạnh, dựa trên niềm tin/kinh nghiệm cá nhân của người nói — khác はずがない (khách quan hơn, dựa trên logic/quy tắc, học ở N2).",
        culture="そんなわけがない là câu phản bác đầy cảm xúc rất phổ biến khi ai đó nhận được tin gây sốc, khó tin."),

    slide(L, 2,
        "2. Phủ định gián tiếp: [Thể thông thường] わけではない",
        "V/A(thể thông thường) + わけではない　　N/な-adj + な + わけではない",
        "わけではない KHÔNG phủ định TOÀN BỘ sự việc, mà chỉ phủ định một PHẦN/MỘT CÁCH HIỂU cụ "
        "thể — 'không phải là...' nhẹ nhàng hơn いいえ/ちがいます, thường dùng để ĐÍNH CHÍNH hiểu lầm.",
        [
            ex(L, 2, 1, [t("t-l1s2-1", "かれ", "彼", "かれ"), t("t-l1s2-2", "は"),
                         t("t-l1s2-3", "すうがく", "数学", "すうがく"), t("t-l1s2-4", "が"),
                         t("t-l1s2-5", "とくいな", "得意な", "とくいな", key=True), t("t-l1s2-6", "わけでは", key=True),
                         t("t-l1s2-7", "ありません", key=True)],
               "Không phải là anh ấy giỏi toán (chỉ là điểm tạm ổn thôi)."),
            ex(L, 2, 2, [t("t-l1s2-8", "みんな", "皆", "みんな"), t("t-l1s2-9", "が"),
                         t("t-l1s2-10", "さんせい", "賛成", "さんせい", key=True), t("t-l1s2-11", "した"),
                         t("t-l1s2-12", "わけでは", key=True), t("t-l1s2-13", "ありません", key=True)],
               "Không phải là mọi người đều tán thành (một số người phản đối)."),
        ],
        tips="わけではない thường dùng để ĐÍNH CHÍNH một hiểu lầm đã hình thành trước đó — thường xuất hiện sau でも/しかし để phản bác nhẹ nhàng.",
        culture="日本語が上手なわけではありません là câu khiêm tốn phổ biến khi được khen giỏi tiếng Nhật — phủ nhận nhẹ nhàng, không phủ nhận thẳng thừng."),

    slide(L, 3,
        "3. So sánh わけがない và わけではない",
        "わけがない: PHỦ ĐỊNH TOÀN BỘ, mạnh mẽ ('không đời nào')　vs　わけではない: PHỦ ĐỊNH MỘT PHẦN, nhẹ nhàng ('không hẳn là')",
        "Hai cấu trúc trông giống nhau (cùng có わけ) nhưng mức độ và phạm vi phủ định HOÀN TOÀN "
        "KHÁC — わけがない bác bỏ dứt khoát, わけではない chỉ điều chỉnh một phần nhận định.",
        [
            ex(L, 3, 1, [t("t-l1s3-1", "せんもん", "専門", "せんもん", key=True), t("t-l1s3-2", "じゃない", key=True),
                         t("t-l1s3-3", "かれ", "彼", "かれ"), t("t-l1s3-4", "が"), t("t-l1s3-5", "この"),
                         t("t-l1s3-6", "もんだい", "問題", "もんだい"), t("t-l1s3-7", "を"), t("t-l1s3-8", "とけた", "解けた", "とけた"),
                         t("t-l1s3-9", "わけが", key=True), t("t-l1s3-10", "ない", key=True)],
               "Không phải chuyên môn của anh ấy nên không thể nào anh ấy giải được bài toán này. (わけがない)"),
            ex(L, 3, 2, [t("t-l1s3-11", "かれ", "彼", "かれ"), t("t-l1s3-12", "は"),
                         t("t-l1s3-13", "にがて", "苦手", "にがて"), t("t-l1s3-14", "です"), t("t-l1s3-15", "が"),
                         t("t-l1s3-16", "、"), t("t-l1s3-17", "まったく", "全く", "まったく"),
                         t("t-l1s3-18", "できない", key=True), t("t-l1s3-19", "わけでは", key=True),
                         t("t-l1s3-20", "ありません", key=True)],
               "Anh ấy kém môn đó, nhưng không phải là hoàn toàn không làm được. (わけではない)"),
        ],
        tips="Mẹo phân biệt nhanh: わけがない thường dịch được là 'không đời nào'; わけではない dịch được là 'không hẳn/không phải hoàn toàn'.",
        culture="Cả hai cấu trúc đều rất phổ biến trong tranh luận, phản biện lịch sự — thể hiện quan điểm mà không nói thẳng いいえ gây mất lòng."),

    slide(L, 4,
        "4. わけではない thường đi cùng でも/しかし để đính chính",
        "[Nhận định trước đó] でも／しかし、[thực ra] わけではありません",
        "Cấu trúc điển hình: MỞ ĐẦU bằng một nhận định có vẻ đúng, rồi dùng でも/しかし + "
        "わけではありません để LÀM RÕ nó không hoàn toàn chính xác.",
        [
            ex(L, 4, 1, [t("t-l1s4-1", "にほんご", "日本語", "にほんご"), t("t-l1s4-2", "が"),
                         t("t-l1s4-3", "じょうたつ", "上達", "じょうたつ", key=True), t("t-l1s4-4", "しました"),
                         t("t-l1s4-5", "。"), t("t-l1s4-6", "でも"), t("t-l1s4-7", "、"),
                         t("t-l1s4-8", "じしん", "自信", "じしん", key=True), t("t-l1s4-9", "が"),
                         t("t-l1s4-10", "ある", key=True), t("t-l1s4-11", "わけでは", key=True),
                         t("t-l1s4-12", "ありません", key=True)],
               "Tiếng Nhật của tôi đã tiến bộ. Nhưng không phải là tôi (đã) có sự tự tin."),
        ],
        tips="Đây là mẫu câu rất tự nhiên khi khiêm tốn về thành tích của mình — công nhận một phần rồi ngay lập tức làm rõ giới hạn của nó.",
        culture="Khiêm tốn kiểu Nhật thường theo mẫu: khen bản thân MỘT CHÚT rồi lập tức わけではありません để giảm nhẹ, tránh tự cao."),
]

DIALOGUE = [
    line(L, 1, "田中", "Đồng nghiệp",
         [t("d1-1", "山田さん", "山田さん", "山田さん"), t("d1-2", "が"), t("d1-3", "この"),
          t("d1-4", "きろく", "記録", "きろく", key=True), t("d1-5", "を"), t("d1-6", "やぶった", "破った", "やぶった"),
          t("d1-7", "そうです", "そうです", "そうです"), t("d1-8", "よ")],
         "Nghe nói anh Yamada đã phá kỷ lục này đấy."),
    line(L, 2, "サントス", "Đồng nghiệp",
         [t("d1-9", "え"), t("d1-10", "！"), t("d1-11", "そんな"), t("d1-12", "わけが", key=True),
          t("d1-13", "ありません", key=True), t("d1-14", "。"), t("d1-15", "やまださん", "山田さん", "やまださん"),
          t("d1-16", "は"), t("d1-17", "スポーツ"), t("d1-18", "が"), t("d1-19", "にがて", "苦手", "にがて", key=True),
          t("d1-20", "です")],
         "Ơ! Không thể nào. Anh Yamada kém thể thao mà."),
    line(L, 3, "田中", "Đồng nghiệp",
         [t("d1-21", "でも"), t("d1-22", "、"), t("d1-23", "さいきん", "最近", "さいきん"), t("d1-24", "、"),
          t("d1-25", "とても"), t("d1-26", "れんしゅう", "練習", "れんしゅう"), t("d1-27", "して", key=True),
          t("d1-28", "いました", "居ました", "いました")],
         "Nhưng gần đây, anh ấy đã luyện tập rất chăm chỉ đấy."),
    line(L, 4, "サントス", "Đồng nghiệp",
         [t("d1-29", "そうですか"), t("d1-30", "。"), t("d1-31", "でも"), t("d1-32", "、"),
          t("d1-33", "せんもん", "専門", "せんもん", key=True), t("d1-34", "の"), t("d1-35", "せんしゅ", "選手", "せんしゅ"),
          t("d1-36", "に"), t("d1-37", "かった", "勝った", "かった"), t("d1-38", "わけが", key=True),
          t("d1-39", "ない", key=True), t("d1-40", "と"), t("d1-41", "おもいます", "思います", "おもいます")],
         "Vậy à. Nhưng tôi vẫn nghĩ không thể nào anh ấy thắng được vận động viên chuyên nghiệp."),
    line(L, 5, "田中", "Đồng nghiệp",
         [t("d1-42", "たしかに", "確かに", "たしかに"), t("d1-43", "、"), t("d1-44", "せんもん", "専門", "せんもん", key=True),
          t("d1-45", "の"), t("d1-46", "せんしゅ", "選手", "せんしゅ"), t("d1-47", "に"), t("d1-48", "かった", "勝った", "かった"),
          t("d1-49", "わけでは", key=True), t("d1-50", "ありません", key=True), t("d1-51", "。"),
          t("d1-52", "きろく", "記録", "きろく"), t("d1-53", "を"), t("d1-54", "こうしんした", "更新した", "こうしんした"),
          t("d1-55", "だけ", "だけ", "だけ"), t("d1-56", "です")],
         "Đúng là, không phải là anh ấy thắng vận động viên chuyên nghiệp. Chỉ là anh ấy đã phá kỷ lục thôi."),
    line(L, 6, "サントス", "Đồng nghiệp",
         [t("d1-57", "なるほど"), t("d1-58", "。"), t("d1-59", "わたし", "私", "わたし"), t("d1-60", "が"),
          t("d1-61", "かんちがい", "勘違い", "かんちがい", key=True), t("d1-62", "して", key=True),
          t("d1-63", "いました", "居ました", "いました")],
         "Ra vậy. Tôi đã hiểu nhầm rồi."),
    line(L, 7, "田中", "Đồng nghiệp",
         [t("d1-64", "だいじょうぶ", "大丈夫", "だいじょうぶ"), t("d1-65", "です", "です", "です"), t("d1-66", "よ"),
          t("d1-67", "。"), t("d1-68", "ごかい", "誤解", "ごかい", key=True), t("d1-69", "しやすい"),
          t("d1-70", "はなし", "話", "はなし"), t("d1-71", "でした")],
         "Không sao đâu. Đây là câu chuyện dễ gây hiểu lầm mà."),
    line(L, 8, "サントス", "Đồng nghiệp",
         [t("d1-72", "やまださん", "山田さん", "やまださん"), t("d1-73", "は"), t("d1-74", "ほんとう", "本当", "ほんとう"),
          t("d1-75", "に"), t("d1-76", "じょうたつ", "上達", "じょうたつ", key=True), t("d1-77", "した", "した", "した"),
          t("d1-78", "んです", "んです", "んです"), t("d1-79", "ね")],
         "Anh Yamada thật sự đã tiến bộ nhỉ."),
    line(L, 9, "田中", "Đồng nghiệp",
         [t("d1-80", "はい"), t("d1-81", "。"), t("d1-82", "でも"), t("d1-83", "、"),
          t("d1-84", "じしん", "自信", "じしん", key=True), t("d1-85", "が"), t("d1-86", "ある", key=True),
          t("d1-87", "わけでは", key=True), t("d1-88", "ない", key=True), t("d1-89", "と"),
          t("d1-90", "いっていました", "言っていました", "いっていました")],
         "Vâng. Nhưng anh ấy nói không phải là đã có sự tự tin."),
    line(L, 10, "サントス", "Đồng nghiệp",
         [t("d1-91", "けんきょ", "謙虚", "けんきょ"), t("d1-92", "です"), t("d1-93", "ね"), t("d1-94", "。"),
          t("d1-95", "すごい"), t("d1-96", "です"), t("d1-97", "ね")],
         "Khiêm tốn thật nhỉ. Giỏi thật đấy."),
]

EXERCISES = [
    q(L, 1, "「そんなわけがありません」 nghĩa là:",
      ["Không thể nào có chuyện đó (phủ định mạnh mẽ)", "Có thể có chuyện đó",
       "Chuyện đó đã xảy ra rồi", "Không rõ chuyện đó có xảy ra không"], 0,
      "わけがない diễn tả sự phủ định MẠNH MẼ, dựa trên suy luận/niềm tin chắc chắn của người nói.",
      "Xem nghĩa わけがない ở slide 1."),
    q(L, 2, "「数学が得意なわけではありません」 nghĩa là:",
      ["Không phải là (anh ấy) giỏi toán hoàn toàn (có thể chỉ tạm ổn)",
       "Anh ấy hoàn toàn không biết gì về toán", "Anh ấy rất giỏi toán",
       "Câu này không có nghĩa rõ ràng"], 0,
      "わけではない chỉ phủ định MỘT PHẦN nhận định, không phủ định hoàn toàn — 'không hẳn là'.",
      "So sánh với わけがない (phủ định toàn bộ)."),
    q(L, 3, "わけがない và わけではない khác nhau chủ yếu ở:",
      ["わけがない phủ định TOÀN BỘ, mạnh mẽ; わけではない phủ định MỘT PHẦN, nhẹ nhàng",
       "Hoàn toàn giống nhau", "わけがない chỉ dùng cho câu hỏi",
       "わけではない chỉ dùng cho phủ định kép"], 0,
      "Đây là điểm khác biệt cốt lõi của bài học — mức độ và phạm vi phủ định khác nhau.",
      "Xem so sánh trực tiếp ở slide 3."),
    q(L, 4, "「日本語が上達しました。でも、自信があるわけではありません」 — cấu trúc này dùng để:",
      ["Công nhận một điều tốt rồi ngay lập tức khiêm tốn, giới hạn lại nhận định đó",
       "Phủ định hoàn toàn việc đã tiến bộ", "Khẳng định chắc chắn có tự tin",
       "Không có mục đích gì đặc biệt"], 0,
      "Đây là mẫu khiêm tốn kiểu Nhật: khen bản thân một chút rồi dùng わけではありません để giảm nhẹ.",
      "Xem ví dụ và ghi chú văn hóa ở slide 4."),
    q(L, 5, "「彼がこの記録を破ったわけがない」 — わけがない ở đây dựa trên điều gì?",
      ["Niềm tin/kinh nghiệm CHỦ QUAN của người nói (biết anh ấy kém thể thao)",
       "Một quy tắc khách quan, khoa học đã được chứng minh", "Không dựa trên điều gì cả",
       "Lời của người khác kể lại"], 0,
      "わけがない mang tính CHỦ QUAN, dựa trên hiểu biết/niềm tin cá nhân — khác はずがない khách quan hơn (học ở N2).",
      "Xem ghi chú so sánh ở slide 1."),
    q(L, 6, "「みんなが賛成したわけではありません」 nghĩa là:",
      ["Không phải TẤT CẢ mọi người đều tán thành (một số phản đối)",
       "Không ai tán thành cả", "Tất cả mọi người đều tán thành",
       "Không rõ ai tán thành"], 0,
      "わけではない phủ định TOÀN THỂ tính (all), ngụ ý có ngoại lệ — không phải 100% đồng ý.",
      "Áp dụng đúng nghĩa わけではない cho câu có 'みんな' (tất cả)."),
    q(L, 7, "Câu nào SAI khi ghép わけがない với tính từ な/danh từ?",
      ["専門わけがない (thiếu な)", "専門なわけがない (đúng)",
       "偶然なわけがない (đúng)", "得意なわけがない (đúng)"], 0,
      "Tính từ な/danh từ cần thêm な trước わけがない: 専門 → 専門な わけがない.",
      "Xem công thức chia ở slide 1."),
    q(L, 8, "「確かに、専門の選手に勝ったわけではありません」 — 確かに có vai trò gì?",
      ["Công nhận một phần đúng trước khi đưa ra điều chỉnh bằng わけではありません",
       "Phủ định hoàn toàn câu trước đó", "Biến câu thành câu hỏi",
       "Không có vai trò gì đặc biệt"], 0,
      "確かに (đúng là) thường mở đầu câu có わけではありません để công nhận một phần rồi làm rõ giới hạn.",
      "Xem cách dùng trong hội thoại."),
    q(L, 9, "Trong hội thoại, vì sao Santos ban đầu không tin Yamada phá kỷ lục?",
      ["Vì biết Yamada kém thể thao", "Vì không thích Yamada",
       "Vì kỷ lục đó rất khó phá", "Không có lý do cụ thể"], 0,
      "Santos nói 「山田さんはスポーツが苦手です」.",
      "Xem câu thoại thứ 2."),
    q(L, 10, "Cuối cùng, Yamada nói gì về sự tiến bộ của mình?",
      ["Không phải là đã có sự tự tin", "Đã rất tự tin", "Không hề tiến bộ", "Không nói gì cả"], 0,
      "Tanaka thuật lại lời Yamada: 「自信があるわけではないと言っていました」.",
      "Xem câu thoại thứ 9."),
]

LESSON = lesson(
    L,
    "Bài 1: Phán đoán chắc chắn (わけがない & わけではない)",
    "Bài mở đầu N3: わけがない diễn tả phủ định MẠNH MẼ, chủ quan ('không đời nào', dựa trên niềm "
    "tin/kinh nghiệm cá nhân — khác はずがない khách quan hơn ở N2), và わけではない diễn tả phủ "
    "định MỘT PHẦN, nhẹ nhàng ('không hẳn là', thường dùng đính chính hiểu lầm, đi kèm でも/しかし).",
    VOCAB, KANJI, SLIDES, DIALOGUE, EXERCISES,
)

if __name__ == "__main__":
    pool.mark_used([w["word"] for w in VOCAB if w["word"]], lesson=L)
    merge([LESSON])
