# -*- coding: utf-8 -*-
"""N3 — Bai 20 (chot): Tong ket ngu phap N3 qua doi thoai hop tong ket du an - ket hop cac cau
truc da hoc: okagede/seide (b4), ippouda/bakarida (b14), ni chigainai/hazuda (b12), bekida (b19),
nimokakawarazu/kuseni (b10), dakedenaku/bakarika (b15), ni kanshite/ni tsuite (b17), to iu koto (b18).

Tu vung minh hoa TU CHON tu pool mo data/jlpt-vocab/n3.csv (xem NOTICE.md).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from n3_lib import v, k, t, ex, slide, line, q, lesson, merge
from jlpt_pool import Pool

L = 20
pool = Pool("n3")

VOCAB = [
    v(1,  "かいぜんします", "改善します", "かいぜんします", "kaizen shimasu", "verb", "Cải thiện", "じょうきょうを 改善します = cải thiện tình huống.", L),
    v(2,  "はんせいします", "反省します", "はんせいします", "hansei shimasu", "verb", "Rút kinh nghiệm, phản tỉnh", "しっぱいを 反省します = rút kinh nghiệm từ thất bại.", L),
    v(3,  "ひょうかします", "評価します", "ひょうかします", "hyouka shimasu", "verb", "Đánh giá", "けっかを 評価します = đánh giá kết quả.", L),
    v(4,  "もくひょう", "目標", "もくひょう", "mokuhyou", "noun", "Mục tiêu", "目標を たてます = lập mục tiêu.", L),
    v(5,  "チーム", "チーム", "チーム", "chiimu", "noun", "Đội nhóm", "チームの 努力 = nỗ lực của đội nhóm.", L),
    v(6,  "どりょく", "努力", "どりょく", "doryoku", "noun", "Nỗ lực", "Đã gặp N3 bài 8.", L),
    v(7,  "じゅんび", "準備", "じゅんび", "junbi", "noun", "Sự chuẩn bị", "Đã gặp N4 bài 26.", L),
    v(8,  "けっか", "結果", "けっか", "kekka", "noun", "Kết quả", "Đã gặp N4 bài 39.", L),
    v(9,  "かいぎ", "会議", "かいぎ", "kaigi", "noun", "Cuộc họp", "Đã gặp N4 bài 30.", L),
    v(10, "せきにん", "責任", "せきにん", "sekinin", "noun", "Trách nhiệm", "Đã gặp N3 bài 19.", L),
    v(11, "きそく", "規則", "きそく", "kisoku", "noun", "Quy tắc", "Đã gặp N4 bài 33.", L),
    v(12, "じょうきょう", "状況", "じょうきょう", "joukyou", "noun", "Tình huống", "Đã gặp N3 bài 13.", L),
    v(13, "もんだい", "問題", "もんだい", "mondai", "noun", "Vấn đề", "Đã gặp N5 bài 22.", L),
    v(14, "せいこうします", "成功します", "せいこうします", "seikou shimasu", "verb", "Thành công", "Đã gặp N3 bài 8.", L),
    v(15, "しっぱいします", "失敗します", "しっぱいします", "shippai shimasu", "verb", "Thất bại", "Đã gặp N4 bài 43.", L),
    v(16, "けいかく", "計画", "けいかく", "keikaku", "noun", "Kế hoạch", "Đã gặp N4 bài 26.", L),
    v(17, "らいねん", "来年", "らいねん", "rainen", "noun", "Năm sau", "Đã gặp N4 bài 26.", L),
    v(18, "かいしゃ", "会社", "かいしゃ", "kaisha", "noun", "Công ty", "Đã gặp N4 bài 26.", L),
    v(19, "みんな", "みんな", "みんな", "minna", "pronoun", "Mọi người", "Đã gặp N4 bài 26.", L),
    v(20, "はなします", "話します", "はなします", "hanashimasu", "verb", "Nói chuyện", "Đã gặp N4 bài 26.", L),
]

KANJI = [
    k(1, "改", "CẢI", 7, ["カイ (kai)"], ["あらた(める)"], "Sửa đổi, cải thiện.",
      [("改善", "かいぜん", "Cải thiện"), ("改める", "あらためる", "Sửa đổi")], L),
    k(2, "善", "THIỆN", 12, ["ゼン (zen)"], ["よ(い)"], "Tốt đẹp, thiện lương.",
      [("改善", "かいぜん", "Cải thiện"), ("善悪", "ぜんあく", "Thiện ác")], L),
    k(3, "反", "PHẢN", 4, ["ハン (han)"], ["そ(る)"], "Trái ngược, phản đối.",
      [("反省", "はんせい", "Rút kinh nghiệm"), ("反対", "はんたい", "Phản đối")], L),
    k(4, "省", "TỈNH", 9, ["セイ (sei)", "ショウ (shou)"], ["はぶ(く)"], "Suy xét, tiết kiệm.",
      [("反省", "はんせい", "Rút kinh nghiệm"), ("省略", "しょうりゃく", "Lược bỏ")], L),
    k(5, "標", "TIÊU", 15, ["ヒョウ (hyou)"], [], "Mục tiêu, dấu hiệu.",
      [("目標", "もくひょう", "Mục tiêu"), ("標準", "ひょうじゅん", "Tiêu chuẩn")], L),
]

SLIDES = [
    slide(L, 1,
        "1. Ôn tập: Nguyên nhân + Xu hướng (おかげで/せいで + 一方だ/ばかりだ)",
        "N/[thể thường]+おかげで/せいで、[kết quả]+一方だ/ばかりだ",
        "Khi tổng kết một dự án, ta thường nêu NGUYÊN NHÂN (おかげで cho kết quả tích cực, せいで "
        "cho kết quả tiêu cực — đã học ở bài 4) dẫn đến một XU HƯỚNG LIÊN TỤC (一方だ/ばかりだ — bài 14).",
        [
            ex(L, 1, 1, [t("t-l20s1-1", "チーム", "チーム", "チーム", key=True), t("t-l20s1-2", "の"),
                         t("t-l20s1-3", "どりょく", "努力", "どりょく", key=True), t("t-l20s1-4", "の"),
                         t("t-l20s1-5", "おかげで", key=True), t("t-l20s1-6", "、"), t("t-l20s1-7", "けっか", "結果", "けっか", key=True),
                         t("t-l20s1-8", "は"), t("t-l20s1-9", "よく", "良く", "よく"), t("t-l20s1-10", "なる"),
                         t("t-l20s1-11", "いっぽう", "一方", "いっぽう", key=True), t("t-l20s1-12", "です")],
               "Nhờ nỗ lực của đội, kết quả chỉ ngày càng tốt lên."),
            ex(L, 1, 2, [t("t-l20s1-13", "じゅんび", "準備", "じゅんび", key=True), t("t-l20s1-14", "ぶそく", "不足", "ぶそく"),
                         t("t-l20s1-15", "の"), t("t-l20s1-16", "せいで", key=True), t("t-l20s1-17", "、"),
                         t("t-l20s1-18", "もんだい", "問題", "もんだい", key=True), t("t-l20s1-19", "が"),
                         t("t-l20s1-20", "ふえる", "増える", "ふえる"), t("t-l20s1-21", "ばかり", key=True), t("t-l20s1-22", "です")],
               "Vì thiếu chuẩn bị, vấn đề chỉ ngày càng tăng thôi."),
        ],
        tips="Ôn nhanh: おかげで=nguyên nhân TÍCH CỰC, せいで=nguyên nhân TIÊU CỰC (bài 4) — kết hợp 一方だ (trang trọng) hoặc ばかりだ (thân mật, thất vọng) từ bài 14.",
        culture="Báo cáo tổng kết công ty Nhật luôn mở đầu bằng nguyên nhân rồi mới nêu xu hướng kết quả — đây là cấu trúc lập luận chuẩn mực."),

    slide(L, 2,
        "2. Ôn tập: Suy đoán + Nghĩa vụ (に違いない/はずだ + べきだ)",
        "[suy đoán]に違いない/はずだ。だから、[khuyến nghị]べきだ",
        "Sau khi SUY LUẬN về nguyên nhân/tình huống dựa trên bằng chứng (に違いない) hoặc logic "
        "(はずだ — bài 12), ta thường đưa ra NGHĨA VỤ/KHUYẾN NGHỊ (べきだ — bài 19) để giải quyết vấn đề.",
        [
            ex(L, 2, 1, [t("t-l20s2-1", "げんいん", "原因", "げんいん"), t("t-l20s2-2", "は"),
                         t("t-l20s2-3", "じゅんび", "準備", "じゅんび", key=True), t("t-l20s2-4", "ぶそく", "不足", "ぶそく"),
                         t("t-l20s2-5", "に"), t("t-l20s2-6", "ちがいない", "違いない", "ちがいない", key=True), t("t-l20s2-7", "。"),
                         t("t-l20s2-8", "だから"), t("t-l20s2-9", "、"), t("t-l20s2-10", "もっと"),
                         t("t-l20s2-11", "けいかく", "計画", "けいかく", key=True), t("t-l20s2-12", "を"),
                         t("t-l20s2-13", "たてる", "立てる", "たてる"), t("t-l20s2-14", "べき", key=True), t("t-l20s2-15", "だ")],
               "Nguyên nhân chắc chắn là thiếu chuẩn bị. Vì vậy, nên lập kế hoạch kỹ hơn."),
            ex(L, 2, 2, [t("t-l20s2-16", "らいねん", "来年", "らいねん", key=True), t("t-l20s2-17", "は"),
                         t("t-l20s2-18", "せいこう", "成功", "せいこう", key=True), t("t-l20s2-19", "する"),
                         t("t-l20s2-20", "はず", key=True), t("t-l20s2-21", "です"), t("t-l20s2-22", "。"),
                         t("t-l20s2-23", "でも"), t("t-l20s2-24", "、"), t("t-l20s2-25", "みんな", "みんな", "みんな"),
                         t("t-l20s2-26", "が"), t("t-l20s2-27", "せきにん", "責任", "せきにん", key=True), t("t-l20s2-28", "を"),
                         t("t-l20s2-29", "もつ", "持つ", "もつ"), t("t-l20s2-30", "べき", key=True), t("t-l20s2-31", "です")],
               "Năm sau lẽ ra sẽ thành công. Nhưng mọi người nên có trách nhiệm."),
        ],
        tips="Ôn nhanh: に違いない=chắc chắn từ BẰNG CHỨNG, はずだ=lẽ ra từ LOGIC (bài 12) — cả hai làm tiền đề hợp lý trước khi đưa ra べきだ (bài 19).",
        culture="Cấu trúc 'suy luận nguyên nhân → đề xuất hành động' là khung sườn chuẩn của mọi buổi họp rút kinh nghiệm (反省会) ở công ty Nhật."),

    slide(L, 3,
        "3. Ôn tập: Nhượng bộ + Mở rộng (にもかかわらず/くせに + だけでなく/ばかりか)",
        "[khó khăn]にもかかわらず、[thành quả]だけでなく/ばかりか、[thêm nữa]",
        "Khi khen ngợi một thành tích VƯỢT QUA KHÓ KHĂN, thường kết hợp にもかかわらず (mặc dù "
        "khó khăn khách quan — bài 10) với だけでなく/ばかりか (không chỉ đạt X mà còn đạt Y — bài 15) để nhấn mạnh sự nỗ lực vượt trội.",
        [
            ex(L, 3, 1, [t("t-l20s3-1", "じかん", "時間", "じかん"), t("t-l20s3-2", "が"),
                         t("t-l20s3-3", "たりない", "足りない", "たりない"), t("t-l20s3-4", "にも", key=True),
                         t("t-l20s3-5", "かかわらず", key=True), t("t-l20s3-6", "、"), t("t-l20s3-7", "けっか", "結果", "けっか", key=True),
                         t("t-l20s3-8", "は"), t("t-l20s3-9", "よかった"), t("t-l20s3-10", "ばかりか", key=True),
                         t("t-l20s3-11", "、"), t("t-l20s3-12", "ひょうか", "評価", "ひょうか", key=True), t("t-l20s3-13", "も"),
                         t("t-l20s3-14", "たかかった", "高かった", "たかかった"), t("t-l20s3-15", "です")],
               "Mặc dù thiếu thời gian, kết quả không những tốt mà đánh giá còn cao."),
            ex(L, 3, 2, [t("t-l20s3-16", "もんだい", "問題", "もんだい", key=True), t("t-l20s3-17", "が"),
                         t("t-l20s3-18", "おおい", "多い", "おおい"), t("t-l20s3-19", "にも", key=True),
                         t("t-l20s3-20", "かかわらず", key=True), t("t-l20s3-21", "、"), t("t-l20s3-22", "じょうきょう", "状況", "じょうきょう", key=True),
                         t("t-l20s3-23", "を"), t("t-l20s3-24", "かいぜん", "改善", "かいぜん", key=True), t("t-l20s3-25", "しました")],
               "Mặc dù có nhiều vấn đề, đã cải thiện được tình huống."),
        ],
        tips="Ôn nhanh: にもかかわらず=khách quan, KHÔNG chê trách (bài 10, khác くせに mang tính chê trách) — kết hợp だけでなく (trung tính) hoặc ばかりか (nhấn mạnh, ngạc nhiên) từ bài 15.",
        culture="Bài phát biểu khen thưởng cuối năm ở công ty Nhật hay dùng cấu trúc này để vinh danh nỗ lực vượt khó của nhân viên."),

    slide(L, 4,
        "4. Ôn tập: Chủ đề + Truyền đạt (に関して/について + ということ)",
        "[chủ đề]について/に関して、[nội dung]ということだ/ということになる",
        "Khi TRÌNH BÀY/BÁO CÁO về một CHỦ ĐỀ cụ thể (について thân mật/に関して trang trọng — bài "
        "17), thường kết thúc bằng cách TRUYỀN ĐẠT kết luận đã thống nhất (ということ — bài 18) — cấu trúc chuẩn của báo cáo N3.",
        [
            ex(L, 4, 1, [t("t-l20s4-1", "この"), t("t-l20s4-2", "プロジェクト", "プロジェクト", "プロジェクト"), t("t-l20s4-3", "に"),
                         t("t-l20s4-4", "かんして", "関して", "かんして", key=True), t("t-l20s4-5", "、"),
                         t("t-l20s4-6", "らいねん", "来年", "らいねん", key=True), t("t-l20s4-7", "も"),
                         t("t-l20s4-8", "つづける", "続ける", "つづける"), t("t-l20s4-9", "という", key=True),
                         t("t-l20s4-10", "こと", "事", "こと", key=True), t("t-l20s4-11", "に"), t("t-l20s4-12", "なりました", "成りました", "なりました")],
               "Về dự án này, đã được quyết định là sẽ tiếp tục vào năm sau."),
            ex(L, 4, 2, [t("t-l20s4-13", "かいぜん", "改善", "かいぜん", key=True), t("t-l20s4-14", "に"),
                         t("t-l20s4-15", "ついて", key=True), t("t-l20s4-16", "、"), t("t-l20s4-17", "かいぎ", "会議", "かいぎ", key=True),
                         t("t-l20s4-18", "で"), t("t-l20s4-19", "はなしあう", "話し合う", "はなしあう"), t("t-l20s4-20", "という", key=True),
                         t("t-l20s4-21", "こと", "事", "こと", key=True), t("t-l20s4-22", "だ")],
               "Nghe nói sẽ thảo luận về việc cải thiện tại cuộc họp."),
        ],
        tips="Ôn nhanh: について/に関して nêu CHỦ ĐỀ (bài 17) → ということだ TRUYỀN TIN, ということになる KẾT LUẬN khách quan (bài 18) — khung câu chuẩn của mọi bản báo cáo.",
        culture="Đây là 4 nhóm ngữ pháp N3 cốt lõi thường xuất hiện lồng ghép trong đề đọc hiểu JLPT N3 — nắm vững cách KẾT HỢP chúng quan trọng hơn học thuộc riêng lẻ."),
]

DIALOGUE = [
    line(L, 1, "田中", "Trưởng nhóm dự án",
         [t("d20-1", "きょう", "今日", "きょう"), t("d20-2", "の"), t("d20-3", "かいぎ", "会議", "かいぎ", key=True),
          t("d20-4", "は"), t("d20-5", "プロジェクト", "プロジェクト", "プロジェクト"), t("d20-6", "の"),
          t("d20-7", "はんせい", "反省", "はんせい", key=True), t("d20-8", "です")],
         "Cuộc họp hôm nay là để rút kinh nghiệm dự án."),
    line(L, 2, "サントス", "Thành viên nhóm",
         [t("d20-9", "チーム", "チーム", "チーム", key=True), t("d20-10", "の"), t("d20-11", "どりょく", "努力", "どりょく", key=True),
          t("d20-12", "の"), t("d20-13", "おかげで", key=True), t("d20-14", "、"), t("d20-15", "けっか", "結果", "けっか", key=True),
          t("d20-16", "は"), t("d20-17", "よく", "良く", "よく"), t("d20-18", "なる"), t("d20-19", "いっぽう", "一方", "いっぽう", key=True),
          t("d20-20", "です")],
         "Nhờ nỗ lực của đội, kết quả chỉ ngày càng tốt lên."),
    line(L, 3, "田中", "Trưởng nhóm dự án",
         [t("d20-21", "でも"), t("d20-22", "、"), t("d20-23", "じゅんび", "準備", "じゅんび", key=True),
          t("d20-24", "ぶそく", "不足", "ぶそく"), t("d20-25", "の"), t("d20-26", "せいで", key=True),
          t("d20-27", "、"), t("d20-28", "もんだい", "問題", "もんだい", key=True), t("d20-29", "も"),
          t("d20-30", "ふえる", "増える", "ふえる"), t("d20-31", "ばかり", key=True), t("d20-32", "でした")],
         "Nhưng vì thiếu chuẩn bị, vấn đề cũng chỉ ngày càng tăng thôi."),
    line(L, 4, "サントス", "Thành viên nhóm",
         [t("d20-33", "げんいん", "原因", "げんいん"), t("d20-34", "は"), t("d20-35", "けいかく", "計画", "けいかく", key=True),
          t("d20-36", "ぶそく", "不足", "ぶそく"), t("d20-37", "に"), t("d20-38", "ちがいありません", "違いありません", "ちがいありません", key=True)],
         "Nguyên nhân chắc chắn là do thiếu kế hoạch."),
    line(L, 5, "田中", "Trưởng nhóm dự án",
         [t("d20-39", "だから"), t("d20-40", "、"), t("d20-41", "みんな", "みんな", "みんな", key=True),
          t("d20-42", "が"), t("d20-43", "せきにん", "責任", "せきにん", key=True), t("d20-44", "を"),
          t("d20-45", "もつ", "持つ", "もつ"), t("d20-46", "べき", key=True), t("d20-47", "です")],
         "Vì vậy, mọi người nên có trách nhiệm."),
    line(L, 6, "サントス", "Thành viên nhóm",
         [t("d20-48", "じかん", "時間", "じかん"), t("d20-49", "が"), t("d20-50", "たりない", "足りない", "たりない"),
          t("d20-51", "にも", key=True), t("d20-52", "かかわらず", key=True), t("d20-53", "、"),
          t("d20-54", "ひょうか", "評価", "ひょうか", key=True), t("d20-55", "は"), t("d20-56", "たかかった", "高かった", "たかかった"),
          t("d20-57", "ばかりか", key=True), t("d20-58", "、"), t("d20-59", "みんな", "みんな", "みんな"), t("d20-60", "も"),
          t("d20-61", "よろこびました", "喜びました", "よろこびました")],
         "Mặc dù thiếu thời gian, đánh giá không những cao mà mọi người còn vui mừng."),
    line(L, 7, "田中", "Trưởng nhóm dự án",
         [t("d20-62", "きそく", "規則", "きそく", key=True), t("d20-63", "に", key=True), t("d20-64", "ついて", key=True),
          t("d20-65", "も"), t("d20-66", "かいぜん", "改善", "かいぜん", key=True), t("d20-67", "する"),
          t("d20-68", "べき", key=True), t("d20-69", "です", "です", "です"), t("d20-70", "ね")],
         "Về quy tắc, cũng nên cải thiện nhỉ."),
    line(L, 8, "サントス", "Thành viên nhóm",
         [t("d20-73", "はい"), t("d20-74", "。"), t("d20-75", "らいねん", "来年", "らいねん", key=True),
          t("d20-76", "も"), t("d20-77", "この"), t("d20-78", "プロジェクト", "プロジェクト", "プロジェクト"), t("d20-79", "を"),
          t("d20-80", "つづける", "続ける", "つづける"), t("d20-81", "という", key=True), t("d20-82", "こと", "事", "こと", key=True),
          t("d20-83", "に"), t("d20-84", "なりました", "成りました", "なりました")],
         "Vâng. Năm sau đã được quyết định là sẽ tiếp tục dự án này."),
    line(L, 9, "田中", "Trưởng nhóm dự án",
         [t("d20-85", "じゃあ"), t("d20-86", "、"), t("d20-87", "かいぜん", "改善", "かいぜん", key=True),
          t("d20-88", "に", key=True), t("d20-89", "ついて", key=True), t("d20-90", "、"),
          t("d20-91", "つぎ", "次", "つぎ"), t("d20-92", "の"), t("d20-93", "かいぎ", "会議", "かいぎ", key=True),
          t("d20-94", "で"), t("d20-95", "はなしあいましょう", "話し合いましょう", "はなしあいましょう")],
         "Vậy thì, về việc cải thiện, hãy cùng thảo luận ở cuộc họp tiếp theo."),
    line(L, 10, "サントス", "Thành viên nhóm",
         [t("d20-96", "はい"), t("d20-97", "、"), t("d20-98", "わかりました", "分かりました", "わかりました"),
          t("d20-99", "。"), t("d20-100", "らいねん", "来年", "らいねん", key=True), t("d20-101", "は"),
          t("d20-102", "もっと"), t("d20-103", "せいこう", "成功", "せいこう", key=True), t("d20-104", "する"),
          t("d20-105", "はず", key=True), t("d20-106", "です")],
         "Vâng, đã hiểu rồi. Năm sau lẽ ra sẽ thành công hơn nữa."),
]

EXERCISES = [
    q(L, 1, "「チームの努力のおかげで、結果は良くなる一方です」 — kết hợp hai cấu trúc nào?",
      ["おかげで (nguyên nhân tích cực, bài 4) + 一方だ (xu hướng liên tục, bài 14)",
       "せいで (nguyên nhân tiêu cực) + ばかりだ", "べきだ + はずだ",
       "について + ということ"], 0,
      "Câu này kết hợp おかげで (nguyên nhân TÍCH CỰC) với 一方だ (xu hướng liên tục, khách quan).",
      "Xem slide 1 về ôn tập おかげで/せいで + 一方だ/ばかりだ."),
    q(L, 2, "「原因は計画不足に違いありません。だから、責任を持つべきです」 — trình tự lập luận ở đây là gì?",
      ["Suy đoán nguyên nhân bằng bằng chứng (に違いない) → đưa ra khuyến nghị (べきだ)",
       "Truyền đạt tin nghe được → giải thích ý nghĩa", "So sánh hai sự việc → kết luận",
       "Phủ định hoàn toàn → xin lỗi"], 0,
      "Câu này theo trình tự: suy đoán nguyên nhân chắc chắn (に違いない) rồi đưa ra nghĩa vụ/khuyến nghị (べきだ).",
      "Xem slide 2 về ôn tập に違いない/はずだ + べきだ."),
    q(L, 3, "「時間が足りないにもかかわらず、評価は高かったばかりか、みんなも喜びました」 — にもかかわらず và ばかりか kết hợp để làm gì?",
      ["Nhấn mạnh thành tích VƯỢT QUA khó khăn khách quan một cách ấn tượng",
       "Phủ định hoàn toàn thành tích đạt được", "Chê trách người khác về khó khăn",
       "So sánh hai dự án khác nhau"], 0,
      "にもかかわらず nêu khó khăn khách quan, ばかりか nhấn mạnh thành tích vượt xa kỳ vọng — kết hợp để khen ngợi nỗ lực vượt khó.",
      "Xem slide 3 về ôn tập にもかかわらず/くせに + だけでなく/ばかりか."),
    q(L, 4, "「このプロジェクトに関して、来年も続けるということになりました」 — kết hợp hai cấu trúc nào?",
      ["に関して (nêu chủ đề, bài 17) + ということになる (kết luận khách quan, bài 18)",
       "について + べきだ", "おかげで + はずだ", "にもかかわらず + について"], 0,
      "Câu này nêu chủ đề (このプロジェクトに関して) rồi truyền đạt kết luận đã được quyết định (ということになりました).",
      "Xem slide 4 về ôn tập に関して/について + ということ."),
    q(L, 5, "Tại sao dùng にもかかわらず mà không dùng くせに trong câu khen ngợi thành tích đội nhóm?",
      ["Vì にもかかわらず khách quan, không chê trách; くせに luôn mang sắc thái chê trách (bài 10)",
       "Vì cả hai hoàn toàn giống nhau", "Vì くせに chỉ dùng cho câu hỏi",
       "Vì にもかかわらず chỉ dùng cho phủ định"], 0,
      "くせに luôn ẩn chứa sắc thái CHÊ TRÁCH — không phù hợp để khen ngợi; にもかかわらず khách quan, phù hợp hơn.",
      "Ôn lại bài 10 về にもかかわらず vs くせに."),
    q(L, 6, "「準備不足のせいで、問題も増えるばかりでした」 — せいで khác おかげで ở điểm nào?",
      ["せいで dùng cho nguyên nhân dẫn đến kết quả TIÊU CỰC; おかげで dùng cho kết quả TÍCH CỰC",
       "Hoàn toàn giống nhau, dùng thay thế được", "せいで chỉ dùng cho câu hỏi",
       "おかげで chỉ dùng cho phủ định"], 0,
      "せいで luôn đi với kết quả TIÊU CỰC (vấn đề tăng); おかげで đi với kết quả TÍCH CỰC — đây là ôn lại bài 4.",
      "Ôn lại bài 4 về おかげで/せいで."),
    q(L, 7, "「来年はもっと成功するはずです」 — はずだ ở đây dựa trên căn cứ gì?",
      ["Suy luận LOGIC dựa trên tình hình đã cải thiện (khách quan hơn linh cảm)",
       "Bằng chứng cụ thể không thể chối cãi", "Cảm xúc mãnh liệt của người nói",
       "Sự chê trách đối với đội nhóm"], 0,
      "はずだ (khác に違いない) dựa trên suy luận LOGIC từ thông tin đã biết (đã cải thiện quy tắc, kế hoạch) — ôn lại bài 12.",
      "Ôn lại bài 12 về に違いない vs はずだ."),
    q(L, 8, "Theo hội thoại, nguyên nhân của vấn đề trong dự án là gì?",
      ["Thiếu kế hoạch (計画不足に違いありません)", "Thiếu tiền", "Thiếu nhân sự",
       "Không được đề cập trong hội thoại"], 0,
      "Santos nói 「原因は計画不足に違いありません」.",
      "Xem câu thoại thứ 4."),
    q(L, 9, "Dự án có được tiếp tục vào năm sau không?",
      ["Có, đã quyết định tiếp tục (来年も続けるということになりました)",
       "Không, dự án đã bị hủy", "Chưa quyết định được", "Không được đề cập trong hội thoại"], 0,
      "Santos nói 「来年もこのプロジェクトを続けるということになりました」.",
      "Xem câu thoại thứ 8."),
    q(L, 10, "Điều gì sẽ được thảo luận ở cuộc họp tiếp theo?",
      ["Việc cải thiện (改善について、次の会議で話し合いましょう)",
       "Việc tuyển nhân viên mới", "Việc đóng cửa công ty",
       "Không có gì để thảo luận thêm"], 0,
      "田中 nói 「改善について、次の会議で話し合いましょう」.",
      "Xem câu thoại thứ 9."),
]

LESSON = lesson(
    L,
    "Bài 20: Tổng kết ngữ pháp đàm thoại thực chiến",
    "Bài tổng kết N3 kết hợp các cấu trúc trọng điểm đã học qua một cuộc họp rút kinh nghiệm dự "
    "án thực tế: おかげで/せいで + 一方だ/ばかりだ (nguyên nhân → xu hướng), に違いない/はずだ + べき"
    "だ (suy đoán → khuyến nghị), にもかかわらず + だけでなく/ばかりか (nhượng bộ → mở rộng thành "
    "tích), và に関して/について + ということ (chủ đề → truyền đạt kết luận) — nắm vững cách KẾT "
    "HỢP các cấu trúc này quan trọng hơn học thuộc riêng lẻ, đúng như cách chúng xuất hiện trong "
    "đề thi JLPT N3 thực tế. Hoàn thành trọn vẹn 20/20 bài N3!",
    VOCAB, KANJI, SLIDES, DIALOGUE, EXERCISES,
)

if __name__ == "__main__":
    pool.mark_used([w["word"] for w in VOCAB if w["word"]], lesson=L)
    merge([LESSON])
