# -*- coding: utf-8 -*-
"""N3 — Bai 18: Truyen dat thong tin chinh thuc ということだ (nghe noi, trang trong), giai thich
ということは, va ket luan logic ということになる.

Tu vung minh hoa TU CHON tu pool mo data/jlpt-vocab/n3.csv (xem NOTICE.md).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from n3_lib import v, k, t, ex, slide, line, q, lesson, merge
from jlpt_pool import Pool

L = 18
pool = Pool("n3")

VOCAB = [
    v(1,  "しらせ", "知らせ", "しらせ", "shirase", "noun", "Tin báo, thông báo", "会社から 知らせが あります = có thông báo từ công ty.", L),
    v(2,  "えんきします", "延期します", "えんきします", "enki shimasu", "verb", "Hoãn lại", "会議を 延期します = hoãn cuộc họp.", L),
    v(3,  "けっていします", "決定します", "けっていします", "kettei shimasu", "verb", "Quyết định", "計画を 決定します = quyết định kế hoạch.", L),
    v(4,  "へんこうします", "変更します", "へんこうします", "henkou shimasu", "verb", "Thay đổi", "予定を 変更します = thay đổi lịch trình.", L),
    v(5,  "しょうにんします", "承認します", "しょうにんします", "shounin shimasu", "verb", "Phê duyệt, chấp thuận", "計画を 承認します = phê duyệt kế hoạch.", L),
    v(6,  "めいれいします", "命令します", "めいれいします", "meirei shimasu", "verb", "Ra lệnh", "社長が 命令します = giám đốc ra lệnh.", L),
    v(7,  "ちゅうし", "中止", "ちゅうし", "chuushi", "noun", "Hủy bỏ", "Đã gặp N3 bài 10.", L),
    v(8,  "かいぎ", "会議", "かいぎ", "kaigi", "noun", "Cuộc họp", "Đã gặp N4 bài 30.", L),
    v(9,  "けいかく", "計画", "けいかく", "keikaku", "noun", "Kế hoạch", "Đã gặp N4 bài 26.", L),
    v(10, "じゅんび", "準備", "じゅんび", "junbi", "noun", "Sự chuẩn bị", "Đã gặp N4 bài 26.", L),
    v(11, "ひつよう", "必要", "ひつよう", "hitsuyou", "adjective", "Cần thiết", "Đã gặp N5 bài 22.", L),
    v(12, "おわります", "終わります", "おわります", "owarimasu", "verb", "Kết thúc", "Đã gặp N4 bài 26.", L),
    v(13, "しゃちょう", "社長", "しゃちょう", "shachou", "noun", "Giám đốc", "Đã gặp N4 bài 41.", L),
    v(14, "らいしゅう", "来週", "らいしゅう", "raishuu", "noun", "Tuần sau", "Đã gặp N4 bài 26.", L),
    v(15, "きょう", "今日", "きょう", "kyou", "noun", "Hôm nay", "Đã gặp N5 bài 1.", L),
    v(16, "でんわ", "電話", "でんわ", "denwa", "noun", "Điện thoại", "Đã gặp N4 bài 34.", L),
    v(17, "れんらくします", "連絡します", "れんらくします", "renraku shimasu", "verb", "Liên lạc", "Đã gặp N4 bài 41.", L),
    v(18, "きまります", "決まります", "きまります", "kimarimasu", "verb", "Được quyết định", "Đã gặp N4 bài 33.", L),
    v(19, "まだ", "まだ", "まだ", "mada", "adverb", "Vẫn chưa", "Đã gặp N4 bài 26.", L),
    v(20, "もんだい", "問題", "もんだい", "mondai", "noun", "Vấn đề", "Đã gặp N5 bài 22.", L),
]

KANJI = [
    k(1, "承", "THỪA", 8, ["ショウ (shou)"], ["うけたまわ(る)"], "Vâng theo, thừa nhận.",
      [("承認", "しょうにん", "Phê duyệt"), ("了承", "りょうしょう", "Đồng ý, chấp thuận")], L),
    k(2, "認", "NHẬN", 14, ["ニン (nin)"], ["みと(める)"], "Nhận biết, công nhận.",
      [("承認", "しょうにん", "Phê duyệt"), ("確認", "かくにん", "Xác nhận")], L),
    k(3, "命", "MỆNH", 8, ["メイ (mei)"], ["いのち"], "Mệnh lệnh, sinh mệnh.",
      [("命令", "めいれい", "Ra lệnh"), ("命", "いのち", "Sinh mệnh")], L),
    k(4, "令", "LỆNH", 5, ["レイ (rei)"], [], "Lệnh, mệnh lệnh.",
      [("命令", "めいれい", "Ra lệnh"), ("法令", "ほうれい", "Pháp lệnh")], L),
    k(5, "延", "DIÊN", 8, ["エン (en)"], ["の(びる)"], "Kéo dài, trì hoãn.",
      [("延期", "えんき", "Hoãn lại"), ("延長", "えんちょう", "Kéo dài, gia hạn")], L),
]

SLIDES = [
    slide(L, 1,
        "1. Truyền đạt thông tin (trang trọng): [thể thường] ということだ",
        "[Thể thường] + ということだ",
        "ということだ dùng để TRUYỀN ĐẠT một thông tin đã nghe/đọc được một cách TRANG TRỌNG, "
        "KHÁCH QUAN — thường thấy trong thông báo chính thức, tin tức, văn bản hành chính, đáng tin cậy hơn そうだ đời thường.",
        [
            ex(L, 1, 1, [t("t-l18s1-1", "かいぎ", "会議", "かいぎ", key=True), t("t-l18s1-2", "は"),
                         t("t-l18s1-3", "えんき", "延期", "えんき", key=True), t("t-l18s1-4", "に"),
                         t("t-l18s1-5", "なった"), t("t-l18s1-6", "という", key=True), t("t-l18s1-7", "こと", "事", "こと", key=True),
                         t("t-l18s1-8", "だ")],
               "Nghe nói cuộc họp đã bị hoãn lại."),
            ex(L, 1, 2, [t("t-l18s1-9", "けいかく", "計画", "けいかく", key=True), t("t-l18s1-10", "が"),
                         t("t-l18s1-11", "へんこう", "変更", "へんこう", key=True), t("t-l18s1-12", "された"),
                         t("t-l18s1-13", "という", key=True), t("t-l18s1-14", "こと", "事", "こと", key=True),
                         t("t-l18s1-15", "です")],
               "Nghe nói kế hoạch đã bị thay đổi."),
        ],
        tips="ということだ thường xuất hiện ở cuối bản tin, thông báo chính thức — nguồn tin được ngụ ý là ĐÁNG TIN CẬY, đã qua xác nhận.",
        culture="Bản tin thời sự Nhật hay kết thúc bằng: '会議は来週に延期されるということです' (nghe nói cuộc họp sẽ được hoãn sang tuần sau)."),

    slide(L, 2,
        "2. Giải thích ý nghĩa: A ということは、B ということだ",
        "A(thể thường) + ということは、B(thể thường) + ということだ",
        "Khi dùng để GIẢI THÍCH Ý NGHĨA của một điều gì đó (diễn giải lại theo cách khác, 'tức "
        "là...'), ということ nối hai mệnh đề để làm rõ nghĩa cho nhau — thường dùng trong suy luận, phân tích.",
        [
            ex(L, 2, 1, [t("t-l18s2-1", "かいぎ", "会議", "かいぎ", key=True), t("t-l18s2-2", "が"),
                         t("t-l18s2-3", "ちゅうし", "中止", "ちゅうし", key=True), t("t-l18s2-4", "に"),
                         t("t-l18s2-5", "なった"), t("t-l18s2-6", "という", key=True), t("t-l18s2-7", "こと", "事", "こと"),
                         t("t-l18s2-8", "は"), t("t-l18s2-9", "、"), t("t-l18s2-10", "じゅんび", "準備", "じゅんび", key=True),
                         t("t-l18s2-11", "が"), t("t-l18s2-12", "まだ"), t("t-l18s2-13", "おわって", "終わって", "おわって"),
                         t("t-l18s2-14", "いない"), t("t-l18s2-15", "という", key=True), t("t-l18s2-16", "こと", "事", "こと", key=True),
                         t("t-l18s2-17", "だ")],
               "Cuộc họp bị hủy tức là việc chuẩn bị vẫn chưa xong."),
            ex(L, 2, 2, [t("t-l18s2-18", "しょうにん", "承認", "しょうにん", key=True), t("t-l18s2-19", "が"),
                         t("t-l18s2-20", "ない"), t("t-l18s2-21", "という", key=True), t("t-l18s2-22", "こと", "事", "こと"),
                         t("t-l18s2-23", "は"), t("t-l18s2-24", "、"), t("t-l18s2-25", "けいかく", "計画", "けいかく", key=True),
                         t("t-l18s2-26", "を"), t("t-l18s2-27", "すすめられない"), t("t-l18s2-28", "という", key=True),
                         t("t-l18s2-29", "こと", "事", "こと", key=True), t("t-l18s2-30", "だ")],
               "Không có phê duyệt tức là không thể tiến hành kế hoạch."),
        ],
        tips="Có thể rút gọn thành というのは thay vì ということは ở vế đầu, ý nghĩa tương đương.",
        culture="Trong bài giảng, sách giáo khoa Nhật hay dùng cấu trúc này để diễn giải khái niệm: 'AIとは、人工知能ということだ' (AI tức là trí tuệ nhân tạo)."),

    slide(L, 3,
        "3. Kết luận logic: [thể thường] ということになる",
        "[Thể thường] + ということになる",
        "ということになる diễn tả một KẾT LUẬN được RÚT RA từ logic/tình huống (không phải quyết "
        "định chủ quan của người nói) — 'rốt cuộc/tóm lại là...', dùng khi tổng kết một điều đã được quyết định bởi hoàn cảnh khách quan.",
        [
            ex(L, 3, 1, [t("t-l18s3-1", "しょうにん", "承認", "しょうにん", key=True), t("t-l18s3-2", "が"),
                         t("t-l18s3-3", "ひつよう", "必要", "ひつよう", key=True), t("t-l18s3-4", "だ"),
                         t("t-l18s3-5", "という", key=True), t("t-l18s3-6", "こと", "事", "こと", key=True),
                         t("t-l18s3-7", "に"), t("t-l18s3-8", "なります", "成ります", "なります")],
               "Tóm lại là cần phải có sự phê duyệt."),
            ex(L, 3, 2, [t("t-l18s3-9", "かいぎ", "会議", "かいぎ", key=True), t("t-l18s3-10", "は"),
                         t("t-l18s3-11", "らいしゅう", "来週", "らいしゅう", key=True), t("t-l18s3-12", "に"),
                         t("t-l18s3-13", "えんき", "延期", "えんき", key=True), t("t-l18s3-14", "する"),
                         t("t-l18s3-15", "という", key=True), t("t-l18s3-16", "こと", "事", "こと", key=True),
                         t("t-l18s3-17", "に"), t("t-l18s3-18", "なりました", "成りました", "なりました")],
               "Kết quả là cuộc họp sẽ được hoãn sang tuần sau."),
        ],
        tips="ということになる nhấn KẾT QUẢ KHÁCH QUAN (do hoàn cảnh dẫn đến), khác ことにする (N4) là QUYẾT ĐỊNH CHỦ QUAN của người nói.",
        culture="Trong biên bản họp công ty Nhật: '来月から新しい規則を適用するということになりました' (kết quả là quy định mới sẽ được áp dụng từ tháng sau)."),

    slide(L, 4,
        "4. So sánh ba cách dùng của ということ",
        "ということだ: TRUYỀN ĐẠT tin nghe được　vs　ということは〜だ: GIẢI THÍCH ý nghĩa　vs　ということになる: KẾT LUẬN logic khách quan",
        "Cả ba đều dùng chung mẫu ということ nhưng CHỨC NĂNG khác nhau: (1) TRUYỀN TIN từ nguồn "
        "khác; (2) GIẢI THÍCH/diễn giải lại ý nghĩa; (3) rút ra KẾT LUẬN từ logic/hoàn cảnh khách quan.",
        [
            ex(L, 4, 1, [t("t-l18s4-1", "しゃちょう", "社長", "しゃちょう", key=True), t("t-l18s4-2", "が"),
                         t("t-l18s4-3", "けってい", "決定", "けってい", key=True), t("t-l18s4-4", "した"),
                         t("t-l18s4-5", "という", key=True), t("t-l18s4-6", "こと", "事", "こと", key=True),
                         t("t-l18s4-7", "だ")],
               "Nghe nói giám đốc đã quyết định. (truyền đạt tin nghe được)"),
            ex(L, 4, 2, [t("t-l18s4-8", "めいれい", "命令", "めいれい", key=True), t("t-l18s4-9", "が"),
                         t("t-l18s4-10", "ない"), t("t-l18s4-11", "という", key=True), t("t-l18s4-12", "こと", "事", "こと"),
                         t("t-l18s4-13", "は"), t("t-l18s4-14", "、"), t("t-l18s4-15", "じゆうに"),
                         t("t-l18s4-16", "できる"), t("t-l18s4-17", "という", key=True), t("t-l18s4-18", "こと", "事", "こと", key=True),
                         t("t-l18s4-19", "だ")],
               "Không có mệnh lệnh tức là có thể làm tự do. (giải thích ý nghĩa)"),
        ],
        tips="Nhìn vào vế trước để phân biệt: có động từ nghe/thấy ngụ ý → ということだ; hai mệnh đề đối chiếu nghĩa → ということは; kết quả từ tình huống → ということになる.",
        culture="Ba cấu trúc này đều là điểm ngữ pháp N3 quan trọng, thường xuất hiện trong đề đọc hiểu về thông báo, quy định công ty."),
]

DIALOGUE = [
    line(L, 1, "田中", "Đồng nghiệp",
         [t("d18-1", "きょう", "今日", "きょう", key=True), t("d18-2", "の"), t("d18-3", "かいぎ", "会議", "かいぎ", key=True),
          t("d18-4", "は"), t("d18-5", "えんき", "延期", "えんき", key=True), t("d18-6", "に"), t("d18-7", "なった"),
          t("d18-8", "という", key=True), t("d18-9", "こと", "事", "こと", key=True), t("d18-10", "です")],
         "Nghe nói cuộc họp hôm nay đã bị hoãn."),
    line(L, 2, "サントス", "Đồng nghiệp",
         [t("d18-11", "それ"), t("d18-12", "は"), t("d18-13", "、"), t("d18-14", "じゅんび", "準備", "じゅんび", key=True),
          t("d18-15", "が"), t("d18-16", "まだ"), t("d18-17", "おわって", "終わって", "おわって"), t("d18-18", "いない"),
          t("d18-19", "という", key=True), t("d18-20", "こと", "事", "こと", key=True), t("d18-21", "です", "です", "です"),
          t("d18-22", "か")],
         "Vậy tức là việc chuẩn bị vẫn chưa xong à?"),
    line(L, 3, "田中", "Đồng nghiệp",
         [t("d18-23", "はい"), t("d18-24", "。"), t("d18-25", "しゃちょう", "社長", "しゃちょう", key=True), t("d18-26", "が"),
          t("d18-27", "けってい", "決定", "けってい", key=True), t("d18-28", "した"), t("d18-29", "という", key=True),
          t("d18-30", "こと", "事", "こと", key=True), t("d18-31", "です")],
         "Vâng. Nghe nói giám đốc đã quyết định như vậy."),
    line(L, 4, "サントス", "Đồng nghiệp",
         [t("d18-32", "けいかく", "計画", "けいかく", key=True), t("d18-33", "も"), t("d18-34", "へんこう", "変更", "へんこう", key=True),
          t("d18-35", "されます", "されます", "されます"), t("d18-36", "か")],
         "Kế hoạch cũng sẽ bị thay đổi à?"),
    line(L, 5, "田中", "Đồng nghiệp",
         [t("d18-37", "しょうにん", "承認", "しょうにん", key=True), t("d18-38", "が"), t("d18-39", "ひつよう", "必要", "ひつよう", key=True),
          t("d18-40", "だ"), t("d18-41", "という", key=True), t("d18-42", "こと", "事", "こと", key=True), t("d18-43", "に"),
          t("d18-44", "なります", "成ります", "なります")],
         "Tóm lại là cần phải có sự phê duyệt."),
    line(L, 6, "サントス", "Đồng nghiệp",
         [t("d18-45", "かいぎ", "会議", "かいぎ", key=True), t("d18-46", "は"), t("d18-47", "らいしゅう", "来週", "らいしゅう", key=True),
          t("d18-48", "に"), t("d18-49", "えんき", "延期", "えんき", key=True), t("d18-50", "する"), t("d18-51", "という", key=True),
          t("d18-52", "こと", "事", "こと", key=True), t("d18-53", "に"), t("d18-54", "なりました", "成りました", "なりました")],
         "Kết quả là cuộc họp sẽ được hoãn sang tuần sau."),
    line(L, 7, "田中", "Đồng nghiệp",
         [t("d18-55", "でんわ", "電話", "でんわ", key=True), t("d18-56", "で"), t("d18-57", "みんな"), t("d18-58", "に"),
          t("d18-59", "れんらく", "連絡", "れんらく", key=True), t("d18-60", "しましょう")],
         "Hãy liên lạc với mọi người bằng điện thoại nhé."),
    line(L, 8, "サントス", "Đồng nghiệp",
         [t("d18-61", "しゃちょう", "社長", "しゃちょう", key=True), t("d18-62", "が"), t("d18-63", "めいれい", "命令", "めいれい", key=True),
          t("d18-64", "した"), t("d18-65", "という", key=True), t("d18-66", "こと", "事", "こと", key=True),
          t("d18-67", "です", "です", "です"), t("d18-68", "か")],
         "Có phải giám đốc đã ra lệnh như vậy không?"),
    line(L, 9, "田中", "Đồng nghiệp",
         [t("d18-69", "いいえ"), t("d18-70", "、"), t("d18-71", "めいれい", "命令", "めいれい", key=True), t("d18-72", "が"),
          t("d18-73", "ない"), t("d18-74", "という", key=True), t("d18-75", "こと", "事", "こと"), t("d18-76", "は"),
          t("d18-77", "、"), t("d18-78", "じゆうに"), t("d18-79", "きめられる"), t("d18-80", "という", key=True),
          t("d18-81", "こと", "事", "こと", key=True), t("d18-82", "です")],
         "Không, không có mệnh lệnh tức là chúng ta có thể tự quyết định."),
    line(L, 10, "サントス", "Đồng nghiệp",
         [t("d18-83", "わかりました", "分かりました", "わかりました"), t("d18-84", "。"), t("d18-85", "もんだい", "問題", "もんだい", key=True),
          t("d18-86", "が"), t("d18-87", "きまったら", "決まったら", "きまったら"), t("d18-88", "、"),
          t("d18-89", "しらせ", "知らせ", "しらせ", key=True), t("d18-90", "を"), t("d18-91", "おくります", "送ります", "おくります")],
         "Đã hiểu rồi. Khi vấn đề được quyết định, tôi sẽ gửi thông báo."),
]

EXERCISES = [
    q(L, 1, "「会議は延期になったということだ」 — ということだ diễn tả điều gì?",
      ["Truyền đạt một thông tin đã nghe/đọc được, mang tính trang trọng, khách quan",
       "Giải thích ý nghĩa của một từ", "Kết luận logic từ tình huống",
       "Phủ định việc cuộc họp bị hoãn"], 0,
      "ということだ dùng để TRUYỀN ĐẠT thông tin đã nghe được, trang trọng hơn そうだ, thường thấy trong thông báo chính thức.",
      "Xem cấu trúc ということだ ở slide 1."),
    q(L, 2, "「会議が中止になったということは、準備が終わっていないということだ」 — cấu trúc này dùng để làm gì?",
      ["Giải thích/diễn giải ý nghĩa của một sự việc ('tức là...')",
       "Truyền đạt tin đồn không có căn cứ", "Ra lệnh cho ai đó",
       "Phủ định hoàn toàn sự việc"], 0,
      "ということは〜ということだ nối hai mệnh đề để làm rõ nghĩa cho nhau, giải thích 'A tức là B'.",
      "Xem cấu trúc giải thích ý nghĩa ở slide 2."),
    q(L, 3, "「承認が必要だということになります」 — ということになる khác ということだ ở điểm nào?",
      ["ということになる là KẾT LUẬN từ logic/hoàn cảnh khách quan, không phải tin nghe được",
       "Hoàn toàn giống nhau, không khác gì cả", "ということになる chỉ dùng cho câu hỏi",
       "ということだ chỉ dùng cho phủ định"], 0,
      "ということになる diễn tả kết luận rút ra từ logic/tình huống, khác ということだ là truyền đạt tin đã nghe.",
      "Xem giải thích ということになる ở slide 3."),
    q(L, 4, "ということになる khác ことにする (đã học ở N4) ở điểm nào?",
      ["ということになる là KẾT QUẢ KHÁCH QUAN do hoàn cảnh; ことにする là QUYẾT ĐỊNH CHỦ QUAN của người nói",
       "Hoàn toàn giống nhau, dùng thay thế được cho nhau", "ということになる chỉ dùng cho phủ định",
       "ことにする chỉ dùng trong quá khứ"], 0,
      "ということになる nhấn kết quả KHÁCH QUAN từ hoàn cảnh; ことにする (N4) là quyết định CHỦ QUAN của bản thân người nói.",
      "Xem lưu ý so sánh ở slide 3."),
    q(L, 5, "Ba cách dùng của ということ (だ/は〜だ/になる) khác nhau chủ yếu về:",
      ["Chức năng: truyền tin, giải thích ý nghĩa, hay kết luận logic",
       "Không có gì khác nhau, hoàn toàn thay thế được cho nhau",
       "Chỉ khác nhau về thì quá khứ/hiện tại", "Chỉ dùng được cho câu phủ định"], 0,
      "ということだ=truyền tin; ということは〜だ=giải thích ý nghĩa; ということになる=kết luận logic khách quan.",
      "Xem bảng so sánh ở slide 4."),
    q(L, 6, "「社長が決定したということだ」 nghĩa là:",
      ["Nghe nói giám đốc đã quyết định (thông tin truyền đạt từ nguồn khác)",
       "Giám đốc chưa quyết định gì cả", "Người nói tự quyết định thay giám đốc",
       "Giám đốc phủ nhận việc quyết định"], 0,
      "ということだ ở đây truyền đạt thông tin đã nghe được rằng giám đốc đã quyết định.",
      "Áp dụng cấu trúc ということだ cho ngữ cảnh câu."),
    q(L, 7, "「命令がないということは、自由にできるということだ」 nghĩa là:",
      ["Không có mệnh lệnh tức là có thể làm tự do (giải thích ý nghĩa)",
       "Phải chờ mệnh lệnh mới được làm", "Mệnh lệnh đã được ban hành",
       "Không ai được phép làm gì cả"], 0,
      "ということは〜だ ở đây giải thích ý nghĩa: việc không có mệnh lệnh ĐỒNG NGHĨA với việc có thể tự do làm.",
      "Áp dụng cấu trúc giải thích ý nghĩa ở slide 2."),
    q(L, 8, "Theo hội thoại, vì sao cuộc họp hôm nay bị hoãn?",
      ["Vì việc chuẩn bị vẫn chưa xong (準備が終わっていない)", "Vì giám đốc vắng mặt",
       "Vì trời mưa to", "Không được đề cập trong hội thoại"], 0,
      "Santos suy luận 「準備が終わっていないということですか」và được xác nhận.",
      "Xem câu thoại thứ 2-3."),
    q(L, 9, "Cuộc họp sẽ được hoãn đến khi nào theo hội thoại?",
      ["Tuần sau (来週に延期するということになりました)", "Tháng sau", "Ngày mai",
       "Không được đề cập trong hội thoại"], 0,
      "田中 nói 「会議は来週に延期するということになりました」.",
      "Xem câu thoại thứ 6."),
    q(L, 10, "Santos sẽ làm gì khi vấn đề được quyết định?",
      ["Gửi thông báo (お知らせを送ります)", "Không làm gì cả", "Hủy cuộc họp",
       "Tự mình quyết định mọi thứ"], 0,
      "Santos nói 「問題が決まったら、知らせを送ります」.",
      "Xem câu thoại cuối cùng."),
]

LESSON = lesson(
    L,
    "Bài 18: Truyền đạt thông tin chính thức (ということ)",
    "ということだ dùng để TRUYỀN ĐẠT một thông tin đã nghe/đọc được một cách TRANG TRỌNG (mạnh mẽ "
    "hơn そうだ); ということは〜ということだ dùng để GIẢI THÍCH Ý NGHĨA ('A tức là B'); ということに"
    "なる diễn tả KẾT LUẬN LOGIC từ hoàn cảnh khách quan (khác ことにする là quyết định chủ quan).",
    VOCAB, KANJI, SLIDES, DIALOGUE, EXERCISES,
)

if __name__ == "__main__":
    pool.mark_used([w["word"] for w in VOCAB if w["word"]], lesson=L)
    merge([LESSON])
