# -*- coding: utf-8 -*-
"""N4 — Bai 42: Muc dich vi ai/cai gi ために, dung vao viec gi のに.

Tu vung minh hoa TU CHON tu pool mo data/jlpt-vocab/n4.csv (xem NOTICE.md).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from n4_lib import v, k, t, ex, slide, line, q, lesson, merge
from jlpt_pool import Pool

L = 42
pool = Pool("n4")

VOCAB = [
    v(1,  "つかいます", "使います", "つかいます", "tsukaimasu", "verb", "Sử dụng, dùng", "Đã gặp N5 bài 15 — nay dùng làm động từ chính cho のに.", L),
    v(2,  "ためます", "貯めます", "ためます", "tamemasu", "verb", "Tích lũy, để dành (tiền)", "留学の ために、お金を 貯めています = để đi du học, tôi đang để dành tiền.", L),
    v(3,  "はたらきます", "働きます", "はたらきます", "hatarakimasu", "verb", "Làm việc, đi làm", "Đã gặp N5 bài 4.", L),
    v(4,  "べんきょうします", "勉強します", "べんきょうします", "benkyou shimasu", "verb", "Học, học tập", "Đã gặp N5 bài 4.", L),
    v(5,  "やくにたちます", "役に立ちます", "やくにたちます", "yaku ni tachimasu", "verb", "Có ích, hữu dụng", "この道具は 料理を 作るのに 役に立ちます = dụng cụ này hữu ích để nấu ăn.", L),
    v(6,  "りゅうがくします", "留学します", "りゅうがくします", "ryuugaku shimasu", "verb", "Đi du học", "Đã gặp N5 bài 21.", L),
    v(7,  "しょうらい", "将来", "しょうらい", "shourai", "noun", "Tương lai", "Đã gặp bài 31.", L),
    v(8,  "どうぐ", "道具", "どうぐ", "dougu", "noun", "Dụng cụ, công cụ", "この道具は 何に 使いますか = dụng cụ này dùng để làm gì vậy?", L),
    v(9,  "おかね", "お金", "おかね", "okane", "noun", "Tiền", "Đã gặp N5 bài 25.", L),
    v(10, "おかねもち", "お金持ち", "おかねもち", "okanemochi", "noun", "Người giàu có", "お金持ちに なるために = để trở thành người giàu có.", L),
    v(11, "りょうり", "料理", "りょうり", "ryouri", "noun", "Món ăn, nấu ăn", "Đã gặp N5 bài 9.", L),
    v(12, "じかん", "時間", "じかん", "jikan", "noun", "Thời gian", "Đã gặp N5 bài 4.", L),
    v(13, "けんこう", "健康", "けんこう", "kenkou", "adjective", "Sức khỏe, khỏe mạnh", "健康の ために、運動します = để (giữ) sức khỏe, tôi tập thể dục.", L),
    v(14, "しけん", "試験", "しけん", "shiken", "noun", "Kỳ thi", "Đã gặp bài 40.", L),
    v(15, "ごうかくします", "合格します", "ごうかくします", "goukaku shimasu", "verb", "Đậu, đỗ (kỳ thi)", "Đã gặp bài 40.", L),
    v(16, "だいがく", "大学", "だいがく", "daigaku", "noun", "Trường đại học", "Đã gặp N5 bài 1.", L),
    v(17, "はさみ", "鋏", "はさみ", "hasami", "noun", "Cái kéo", "はさみは 紙を 切るのに 使います = kéo dùng để cắt giấy.", L),
    v(18, "かみ", "紙", "かみ", "kami", "noun", "Giấy", "Đã gặp N5 bài 11.", L),
    v(19, "きります", "切ります", "きります", "kirimasu", "verb", "Cắt", "紙を 切ります = cắt giấy.", L),
    v(20, "べんり", "便利", "べんり", "benri", "adjective", "Tiện lợi", "Đã gặp N5 bài 8.", L),
]

KANJI = [
    k(1, "将", "TƯỚNG", 10, ["ショウ (shou)"], [], "Sắp tới, tương lai. Đã gặp bài 31.",
      [("将来", "しょうらい", "Tương lai")], L),
    k(2, "道", "ĐẠO", 12, ["ドウ (dou)"], ["みち"], "Con đường; đạo lý. Đã gặp N5 bài 24.",
      [("道具", "どうぐ", "Dụng cụ"), ("道", "みち", "Con đường")], L),
    k(3, "具", "CỤ", 8, ["グ (gu)"], [], "Dụng cụ. Đã gặp bài 26 (具合).",
      [("道具", "どうぐ", "Dụng cụ"), ("具合", "ぐあい", "Tình trạng")], L),
    k(4, "役", "DỊCH", 7, ["ヤク (yaku)"], [], "Vai trò, chức vụ.",
      [("役に立ちます", "やくにたちます", "Có ích"), ("役者", "やくしゃ", "Diễn viên")], L),
    k(5, "切", "THIẾT", 4, ["セツ (setsu)"], ["き(る)"], "Cắt.",
      [("切ります", "きります", "Cắt"), ("大切", "たいせつ", "Quan trọng"), ("切手", "きって", "Tem thư")], L),
]

SLIDES = [
    slide(L, 1,
        "1. Mục đích với động từ Ý CHÍ: N/V(từ điển) の ために",
        "N + の + ために 　　V(từ điển) + ために   (dùng với động từ TỰ CHỦ điều khiển được: 貯める, 働く, 勉強する)",
        "ために đối lập với ように (bài 36, dùng cho động từ VÔ Ý CHÍ như 聞こえる/分かる) — ために "
        "CHỈ dùng khi người nói TỰ CHỌN thực hiện hành động để đạt mục đích.",
        [
            ex(L, 1, 1, [t("t-l42s1-1", "りゅうがく", "留学", "りゅうがく", key=True), t("t-l42s1-2", "の", key=True),
                         t("t-l42s1-3", "ために", key=True), t("t-l42s1-4", "、"), t("t-l42s1-5", "おかね", "お金", "おかね"),
                         t("t-l42s1-6", "を"), t("t-l42s1-7", "ためて", "貯めて", "ためて"), t("t-l42s1-8", "います", "居ます", "います")],
               "Để đi du học, tôi đang để dành tiền."),
            ex(L, 1, 2, [t("t-l42s1-9", "けんこう", "健康", "けんこう", key=True), t("t-l42s1-10", "の", key=True),
                         t("t-l42s1-11", "ために", key=True), t("t-l42s1-12", "、"), t("t-l42s1-13", "うんどう", "運動", "うんどう"),
                         t("t-l42s1-14", "します")],
               "Để (giữ) sức khỏe, tôi tập thể dục."),
        ],
        tips="Mẹo phân biệt nhanh với ように (bài 36): thử tự hỏi ai đó có thể TỰ QUYẾT ĐỊNH làm/không làm hành động này không — nếu có, dùng ために.",
        culture="お金持ちになるために、毎日働きます phản ánh tinh thần cần cù, có mục tiêu rõ ràng thường thấy trong văn hóa làm việc Nhật."),

    slide(L, 2,
        "2. Dùng vào việc gì: N は [Vる] のに 使います／役に立ちます",
        "N + は + V(từ điển) + の + に + 使います／役に立ちます",
        "のに ở đây KHÁC HẲN のに mang nghĩa 'mặc dù' (sẽ học ở bài 45) — đây là の (danh từ hóa, "
        "N4 bài 38) + に (mục đích) ghép lại, hỏi/trả lời một VẬT dùng để LÀM GÌ.",
        [
            ex(L, 2, 1, [t("t-l42s2-1", "はさみ", "鋏", "はさみ", key=True), t("t-l42s2-2", "は"),
                         t("t-l42s2-3", "かみ", "紙", "かみ"), t("t-l42s2-4", "を"), t("t-l42s2-5", "きる", "切る", "きる"),
                         t("t-l42s2-6", "の", key=True), t("t-l42s2-7", "に", key=True), t("t-l42s2-8", "つかいます", "使います", "つかいます", key=True)],
               "Kéo dùng để cắt giấy."),
            ex(L, 2, 2, [t("t-l42s2-9", "この"), t("t-l42s2-10", "どうぐ", "道具", "どうぐ", key=True), t("t-l42s2-11", "は"),
                         t("t-l42s2-12", "りょうり", "料理", "りょうり"), t("t-l42s2-13", "を"), t("t-l42s2-14", "つくる", "作る", "つくる"),
                         t("t-l42s2-15", "の", key=True), t("t-l42s2-16", "に", key=True), t("t-l42s2-17", "やくに", "役に", "やくに"),
                         t("t-l42s2-18", "たちます", "立ちます", "たちます", key=True)],
               "Dụng cụ này hữu ích để nấu ăn."),
        ],
        tips="Câu hỏi tương ứng: 「これは 何に 使いますか」 (cái này dùng để làm gì) — 何 thay cho cả cụm V+の.",
        culture="この道具は何に使いますか là câu hỏi rất tự nhiên khi thấy một vật dụng lạ, đặc biệt phổ biến khi mua đồ ở Nhật."),

    slide(L, 3,
        "3. So sánh ために và のに (mục đích)",
        "ために: [MỤC ĐÍCH]、[hành động để ĐẠT mục đích đó]　vs　のに: [VẬT]は [MỤC ĐÍCH]の に [công dụng của vật]",
        "ために đặt MỤC ĐÍCH lên trước, hành động theo sau; のに (mục đích) mô tả CÔNG DỤNG của "
        "một VẬT/PHƯƠNG TIỆN cụ thể — hai chiều nhìn khác nhau của cùng khái niệm 'mục đích'.",
        [
            ex(L, 3, 1, [t("t-l42s3-1", "しけん", "試験", "しけん", key=True), t("t-l42s3-2", "に"),
                         t("t-l42s3-3", "ごうかく", "合格", "ごうかく"), t("t-l42s3-4", "する", key=True),
                         t("t-l42s3-5", "ために", key=True), t("t-l42s3-6", "、"), t("t-l42s3-7", "べんきょう", "勉強", "べんきょう"),
                         t("t-l42s3-8", "して", key=True), t("t-l42s3-9", "います", "居ます", "います")],
               "Để đậu kỳ thi, tôi đang học bài. (ために: mục đích → hành động)"),
            ex(L, 3, 2, [t("t-l42s3-10", "じしょ", "辞書", "じしょ", key=True), t("t-l42s3-11", "は"),
                         t("t-l42s3-12", "ことば", "言葉", "ことば"), t("t-l42s3-13", "を"), t("t-l42s3-14", "しらべる", "調べる", "しらべる"),
                         t("t-l42s3-15", "の", key=True), t("t-l42s3-16", "に", key=True), t("t-l42s3-17", "つかいます", "使います", "つかいます", key=True)],
               "Từ điển dùng để tra từ. (のに: vật → công dụng)"),
        ],
        tips="ために trả lời câu hỏi 'LÀM ĐỂ LÀM GÌ'; のに trả lời câu hỏi 'VẬT NÀY DÙNG ĐỂ LÀM GÌ' — chủ ngữ của hai cấu trúc khác hẳn nhau.",
        culture="Cả hai cấu trúc đều rất phổ biến trong hướng dẫn sử dụng sản phẩm và bài luận về mục tiêu cá nhân ở Nhật."),

    slide(L, 4,
        "4. Ba cấu trúc mục đích: ように (b36) / ために / のに — chọn đúng theo ngữ cảnh",
        "ように: động từ VÔ Ý CHÍ 　ために: mục đích CÓ Ý CHÍ, hành động hướng tới 　のに: CÔNG DỤNG của vật/phương tiện",
        "Ba cấu trúc đều dịch gần giống 'để' trong tiếng Việt nhưng áp dụng cho BA TÌNH HUỐNG khác "
        "nhau rõ rệt — chọn sai sẽ khiến câu nghe ngược nghĩa hoặc kỳ lạ với người bản xứ.",
        [
            ex(L, 4, 1, [t("t-l42s4-1", "だいがく", "大学", "だいがく", key=True), t("t-l42s4-2", "に"),
                         t("t-l42s4-3", "はいる", "入る", "はいる"), t("t-l42s4-4", "ために", key=True), t("t-l42s4-5", "、"),
                         t("t-l42s4-6", "がんばって", "頑張って", "がんばって"), t("t-l42s4-7", "います", "居ます", "います")],
               "Để vào được đại học, tôi đang cố gắng. (ため: mục đích có ý chí)"),
            ex(L, 4, 2, [t("t-l42s4-8", "この"), t("t-l42s4-9", "アプリ"), t("t-l42s4-10", "は"),
                         t("t-l42s4-11", "じかん", "時間", "じかん", key=True), t("t-l42s4-12", "を"),
                         t("t-l42s4-13", "かんりする", "管理する", "かんりする"), t("t-l42s4-14", "の", key=True),
                         t("t-l42s4-15", "に", key=True), t("t-l42s4-16", "べんり", "便利", "べんり", key=True), t("t-l42s4-17", "です")],
               "Ứng dụng này tiện lợi để quản lý thời gian. (のに: công dụng)"),
        ],
        tips="Kiểm tra nhanh: chủ ngữ là NGƯỜI muốn đạt mục tiêu → ために; chủ ngữ là VẬT/CÔNG CỤ có công dụng → のに; động từ không tự chủ (nghe/thấy/hiểu/quên) → ように.",
        culture="Ba cấu trúc này thường xuất hiện cùng nhau trong một đoạn văn khi người viết vừa nói mục tiêu cá nhân vừa mô tả công cụ hỗ trợ."),
]

DIALOGUE = [
    line(L, 1, "田中", "Đồng nghiệp",
         [t("d-l42-1", "山田さん"), t("d-l42-2", "は"), t("d-l42-3", "どうして"), t("d-l42-4", "、"),
          t("d-l42-5", "まいにち", "毎日", "まいにち"), t("d-l42-6", "べんきょう", "勉強", "べんきょう", key=True),
          t("d-l42-7", "して", key=True), t("d-l42-8", "いる", key=True), t("d-l42-9", "んです", key=True),
          t("d-l42-10", "か")],
         "Anh Yamada sao lại học mỗi ngày vậy?"),
    line(L, 2, "山田", "Nhân viên công ty",
         [t("d-l42-11", "りゅうがく", "留学", "りゅうがく", key=True), t("d-l42-12", "の", key=True),
          t("d-l42-13", "ために", key=True), t("d-l42-14", "、"), t("d-l42-15", "しけん", "試験", "しけん", key=True),
          t("d-l42-16", "に"), t("d-l42-17", "ごうかく", "合格", "ごうかく", key=True), t("d-l42-18", "したい", "したい", "したい"),
          t("d-l42-19", "んです", key=True)],
         "Để đi du học, tôi muốn đậu kỳ thi."),
    line(L, 3, "田中", "Đồng nghiệp",
         [t("d-l42-20", "すごい"), t("d-l42-21", "ですね"), t("d-l42-22", "。"), t("d-l42-23", "その"),
          t("d-l42-24", "どうぐ", "道具", "どうぐ", key=True), t("d-l42-25", "は"), t("d-l42-26", "なに", "何", "なに"),
          t("d-l42-27", "に"), t("d-l42-28", "つかいます", "使います", "つかいます", key=True), t("d-l42-29", "か")],
         "Giỏi thật đấy. Cái dụng cụ đó dùng để làm gì vậy?"),
    line(L, 4, "山田", "Nhân viên công ty",
         [t("d-l42-30", "これ"), t("d-l42-31", "は"), t("d-l42-32", "たんご", "単語", "たんご"),
          t("d-l42-33", "を"), t("d-l42-34", "おぼえる", "覚える", "おぼえる"), t("d-l42-35", "の", key=True),
          t("d-l42-36", "に"), t("d-l42-37", "つかいます", "使います", "つかいます", key=True)],
         "Cái này dùng để ghi nhớ từ vựng."),
    line(L, 5, "田中", "Đồng nghiệp",
         [t("d-l42-38", "やくに", "役に", "やくに"), t("d-l42-39", "たちますか", "立ちますか", "たちますか", key=True)],
         "Có hữu ích không?"),
    line(L, 6, "山田", "Nhân viên công ty",
         [t("d-l42-40", "はい"), t("d-l42-41", "、"), t("d-l42-42", "とても"), t("d-l42-43", "べんり", "便利", "べんり", key=True),
          t("d-l42-44", "です"), t("d-l42-45", "。"), t("d-l42-46", "しょうらい", "将来", "しょうらい", key=True),
          t("d-l42-47", "の"), t("d-l42-48", "ために", key=True), t("d-l42-49", "、"), t("d-l42-50", "まいにち", "毎日", "まいにち"),
          t("d-l42-51", "つかって", "使って", "つかって"), t("d-l42-52", "います", "居ます", "います")],
         "Vâng, rất tiện lợi. Vì tương lai, tôi dùng nó mỗi ngày."),
    line(L, 7, "田中", "Đồng nghiệp",
         [t("d-l42-53", "わたし", "私", "わたし"), t("d-l42-54", "も"), t("d-l42-55", "おかねもち", "お金持ち", "おかねもち", key=True),
          t("d-l42-56", "に"), t("d-l42-57", "なる", "成る", "なる"), t("d-l42-58", "ために", key=True), t("d-l42-59", "、"),
          t("d-l42-60", "がんばって", "頑張って", "がんばって"), t("d-l42-61", "はたらいて", "働いて", "はたらいて"),
          t("d-l42-62", "います", "居ます", "います")],
         "Tôi cũng đang làm việc chăm chỉ để trở thành người giàu có."),
    line(L, 8, "山田", "Nhân viên công ty",
         [t("d-l42-63", "いいですね"), t("d-l42-64", "。"), t("d-l42-65", "おかね", "お金", "おかね", key=True),
          t("d-l42-66", "を"), t("d-l42-67", "ためて", "貯めて", "ためて"), t("d-l42-68", "、"),
          t("d-l42-69", "なに", "何", "なに"), t("d-l42-70", "を"), t("d-l42-71", "したい", "したい", "したい"),
          t("d-l42-72", "ですか")],
         "Hay đó. Để dành tiền rồi, anh muốn làm gì?"),
    line(L, 9, "田中", "Đồng nghiệp",
         [t("d-l42-73", "だいがく", "大学", "だいがく"), t("d-l42-74", "に"), t("d-l42-75", "はいる", "入る", "はいる"),
          t("d-l42-76", "こども", "子供", "こども"), t("d-l42-77", "の"), t("d-l42-78", "ために", key=True), t("d-l42-79", "、"),
          t("d-l42-80", "つかいたい", "使いたい", "つかいたい"), t("d-l42-81", "です")],
         "Tôi muốn dùng cho con vào đại học."),
    line(L, 10, "山田", "Nhân viên công ty",
         [t("d-l42-82", "すばらしい", "素晴らしい", "すばらしい"), t("d-l42-83", "です"), t("d-l42-84", "ね"),
          t("d-l42-85", "。"), t("d-l42-86", "がんばりましょう", "頑張りましょう", "がんばりましょう")],
         "Tuyệt vời quá. Cùng cố gắng nhé."),
]

EXERCISES = [
    q(L, 1, "「留学のために、お金を貯めています」 — ために dùng vì động từ 貯める thuộc loại nào?",
      ["Động từ Ý CHÍ (tự mình quyết định thực hiện được)", "Động từ VÔ Ý CHÍ (không tự chủ)",
       "Không phải động từ", "Cả hai loại đều được"], 0,
      "ために CHỈ dùng với động từ Ý CHÍ — người nói TỰ QUYẾT ĐỊNH thực hiện hành động (貯める: để dành, tự chủ được).",
      "So sánh với ように (bài 36) dùng cho động từ vô ý chí."),
    q(L, 2, "「はさみは紙を切るのに使います」 — のに ở đây khác のに (mặc dù) sẽ học ở bài 45 vì:",
      ["Đây là の (danh từ hóa) + に (mục đích), không mang nghĩa nhượng bộ 'mặc dù'",
       "Hoàn toàn giống nhau, cùng một のに", "のに ở đây là lỗi chính tả",
       "のに chỉ có một nghĩa duy nhất"], 0,
      "のに ở bài này là ghép の (N4 bài 38, danh từ hóa) + に (mục đích) — khác hẳn のに nhượng bộ ('mặc dù') sẽ học riêng ở bài 45.",
      "Đây là hai のに khác nhau hoàn toàn về cấu tạo và nghĩa."),
    q(L, 3, "「この道具は何に使いますか」 dùng để hỏi:",
      ["Công dụng của một vật/dụng cụ", "Ai đã mua dụng cụ đó",
       "Giá của dụng cụ đó", "Dụng cụ đó ở đâu"], 0,
      "Đây là câu hỏi chuẩn về CÔNG DỤNG, dùng 何 thay cho cụm [V+の] trong cấu trúc のに.",
      "Xem mẫu câu hỏi ở slide 2."),
    q(L, 4, "ために và のに (mục đích) khác nhau ở CHỦ NGỮ chính của câu:",
      ["ために: chủ ngữ là NGƯỜI có mục tiêu; のに: chủ ngữ là VẬT/CÔNG CỤ có công dụng",
       "Hoàn toàn giống nhau về chủ ngữ", "ために chỉ dùng cho vật",
       "のに chỉ dùng cho người"], 0,
      "ために đặt mục đích của một NGƯỜI trước hành động của họ; のに mô tả một VẬT dùng để làm gì.",
      "Xem so sánh trực tiếp ở slide 3."),
    q(L, 5, "「健康のために、運動します」 nghĩa là:",
      ["Để (giữ) sức khỏe, tôi tập thể dục", "Vì sức khỏe kém nên tôi không tập thể dục",
       "Sức khỏe của tôi rất tốt", "Tập thể dục có hại cho sức khỏe"], 0,
      "健康のために diễn tả MỤC ĐÍCH (để có sức khỏe tốt) của hành động tập thể dục.",
      "Áp dụng đúng cấu trúc N+の+ために."),
    q(L, 6, "Ba cấu trúc mục đích ように/ために/のに khác nhau chủ yếu ở:",
      ["Loại động từ (vô ý chí/có ý chí) và chủ ngữ (người có mục tiêu/vật có công dụng)",
       "Hoàn toàn giống nhau, dùng thay thế tự do", "ように chỉ dùng cho câu hỏi",
       "のに chỉ dùng cho câu phủ định"], 0,
      "Ba cấu trúc áp dụng cho ba tình huống khác nhau: ように (động từ vô ý chí, bài 36), ために (mục đích có ý chí), のに (công dụng của vật).",
      "Xem bảng tổng kết ở slide 4."),
    q(L, 7, "Câu nào ĐÚNG khi nói 'từ điển dùng để tra từ'?",
      ["辞書は言葉を調べるのに使います", "辞書は言葉を調べるために使います",
       "辞書は言葉を調べるように使います", "辞書は言葉を調べることに使います"], 0,
      "Đây là câu mô tả CÔNG DỤNG của một vật (từ điển), nên dùng のに, không dùng ために (dành cho mục đích của người).",
      "Xác định chủ ngữ là VẬT hay NGƯỜI."),
    q(L, 8, "「大学に入るために、頑張っています」 — vì sao KHÔNG dùng のに ở đây?",
      ["Chủ ngữ là NGƯỜI đang cố gắng đạt mục tiêu (vào đại học), không phải vật có công dụng",
       "のに mới đúng, ために sai", "Cả hai đều sai, phải dùng ように",
       "Không có lý do gì đặc biệt"], 0,
      "Đây là mục đích của một NGƯỜI (tôi muốn vào đại học) → dùng ために, không dùng のに (dành cho công dụng vật).",
      "Phân biệt theo chủ ngữ như đã học ở slide 3."),
    q(L, 9, "Trong hội thoại, Yamada học chăm chỉ để làm gì?",
      ["Để đậu kỳ thi đi du học", "Để được thăng chức", "Để thi lấy bằng lái xe", "Không có lý do cụ thể"], 0,
      "Yamada nói 「留学のために、試験に合格したいんです」.",
      "Xem câu thoại thứ 2."),
    q(L, 10, "Tanaka để dành tiền để làm gì?",
      ["Để dùng cho con vào đại học", "Để đi du lịch", "Để mua nhà", "Để nghỉ hưu sớm"], 0,
      "Tanaka nói 「大学に入る子供のために、使いたいです」.",
      "Xem câu thoại thứ 9."),
]

LESSON = lesson(
    L,
    "Bài 42: Mục đích vì ai/cái gì (〜ために) & Dùng vào việc gì (〜のに)",
    "Diễn tả mục đích với động từ Ý CHÍ (đối lập ように bài 36) bằng N/Vの/từ điển+ために (mục "
    "đích → hành động, chủ ngữ là người), và công dụng của một vật bằng V(từ điển)のに+使います/"
    "役に立ちます (の danh từ hóa + に mục đích, khác hẳn のに nhượng bộ ở bài 45) — tổng kết ba "
    "cấu trúc mục đích ように/ために/のに theo loại động từ và chủ ngữ.",
    VOCAB, KANJI, SLIDES, DIALOGUE, EXERCISES,
)

if __name__ == "__main__":
    pool.mark_used([w["word"] for w in VOCAB], lesson=L)
    merge([LESSON])
