# -*- coding: utf-8 -*-
"""N4 — Bai 26 (bai mo dau N4): Giai thich ly do & nhan manh 〜んです.

Tu vung minh hoa TU CHON tu pool mo data/jlpt-vocab/n4.csv (xem NOTICE.md).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from n4_lib import v, k, t, ex, slide, line, q, lesson, merge
from jlpt_pool import Pool

L = 26
pool = Pool("n4")

VOCAB = [
    v(1,  "ねぼうします", "寝坊します", "ねぼうします", "nebou shimasu", "verb", "Ngủ quên, dậy muộn", "寝坊したんです = tại vì tôi ngủ quên.", L),
    v(2,  "おくれます", "遅れます", "おくれます", "okuremasu", "verb", "Đến muộn, trễ", "電車が 遅れたんです = tại vì tàu điện bị trễ.", L),
    v(3,  "こわれます", "壊れます", "こわれます", "kowaremasu", "verb", "Bị hỏng, bị vỡ", "自動詞 (tự động từ) — vật TỰ hỏng, không cần ai tác động.", L),
    v(4,  "なおります", "治ります", "なおります", "naorimasu", "verb", "Khỏi bệnh, lành lại", "風邪が 治ったんです = tôi đã khỏi cảm rồi.", L),
    v(5,  "じこ", "事故", "じこ", "jiko", "noun", "Tai nạn", "事故が あったんです = đã có tai nạn xảy ra.", L),
    v(6,  "りゆう", "理由", "りゆう", "riyuu", "noun", "Lý do", "理由は 何ですか = lý do là gì vậy?", L),
    v(7,  "ぐあい", "具合", "ぐあい", "guai", "noun", "Tình trạng (sức khỏe, máy móc)", "具合が悪いんです = tôi thấy không khỏe trong người.", L),
    v(8,  "ねつ", "熱", "ねつ", "netsu", "noun", "Sốt, nhiệt độ", "熱が あるんです = tôi đang bị sốt.", L),
    v(9,  "かいぎ", "会議", "かいぎ", "kaigi", "noun", "Cuộc họp", "Đã gặp N5 bài 7 — nay dùng làm bối cảnh giải thích lý do.", L),
    v(10, "かいぎしつ", "会議室", "かいぎしつ", "kaigishitsu", "noun", "Phòng họp", "Đã gặp N5 bài 3.", L),
    v(11, "でんしゃ", "電車", "でんしゃ", "densha", "noun", "Tàu điện", "Đã gặp N5 bài 5 — nay dùng làm nguyên nhân trễ giờ.", L),
    v(12, "しごと", "仕事", "しごと", "shigoto", "noun", "Công việc", "Đã gặp N5 bài 9.", L),
    v(13, "びょういん", "病院", "びょういん", "byouin", "noun", "Bệnh viện", "Đã gặp N5 bài 3.", L),
    v(14, "かぜ", "風邪", "かぜ", "kaze", "noun", "Cảm lạnh, cảm cúm", "風邪を ひきました = tôi bị cảm.", L),
    v(15, "たいてい", "大抵", "たいてい", "taitei", "adverb", "Thường thì, đại khái", "たいてい 7時に 起きます = thường thì 7 giờ tôi dậy.", L),
    v(16, "やはり／やっぱり", "", "", "yahari/yappari", "adverb", "Quả nhiên, đúng như dự đoán", "やっぱり そうだったんですね = quả nhiên đúng như vậy nhỉ.", L),
    v(17, "とうとう", "", "", "toutou", "adverb", "Cuối cùng thì, rốt cuộc", "とうとう 治ったんです = cuối cùng thì cũng khỏi bệnh.", L),
    v(18, "いけん", "意見", "いけん", "iken", "noun", "Ý kiến, quan điểm", "Đã có nền tảng từ 〜と思います (N5 bài 21) — nay mở rộng cách hỏi ý kiến.", L),
    v(19, "しっかり", "", "", "shikkari", "adverb", "Chắc chắn, kỹ càng", "しっかり 休んで ください = xin hãy nghỉ ngơi cho kỹ.", L),
    v(20, "だいじょうぶ", "大丈夫", "だいじょうぶ", "daijoubu", "adjective", "Ổn, không sao", "Đã gặp N5 bài 15.", L),
]

KANJI = [
    k(1, "由", "DO", 5, ["ユウ (yuu)", "ユ (yu)"], ["よし"], "Nguyên do, lý do.",
      [("理由", "りゆう", "Lý do"), ("由来", "ゆらい", "Nguồn gốc"), ("自由", "じゆう", "Tự do")], L),
    k(2, "具", "CỤ", 8, ["グ (gu)"], [], "Dụng cụ, tình trạng.",
      [("具合", "ぐあい", "Tình trạng"), ("道具", "どうぐ", "Dụng cụ"), ("家具", "かぐ", "Đồ nội thất")], L),
    k(3, "熱", "NHIỆT", 15, ["ネツ (netsu)"], ["あつ(い)"], "Nhiệt, sốt, nhiệt tình.",
      [("熱", "ねつ", "Sốt"), ("熱心", "ねっしん", "Nhiệt tình"), ("熱い", "あつい", "Nóng (đồ vật)")], L),
    k(4, "治", "TRỊ", 8, ["チ (chi)", "ジ (ji)"], ["なお(る)", "おさ(める)"], "Chữa trị, cai trị.",
      [("治ります", "なおります", "Khỏi bệnh"), ("政治", "せいじ", "Chính trị"), ("治療", "ちりょう", "Điều trị")], L),
    k(5, "故", "CỐ", 9, ["コ (ko)"], ["ゆえ"], "Cớ sự, biến cố; cố ý.",
      [("事故", "じこ", "Tai nạn"), ("故障", "こしょう", "Hỏng hóc"), ("故意", "こい", "Cố ý")], L),
]

SLIDES = [
    slide(L, 1,
        "1. Giải thích lý do đã biết/quan sát được: [Thể thông thường] んです",
        "V/A(thể thông thường) + んです　　N/な-adj + なんです",
        "んです (nói tắt của のです) dùng khi GIẢI THÍCH bối cảnh, nguyên nhân của một tình huống mà "
        "cả hai bên đều đã nhận thấy — khác です/ます đơn thuần chỉ nêu sự việc suông.",
        [
            ex(L, 1, 1, [t("t-l26s1-1", "どうして"), t("t-l26s1-2", "、"), t("t-l26s1-3", "かいしゃ", "会社", "かいしゃ"),
                         t("t-l26s1-4", "を"), t("t-l26s1-5", "やすんだ", "休んだ", "やすんだ"),
                         t("t-l26s1-6", "んです", key=True), t("t-l26s1-7", "か")],
               "Sao lại nghỉ làm vậy? (thấy anh đã nghỉ, hỏi lý do)"),
            ex(L, 1, 2, [t("t-l26s1-8", "ねつ", "熱", "ねつ"), t("t-l26s1-9", "が"),
                         t("t-l26s1-10", "あった", "有った", "あった"), t("t-l26s1-11", "んです", key=True)],
               "Tại vì tôi bị sốt."),
            ex(L, 1, 3, [t("t-l26s1-12", "びょうき", "病気", "びょうき"), t("t-l26s1-13", "なんです", key=True),
                         t("t-l26s1-14", "か")],
               "Anh bị bệnh à? (danh từ+なんです, tương tự な-adj)"),
        ],
        tips="んです KHÔNG dùng khi mở đầu chủ đề mới hoàn toàn — chỉ dùng để giải thích/hỏi về điều đã QUAN SÁT thấy.",
        culture="Câu hỏi どうしてですか nghe hơi cộc; どうしてなんですか tự nhiên và mềm mại hơn nhiều trong giao tiếp."),

    slide(L, 2,
        "2. んです nhấn mạnh và xin phép có lý do",
        "んです + が、[yêu cầu/xin phép]",
        "Trước khi xin phép hoặc yêu cầu điều gì có phần bất thường, người Nhật hay NÊU LÝ DO bằng "
        "んです trước, rồi mới nói yêu cầu — làm câu nói mềm mại, dễ chấp nhận hơn.",
        [
            ex(L, 2, 1, [t("t-l26s2-1", "ぐあい", "具合", "ぐあい"), t("t-l26s2-2", "が"),
                         t("t-l26s2-3", "わるい", "悪い", "わるい"), t("t-l26s2-4", "んです", key=True),
                         t("t-l26s2-5", "が"), t("t-l26s2-6", "、"), t("t-l26s2-7", "はやく"),
                         t("t-l26s2-8", "かえっても", "帰っても", "かえっても"), t("t-l26s2-9", "いいですか")],
               "Tôi thấy không khỏe trong người, tôi về sớm được không ạ?"),
            ex(L, 2, 2, [t("t-l26s2-10", "でんしゃ", "電車", "でんしゃ"), t("t-l26s2-11", "が"),
                         t("t-l26s2-12", "おくれた", "遅れた", "おくれた"), t("t-l26s2-13", "んです", key=True),
                         t("t-l26s2-14", "。"), t("t-l26s2-15", "すみません")],
               "Tàu điện bị trễ. Tôi xin lỗi."),
        ],
        tips="Mở đầu bằng lý do (んですが) rồi mới xin phép khiến câu nghe lịch sự, có căn cứ hơn là xin phép suông.",
        culture="Trễ giờ họp ở Nhật gần như luôn kèm theo lời giải thích ngắn bằng んです — im lặng không giải thích bị coi là thiếu trách nhiệm."),

    slide(L, 3,
        "3. So sánh んです và ですます thường",
        "A: 熱が あります。 (nêu sự việc)　vs　B: 熱が あるんです。 (giải thích, có ẩn ý)",
        "Câu A chỉ đơn thuần THÔNG BÁO. Câu B ẩn ý: 'đây là LÝ DO cho việc gì đó bạn vừa thấy/hỏi' "
        "— thường xuất hiện sau một câu hỏi hoặc một tình huống cần giải thích.",
        [
            ex(L, 3, 1, [t("t-l26s3-1", "かお", "顔", "かお"), t("t-l26s3-2", "いろ", "色", "いろ"),
                         t("t-l26s3-3", "が"), t("t-l26s3-4", "わるい", "悪い", "わるい"), t("t-l26s3-5", "です"),
                         t("t-l26s3-6", "ね"), t("t-l26s3-7", "。"), t("t-l26s3-8", "どうしたんです", key=True),
                         t("t-l26s3-9", "か")],
               "Sắc mặt anh không tốt nhỉ. Có chuyện gì vậy?"),
            ex(L, 3, 2, [t("t-l26s3-10", "じつは", "実は", "じつは"), t("t-l26s3-11", "、"),
                         t("t-l26s3-12", "きのう", "昨日", "きのう"), t("t-l26s3-13", "から"),
                         t("t-l26s3-14", "ねつ", "熱", "ねつ"), t("t-l26s3-15", "が"),
                         t("t-l26s3-16", "あるんです", key=True)],
               "Thật ra là từ hôm qua tôi bị sốt."),
        ],
        tips="どうしたんですか là câu hỏi thăm hỏi tự nhiên khi thấy ai đó có vẻ khác thường — lịch sự hơn hẳn どうしましたか đơn thuần.",
        culture="実は (thật ra là) thường mở đầu câu trả lời có んです — báo hiệu sắp tiết lộ lý do/bí mật gì đó."),

    slide(L, 4,
        "4. Tự động từ trong câu んです: 壊れます / 治ります",
        "N が [tự động từ] んです   (vật TỰ xảy ra trạng thái, không ai tác động)",
        "壊れます (tự hỏng) và 治ります (tự khỏi) là TỰ ĐỘNG TỪ — chủ ngữ tự trải qua thay đổi, "
        "không cần ai gây ra. Cấu trúc này sẽ được học kỹ hơn ở bài 29.",
        [
            ex(L, 4, 1, [t("t-l26s4-1", "パソコン"), t("t-l26s4-2", "が"),
                         t("t-l26s4-3", "こわれた", "壊れた", "こわれた", key=True), t("t-l26s4-4", "んです", key=True)],
               "Máy tính bị hỏng rồi."),
            ex(L, 4, 2, [t("t-l26s4-5", "かぜ", "風邪", "かぜ"), t("t-l26s4-6", "が"),
                         t("t-l26s4-7", "もう"), t("t-l26s4-8", "なおった", "治った", "なおった", key=True),
                         t("t-l26s4-9", "んです", key=True)],
               "Cảm cúm của tôi đã khỏi rồi."),
        ],
        tips="Chú ý 壊れる (tự hỏng, không ai làm hỏng) khác 壊す (làm hỏng, có người tác động) — cặp tự động từ/tha động từ sẽ học đầy đủ ở bài 29.",
        culture="Báo hỏng thiết bị ở công ty Nhật thường dùng んです để nhấn mạnh đây không phải lỗi của người báo cáo: パソコンが壊れたんです (máy TỰ hỏng)."),
]

DIALOGUE = [
    line(L, 1, "田中", "Đồng nghiệp",
         [t("d-l26-1", "山田さん"), t("d-l26-2", "、"), t("d-l26-3", "かお", "顔", "かお"), t("d-l26-4", "いろ", "色", "いろ"),
          t("d-l26-5", "が"), t("d-l26-6", "わるい", "悪い", "わるい"), t("d-l26-7", "ですね"), t("d-l26-8", "。"),
          t("d-l26-9", "どうしたんです", key=True), t("d-l26-10", "か")],
         "Anh Yamada, sắc mặt anh không tốt nhỉ. Có chuyện gì vậy?"),
    line(L, 2, "山田", "Nhân viên công ty",
         [t("d-l26-11", "じつは", "実は", "じつは"), t("d-l26-12", "、"), t("d-l26-13", "きのう", "昨日", "きのう"),
          t("d-l26-14", "から"), t("d-l26-15", "ねつ", "熱", "ねつ", key=True), t("d-l26-16", "が"),
          t("d-l26-17", "あるんです", key=True)],
         "Thật ra là từ hôm qua tôi bị sốt."),
    line(L, 3, "田中", "Đồng nghiệp",
         [t("d-l26-18", "びょういん", "病院", "びょういん", key=True), t("d-l26-19", "に"), t("d-l26-20", "いった", "行った", "いった"),
          t("d-l26-21", "んです", key=True), t("d-l26-22", "か")],
         "Anh đã đi bệnh viện chưa?"),
    line(L, 4, "山田", "Nhân viên công ty",
         [t("d-l26-23", "はい"), t("d-l26-24", "。"), t("d-l26-25", "でも"), t("d-l26-26", "、"),
          t("d-l26-27", "まだ"), t("d-l26-28", "なおって", "治って", "なおって"), t("d-l26-29", "いません"), t("d-l26-30", "。"),
          t("d-l26-31", "きょう", "今日", "きょう"), t("d-l26-32", "は"), t("d-l26-33", "はやく"),
          t("d-l26-34", "かえっても", "帰っても", "かえっても"), t("d-l26-35", "いいですか")],
         "Vâng, tôi đã đi rồi. Nhưng vẫn chưa khỏi. Hôm nay tôi về sớm được không?"),
    line(L, 5, "田中", "Đồng nghiệp",
         [t("d-l26-36", "もちろん"), t("d-l26-37", "です"), t("d-l26-38", "。"), t("d-l26-39", "しっかり", "しっかり", "しっかり", key=True),
          t("d-l26-40", "やすんで", "休んで", "やすんで"), t("d-l26-41", "ください")],
         "Tất nhiên rồi. Anh nghỉ ngơi cho kỹ nhé."),
    line(L, 6, "山田", "Nhân viên công ty",
         [t("d-l26-42", "ありがとう"), t("d-l26-43", "ございます"), t("d-l26-44", "。"), t("d-l26-45", "あ"),
          t("d-l26-46", "、"), t("d-l26-47", "きょう", "今日", "きょう"), t("d-l26-48", "の"), t("d-l26-49", "かいぎ", "会議", "かいぎ", key=True),
          t("d-l26-50", "は"), t("d-l26-51", "どうしましょうか")],
         "Cảm ơn chị. À, cuộc họp hôm nay thì tính sao đây?"),
    line(L, 7, "田中", "Đồng nghiệp",
         [t("d-l26-52", "しんぱい", "心配", "しんぱい"), t("d-l26-53", "しないで", "しないで", "しないで"), t("d-l26-54", "ください"),
          t("d-l26-55", "。"), t("d-l26-56", "わたし", "私", "わたし"), t("d-l26-57", "が"), t("d-l26-58", "やります")],
         "Đừng lo, để tôi lo phần đó cho."),
    line(L, 8, "山田", "Nhân viên công ty",
         [t("d-l26-59", "たすかります", "助かります", "たすかります"), t("d-l26-60", "。"), t("d-l26-61", "じつは", "実は", "じつは"),
          t("d-l26-62", "、"), t("d-l26-63", "けさ", "今朝", "けさ"), t("d-l26-64", "も"), t("d-l26-65", "でんしゃ", "電車", "でんしゃ", key=True),
          t("d-l26-66", "が"), t("d-l26-67", "おくれた", "遅れた", "おくれた", key=True), t("d-l26-68", "んです", key=True)],
         "Cảm ơn chị nhiều. Thật ra sáng nay tàu điện cũng bị trễ nữa."),
    line(L, 9, "田中", "Đồng nghiệp",
         [t("d-l26-69", "たいへんでした", "大変でした", "たいへんでした"), t("d-l26-70", "ね"), t("d-l26-71", "。"),
          t("d-l26-72", "じこ", "事故", "じこ", key=True), t("d-l26-73", "が"), t("d-l26-74", "あったんです", key=True), t("d-l26-75", "か")],
         "Vất vả thật đấy nhỉ. Có tai nạn gì à?"),
    line(L, 10, "山田", "Nhân viên công ty",
         [t("d-l26-76", "はい"), t("d-l26-77", "、"), t("d-l26-78", "そうらしい"), t("d-l26-79", "です"), t("d-l26-80", "。"),
          t("d-l26-81", "やっぱり", "やっぱり", "やっぱり", key=True), t("d-l26-82", "けさ", "今朝", "けさ"),
          t("d-l26-83", "は"), t("d-l26-84", "つき", "月", "つき"), t("d-l26-85", "が"), t("d-l26-86", "わるい", "悪い", "わるい"),
          t("d-l26-87", "です"), t("d-l26-88", "ね")],
         "Vâng, hình như vậy. Quả nhiên hôm nay không phải là ngày may mắn."),
]

EXERCISES = [
    q(L, 1, "「どうしたんですか」 khác 「どうしましたか」 ở chỗ:",
      ["んですか mềm mại, thân thiện hơn khi hỏi lý do một tình huống đã quan sát thấy",
       "Hoàn toàn giống nhau", "んですか là câu ra lệnh",
       "どうしましたか không đúng ngữ pháp"], 0,
      "んですか thêm sắc thái quan tâm, hỏi về NGUYÊN NHÂN của điều đã nhận thấy — tự nhiên hơn trong giao tiếp.",
      "Xem ngữ cảnh sử dụng ở slide 3."),
    q(L, 2, "「熱が あるんです」 dùng khi nào?",
      ["Giải thích lý do cho một tình huống đã được hỏi/nhận thấy (vd: sắc mặt xấu)",
       "Chỉ đơn thuần thông báo có sốt, không liên quan gì trước đó",
       "Ra lệnh ai đó phải bị sốt", "Hỏi có ai bị sốt không"], 0,
      "んです luôn gắn với một BỐI CẢNH cần giải thích — không dùng để mở đầu chủ đề hoàn toàn mới.",
      "So sánh với câu 「熱があります」 đơn thuần."),
    q(L, 3, "「病気なんですか」 — vì sao có な trước んです?",
      ["病気 là danh từ, cần thêm な trước んです (giống tính từ な)",
       "な là lỗi thừa", "病気 phải chia thành 病気だ trước",
       "Chỉ tính từ mới cần な, danh từ thì không"], 0,
      "Danh từ và tính từ な cần thêm な trước んです: N/な-adj + なんです.",
      "So sánh với thể thông thường của danh từ/tính từ な đã học ở N5 bài 20."),
    q(L, 4, "Câu nào dùng んです để XIN PHÉP một cách có lý do?",
      ["具合が悪いんですが、帰ってもいいですか", "具合が悪いです。帰ります",
       "具合が悪いので帰れ", "具合が悪いですか"], 0,
      "んですが + xin phép là cấu trúc chuẩn: nêu lý do trước, rồi mới xin phép — nghe lịch sự và có căn cứ hơn.",
      "Xem cấu trúc ở slide 2."),
    q(L, 5, "壊れます là loại động từ nào?",
      ["Tự động từ (vật tự hỏng, không cần ai tác động)",
       "Tha động từ (cần người làm hỏng)", "Động từ nhóm 3 bất quy tắc",
       "Tính từ"], 0,
      "壊れる là tự động từ — chủ ngữ (máy tính) TỰ trải qua trạng thái hỏng, không có tác nhân gây ra được nói tới.",
      "Sẽ học kỹ hơn về cặp tự/tha động từ ở bài 29."),
    q(L, 6, "「実は」 thường xuất hiện ở đâu trong câu có んです?",
      ["Đầu câu trả lời, báo hiệu sắp tiết lộ lý do/thông tin ẩn",
       "Cuối câu hỏi", "Chỉ dùng trong câu phủ định",
       "Không có vị trí cố định nào"], 0,
      "実は (thật ra là) mở đầu câu trả lời có んです, báo hiệu người nói sắp giải thích điều gì đó chưa nói ra.",
      "Xem ví dụ ở slide 3 và hội thoại."),
    q(L, 7, "「電車が遅れたんです。すみません」 — んです ở đây có tác dụng gì?",
      ["Giải thích LÝ DO cho việc đến muộn (xin lỗi có căn cứ)",
       "Ra lệnh tàu điện phải trễ", "Hỏi tàu điện có trễ không",
       "Không có tác dụng gì đặc biệt"], 0,
      "んです giải thích nguyên nhân của việc đến muộn, làm lời xin lỗi có căn cứ, dễ được thông cảm hơn.",
      "Xem văn hóa xin lỗi có giải thích ở slide 2."),
    q(L, 8, "とうとう và やっぱり khác nhau ở:",
      ["とうとう = cuối cùng thì (sau một quá trình); やっぱり = đúng như dự đoán",
       "Hoàn toàn giống nhau", "とうとう chỉ dùng cho câu phủ định",
       "やっぱり chỉ dùng cho câu hỏi"], 0,
      "とうとう nhấn mạnh kết quả SAU một thời gian dài chờ đợi; やっぱり nhấn mạnh việc ĐÃ ĐOÁN TRƯỚC đúng như vậy.",
      "Xem nghĩa riêng của từng phó từ ở phần từ vựng."),
    q(L, 9, "Trong hội thoại, vì sao Yamada muốn về sớm?",
      ["Vì bị sốt từ hôm qua", "Vì có việc gia đình", "Vì tàu điện trễ", "Vì cuộc họp bị hủy"], 0,
      "Yamada nói 「実は、昨日から熱があるんです」.",
      "Xem câu thoại thứ 2."),
    q(L, 10, "Sáng hôm đó Yamada gặp chuyện gì trên đường đi làm?",
      ["Tàu điện bị trễ vì có tai nạn", "Xe hỏng giữa đường", "Ngủ quên",
       "Không gặp chuyện gì cả"], 0,
      "Yamada nói 「電車が遅れたんです」 và Tanaka hỏi 「事故があったんですか」, được xác nhận là đúng.",
      "Xem các câu thoại cuối cùng."),
]

LESSON = lesson(
    L,
    "Bài 26: Giải thích lý do & Nhấn mạnh (〜んです)",
    "Bài mở đầu N4: dùng んです để giải thích bối cảnh/nguyên nhân của một tình huống đã được "
    "quan sát/hỏi tới (khác です/ます đơn thuần thông báo), xin phép có lý do bằng んですが, và "
    "giới thiệu khái niệm tự động từ (壊れる, 治る) sẽ học kỹ ở bài 29.",
    VOCAB, KANJI, SLIDES, DIALOGUE, EXERCISES,
)

if __name__ == "__main__":
    pool.mark_used([w["word"] for w in VOCAB], lesson=L)
    merge([LESSON])
