# -*- coding: utf-8 -*-
"""N5 — Bài 10: Tồn tại của vật (あります) và sinh vật (います), từ chỉ vị trí.

Tu vung minh hoa TU CHON tu pool mo data/jlpt-vocab/n5.csv (xem NOTICE.md).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from n5_lib import v, k, t, ex, slide, line, q, lesson, merge
from jlpt_pool import Pool

L = 10
pool = Pool("n5")

VOCAB = [
    v(1,  "あります", "有ります", "あります", "arimasu", "verb", "Có, tồn tại (vật vô tri, thực vật)", "Chia giống động từ nhóm 1 bình thường.", L),
    v(2,  "います", "居ます", "います", "imasu", "verb", "Có, tồn tại (người, động vật)", "Chỉ dùng cho SINH VẬT SỐNG có thể tự di chuyển.", L),
    v(3,  "うえ", "上", "うえ", "ue", "noun", "Trên, phía trên", "Đã gặp kanji ở bài 3, nay dùng làm từ chỉ vị trí độc lập.", L),
    v(4,  "した", "下", "した", "shita", "noun", "Dưới, phía dưới", "Trái nghĩa với 上.", L),
    v(5,  "まえ", "前", "まえ", "mae", "noun", "Trước, phía trước", "駅の前 = trước ga.", L),
    v(6,  "うしろ", "後ろ", "うしろ", "ushiro", "noun", "Sau, phía sau", "Trái nghĩa với 前.", L),
    v(7,  "なか", "中", "なか", "naka", "noun", "Trong, giữa", "箱の中 = trong hộp.", L),
    v(8,  "そと", "外", "そと", "soto", "noun", "Ngoài", "Đã gặp kanji bài 3.", L),
    v(9,  "となり", "隣", "となり", "tonari", "noun", "Bên cạnh, liền kề", "銀行の隣 = bên cạnh ngân hàng.", L),
    v(10, "ちかく", "近く", "ちかく", "chikaku", "noun", "Gần, khu vực gần đây", "駅の近く = gần ga.", L),
    v(11, "あいだ", "間", "あいだ", "aida", "noun", "Giữa (hai vật)", "AとBの間 = giữa A và B.", L),
    v(12, "つくえ", "机", "つくえ", "tsukue", "noun", "Cái bàn", "Đã gặp bài 2 (đồ vật) — nay dùng làm mốc chỉ vị trí.", L),
    v(13, "いす", "椅子", "いす", "isu", "noun", "Cái ghế", "Đã gặp bài 2.", L),
    v(14, "はこ", "箱", "はこ", "hako", "noun", "Cái hộp", "", L),
    v(15, "かびん", "花瓶", "かびん", "kabin", "noun", "Bình hoa", "", L),
    v(16, "き", "木", "き", "ki", "noun", "Cây", "Vật vô tri về mặt ngữ pháp — dùng あります dù là sinh vật sống về mặt sinh học.", L),
    v(17, "いぬ", "犬", "いぬ", "inu", "noun", "Con chó", "Dùng います.", L),
    v(18, "ねこ", "猫", "ねこ", "neko", "noun", "Con mèo", "Dùng います.", L),
    v(19, "とり", "鳥", "とり", "tori", "noun", "Con chim", "Dùng います.", L),
    v(20, "ぎんこう", "銀行", "ぎんこう", "ginkou", "noun", "Ngân hàng", "Đã gặp bài 4 — nay dùng làm mốc vị trí.", L),
    v(21, "なんですか", "何ですか", "なんですか", "nan desu ka", "phrase", "Là cái gì vậy?", "Hỏi xác nhận đồ vật.", L),
    v(22, "だれですか", "誰ですか", "だれですか", "dare desu ka", "phrase", "Là ai vậy?", "Hỏi xác nhận người.", L),
]

KANJI = [
    k(1, "前", "TIỀN", 9, ["ゼン (zen)"], ["まえ"], "Trước, phía trước.",
      [("前", "まえ", "Phía trước"), ("午前", "ごぜん", "Buổi sáng"), ("名前", "なまえ", "Tên")], L),
    k(2, "後", "HẬU", 9, ["ゴ (go)", "コウ (kou)"], ["うし(ろ)", "あと"], "Sau, phía sau.",
      [("後ろ", "うしろ", "Phía sau"), ("午後", "ごご", "Buổi chiều"), ("後で", "あとで", "Lát nữa")], L),
    k(3, "中", "TRUNG", 4, ["チュウ (chuu)"], ["なか"], "Trong, giữa. Đã gặp ở bài 3.",
      [("中", "なか", "Bên trong"), ("一日中", "いちにちじゅう", "Suốt cả ngày"), ("中国", "ちゅうごく", "Trung Quốc")], L),
    k(4, "間", "GIAN", 12, ["カン (kan)"], ["あいだ", "ま"], "Khoảng giữa, khoảng thời gian. Bộ 門 (cửa) + 日 (mặt trời).",
      [("間", "あいだ", "Khoảng giữa"), ("時間", "じかん", "Thời gian"), ("人間", "にんげん", "Con người")], L),
    k(5, "外", "NGOẠI", 5, ["ガイ (gai)"], ["そと"], "Bên ngoài. Đã gặp ở bài 3.",
      [("外", "そと", "Bên ngoài"), ("外国", "がいこく", "Nước ngoài"), ("外国人", "がいこくじん", "Người nước ngoài")], L),
]

SLIDES = [
    slide(L, 1,
        "1. Vật vô tri: N[nơi] に N[vật] が あります",
        "[Nơi chốn] + に + [Vật] + が + あります",
        "あります dùng cho VẬT KHÔNG TỰ DI CHUYỂN được: đồ vật, thực vật, tòa nhà. に đánh dấu "
        "nơi tồn tại, khác với で (nơi hành động) đã học ở bài 6 — đây là câu MIÊU TẢ, không phải hành động.",
        [
            ex(L, 1, 1, [t("t-l10s1-1", "つくえ", "机", "つくえ"), t("t-l10s1-2", "の"),
                         t("t-l10s1-3", "うえ", "上", "うえ", key=True), t("t-l10s1-4", "に", key=True),
                         t("t-l10s1-5", "ほん", "本", "ほん"), t("t-l10s1-6", "が"),
                         t("t-l10s1-7", "あります", "有ります", "あります", key=True)],
               "Trên bàn có quyển sách."),
            ex(L, 1, 2, [t("t-l10s1-8", "はこ", "箱", "はこ"), t("t-l10s1-9", "の"),
                         t("t-l10s1-10", "なか", "中", "なか", key=True), t("t-l10s1-11", "に", key=True),
                         t("t-l10s1-12", "なに", "何", "なに", key=True), t("t-l10s1-13", "が"),
                         t("t-l10s1-14", "ありますか", "有りますか", "ありますか")],
               "Trong hộp có gì vậy?"),
        ],
        tips="に (nơi tồn tại, tĩnh) khác で (nơi hành động, động) — 机にあります vs 食堂で食べます.",
        culture="木 (cây) tuy là sinh vật sống nhưng dùng あります vì KHÔNG TỰ DI CHUYỂN được — quy tắc dựa trên khả năng di chuyển, không phải sự sống."),

    slide(L, 2,
        "2. Sinh vật: N[nơi] に N[người/vật sống] が います",
        "[Nơi chốn] + に + [Người/động vật] + が + います",
        "います dùng cho NGƯỜI và ĐỘNG VẬT có thể tự di chuyển. Cùng cấu trúc に…が như あります, "
        "chỉ khác động từ tùy loại chủ thể.",
        [
            ex(L, 2, 1, [t("t-l10s2-1", "こうえん", "公園", "こうえん"), t("t-l10s2-2", "に", key=True),
                         t("t-l10s2-3", "いぬ", "犬", "いぬ"), t("t-l10s2-4", "が"),
                         t("t-l10s2-5", "います", "居ます", "います", key=True)],
               "Ở công viên có con chó."),
            ex(L, 2, 2, [t("t-l10s2-6", "きょうしつ", "教室", "きょうしつ"), t("t-l10s2-7", "に", key=True),
                         t("t-l10s2-8", "だれ", "誰", "だれ", key=True), t("t-l10s2-9", "が"),
                         t("t-l10s2-10", "いますか", "居ますか", "いますか")],
               "Trong lớp học có ai vậy?"),
        ],
        tips="Câu hỏi 何 dùng với あります, câu hỏi 誰 dùng với います — chọn động từ theo loại chủ thể được hỏi.",
        culture="Khi ai hỏi về gia đình: 「家族が いますか」 dùng います vì hỏi về NGƯỜI."),

    slide(L, 3,
        "3. Vị trí chi tiết: N の 上／下／前／後ろ／中",
        "[Vật mốc] + の + [từ chỉ vị trí]",
        "Cấu trúc の nối vật mốc với từ chỉ vị trí — giống の sở hữu đã học ở bài 2, nhưng ở đây "
        "diễn tả QUAN HỆ KHÔNG GIAN chứ không phải sở hữu.",
        [
            ex(L, 3, 1, [t("t-l10s3-1", "ねこ", "猫", "ねこ"), t("t-l10s3-2", "は"),
                         t("t-l10s3-3", "いす", "椅子", "いす"), t("t-l10s3-4", "の"),
                         t("t-l10s3-5", "した", "下", "した", key=True), t("t-l10s3-6", "に"),
                         t("t-l10s3-7", "います", "居ます", "います")],
               "Con mèo ở dưới ghế."),
            ex(L, 3, 2, [t("t-l10s3-8", "ぎんこう", "銀行", "ぎんこう"), t("t-l10s3-9", "は"),
                         t("t-l10s3-10", "としょかん", "図書館", "としょかん"), t("t-l10s3-11", "の"),
                         t("t-l10s3-12", "となり", "隣", "となり", key=True), t("t-l10s3-13", "に"),
                         t("t-l10s3-14", "あります", "有ります", "あります")],
               "Ngân hàng ở bên cạnh thư viện."),
            ex(L, 3, 3, [t("t-l10s3-15", "かびん", "花瓶", "かびん"), t("t-l10s3-16", "は"),
                         t("t-l10s3-17", "つくえ", "机", "つくえ"), t("t-l10s3-18", "と"),
                         t("t-l10s3-19", "いす", "椅子", "いす"), t("t-l10s3-20", "の"),
                         t("t-l10s3-21", "あいだ", "間", "あいだ", key=True), t("t-l10s3-22", "に"),
                         t("t-l10s3-23", "あります", "有ります", "あります")],
               "Bình hoa ở giữa bàn và ghế."),
        ],
        tips="間 luôn cần HAI mốc nối bằng と: AとBの間 — chỉ nói một mốc là sai ngữ pháp.",
        culture="Địa chỉ Nhật hay mô tả bằng vị trí tương đối (◯◯の隣, ◯◯の前) hơn là số nhà, đặc biệt ở khu phố cũ."),

    slide(L, 4,
        "4. Đảo trật tự: N[vật] は N[nơi] に あります／います",
        "[Vật/người đã biết] + は + [nơi chốn] + に + あります／います",
        "Khi VẬT đã được nhắc tới trước đó (chủ đề), đảo は lên đầu thay vì bắt đầu bằng nơi chốn. "
        "So sánh với câu ở slide 1-2 khi nơi chốn là thông tin đã biết, còn vật là thông tin mới.",
        [
            ex(L, 4, 1, [t("t-l10s4-1", "としょかん", "図書館", "としょかん"), t("t-l10s4-2", "は"),
                         t("t-l10s4-3", "どこ", key=True), t("t-l10s4-4", "に"),
                         t("t-l10s4-5", "ありますか", "有りますか", "ありますか")],
               "Thư viện ở đâu vậy?"),
            ex(L, 4, 2, [t("t-l10s4-6", "としょかん", "図書館", "としょかん"), t("t-l10s4-7", "は"),
                         t("t-l10s4-8", "えき", "駅", "えき"), t("t-l10s4-9", "の"),
                         t("t-l10s4-10", "ちかく", "近く", "ちかく", key=True), t("t-l10s4-11", "に"),
                         t("t-l10s4-12", "あります", "有ります", "あります")],
               "Thư viện ở gần nhà ga."),
        ],
        tips="Mẹo chọn cấu trúc: hỏi 'CÁI GÌ ở đâu đó' → dùng は đầu câu; hỏi 'ở đó CÓ GÌ' → dùng が như slide 1.",
        culture="ATM và コンビニ ở Nhật dùng cấu trúc chỉ vị trí này rất nhiều khi chỉ đường cho khách du lịch."),
]

DIALOGUE = [
    line(L, 1, "ワン", "Sinh viên",
         [t("d-l10-1", "すみません"), t("d-l10-2", "、"), t("d-l10-3", "としょかん", "図書館", "としょかん"),
          t("d-l10-4", "は"), t("d-l10-5", "どこ", key=True), t("d-l10-6", "に"), t("d-l10-7", "ありますか", "有りますか", "ありますか")],
         "Xin lỗi, thư viện ở đâu vậy ạ?"),
    line(L, 2, "サントス", "Sinh viên",
         [t("d-l10-8", "ぎんこう", "銀行", "ぎんこう", key=True), t("d-l10-9", "の"),
          t("d-l10-10", "となり", "隣", "となり", key=True), t("d-l10-11", "に"),
          t("d-l10-12", "あります", "有ります", "あります")],
         "Ở bên cạnh ngân hàng."),
    line(L, 3, "ワン", "Sinh viên",
         [t("d-l10-13", "そうですか"), t("d-l10-14", "。"), t("d-l10-15", "ありがとう"),
          t("d-l10-16", "ございます"), t("d-l10-17", "。"), t("d-l10-18", "あ"), t("d-l10-19", "、"),
          t("d-l10-20", "こうえん", "公園", "こうえん"), t("d-l10-21", "に"), t("d-l10-22", "いぬ", "犬", "いぬ", key=True),
          t("d-l10-23", "が"), t("d-l10-24", "います", "居ます", "います", key=True), t("d-l10-25", "ね")],
         "Ra vậy. Cảm ơn nhiều. À, có con chó ở công viên kìa."),
    line(L, 4, "サントス", "Sinh viên",
         [t("d-l10-26", "ほんとう", "本当", "ほんとう"), t("d-l10-27", "ですか")],
         "Thật à?"),
    line(L, 5, "ワン", "Sinh viên",
         [t("d-l10-28", "ええ"), t("d-l10-29", "。"), t("d-l10-30", "き", "木", "き", key=True),
          t("d-l10-31", "の"), t("d-l10-32", "した", "下", "した", key=True), t("d-l10-33", "に"),
          t("d-l10-34", "います", "居ます", "います")],
         "Ừ. Nó ở dưới gốc cây."),
    line(L, 6, "サントス", "Sinh viên",
         [t("d-l10-35", "ねこ", "猫", "ねこ", key=True), t("d-l10-36", "も"), t("d-l10-37", "いますか", "居ますか", "いますか")],
         "Có cả mèo nữa không?"),
    line(L, 7, "ワン", "Sinh viên",
         [t("d-l10-38", "いいえ"), t("d-l10-39", "、"), t("d-l10-40", "ねこ", "猫", "ねこ"),
          t("d-l10-41", "は"), t("d-l10-42", "いません"), t("d-l10-43", "。"), t("d-l10-44", "でも"),
          t("d-l10-45", "とり", "鳥", "とり", key=True), t("d-l10-46", "が"), t("d-l10-47", "います", "居ます", "います")],
         "Không, không có mèo. Nhưng có chim."),
    line(L, 8, "サントス", "Sinh viên",
         [t("d-l10-48", "そうですか"), t("d-l10-49", "。"), t("d-l10-50", "ところで"),
          t("d-l10-51", "、"), t("d-l10-52", "かばん", "鞄", "かばん"), t("d-l10-53", "の"),
          t("d-l10-54", "なか", "中", "なか", key=True), t("d-l10-55", "に"), t("d-l10-56", "なに", "何", "なに", key=True),
          t("d-l10-57", "が"), t("d-l10-58", "ありますか", "有りますか", "ありますか")],
         "Ra vậy. À mà, trong cặp anh có gì vậy?"),
    line(L, 9, "ワン", "Sinh viên",
         [t("d-l10-59", "じしょ", "辞書", "じしょ"), t("d-l10-60", "と"), t("d-l10-61", "ノート"),
          t("d-l10-62", "が"), t("d-l10-63", "あります", "有ります", "あります")],
         "Có từ điển và vở."),
    line(L, 10, "サントス", "Sinh viên",
         [t("d-l10-64", "じゃ"), t("d-l10-65", "、"), t("d-l10-66", "いっしょに", "一緒に", "いっしょに"),
          t("d-l10-67", "べんきょう", "勉強", "べんきょう"), t("d-l10-68", "しませんか", key=True)],
         "Vậy, cùng học không?"),
]

EXERCISES = [
    q(L, 1, "Muốn nói 'trên bàn có sách', dùng động từ nào?",
      ["あります", "います", "です", "あげます"], 0,
      "本 (sách) là vật vô tri không tự di chuyển được, dùng あります.",
      "Xét chủ thể có tự di chuyển được không."),
    q(L, 2, "「公園に 猫が います」 — vì sao dùng います mà không dùng あります?",
      ["猫 là động vật, có thể tự di chuyển", "猫 là vật vô tri",
       "います chỉ dùng cho người", "Cả hai đều đúng như nhau"], 0,
      "います dành cho SINH VẬT SỐNG có khả năng tự di chuyển: người và động vật.",
      "Con mèo có tự di chuyển được không?"),
    q(L, 3, "木 (cây) tuy là sinh vật sống nhưng dùng động từ nào?",
      ["あります", "います", "Cả hai đều được", "Không dùng động từ nào"], 0,
      "Quy tắc あります/います dựa trên KHẢ NĂNG TỰ DI CHUYỂN, không phải sự sống sinh học — cây không tự di chuyển nên dùng あります.",
      "Đây là điểm hay gây nhầm lẫn nhất của bài này."),
    q(L, 4, "「机の 上に 本が あります」 — の ở đây có vai trò gì?",
      ["Nối vật mốc (机) với từ chỉ vị trí (上)", "Chỉ sở hữu như bài 2",
       "Là lỗi ngữ pháp, phải bỏ đi", "Chỉ dùng cho câu hỏi"], 0,
      "の ở đây nối vật mốc với từ chỉ vị trí, diễn tả quan hệ không gian — một chức năng khác của の ngoài sở hữu.",
      "So sánh với の sở hữu đã học ở bài 2."),
    q(L, 5, "Muốn nói 'bình hoa ở giữa bàn và ghế', câu nào ĐÚNG?",
      ["花瓶は 机と 椅子の 間に あります", "花瓶は 机の 間に あります",
       "花瓶は 机、椅子の 間に あります", "花瓶は 机や 椅子の 間に あります"], 0,
      "間 luôn cần HAI mốc nối bằng と: A と B の間 — thiếu một mốc hoặc sai trợ từ nối là sai ngữ pháp.",
      "間 cần đủ hai điểm mốc."),
    q(L, 6, "So sánh 「教室に 誰が いますか」 và 「教室に 何が ありますか」:",
      ["Một hỏi về NGƜỜI, một hỏi về VẬT", "Cả hai đều hỏi về vật",
       "Cả hai đều hỏi về người", "Không có gì khác nhau"], 0,
      "誰 (ai) dùng với います (hỏi người/sinh vật), 何 (gì) dùng với あります (hỏi vật vô tri).",
      "Xem từ để hỏi đi kèm động từ nào."),
    q(L, 7, "「図書館は どこに ありますか」 khác với 「どこに 図書館が ありますか」 ở:",
      ["Câu đầu coi 図書館 là chủ đề đã biết, câu sau là hỏi thông tin mới hoàn toàn",
       "Câu đầu sai ngữ pháp", "Hoàn toàn giống nhau về sắc thái",
       "Câu sau chỉ dùng cho động vật"], 0,
      "は đưa vật/nơi đã biết lên làm chủ đề; が dùng khi thông tin còn mới, thường đi kèm hỏi 'ở đó có gì'.",
      "Xem lại slide 4 về đảo trật tự."),
    q(L, 8, "Trợ từ đánh dấu nơi tồn tại trong あります/います là:",
      ["に", "で", "を", "へ"], 0,
      "に đánh dấu nơi TỒN TẠI (tĩnh), khác で (nơi hành động, bài 6) và へ (hướng di chuyển, bài 5).",
      "So sánh ba trợ từ nơi chốn đã học."),
    q(L, 9, "「猫は いません」 nghĩa là:",
      ["Không có mèo (phủ định います)", "Có mèo",
       "Con mèo không thích", "Con mèo không đến"], 0,
      "いません là dạng phủ định của います — báo KHÔNG CÓ sinh vật đó.",
      "Xem dạng phủ định của います."),
    q(L, 10, "Trong hội thoại, con chó ở vị trí nào trong công viên?",
      ["Dưới gốc cây", "Trên ghế", "Bên cạnh ngân hàng", "Trong hộp"], 0,
      "ワン nói con chó 木の下に います (ở dưới gốc cây).",
      "Xem lại câu thoại thứ 5."),
]

LESSON = lesson(
    L,
    "Bài 10: Tồn tại Người & Vật (あります / います & Từ chỉ vị trí)",
    "Phân biệt あります (vật vô tri, không tự di chuyển — kể cả cây) với います (người, động vật "
    "có thể tự di chuyển), cấu trúc [nơi]に[vật]が có/tồn tại, các từ chỉ vị trí 上/下/前/後ろ/中/隣/"
    "近く/間 nối bằng の, và cách đảo trật tự khi vật là chủ đề đã biết.",
    VOCAB, KANJI, SLIDES, DIALOGUE, EXERCISES,
)

if __name__ == "__main__":
    pool.mark_used([w["word"] for w in VOCAB], lesson=L)
    merge([LESSON])
