# -*- coding: utf-8 -*-
"""N5 — Bài 3 (Minna no Nihongo I): Nơi chốn, vị trí và hỏi giá."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from n5_lib import v, k, t, ex, slide, line, q, lesson, merge

L = 3

VOCAB = [
    v(1,  "ここ", "", "", "koko", "noun", "Chỗ này, ở đây (nơi người nói đang đứng)", "Bộ ba こ - そ - あ lặp lại như bài 2.", L),
    v(2,  "そこ", "", "", "soko", "noun", "Chỗ đó (nơi người nghe đang đứng)", "Gần đối phương.", L),
    v(3,  "あそこ", "", "", "asoko", "noun", "Chỗ kia (xa cả hai người)", "Chú ý: あそこ chứ KHÔNG phải あこ.", L),
    v(4,  "どこ", "", "", "doko", "noun", "Ở đâu (từ để hỏi nơi chốn)", "Nhóm ど luôn là từ để hỏi.", L),
    v(5,  "こちら", "", "", "kochira", "noun", "Phía này, đằng này (lịch sự)", "Vừa chỉ hướng vừa thay cho ここ khi cần lịch sự.", L),
    v(6,  "そちら", "", "", "sochira", "noun", "Phía đó, đằng đó (lịch sự)", "Dùng với khách, người trên.", L),
    v(7,  "あちら", "", "", "achira", "noun", "Phía kia, đằng kia (lịch sự)", "Nhân viên cửa hàng dùng suốt.", L),
    v(8,  "どちら", "", "", "dochira", "noun", "Phía nào, ở đâu ạ (lịch sự)", "Hỏi quê quán, công ty thì bắt buộc dùng どちら.", L),
    v(9,  "きょうしつ", "教室", "きょうしつ", "kyoushitsu", "noun", "Phòng học, lớp học", "教 (dạy) + 室 (phòng).", L),
    v(10, "しょくどう", "食堂", "しょくどう", "shokudou", "noun", "Nhà ăn, căng tin", "食 (ăn) + 堂 (sảnh).", L),
    v(11, "じむしょ", "事務所", "じむしょ", "jimusho", "noun", "Văn phòng", "Nơi làm giấy tờ, hành chính.", L),
    v(12, "かいぎしつ", "会議室", "かいぎしつ", "kaigishitsu", "noun", "Phòng họp", "会議 = cuộc họp.", L),
    v(13, "うけつけ", "受付", "うけつけ", "uketsuke", "noun", "Quầy lễ tân, quầy tiếp đón", "Vào tòa nhà Nhật là ghé 受付 trước.", L),
    v(14, "へや", "部屋", "へや", "heya", "noun", "Căn phòng", "Trọng âm rơi vào や.", L),
    v(15, "トイレ", "", "", "toire", "noun", "Nhà vệ sinh", "Lịch sự hơn: お手洗い (おてあらい).", L),
    v(16, "かいだん", "階段", "かいだん", "kaidan", "noun", "Cầu thang bộ", "階 (tầng) + 段 (bậc).", L),
    v(17, "エレベーター", "", "", "erebeetaa", "noun", "Thang máy", "Kéo dài cả ベー lẫn ター.", L),
    v(18, "エスカレーター", "", "", "esukareetaa", "noun", "Thang cuốn", "Osaka đứng bên phải, Tokyo đứng bên trái.", L),
    v(19, "くに", "国", "くに", "kuni", "noun", "Đất nước, quê hương", "Hỏi lịch sự thì thêm お: お国.", L),
    v(20, "かいしゃ", "会社", "かいしゃ", "kaisha", "noun", "Công ty", "会 (hội) + 社 (xã).", L),
    v(21, "うち", "家", "うち", "uchi", "noun", "Nhà mình, nhà (của ai đó)", "うち còn nghĩa là 'phe mình, công ty mình'.", L),
    v(22, "でんわ", "電話", "でんわ", "denwa", "noun", "Điện thoại, cuộc gọi", "電 (điện) + 話 (thoại).", L),
    v(23, "くつ", "靴", "くつ", "kutsu", "noun", "Giày", "Vào nhà Nhật là cởi giày ngay ở 玄関.", L),
    v(24, "ネクタイ", "", "", "nekutai", "noun", "Cà vạt", "Từ tiếng Anh necktie.", L),
    v(25, "ワイン", "", "", "wain", "noun", "Rượu vang", "Đọc wa-in, hai nhịp.", L),
    v(26, "うりば", "売り場", "うりば", "uriba", "noun", "Quầy bán hàng, khu bán ~", "売る (bán) + 場 (chỗ).", L),
    v(27, "ちか", "地下", "ちか", "chika", "noun", "Tầng hầm, dưới lòng đất", "地下一階 = tầng hầm 1.", L),
    v(28, "〜かい", "〜階", "〜かい", "-kai", "noun", "Tầng thứ ~", "1階 いっかい, 3階 さんがい, 6階 ろっかい.", L),
    v(41, "なんがい", "何階", "なんがい", "nangai", "noun", "Tầng mấy", "Biến âm thành がい. なんかい nghĩa là 'mấy lần'.", L),
    v(42, "ロビー", "", "", "robii", "noun", "Sảnh lớn, hành lang tiếp khách", "Sảnh khách sạn, tòa nhà văn phòng.", L),
    v(43, "イタリア", "", "", "Itaria", "noun", "Nước Ý", "Danh từ riêng, viết Katakana.", L),
    v(44, "スイス", "", "", "Suisu", "noun", "Thụy Sĩ", "Nổi tiếng về đồng hồ — hay gặp trong bài này.", L),
    v(45, "しんおおさか", "新大阪", "しんおおさか", "Shin-Oosaka", "noun", "Ga Shin-Osaka", "Ga tàu Shinkansen ở Osaka.", L),
    v(29, "〜えん", "〜円", "〜えん", "-en", "noun", "~ yên (tiền Nhật)", "Viết ký hiệu ¥ hoặc 円.", L),
    v(30, "いくら", "", "", "ikura", "noun", "Bao nhiêu tiền", "Chỉ hỏi GIÁ. Hỏi số lượng thì dùng いくつ.", L),
    v(31, "ひゃく", "百", "ひゃく", "hyaku", "noun", "Một trăm", "300 さんびゃく, 600 ろっぴゃく, 800 はっぴゃく.", L),
    v(32, "せん", "千", "せん", "sen", "noun", "Một nghìn", "3000 さんぜん, 8000 はっせん.", L),
    v(33, "まん", "万", "まん", "man", "noun", "Một vạn (10.000)", "Người Nhật đếm theo VẠN, không theo nghìn.", L),
    v(34, "すみません", "", "", "sumimasen", "phrase", "Xin lỗi / cho hỏi / cảm ơn", "Câu vạn năng: gọi người, xin lỗi, và cả cảm ơn.", L),
    v(35, "[〜を]ください", "", "", "[~o] kudasai", "phrase", "Cho tôi ~ (khi mua, khi gọi món)", "Chỉ tay vào vật rồi nói これを ください.", L),
    v(36, "みせてください", "見せて ください", "みせて ください", "misete kudasai", "phrase", "Cho tôi xem thử với", "Câu cửa miệng khi đi mua sắm.", L),
    v(37, "じゃ", "", "", "ja", "phrase", "Vậy thì, thế thì", "Dạng nói tắt của では.", L),
    v(38, "〜でございます", "", "", "-de gozaimasu", "phrase", "Là ~ (kính ngữ của です)", "Nhân viên bán hàng nói với khách.", L),
    v(39, "おてあらい", "お手洗い", "おてあらい", "otearai", "noun", "Nhà vệ sinh (cách nói lịch sự)", "Nghĩa đen: chỗ rửa tay.", L),
    v(40, "たばこ", "煙草", "たばこ", "tabako", "noun", "Thuốc lá", "たばこを 吸います = hút thuốc.", L),
]

KANJI = [
    k(1, "上", "THƯỢNG", 3, ["ジョウ (jou)"], ["うえ", "あ(がる)"], "Ở trên, phía trên. Một vạch nhô LÊN khỏi đường ngang.",
      [("上", "うえ", "Phía trên"), ("上手", "じょうず", "Giỏi, khéo"), ("屋上", "おくじょう", "Sân thượng")], L),
    k(2, "下", "HẠ", 3, ["カ (ka)", "ゲ (ge)"], ["した", "さ(がる)"], "Ở dưới, phía dưới. Ngược hẳn với 上.",
      [("下", "した", "Phía dưới"), ("地下", "ちか", "Tầng hầm"), ("下手", "へた", "Kém, vụng")], L),
    k(3, "中", "TRUNG", 4, ["チュウ (chuu)"], ["なか"], "Ở giữa, bên trong. Một vạch xuyên qua giữa khung.",
      [("中", "なか", "Bên trong"), ("中国", "ちゅうごく", "Trung Quốc"), ("食事中", "しょくじちゅう", "Đang dùng bữa")], L),
    k(4, "外", "NGOẠI", 5, ["ガイ (gai)"], ["そと"], "Bên ngoài, nước ngoài.",
      [("外", "そと", "Bên ngoài"), ("外国", "がいこく", "Nước ngoài"), ("外国人", "がいこくじん", "Người nước ngoài")], L),
    k(5, "国", "QUỐC", 8, ["コク (koku)"], ["くに"], "Đất nước. Vua (玉) nằm trong vòng biên giới khép kín.",
      [("国", "くに", "Đất nước"), ("外国", "がいこく", "Nước ngoài"), ("中国", "ちゅうごく", "Trung Quốc")], L),
    k(6, "会", "HỘI", 6, ["カイ (kai)"], ["あ(う)"], "Gặp gỡ, hội họp.",
      [("会社", "かいしゃ", "Công ty"), ("会議", "かいぎ", "Cuộc họp"), ("会います", "あいます", "Gặp mặt")], L),
    k(7, "社", "XÃ", 7, ["シャ (sha)"], ["やしろ"], "Công ty, đoàn thể; đền thờ Thần đạo.",
      [("会社", "かいしゃ", "Công ty"), ("社員", "しゃいん", "Nhân viên"), ("神社", "じんじゃ", "Đền thờ")], L),
    k(8, "円", "VIÊN", 4, ["エン (en)"], ["まる(い)"], "Tròn; đồng yên Nhật.",
      [("円", "えん", "Đồng yên"), ("一万円", "いちまんえん", "Một vạn yên"), ("円い", "まるい", "Tròn")], L),
]

SLIDES = [
    slide(L, 1,
        "1. ここ / そこ / あそこ は N です",
        "ここ / そこ / あそこ + は + [Nơi chốn] + です",
        "Bộ ba nơi chốn chạy đúng luật こ - そ - あ của bài 2: ここ chỗ người nói đứng, "
        "そこ chỗ người nghe đứng, あそこ chỗ xa cả hai. Từ để hỏi tương ứng là どこ.",
        [
            ex(L, 1, 1, [t("t-l3s1-1", "ここ", key=True), t("t-l3s1-2", "は"),
                         t("t-l3s1-3", "しょくどう", "食堂", "しょくどう"), t("t-l3s1-4", "です")],
               "Ở đây là nhà ăn."),
            ex(L, 1, 2, [t("t-l3s1-5", "そこ", key=True), t("t-l3s1-6", "は"),
                         t("t-l3s1-7", "かいぎしつ", "会議室", "かいぎしつ"), t("t-l3s1-8", "です")],
               "Chỗ đó là phòng họp."),
            ex(L, 1, 3, [t("t-l3s1-9", "あそこ", key=True), t("t-l3s1-10", "は"),
                         t("t-l3s1-11", "うけつけ", "受付", "うけつけ"), t("t-l3s1-12", "です")],
               "Đằng kia là quầy lễ tân."),
        ],
        tips="Đừng đọc あそこ thành あこ — đây là lỗi phát âm phổ biến nhất của người Việt ở bài này.",
        culture="Khách vào tòa nhà Nhật luôn được hướng dẫn tới 受付 trước, không tự đi thẳng vào trong."),

    slide(L, 2,
        "2. Hỏi vị trí: N は どこですか",
        "N + は + どこ + ですか  →  N + は + ここ / そこ / あそこ + です",
        "Đảo lại mẫu 1: đưa nơi chốn ra sau, đưa ĐỒ VẬT hoặc NƠI cần tìm lên đầu câu. "
        "Câu hỏi có どこ thì KHÔNG đáp はい／いいえ, phải chỉ thẳng vị trí.",
        [
            ex(L, 2, 1, [t("t-l3s2-1", "トイレ"), t("t-l3s2-2", "は"),
                         t("t-l3s2-3", "どこ", key=True), t("t-l3s2-4", "ですか")],
               "Nhà vệ sinh ở đâu vậy ạ?"),
            ex(L, 2, 2, [t("t-l3s2-5", "あそこ", key=True), t("t-l3s2-6", "です")],
               "Ở đằng kia ạ."),
            ex(L, 2, 3, [t("t-l3s2-7", "エレベーター"), t("t-l3s2-8", "は"),
                         t("t-l3s2-9", "あちら", key=True), t("t-l3s2-10", "です")],
               "Thang máy ở phía bên kia ạ."),
        ],
        tips="Muốn hỏi đường cho lịch sự, mở đầu bằng すみません rồi mới đến câu hỏi.",
        culture="Hỏi nhà vệ sinh thì nói お手洗い nghe nhã hơn hẳn トイレ, nhất là ở nhà hàng."),

    slide(L, 3,
        "3. こちら / そちら / あちら / どちら (lịch sự)",
        "こちら / そちら / あちら / どちら + は + ... です",
        "Bộ này vừa chỉ HƯỚNG, vừa là bản LỊCH SỰ của ここ/そこ/あそこ/どこ. "
        "Nói chuyện với khách hàng, cấp trên, người lạ thì luôn ưu tiên bộ ちら.",
        [
            ex(L, 3, 1, [t("t-l3s3-1", "でんわ", "電話", "でんわ"), t("t-l3s3-2", "は"),
                         t("t-l3s3-3", "こちら", key=True), t("t-l3s3-4", "です")],
               "Điện thoại ở phía này ạ."),
            ex(L, 3, 2, [t("t-l3s3-5", "おてあらい", "お手洗い", "おてあらい"), t("t-l3s3-6", "は"),
                         t("t-l3s3-7", "そちら", key=True), t("t-l3s3-8", "です")],
               "Nhà vệ sinh ở phía đó ạ."),
            ex(L, 3, 3, [t("t-l3s3-9", "かいだん", "階段", "かいだん"), t("t-l3s3-10", "は"),
                         t("t-l3s3-11", "どちら", key=True), t("t-l3s3-12", "ですか")],
               "Cầu thang bộ ở phía nào ạ?"),
        ],
        tips="こちら còn dùng để GIỚI THIỆU người: 「こちらは 山田さんです」 = Đây là anh Yamada.",
        culture="Nhân viên Nhật chỉ đường bằng cả BÀN TAY ngửa, tuyệt đối không chỉ bằng một ngón trỏ."),

    slide(L, 4,
        "4. Hỏi lịch sự nơi thuộc về: お国は どちらですか",
        "お + [国 / 会社 / 大学] + は + どちら + ですか",
        "Hỏi quê quán, công ty, trường học của người khác thì dùng どちら chứ KHÔNG dùng どこ — "
        "どこ nghe cộc lốc. Thêm お phía trước danh từ để tỏ sự tôn trọng vật của người đối diện.",
        [
            ex(L, 4, 1, [t("t-l3s4-1", "おくに", "お国", "おくに", key=True), t("t-l3s4-2", "は"),
                         t("t-l3s4-3", "どちら", key=True), t("t-l3s4-4", "ですか")],
               "Anh/chị quê ở đâu ạ?"),
            ex(L, 4, 2, [t("t-l3s4-5", "ベトナム"), t("t-l3s4-6", "です")],
               "Tôi người Việt Nam ạ."),
            ex(L, 4, 3, [t("t-l3s4-7", "かいしゃ", "会社", "かいしゃ"), t("t-l3s4-8", "は"),
                         t("t-l3s4-9", "どちら", key=True), t("t-l3s4-10", "ですか")],
               "Anh/chị làm ở công ty nào ạ?"),
        ],
        tips="Chữ お chỉ gắn cho vật CỦA NGƯỜI KHÁC. Nói về mình phải bỏ お: 「国は ベトナムです」.",
        culture="Người Nhật hỏi 出身 (quê quán) rất sớm trong lần gặp đầu để tìm điểm chung."),

    slide(L, 5,
        "5. Vị trí trong tòa nhà: N は 〜階です",
        "N + は + [số] + 階 (かい) + です",
        "Chỉ tầng bằng 〜階. Cảnh giác biến âm: 1階 いっかい, 3階 さんがい, 6階 ろっかい, "
        "8階 はっかい, 10階 じゅっかい. Tầng hầm là 地下〜階.",
        [
            ex(L, 5, 1, [t("t-l3s5-1", "くつ", "靴", "くつ"), t("t-l3s5-2", "うりば", "売り場", "うりば"),
                         t("t-l3s5-3", "は"), t("t-l3s5-4", "ごかい", "5階", "ごかい", key=True), t("t-l3s5-5", "です")],
               "Quầy giày ở tầng 5."),
            ex(L, 5, 2, [t("t-l3s5-6", "しょくどう", "食堂", "しょくどう"), t("t-l3s5-7", "は"),
                         t("t-l3s5-8", "ちか", "地下", "ちか", key=True),
                         t("t-l3s5-9", "いっかい", "1階", "いっかい"), t("t-l3s5-10", "です")],
               "Nhà ăn ở tầng hầm 1."),
            ex(L, 5, 3, [t("t-l3s5-11", "じむしょ", "事務所", "じむしょ"), t("t-l3s5-12", "は"),
                         t("t-l3s5-13", "なんがい", "何階", "なんがい", key=True), t("t-l3s5-14", "ですか")],
               "Văn phòng ở tầng mấy vậy ạ?"),
        ],
        tips="Hỏi tầng mấy là 何階 (なんがい) — biến thành がい, đừng đọc なんかい (nghĩa là 'mấy lần').",
        culture="Nhiều tòa nhà Nhật không có tầng 4 vì 四 (し) đồng âm với 死 (chết)."),

    slide(L, 6,
        "6. Hỏi giá: いくらですか",
        "N + は + いくら + ですか  →  [số] + 円 + です",
        "いくら chỉ hỏi GIÁ TIỀN. Người Nhật đếm theo đơn vị VẠN (万) chứ không theo nghìn: "
        "30.000 đọc là 三万 (さんまん), không phải 'ba mươi nghìn'.",
        [
            ex(L, 6, 1, [t("t-l3s6-1", "この"), t("t-l3s6-2", "とけい", "時計", "とけい"), t("t-l3s6-3", "は"),
                         t("t-l3s6-4", "いくら", key=True), t("t-l3s6-5", "ですか")],
               "Cái đồng hồ này bao nhiêu tiền ạ?"),
            ex(L, 6, 2, [t("t-l3s6-6", "にまんはっせんえん", "2万8千円", "にまんはっせんえん", key=True),
                         t("t-l3s6-7", "です")],
               "28.000 yên ạ."),
            ex(L, 6, 3, [t("t-l3s6-8", "じゃ"), t("t-l3s6-9", "、"), t("t-l3s6-10", "これ"),
                         t("t-l3s6-11", "を"), t("t-l3s6-12", "ください", key=True)],
               "Vậy thì cho tôi cái này."),
        ],
        tips="Biến âm phải thuộc: 300 さんびゃく, 600 ろっぴゃく, 800 はっぴゃく, 3000 さんぜん, 8000 はっせん.",
        culture="Trả tiền ở Nhật thì đặt tiền vào KHAY nhỏ trên quầy, không đưa thẳng vào tay thu ngân."),
]

DIALOGUE = [
    line(L, 1, "マリア", "Khách mua hàng",
         [t("d-l3-1", "すみません", key=True), t("d-l3-2", "。"),
          t("d-l3-3", "ワイン"), t("d-l3-4", "うりば", "売り場", "うりば"), t("d-l3-5", "は"),
          t("d-l3-6", "どこ", key=True), t("d-l3-7", "ですか")],
         "Xin lỗi cho hỏi. Quầy bán rượu vang ở đâu ạ?"),
    line(L, 2, "店員", "Nhân viên cửa hàng",
         [t("d-l3-8", "ちか", "地下", "ちか"), t("d-l3-9", "いっかい", "1階", "いっかい", key=True),
          t("d-l3-10", "で ございます", key=True)],
         "Ở tầng hầm 1 ạ."),
    line(L, 3, "マリア", "Khách mua hàng",
         [t("d-l3-11", "エスカレーター"), t("d-l3-12", "は"),
          t("d-l3-13", "どちら", key=True), t("d-l3-14", "ですか")],
         "Thang cuốn ở phía nào ạ?"),
    line(L, 4, "店員", "Nhân viên cửa hàng",
         [t("d-l3-15", "あちら", key=True), t("d-l3-16", "で ございます"), t("d-l3-17", "。"),
          t("d-l3-18", "どうぞ")],
         "Ở đằng kia ạ. Xin mời quý khách."),
    line(L, 5, "マリア", "Khách mua hàng",
         [t("d-l3-19", "どうも"), t("d-l3-20", "。"),
          t("d-l3-21", "あのう"), t("d-l3-22", "、"), t("d-l3-23", "その"),
          t("d-l3-24", "ワイン"), t("d-l3-25", "を"),
          t("d-l3-26", "みせて ください", "見せて ください", "みせて ください", key=True)],
         "Cảm ơn ạ. À, cho tôi xem thử chai rượu vang đó với."),
    line(L, 6, "店員", "Nhân viên cửa hàng",
         [t("d-l3-27", "はい"), t("d-l3-28", "、"), t("d-l3-29", "どうぞ"), t("d-l3-30", "。"),
          t("d-l3-31", "イタリア"), t("d-l3-32", "の"), t("d-l3-33", "ワイン"), t("d-l3-34", "です")],
         "Vâng, xin mời. Đây là rượu vang của Ý ạ."),
    line(L, 7, "マリア", "Khách mua hàng",
         [t("d-l3-35", "これ"), t("d-l3-36", "は"),
          t("d-l3-37", "いくら", key=True), t("d-l3-38", "ですか")],
         "Chai này bao nhiêu tiền ạ?"),
    line(L, 8, "店員", "Nhân viên cửa hàng",
         [t("d-l3-39", "さんぜんはっぴゃくえん", "3千8百円", "さんぜんはっぴゃくえん", key=True),
          t("d-l3-40", "で ございます")],
         "Dạ 3.800 yên ạ."),
    line(L, 9, "マリア", "Khách mua hàng",
         [t("d-l3-41", "じゃ"), t("d-l3-42", "、"), t("d-l3-43", "これ"),
          t("d-l3-44", "を"), t("d-l3-45", "ください", key=True)],
         "Vậy cho tôi lấy chai này."),
    line(L, 10, "店員", "Nhân viên cửa hàng",
         [t("d-l3-46", "ありがとう"), t("d-l3-47", "ございます"), t("d-l3-48", "。"),
          t("d-l3-49", "レジ"), t("d-l3-50", "は"), t("d-l3-51", "こちら", key=True), t("d-l3-52", "です")],
         "Cảm ơn quý khách. Quầy thu ngân ở phía này ạ."),
]

EXERCISES = [
    q(L, 1, "Bạn đang đứng ở nhà ăn và muốn nói 'ở đây là nhà ăn':",
      ["ここは 食堂です", "そこは 食堂です", "あそこは 食堂です", "どこは 食堂です"], 0,
      "ここ chỉ nơi NGƯỜI NÓI đang đứng. そこ là chỗ người nghe, あそこ là chỗ xa cả hai.",
      "Bạn đang đứng ngay đó."),
    q(L, 2, "Hỏi quê quán của khách hàng, câu nào PHÙ HỢP nhất?",
      ["お国は どちらですか", "国は どこですか", "お国は どこですか", "国は どちらですか"], 0,
      "Với người cần tôn trọng: dùng お + 国 và どちら. どこ nghe cộc lốc, bỏ お thì mất phần kính trọng.",
      "Cần cả お lẫn どちら."),
    q(L, 3, "「3階」 đọc đúng là:",
      ["さんがい", "さんかい", "さんげ", "みっかい"], 0,
      "階 biến âm sau さん thành がい. Tương tự 何階 đọc なんがい.",
      "Có biến âm đục."),
    q(L, 4, "Chữ お trong 「お国」 dùng khi nào?",
      ["Khi nói về đất nước của NGƯỜI KHÁC",
       "Khi nói về đất nước của MÌNH",
       "Lúc nào cũng phải có",
       "Chỉ dùng trong văn viết"], 0,
      "Tiền tố お tôn trọng vật của đối phương. Nói về mình phải bỏ đi: 「国は ベトナムです」.",
      "Kính ngữ hướng về ai?"),
    q(L, 5, "いくら dùng để hỏi gì?",
      ["Giá tiền", "Số lượng", "Nơi chốn", "Thời gian"], 0,
      "いくら chỉ hỏi GIÁ. Hỏi số lượng là いくつ, hỏi nơi chốn là どこ, hỏi giờ là 何時.",
      "Liên quan tới tiền."),
    q(L, 6, "28.000 yên đọc theo kiểu Nhật là:",
      ["にまんはっせんえん", "にじゅうはっせんえん", "にせんはちひゃくえん", "にまんはちせんえん"], 0,
      "Nhật đếm theo VẠN: 28.000 = 2 vạn + 8 nghìn = 二万八千. Chú ý 8000 biến âm thành はっせん.",
      "Tách theo đơn vị 万."),
    q(L, 7, "Câu nào nhân viên cửa hàng sẽ nói với khách?",
      ["あちらで ございます", "あそこだよ", "あそこです", "あちらだ"], 0,
      "Với khách hàng dùng bộ ちら + kính ngữ で ございます. です còn được, nhưng だ/だよ là suồng sã.",
      "Mức lịch sự cao nhất."),
    q(L, 8, "Cách nói nhã nhặn hơn của 「トイレ」 là:",
      ["お手洗い", "お風呂", "台所", "玄関"], 0,
      "お手洗い (chỗ rửa tay) là cách nói giảm nhẹ. お風呂 là bồn tắm, 台所 là bếp, 玄関 là lối vào.",
      "Nghĩa đen là 'rửa tay'."),
    q(L, 9, "Câu nào dùng để xin xem hàng?",
      ["見せて ください", "見て ください", "ください", "どうぞ"], 0,
      "見せて ください = 'cho tôi xem'. 見て ください là 'bạn hãy nhìn đi' — ngược chiều hành động.",
      "Ai là người xem?"),
    q(L, 10, "Nhiều tòa nhà Nhật không có tầng 4 vì:",
      ["四 (し) đồng âm với 死 (chết)", "Xây thiếu tiền",
       "Luật xây dựng cấm", "Tầng 4 dành cho kho"], 0,
      "Kiêng số 4 vì đồng âm với 'tử'. Số 9 (く) đồng âm với 苦 (khổ) cũng bị kiêng.",
      "Liên quan tới cách đọc số."),
]

LESSON = lesson(
    L,
    "Bài 3: Nơi chốn & Vị trí (ここ / そこ / あそこ / どこ / こちら / いくら)",
    "Trỏ nơi chốn theo bộ ここ / そこ / あそこ / どこ và bản lịch sự こちら / そちら / あちら / どちら, "
    "hỏi vị trí trong tòa nhà bằng 〜階, hỏi quê quán công ty bằng お〜は どちらですか, "
    "và hỏi giá hàng hóa bằng いくらですか kèm cách đọc số đếm theo đơn vị vạn.",
    VOCAB, KANJI, SLIDES, DIALOGUE, EXERCISES,
)

if __name__ == '__main__':
    merge([LESSON])
