# -*- coding: utf-8 -*-
"""N5 — Bài 22: Menh de dinh ngu bo nghia cho danh tu (連体修飾).

Tu vung minh hoa TU CHON tu pool mo data/jlpt-vocab/n5.csv (xem NOTICE.md).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from n5_lib import v, k, t, ex, slide, line, q, lesson, merge
from jlpt_pool import Pool

L = 22
pool = Pool("n5")

VOCAB = [
    v(1,  "きます", "着ます", "きます", "kimasu", "verb", "Mặc (áo, đồ phía trên eo)", "Thể từ điển: 着る. Nhóm II. 眼鏡をかける (đeo kính) dùng động từ khác.", L),
    v(2,  "かけます", "掛けます", "かけます", "kakemasu", "verb", "Đeo (kính), treo", "眼鏡を かけます = đeo kính. Nhóm II.", L),
    v(3,  "かぶります", "被ります", "かぶります", "kaburimasu", "verb", "Đội (mũ, nón)", "帽子を かぶります = đội mũ. Nhóm I.", L),
    v(4,  "たてます", "建てます", "たてます", "tatemasu", "verb", "Xây dựng", "Nhóm II. あの 建物を 建てました = đã xây tòa nhà đó.", L),
    v(5,  "かきます", "書きます", "かきます", "kakimasu", "verb", "Viết", "Đã gặp bài 6 — nay dùng làm mệnh đề định ngữ (sách do ai viết).", L),
    v(6,  "つくります", "作ります", "つくります", "tsukurimasu", "verb", "Làm, chế tạo, nấu", "Đã gặp bài 6 — nay dùng làm mệnh đề định ngữ (món ăn do ai nấu).", L),
    v(7,  "めがね", "眼鏡", "めがね", "megane", "noun", "Kính mắt", "眼鏡を かけている人 = người đang đeo kính.", L),
    v(8,  "ぼうし", "帽子", "ぼうし", "boushi", "noun", "Mũ, nón", "帽子を かぶっている人 = người đang đội mũ.", L),
    v(9,  "ふく", "服", "ふく", "fuku", "noun", "Quần áo", "赤い 服を 着ている人 = người đang mặc đồ đỏ.", L),
    v(10, "ようふく", "洋服", "ようふく", "youfuku", "noun", "Trang phục kiểu Tây", "Phân biệt với 着物 (kimono, trang phục truyền thống).", L),
    v(11, "たてもの", "建物", "たてもの", "tatemono", "noun", "Tòa nhà, công trình", "あそこに ある 建物 = tòa nhà ở đằng kia.", L),
    v(12, "みせ", "店", "みせ", "mise", "noun", "Cửa hàng", "駅の 近くに ある 店 = cửa hàng gần ga.", L),
    v(13, "レストラン", "", "", "resutoran", "noun", "Nhà hàng", "先週 行った レストラン = nhà hàng tuần trước đã đi.", L),
    v(14, "きっさてん", "喫茶店", "きっさてん", "kissaten", "noun", "Quán cà phê kiểu cổ điển", "Đã gặp bài 6.", L),
    v(15, "えいが", "映画", "えいが", "eiga", "noun", "Phim, điện ảnh", "去年 見た 映画 = bộ phim đã xem năm ngoái.", L),
    v(16, "ひと", "人", "ひと", "hito", "noun", "Người", "あそこに いる 人 = người đang ở đằng kia.", L),
    v(17, "つくえ", "机", "つくえ", "tsukue", "noun", "Cái bàn", "Đã gặp bài 2 — nay dùng làm ví dụ mệnh đề định ngữ nơi chốn.", L),
    v(18, "いす", "椅子", "いす", "isu", "noun", "Cái ghế", "Đã gặp bài 2.", L),
    v(19, "おんがく", "音楽", "おんがく", "ongaku", "noun", "Âm nhạc", "Đã gặp bài 6 — nay dùng làm nội dung sở thích trong định ngữ.", L),
    v(20, "しんせつ", "親切", "しんせつ", "shinsetsu", "adjective", "Tốt bụng, ân cần", "Đã gặp bài 16.", L),
]

KANJI = [
    k(1, "着", "TRƯỚC", 12, ["チャク (chaku)"], ["き(る)", "つ(く)"], "Mặc; đến nơi.",
      [("着ます", "きます", "Mặc"), ("到着", "とうちゃく", "Đến nơi"), ("着物", "きもの", "Kimono")], L),
    k(2, "服", "PHỤC", 8, ["フク (fuku)"], [], "Quần áo, trang phục.",
      [("服", "ふく", "Quần áo"), ("洋服", "ようふく", "Trang phục Tây"), ("制服", "せいふく", "Đồng phục")], L),
    k(3, "建", "KIẾN", 9, ["ケン (ken)"], ["た(てる)"], "Xây dựng.",
      [("建物", "たてもの", "Tòa nhà"), ("建てます", "たてます", "Xây dựng"), ("建築", "けんちく", "Kiến trúc")], L),
    k(4, "店", "ĐIẾM", 8, ["テン (ten)"], ["みせ"], "Cửa hàng.",
      [("店", "みせ", "Cửa hàng"), ("店員", "てんいん", "Nhân viên cửa hàng"), ("喫茶店", "きっさてん", "Quán cà phê")], L),
    k(5, "作", "TÁC", 7, ["サク (saku)"], ["つく(る)"], "Làm, sáng tác. Đã gặp ở bài 6.",
      [("作ります", "つくります", "Làm"), ("作品", "さくひん", "Tác phẩm"), ("作文", "さくぶん", "Bài văn")], L),
]

SLIDES = [
    slide(L, 1,
        "1. Mệnh đề định ngữ: [Câu thể thông thường] + N",
        "[Câu ở thể thông thường] + [Danh từ chính]",
        "Muốn bổ nghĩa cho một danh từ bằng CẢ MỘT CÂU (không chỉ một tính từ), đặt câu đó ở thể "
        "thông thường ngay TRƯỚC danh từ — không cần trợ từ nối như の đã học ở bài 2.",
        [
            ex(L, 1, 1, [t("t-l22s1-1", "あの"), t("t-l22s1-2", "めがね", "眼鏡", "めがね", key=True),
                         t("t-l22s1-3", "を"), t("t-l22s1-4", "かけている", "掛けている", "かけている", key=True),
                         t("t-l22s1-5", "ひと", "人", "ひと"), t("t-l22s1-6", "は"),
                         t("t-l22s1-7", "だれ", "誰", "だれ"), t("t-l22s1-8", "ですか")],
               "Người đang đeo kính kia là ai vậy?"),
            ex(L, 1, 2, [t("t-l22s1-9", "きのう", "昨日", "きのう"), t("t-l22s1-10", "みた", "見た", "みた", key=True),
                         t("t-l22s1-11", "えいが", "映画", "えいが"), t("t-l22s1-12", "は"),
                         t("t-l22s1-13", "おもしろかった", "面白かった", "おもしろかった"), t("t-l22s1-14", "です")],
               "Bộ phim tôi xem hôm qua rất thú vị."),
        ],
        tips="Toàn bộ mệnh đề định ngữ (kể cả tân ngữ, trợ từ を bên trong) đứng NGUYÊN VẸN trước danh từ chính — không đảo trật tự như tiếng Việt.",
        culture="Cấu trúc này cực kỳ phổ biến khi mô tả người lạ trong đám đông: 「赤い 帽子を かぶっている人」 = người đội mũ đỏ kia."),

    slide(L, 2,
        "2. Định ngữ với động từ ở các thì khác nhau",
        "V(từ điển)+N (sắp/thường làm) — V(た)+N (đã làm) — Vている+N (đang làm)",
        "Thì của động từ trong mệnh đề định ngữ HOÀN TOÀN ĐỘC LẬP với thì của câu chính — chọn "
        "theo đúng thời điểm của hành động được miêu tả, không theo thì câu chính.",
        [
            ex(L, 2, 1, [t("t-l22s2-1", "やまださん", "山田さん", "やまださん"), t("t-l22s2-2", "が"),
                         t("t-l22s2-3", "つくった", "作った", "つくった", key=True), t("t-l22s2-4", "りょうり", "料理", "りょうり"),
                         t("t-l22s2-5", "は"), t("t-l22s2-6", "おいしい", "美味しい", "おいしい"), t("t-l22s2-7", "です")],
               "Món ăn anh Yamada đã nấu rất ngon."),
            ex(L, 2, 2, [t("t-l22s2-8", "あそこ"), t("t-l22s2-9", "で"), t("t-l22s2-10", "はなしている", "話している", "はなしている", key=True),
                         t("t-l22s2-11", "ひと", "人", "ひと"), t("t-l22s2-12", "は"),
                         t("t-l22s2-13", "だれ", "誰", "だれ"), t("t-l22s2-14", "ですか")],
               "Người đang nói chuyện đằng kia là ai vậy?"),
        ],
        tips="山田さんが作った (山田さん LÀ chủ ngữ của mệnh đề định ngữ, dùng が chứ không phải は khi ở bên trong định ngữ).",
        culture="Chủ ngữ trong mệnh đề định ngữ hầu như luôn dùng が, kể cả khi câu bên ngoài dùng は — đây là quy tắc riêng của cấu trúc này."),

    slide(L, 3,
        "3. Định ngữ chỉ nơi chốn/vật cụ thể",
        "[Câu miêu tả nơi chốn ở thể thông thường] + N",
        "Ứng dụng để chỉ rõ MỘT VẬT/NƠI CỤ THỂ trong số nhiều lựa chọn — rất hữu ích khi giới thiệu "
        "địa điểm hoặc phân biệt đồ vật giống nhau.",
        [
            ex(L, 3, 1, [t("t-l22s3-1", "えき", "駅", "えき"), t("t-l22s3-2", "の"), t("t-l22s3-3", "ちかく", "近く", "ちかく"),
                         t("t-l22s3-4", "に"), t("t-l22s3-5", "ある", "有る", "ある", key=True),
                         t("t-l22s3-6", "レストラン"), t("t-l22s3-7", "は"), t("t-l22s3-8", "やすい", "安い", "やすい"),
                         t("t-l22s3-9", "です")],
               "Nhà hàng ở gần ga thì rẻ."),
            ex(L, 3, 2, [t("t-l22s3-10", "つくえ", "机", "つくえ"), t("t-l22s3-11", "の"), t("t-l22s3-12", "うえ", "上", "うえ"),
                         t("t-l22s3-13", "に"), t("t-l22s3-14", "ある", "有る", "ある", key=True),
                         t("t-l22s3-15", "ほん", "本", "ほん"), t("t-l22s3-16", "を"),
                         t("t-l22s3-17", "とって", "取って", "とって"), t("t-l22s3-18", "ください")],
               "Xin hãy lấy giúp quyển sách ở trên bàn."),
        ],
        tips="ある/いる (tồn tại, bài 10) rất hay xuất hiện trong định ngữ chỉ vị trí — vì bản chất là miêu tả 'vật NẰM Ở đâu'.",
        culture="Chỉ đường ở Nhật hay dùng cấu trúc này: 「あの、白い 建物の 隣に ある 店」 = cửa hàng bên cạnh tòa nhà trắng kia."),

    slide(L, 4,
        "4. Định ngữ với tính từ và mệnh đề phức",
        "[Tính từ/mệnh đề い/な ở thể thông thường] + N",
        "Tính từ い giữ nguyên trong định ngữ (đã quen từ bài 2: この本). Tính từ な PHẢI GIỮ な "
        "khi đứng trước danh từ (đã học ở bài 8) — nguyên tắc này áp dụng cả khi mệnh đề dài hơn.",
        [
            ex(L, 4, 1, [t("t-l22s4-1", "しんせつ", "親切", "しんせつ", key=True), t("t-l22s4-2", "な", key=True),
                         t("t-l22s4-3", "ひと", "人", "ひと"), t("t-l22s4-4", "に"), t("t-l22s4-5", "あいました", "会いました", "あいました")],
               "Tôi đã gặp một người tốt bụng."),
            ex(L, 4, 2, [t("t-l22s4-6", "おんがく", "音楽", "おんがく", key=True), t("t-l22s4-7", "が"),
                         t("t-l22s4-8", "すき", "好き", "すき"), t("t-l22s4-9", "な", key=True), t("t-l22s4-10", "ひと", "人", "ひと"),
                         t("t-l22s4-11", "は"), t("t-l22s4-12", "あつまって", "集まって", "あつまって"),
                         t("t-l22s4-13", "ください")],
               "Những ai thích âm nhạc xin hãy tập hợp lại."),
        ],
        tips="好きな人 (người thích) — dù 好き là tính từ đặc biệt dùng が, khi bổ nghĩa danh từ vẫn PHẢI thêm な như mọi tính từ な khác.",
        culture="音楽が好きな人 là mẫu câu thường thấy trong thông báo tuyển thành viên câu lạc bộ ở trường học Nhật."),
]

DIALOGUE = [
    line(L, 1, "ワン", "Sinh viên",
         [t("d-l22-1", "あの"), t("d-l22-2", "、"), t("d-l22-3", "ぼうし", "帽子", "ぼうし", key=True),
          t("d-l22-4", "を"), t("d-l22-5", "かぶっている", "被っている", "かぶっている", key=True), t("d-l22-6", "ひと", "人", "ひと"),
          t("d-l22-7", "は"), t("d-l22-8", "だれ", "誰", "だれ"), t("d-l22-9", "ですか")],
         "Người đang đội mũ kia là ai vậy?"),
    line(L, 2, "サントス", "Sinh viên",
         [t("d-l22-10", "あの"), t("d-l22-11", "ひと", "人", "ひと"), t("d-l22-12", "は"),
          t("d-l22-13", "あたらしい", "新しい", "あたらしい"), t("d-l22-14", "せんせい", "先生", "せんせい"), t("d-l22-15", "です")],
         "Người đó là thầy giáo mới."),
    line(L, 3, "ワン", "Sinh viên",
         [t("d-l22-16", "そうですか"), t("d-l22-17", "。"), t("d-l22-18", "しんせつ", "親切", "しんせつ", key=True),
          t("d-l22-19", "な", key=True), t("d-l22-20", "せんせい", "先生", "せんせい"), t("d-l22-21", "ですか")],
         "Vậy à. Có phải là thầy giáo tốt bụng không?"),
    line(L, 4, "サントス", "Sinh viên",
         [t("d-l22-22", "はい"), t("d-l22-23", "、"), t("d-l22-24", "とても"), t("d-l22-25", "しんせつ", "親切", "しんせつ"),
          t("d-l22-26", "です"), t("d-l22-27", "。"), t("d-l22-28", "ところで"),
          t("d-l22-29", "、"), t("d-l22-30", "きのう", "昨日", "きのう"), t("d-l22-31", "みた", "見た", "みた", key=True),
          t("d-l22-32", "えいが", "映画", "えいが", key=True), t("d-l22-33", "、"), t("d-l22-34", "どうでしたか")],
         "Vâng, rất tốt bụng. À mà, bộ phim cậu xem hôm qua thế nào?"),
    line(L, 5, "ワン", "Sinh viên",
         [t("d-l22-35", "とても"), t("d-l22-36", "おもしろかった", "面白かった", "おもしろかった"), t("d-l22-37", "です"),
          t("d-l22-38", "。"), t("d-l22-39", "サントスさん"), t("d-l22-40", "が"), t("d-l22-41", "すすめた", "勧めた", "すすめた", key=True),
          t("d-l22-42", "レストラン"), t("d-l22-43", "も"), t("d-l22-44", "とても"), t("d-l22-45", "よかった", "良かった", "よかった")],
         "Rất thú vị. Nhà hàng cậu giới thiệu cũng rất tốt nữa."),
    line(L, 6, "サントス", "Sinh viên",
         [t("d-l22-46", "あの"), t("d-l22-47", "、"), t("d-l22-48", "えき", "駅", "えき"), t("d-l22-49", "の"),
          t("d-l22-50", "ちかく", "近く", "ちかく"), t("d-l22-51", "に"), t("d-l22-52", "ある", "有る", "ある", key=True),
          t("d-l22-53", "みせ", "店", "みせ", key=True), t("d-l22-54", "ですか")],
         "Cửa hàng gần ga đấy à?"),
    line(L, 7, "ワン", "Sinh viên",
         [t("d-l22-55", "はい"), t("d-l22-56", "。"), t("d-l22-57", "あの"), t("d-l22-58", "みせ", "店", "みせ"),
          t("d-l22-59", "で"), t("d-l22-60", "つくって", "作って", "つくって", key=True), t("d-l22-61", "いる"),
          t("d-l22-62", "りょうり", "料理", "りょうり"), t("d-l22-63", "は"), t("d-l22-64", "ぜんぶ"),
          t("d-l22-65", "おいしい", "美味しい", "おいしい"), t("d-l22-66", "です")],
         "Vâng. Món ăn cửa hàng đó làm đều ngon cả."),
    line(L, 8, "サントス", "Sinh viên",
         [t("d-l22-67", "こんど"), t("d-l22-68", "、"), t("d-l22-69", "いっしょに", "一緒に", "いっしょに"),
          t("d-l22-70", "いきましょう", "行きましょう", "いきましょう")],
         "Lần sau mình cùng đi nhé."),
    line(L, 9, "ワン", "Sinh viên",
         [t("d-l22-71", "いいですね"), t("d-l22-72", "。"), t("d-l22-73", "あの"), t("d-l22-74", "たてもの", "建物", "たてもの", key=True),
          t("d-l22-75", "の"), t("d-l22-76", "となり", "隣", "となり"), t("d-l22-77", "に"),
          t("d-l22-78", "ある", "有る", "ある", key=True), t("d-l22-79", "みせ", "店", "みせ"), t("d-l22-80", "ですね")],
         "Hay đó. Là cửa hàng bên cạnh tòa nhà kia phải không?"),
    line(L, 10, "サントス", "Sinh viên",
         [t("d-l22-81", "はい"), t("d-l22-82", "、"), t("d-l22-83", "そうです")],
         "Ừ, đúng vậy."),
]

EXERCISES = [
    q(L, 1, "「眼鏡を かけている 人」 nghĩa là:",
      ["Người đang đeo kính", "Người đang bán kính",
       "Kính của người đó", "Người không đeo kính"], 0,
      "Mệnh đề [眼鏡をかけている] bổ nghĩa trực tiếp cho danh từ 人 — 'người [đang đeo kính]'.",
      "Đọc toàn bộ cụm từ như một khối bổ nghĩa cho 人."),
    q(L, 2, "「昨日 見た 映画」 — 見た ở thì nào và tại sao?",
      ["Thì quá khứ, vì hành động xem phim đã xảy ra trước đó",
       "Thì hiện tại, vì câu chính ở hiện tại", "Thì tương lai",
       "Không có thì cụ thể"], 0,
      "Thì trong mệnh đề định ngữ chọn theo THỜI ĐIỂM của hành động được miêu tả, độc lập với thì câu chính.",
      "Xem lại nguyên tắc chọn thì ở slide 2."),
    q(L, 3, "「山田さんが 作った 料理」 — vì sao dùng が cho 山田さん?",
      ["Chủ ngữ trong mệnh đề định ngữ dùng が, không dùng は",
       "は là lỗi chính tả", "が chỉ dùng cho câu hỏi",
       "Cả は và が đều sai, phải dùng の"], 0,
      "Đây là quy tắc riêng: chủ ngữ BÊN TRONG mệnh đề định ngữ hầu như luôn dùng が.",
      "Xem ghi chú văn hóa/ngữ pháp ở slide 2."),
    q(L, 4, "「音楽が 好きな 人」 — vì sao có な sau 好き?",
      ["好き là tính từ な, bổ nghĩa danh từ trực tiếp phải giữ な",
       "な là lỗi thừa, phải bỏ đi", "な chỉ dùng cho câu hỏi",
       "好き không phải tính từ nên không cần quy tắc gì"], 0,
      "Dù 好き dùng が cho đối tượng, khi ĐỨNG TRƯỚC DANH TỪ nó vẫn là tính từ な nên cần thêm な.",
      "Áp dụng lại quy tắc tính từ な từ bài 8."),
    q(L, 5, "「駅の近くに ある レストラン」 nghĩa là:",
      ["Nhà hàng nằm ở gần ga", "Ga nằm gần nhà hàng",
       "Nhà hàng xa ga", "Không có nhà hàng nào gần ga"], 0,
      "ある (tồn tại, bài 10) trong mệnh đề định ngữ miêu tả VỊ TRÍ của danh từ chính (nhà hàng).",
      "Xem lại cấu trúc あります đã học ở bài 10."),
    q(L, 6, "Câu nào ĐÚNG ngữ pháp?",
      ["机の上に ある 本", "机の上に あります 本",
       "机の上に あるの 本", "机の上に あって 本"], 0,
      "Trong mệnh đề định ngữ, động từ chia ở thể THÔNG THƯỜNG (ある), không chia ます hay thể て đứng riêng trước danh từ.",
      "So sánh bốn cách chia được đưa ra."),
    q(L, 7, "「あそこで 話している 人」 và 「あそこで 話した 人」 khác nhau ở:",
      ["Một đang nói (hiện tại), một đã nói xong (quá khứ)", "Hoàn toàn giống nhau",
       "話している sai ngữ pháp", "話した chỉ dùng cho câu hỏi"], 0,
      "ている diễn tả hành động ĐANG diễn ra; た diễn tả hành động ĐÃ hoàn tất — khác biệt về thì như đã học ở bài 14, 19.",
      "Áp dụng kiến thức Vています và Vた đã học trước đó."),
    q(L, 8, "Trợ từ nào KHÔNG cần thiết khi ghép mệnh đề định ngữ với danh từ chính?",
      ["の (không cần thêm の giữa mệnh đề và danh từ)",
       "を (bên trong mệnh đề)", "が (chủ ngữ bên trong mệnh đề)",
       "に (nếu có trong mệnh đề)"], 0,
      "Khác の nối hai danh từ (bài 2), mệnh đề định ngữ ghép TRỰC TIẾP vào danh từ chính, không cần trợ từ nối thêm.",
      "Đừng nhầm với cấu trúc N1のN2 đã học ở bài 2."),
    q(L, 9, "Trong hội thoại, người đội mũ là ai?",
      ["Thầy giáo mới", "Bạn học cùng lớp", "Nhân viên nhà hàng", "Không được nhắc tới"], 0,
      "サントス trả lời 「あの人は 新しい先生です」.",
      "Xem câu thoại thứ 2."),
    q(L, 10, "Cửa hàng được nhắc tới nằm ở đâu?",
      ["Gần ga, bên cạnh một tòa nhà", "Trong công viên",
       "Xa trung tâm thành phố", "Không được miêu tả vị trí"], 0,
      "Cửa hàng được miêu tả là 「駅の近くに ある店」 và sau đó xác nhận là 「あの建物の隣にある店」.",
      "Xem các câu thoại về vị trí cửa hàng."),
]

LESSON = lesson(
    L,
    "Bài 22: Mệnh đề định ngữ bổ nghĩa cho Danh từ (連体修飾)",
    "Ghép cả một câu ở thể thông thường làm định ngữ đứng trước danh từ chính (không cần trợ từ "
    "nối), chọn thì trong mệnh đề định ngữ độc lập với thì câu chính, quy tắc chủ ngữ が bên trong "
    "mệnh đề, và tính từ な vẫn giữ な khi bổ nghĩa trực tiếp cho danh từ dù trong mệnh đề phức.",
    VOCAB, KANJI, SLIDES, DIALOGUE, EXERCISES,
)

if __name__ == "__main__":
    pool.mark_used([w["word"] for w in VOCAB], lesson=L)
    merge([LESSON])
