# -*- coding: utf-8 -*-
"""N5 — Bài 1 (Minna no Nihongo I): Giới thiệu bản thân."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from n5_lib import v, k, t, ex, slide, line, q, lesson, merge

L = 1

VOCAB = [
    v(1,  "わたし", "私", "わたし", "watashi", "noun", "Tôi (ngôi thứ nhất, trung tính, dùng được mọi lúc)", "Đọc bằng, hạ nhẹ âm cuối.", L),
    v(2,  "わたしたち", "私たち", "わたしたち", "watashitachi", "noun", "Chúng tôi, chúng ta", "たち là hậu tố số nhiều cho người.", L),
    v(3,  "あなた", "貴方", "あなた", "anata", "noun", "Bạn / anh / chị (ngôi thứ 2)", "Biết tên rồi thì gọi tên + さん, đừng dùng あなた.", L),
    v(4,  "あのひと", "あの人", "あのひと", "ano hito", "noun", "Người kia, người đó", "Lịch sự hơn: あの方 (あのかた).", L),
    v(5,  "みなさん", "皆さん", "みなさん", "minasan", "noun", "Các bạn, mọi người, quý vị", "Câu mở đầu khi nói trước đám đông.", L),
    v(6,  "〜さん", "", "", "-san", "particle", "Anh / chị / ông / bà (gắn sau tên người khác)", "TUYỆT ĐỐI không gắn vào tên mình.", L),
    v(7,  "〜ちゃん", "", "", "-chan", "particle", "Bé, cu, em (gọi thân mật trẻ nhỏ, bạn gái thân)", "Chỉ dùng trong gia đình hoặc bạn rất thân.", L),
    v(8,  "〜くん", "〜君", "〜くん", "-kun", "particle", "Cậu, em (gọi bé trai hoặc đàn em nam)", "Cấp trên gọi cấp dưới nam cũng dùng.", L),
    v(9,  "〜じん", "〜人", "〜じん", "-jin", "particle", "Người nước ~ (ベトナム人 = người Việt Nam)", "Nước + 人. Riêng Nhật: 日本人 (にほんじん).", L),
    v(10, "せんせい", "先生", "せんせい", "sensei", "noun", "Thầy / cô giáo, bác sĩ (dùng để GỌI người khác)", "Kéo dài âm せい. Không tự xưng là 先生.", L),
    v(11, "きょうし", "教師", "きょうし", "kyoushi", "noun", "Giáo viên (tên NGHỀ, dùng khi nói nghề của mình)", "Tôi là giáo viên → 私は教師です.", L),
    v(12, "がくせい", "学生", "がくせい", "gakusei", "noun", "Học sinh, sinh viên", "Trọng âm phẳng.", L),
    v(13, "かいしゃいん", "会社員", "かいしゃいん", "kaishain", "noun", "Nhân viên công ty (nói chung)", "Phân biệt với 社員: nhân viên của một công ty cụ thể.", L),
    v(14, "しゃいん", "社員", "しゃいん", "shain", "noun", "Nhân viên của công ty ~ (IMCの社員)", "Luôn đi kèm tên công ty phía trước.", L),
    v(15, "ぎんこういん", "銀行員", "ぎんこういん", "ginkouin", "noun", "Nhân viên ngân hàng", "Hậu tố 員 (いん) = thành viên, nhân viên.", L),
    v(16, "いしゃ", "医者", "いしゃ", "isha", "noun", "Bác sĩ (tên nghề)", "Gọi bác sĩ trước mặt thì dùng 先生.", L),
    v(17, "けんきゅうしゃ", "研究者", "けんきゅうしゃ", "kenkyuusha", "noun", "Nhà nghiên cứu", "Hậu tố 者 (しゃ) = người làm nghề ~.", L),
    v(18, "エンジニア", "", "", "enjinia", "noun", "Kỹ sư", "Từ ngoại lai, viết Katakana.", L),
    v(19, "だいがく", "大学", "だいがく", "daigaku", "noun", "Trường đại học", "Nhấn ở âm い.", L),
    v(20, "びょういん", "病院", "びょういん", "byouin", "noun", "Bệnh viện", "Đừng lẫn với 美容院 (びよういん) = tiệm làm tóc!", L),
    v(21, "でんき", "電気", "でんき", "denki", "noun", "Điện, đèn điện", "電気屋 = cửa hàng đồ điện.", L),
    v(22, "だれ", "誰", "だれ", "dare", "noun", "Ai (từ để hỏi người)", "Lịch sự hơn: どなた.", L),
    v(23, "どなた", "", "", "donata", "noun", "Vị nào, ai ạ (lịch sự)", "Dùng với khách, người trên.", L),
    v(24, "〜さい", "〜歳", "〜さい", "-sai", "noun", "~ tuổi", "1 tuổi いっさい, 8 tuổi はっさい, 20 tuổi はたち.", L),
    v(25, "なんさい", "何歳", "なんさい", "nansai", "noun", "Mấy tuổi", "Lịch sự hơn: おいくつですか.", L),
    v(26, "はい", "", "", "hai", "phrase", "Vâng, đúng vậy", "Cũng dùng để báo “tôi đang nghe”.", L),
    v(27, "いいえ", "", "", "iie", "phrase", "Không, không phải", "Khi được khen thì đáp いいえ cho khiêm tốn.", L),
    v(28, "はじめまして", "初めまして", "はじめまして", "hajimemashite", "phrase", "Rất hân hạnh được gặp (lần đầu)", "Nói kèm cúi đầu khoảng 15 độ.", L),
    v(29, "どうぞよろしくおねがいします", "どうぞよろしくお願いします", "どうぞよろしくおねがいします", "douzo yoroshiku onegaishimasu", "phrase", "Rất mong được giúp đỡ", "Câu chốt bắt buộc khi chào lần đầu.", L),
    v(30, "しつれいですが", "失礼ですが", "しつれいですが", "shitsurei desu ga", "phrase", "Xin lỗi cho hỏi… (mở lời hỏi thông tin)", "Đệm trước khi hỏi tên, tuổi, nghề.", L),
]

KANJI = [
    k(1, "私", "TƯ", 7, ["シ (shi)"], ["わたし", "わたくし"], "Tôi; riêng tư, cá nhân.",
      [("私", "わたし", "Tôi"), ("私立", "しりつ", "Tư lập, dân lập"), ("私生活", "しせいかつ", "Đời sống riêng tư")], L),
    k(2, "人", "NHÂN", 2, ["ジン (jin)", "ニン (nin)"], ["ひと"], "Người. Hình vẽ một người đang đứng dang chân.",
      [("人", "ひと", "Người"), ("日本人", "にほんじん", "Người Nhật"), ("三人", "さんにん", "Ba người")], L),
    k(3, "先", "TIÊN", 6, ["セン (sen)"], ["さき"], "Trước, phía trước, đi trước.",
      [("先生", "せんせい", "Thầy/cô giáo"), ("先月", "せんげつ", "Tháng trước"), ("お先に", "おさきに", "Tôi xin phép trước")], L),
    k(4, "生", "SINH", 5, ["セイ (sei)", "ショウ (shou)"], ["い(きる)", "う(まれる)", "なま"], "Sinh ra, sống; tươi sống.",
      [("学生", "がくせい", "Học sinh, sinh viên"), ("生まれる", "うまれる", "Được sinh ra"), ("生ビール", "なまビール", "Bia tươi")], L),
    k(5, "学", "HỌC", 8, ["ガク (gaku)"], ["まな(ぶ)"], "Học tập, học vấn.",
      [("学校", "がっこう", "Trường học"), ("大学", "だいがく", "Đại học"), ("学ぶ", "まなぶ", "Học hỏi")], L),
    k(6, "会", "HỘI", 6, ["カイ (kai)"], ["あ(う)"], "Gặp gỡ, hội họp.",
      [("会社", "かいしゃ", "Công ty"), ("会議", "かいぎ", "Cuộc họp"), ("会う", "あう", "Gặp mặt")], L),
    k(7, "社", "XÃ", 7, ["シャ (sha)"], ["やしろ"], "Công ty, xã hội; đền thờ Thần đạo.",
      [("会社員", "かいしゃいん", "Nhân viên công ty"), ("社長", "しゃちょう", "Giám đốc"), ("神社", "じんじゃ", "Đền Thần đạo")], L),
    k(8, "名", "DANH", 6, ["メイ (mei)", "ミョウ (myou)"], ["な"], "Tên gọi, danh tiếng.",
      [("名前", "なまえ", "Tên"), ("有名", "ゆうめい", "Nổi tiếng"), ("名刺", "めいし", "Danh thiếp")], L),
]

SLIDES = [
    slide(L, 1,
        "1. Khẳng định: N1 は N2 です",
        "N1 [chủ đề] + は + N2 [danh từ vị ngữ] + です",
        "は đánh dấu CHỦ ĐỀ của câu — thứ mà cả câu đang nói về. Viết bằng chữ は nhưng khi là trợ từ thì "
        "BẮT BUỘC đọc là 'wa'. です đứng cuối câu, vừa khẳng định vừa thể hiện thái độ lịch sự.",
        [
            ex(L, 1, 1, [t("t-l1s1-1", "わたし", "私", "わたし"), t("t-l1s1-2", "は", key=True),
                         t("t-l1s1-3", "マイク・ミラー"), t("t-l1s1-4", "です", key=True)],
               "Tôi là Mike Miller."),
            ex(L, 1, 2, [t("t-l1s1-5", "サントスさん"), t("t-l1s1-6", "は", key=True),
                         t("t-l1s1-7", "がくせい", "学生", "がくせい"), t("t-l1s1-8", "です", key=True)],
               "Anh Santos là sinh viên."),
            ex(L, 1, 3, [t("t-l1s1-9", "わたし", "私", "わたし"), t("t-l1s1-10", "は", key=True),
                         t("t-l1s1-11", "ベトナム", ), t("t-l1s1-12", "じん", "人", "じん"),
                         t("t-l1s1-13", "です", key=True)],
               "Tôi là người Việt Nam."),
        ],
        tips="Khi VIẾT thì dùng chữ は, khi ĐỌC thì bật ra thành 'wa'. Sai chỗ này là lộ ngay người mới học.",
        culture="Người Nhật rất hay lược bỏ 私は khi ngữ cảnh đã rõ. Nói 学生です là đủ hiểu 'tôi là sinh viên'."),

    slide(L, 2,
        "2. Phủ định: N1 は N2 じゃありません",
        "N1 + は + N2 + じゃ ありません  (trang trọng: では ありません)",
        "Muốn nói 'không phải là ~' thì thay です bằng じゃありません. じゃ là dạng nói, では là dạng viết/trang trọng. "
        "Cả hai đều lịch sự, khác nhau ở độ trang trọng chứ không phải đúng/sai.",
        [
            ex(L, 2, 1, [t("t-l1s2-1", "サントスさん"), t("t-l1s2-2", "は", key=True),
                         t("t-l1s2-3", "がくせい", "学生", "がくせい"),
                         t("t-l1s2-4", "じゃ ありません", key=True)],
               "Anh Santos không phải là sinh viên."),
            ex(L, 2, 2, [t("t-l1s2-5", "わたし", "私", "わたし"), t("t-l1s2-6", "は", key=True),
                         t("t-l1s2-7", "いしゃ", "医者", "いしゃ"),
                         t("t-l1s2-8", "では ありません", key=True)],
               "Tôi không phải là bác sĩ."),
            ex(L, 2, 3, [t("t-l1s2-9", "ミラーさん"), t("t-l1s2-10", "は", key=True),
                         t("t-l1s2-11", "にほんじん", "日本人", "にほんじん"),
                         t("t-l1s2-12", "じゃ ありません", key=True)],
               "Anh Miller không phải là người Nhật."),
        ],
        tips="じゃ ありません nói nhanh sẽ thành じゃないです — thân mật hơn một chút, vẫn lịch sự.",
        culture="Người Nhật ngại phủ định thẳng. Thay vì 'không phải', họ hay nói ちょっと… và bỏ lửng."),

    slide(L, 3,
        "3. Nghi vấn: N1 は N2 ですか",
        "N1 + は + N2 + です + か ↗",
        "Chỉ cần thêm trợ từ か vào cuối câu là thành câu hỏi — KHÔNG đảo trật tự từ như tiếng Anh. "
        "Cuối câu lên giọng nhẹ. Trả lời: はい、～です / いいえ、～じゃ ありません.",
        [
            ex(L, 3, 1, [t("t-l1s3-1", "ミラーさん"), t("t-l1s3-2", "は", key=True),
                         t("t-l1s3-3", "かいしゃいん", "会社員", "かいしゃいん"),
                         t("t-l1s3-4", "ですか", key=True)],
               "Anh Miller là nhân viên công ty phải không?"),
            ex(L, 3, 2, [t("t-l1s3-5", "はい"), t("t-l1s3-6", "、"),
                         t("t-l1s3-7", "かいしゃいん", "会社員", "かいしゃいん"), t("t-l1s3-8", "です")],
               "Vâng, đúng là nhân viên công ty."),
            ex(L, 3, 3, [t("t-l1s3-9", "あのひと", "あの人", "あのひと"), t("t-l1s3-10", "は", key=True),
                         t("t-l1s3-11", "だれ", "誰", "だれ", key=True), t("t-l1s3-12", "ですか", key=True)],
               "Người kia là ai vậy?"),
        ],
        tips="Với từ để hỏi (だれ, なん, どこ…) thì KHÔNG trả lời はい/いいえ, phải trả lời thẳng nội dung.",
        culture="Trong văn viết tiếng Nhật, câu hỏi kết thúc bằng か thì dùng dấu 。 chứ không cần dấu ?."),

    slide(L, 4,
        "4. Trợ từ も: cũng vậy",
        "N1 + も + N2 + です   (も thay chỗ của は)",
        "Khi vị ngữ TRÙNG với câu trước, thay は bằng も để nói 'cũng'. Lưu ý: も ĐẨY は ra, "
        "không bao giờ viết 「は も」 cạnh nhau.",
        [
            ex(L, 4, 1, [t("t-l1s4-1", "ミラーさん"), t("t-l1s4-2", "は", key=True),
                         t("t-l1s4-3", "かいしゃいん", "会社員", "かいしゃいん"), t("t-l1s4-4", "です")],
               "Anh Miller là nhân viên công ty."),
            ex(L, 4, 2, [t("t-l1s4-5", "グプタさん"), t("t-l1s4-6", "も", key=True),
                         t("t-l1s4-7", "かいしゃいん", "会社員", "かいしゃいん"), t("t-l1s4-8", "です")],
               "Anh Gupta cũng là nhân viên công ty."),
            ex(L, 4, 3, [t("t-l1s4-9", "わたし", "私", "わたし"), t("t-l1s4-10", "も", key=True),
                         t("t-l1s4-11", "ベトナムじん", "ベトナム人", "ベトナムじん"), t("t-l1s4-12", "です")],
               "Tôi cũng là người Việt Nam."),
        ],
        tips="Nghe ai giới thiệu xong mà mình giống họ, đáp ngay 「わたしもです」 — cực tự nhiên.",
        culture="Nói 私もです là cách nhanh nhất để tạo cảm giác đồng cảm trong hội thoại Nhật."),

    slide(L, 5,
        "5. Trợ từ の: nối hai danh từ",
        "N1 + の + N2   (N1 bổ nghĩa cho N2)",
        "の nối hai danh từ, N1 giải thích cho N2: nơi trực thuộc, người sở hữu, loại. "
        "Thứ tự NGƯỢC tiếng Việt — cái lớn/bao trùm đứng TRƯỚC.",
        [
            ex(L, 5, 1, [t("t-l1s5-1", "IMC"), t("t-l1s5-2", "の", key=True),
                         t("t-l1s5-3", "しゃいん", "社員", "しゃいん"), t("t-l1s5-4", "です")],
               "(Tôi) là nhân viên của công ty IMC."),
            ex(L, 5, 2, [t("t-l1s5-5", "さくら", "桜", "さくら"),
                         t("t-l1s5-6", "だいがく", "大学", "だいがく"), t("t-l1s5-7", "の", key=True),
                         t("t-l1s5-8", "せんせい", "先生", "せんせい"), t("t-l1s5-9", "です")],
               "(Cô ấy) là giáo viên của Đại học Sakura."),
            ex(L, 5, 3, [t("t-l1s5-10", "わたし", "私", "わたし"), t("t-l1s5-11", "の", key=True),
                         t("t-l1s5-12", "なまえ", "名前", "なまえ"), t("t-l1s5-13", "は"),
                         t("t-l1s5-14", "ナム"), t("t-l1s5-15", "です")],
               "Tên tôi là Nam."),
        ],
        tips="Đọc ngược từ phải sang trái là ra nghĩa tiếng Việt: IMC の 社員 → nhân viên ← của IMC.",
        culture="Người Nhật giới thiệu CÔNG TY trước rồi mới tới TÊN: 「IMCのミラーです」 — tập thể đứng trước cá nhân."),

    slide(L, 6,
        "6. Hỏi tuổi & 〜歳",
        "N は + [số] + 歳(さい) です  /  なんさい ですか, おいくつ ですか",
        "Đếm tuổi bằng hậu tố 〜歳. Có ba trường hợp biến âm phải nhớ: 1 tuổi いっさい, 8 tuổi はっさい, "
        "10 tuổi じゅっさい. Riêng 20 tuổi đọc đặc biệt là はたち (二十歳).",
        [
            ex(L, 6, 1, [t("t-l1s6-1", "テレサちゃん"), t("t-l1s6-2", "は"),
                         t("t-l1s6-3", "きゅうさい", "九歳", "きゅうさい", key=True), t("t-l1s6-4", "です")],
               "Bé Teresa 9 tuổi."),
            ex(L, 6, 2, [t("t-l1s6-5", "しつれいですが", "失礼ですが", "しつれいですが", key=True),
                         t("t-l1s6-6", "、"), t("t-l1s6-7", "おいくつ", key=True), t("t-l1s6-8", "ですか")],
               "Xin lỗi cho hỏi, anh/chị bao nhiêu tuổi ạ?"),
            ex(L, 6, 3, [t("t-l1s6-9", "わたし", "私", "わたし"), t("t-l1s6-10", "は"),
                         t("t-l1s6-11", "はたち", "二十歳", "はたち", key=True), t("t-l1s6-12", "です")],
               "Tôi 20 tuổi."),
        ],
        tips="なんさい hỏi trẻ con thì được; hỏi người lớn phải dùng おいくつですか cho lịch sự.",
        culture="Hỏi tuổi phụ nữ ở Nhật khá nhạy cảm — luôn đệm 失礼ですが trước khi hỏi."),
]

DIALOGUE = [
    line(L, 1, "佐藤 (Satou)", "personA",
         [t("d-l1-1a", "はじめまして", "初めまして", "はじめまして"), t("d-l1-1b", "。"),
          t("d-l1-1c", "さとう", "佐藤", "さとう"), t("d-l1-1d", "けいこ", "けい子", "けいこ"),
          t("d-l1-1e", "です")],
         "Rất hân hạnh được gặp. Tôi là Satou Keiko."),
    line(L, 2, "山田 (Yamada)", "personB",
         [t("d-l1-2a", "みなさん", "皆さん", "みなさん"), t("d-l1-2b", "、"),
          t("d-l1-2c", "こちら"), t("d-l1-2d", "は"),
          t("d-l1-2e", "マイク・ミラーさん"), t("d-l1-2f", "です")],
         "Mọi người ơi, đây là anh Mike Miller."),
    line(L, 3, "ミラー (Miller)", "personA",
         [t("d-l1-3a", "はじめまして", "初めまして", "はじめまして"), t("d-l1-3b", "。"),
          t("d-l1-3c", "マイク・ミラー"), t("d-l1-3d", "です"), t("d-l1-3e", "。"),
          t("d-l1-3f", "アメリカ"), t("d-l1-3g", "から"), t("d-l1-3h", "きました", "来ました", "きました")],
         "Rất hân hạnh. Tôi là Mike Miller. Tôi đến từ Mỹ."),
    line(L, 4, "ミラー (Miller)", "personA",
         [t("d-l1-4a", "IMC"), t("d-l1-4b", "の", key=True),
          t("d-l1-4c", "しゃいん", "社員", "しゃいん"), t("d-l1-4d", "です")],
         "Tôi là nhân viên công ty IMC."),
    line(L, 5, "ミラー (Miller)", "personA",
         [t("d-l1-5a", "どうぞ"), t("d-l1-5b", "よろしく"),
          t("d-l1-5c", "おねがいします", "お願いします", "おねがいします")],
         "Rất mong nhận được sự giúp đỡ của mọi người."),
    line(L, 6, "佐藤 (Satou)", "personB",
         [t("d-l1-6a", "ミラーさん"), t("d-l1-6b", "は"),
          t("d-l1-6c", "エンジニア"), t("d-l1-6d", "ですか", key=True)],
         "Anh Miller là kỹ sư phải không ạ?"),
    line(L, 7, "ミラー (Miller)", "personA",
         [t("d-l1-7a", "いいえ"), t("d-l1-7b", "、"),
          t("d-l1-7c", "エンジニア"), t("d-l1-7d", "じゃ ありません", key=True), t("d-l1-7e", "。"),
          t("d-l1-7f", "かいしゃいん", "会社員", "かいしゃいん"), t("d-l1-7g", "です")],
         "Không, tôi không phải kỹ sư. Tôi là nhân viên công ty."),
    line(L, 8, "佐藤 (Satou)", "personB",
         [t("d-l1-8a", "しつれいですが", "失礼ですが", "しつれいですが"), t("d-l1-8b", "、"),
          t("d-l1-8c", "おいくつ"), t("d-l1-8d", "ですか")],
         "Xin lỗi cho hỏi, anh bao nhiêu tuổi ạ?"),
    line(L, 9, "ミラー (Miller)", "personA",
         [t("d-l1-9a", "にじゅうきゅうさい", "二十九歳", "にじゅうきゅうさい", key=True),
          t("d-l1-9b", "です"), t("d-l1-9c", "。"),
          t("d-l1-9d", "さとうさん", "佐藤さん", "さとうさん"), t("d-l1-9e", "も", key=True),
          t("d-l1-9f", "IMC"), t("d-l1-9g", "の"),
          t("d-l1-9h", "しゃいん", "社員", "しゃいん"), t("d-l1-9i", "ですか")],
         "Tôi 29 tuổi. Chị Satou cũng là nhân viên IMC ạ?"),
    line(L, 10, "佐藤 (Satou)", "personB",
         [t("d-l1-10a", "はい"), t("d-l1-10b", "、"), t("d-l1-10c", "そう"), t("d-l1-10d", "です"),
          t("d-l1-10e", "。"), t("d-l1-10f", "よろしく"),
          t("d-l1-10g", "おねがいします", "お願いします", "おねがいします")],
         "Vâng, đúng vậy. Rất mong được hợp tác."),
]

EXERCISES = [
    q(L, 1, "わたし ___ ナムです。(Chọn trợ từ đánh dấu chủ đề)",
      ["は (wa)", "が (ga)", "を (o)", "に (ni)"], 0,
      "は là trợ từ đánh dấu CHỦ ĐỀ. Viết là 'ha' nhưng khi làm trợ từ thì đọc bật ra thành 'wa'.",
      "Trợ từ cơ bản nhất của bài 1."),
    q(L, 2, "ミラーさんは 医者 ___ ありません。(Phủ định danh từ)",
      ["じゃ", "で", "を", "が"], 0,
      "Phủ định của です là じゃ ありません (dạng nói) hoặc では ありません (trang trọng hơn).",
      "Nhớ cặp です ↔ じゃ ありません."),
    q(L, 3, "A: あの人は ___ ですか。 B: 山田さんです。",
      ["だれ", "なん", "どこ", "いくつ"], 0,
      "Hỏi về NGƯỜI thì dùng だれ (lịch sự hơn: どなた). なん hỏi vật, どこ hỏi nơi chốn.",
      "Câu trả lời là tên một người."),
    q(L, 4, "サントスさんは 学生です。カリナさん ___ 学生です。",
      ["も", "は", "の", "と"], 0,
      "Khi vị ngữ TRÙNG với câu trước, dùng も thay cho は để diễn đạt ý 'cũng'.",
      "Hai người cùng một nghề."),
    q(L, 5, "わたしは IMC ___ 社員です。(Nối hai danh từ)",
      ["の", "は", "も", "で"], 0,
      "の nối hai danh từ, danh từ đứng trước bổ nghĩa cho danh từ đứng sau: IMC の 社員 = nhân viên của IMC.",
      "Quan hệ trực thuộc."),
    q(L, 6, "Câu nào trang trọng NHẤT khi phủ định?",
      ["学生では ありません", "学生じゃ ありません", "学生じゃ ないです", "学生じゃ ない"], 0,
      "Thứ tự trang trọng giảm dần: では ありません > じゃ ありません > じゃ ないです > じゃ ない (suồng sã).",
      "Dạng nào dùng trong văn bản?"),
    q(L, 7, "20 tuổi trong tiếng Nhật đọc là gì?",
      ["はたち", "にじゅうさい", "にじっさい", "ふたつさい"], 0,
      "20 tuổi có cách đọc ĐẶC BIỆT là はたち (二十歳), không đọc theo quy tắc にじゅっさい.",
      "Đây là ngoại lệ phải học thuộc."),
    q(L, 8, "Từ nào KHÔNG được dùng để tự giới thiệu nghề của mình?",
      ["先生", "教師", "会社員", "医者"], 0,
      "先生 là từ dùng để GỌI người khác một cách kính trọng. Nói về nghề của mình phải dùng 教師.",
      "Có từ mang sắc thái kính ngữ."),
    q(L, 9, "Chọn câu chào đúng khi gặp lần đầu:",
      ["はじめまして。どうぞ よろしく お願いします。",
       "おはよう ございます。",
       "お元気ですか。",
       "また あした。"], 0,
      "はじめまして dùng riêng cho lần gặp ĐẦU TIÊN, luôn đi kèm どうぞ よろしく お願いします.",
      "Lần đầu tiên gặp mặt."),
    q(L, 10, "「失礼ですが」 được dùng để làm gì?",
      ["Đệm trước khi hỏi thông tin riêng tư",
       "Xin lỗi vì làm sai",
       "Chào tạm biệt",
       "Cảm ơn ai đó"], 0,
      "失礼ですが = 'xin lỗi cho hỏi', dùng để mở lời trước khi hỏi tên, tuổi, nghề nghiệp cho lịch sự.",
      "Nó đứng TRƯỚC một câu hỏi."),
]

LESSON = lesson(
    L,
    "Bài 1: Giới thiệu bản thân — です / じゃありません / ですか / も / の",
    "Chào hỏi lần đầu, xưng hô, nghề nghiệp, quốc tịch và tuổi tác. Nắm trọn bộ khung câu danh từ: "
    "khẳng định です, phủ định じゃ ありません, nghi vấn か, trợ từ も (cũng) và の (nối danh từ).",
    VOCAB, KANJI, SLIDES, DIALOGUE, EXERCISES,
)

if __name__ == '__main__':
    merge([LESSON])
