# -*- coding: utf-8 -*-
"""N5 — Bài 4: Thời gian, giờ giấc & động từ dạng ます.

Tu vung minh hoa TU CHON tu pool mo data/jlpt-vocab/n5.csv (xem NOTICE.md),
KHONG tai tao lai dung bang tu cua bat ky sach giao trinh cu the nao.
Rieng cac tu ngu phap dong (これ/それ/あれ, は/が/を, です/ます...) la
kien thuc ngon ngu pho quat, khong thuoc ve bat ky nha xuat ban nao.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from n5_lib import v, k, t, ex, slide, line, q, lesson, merge
from jlpt_pool import Pool

L = 4
pool = Pool("n5")

VOCAB = [
    v(1,  "いま", "今", "いま", "ima", "noun", "Bây giờ", "Dùng để hỏi giờ: 今 何時ですか。", L),
    v(2,  "〜じ", "〜時", "〜じ", "-ji", "noun", "~ giờ", "4 giờ よじ, 7 giờ しちじ, 9 giờ くじ — không đọc よんじ/ななじ/きゅうじ.", L),
    v(3,  "〜ふん／〜ぷん", "〜分", "〜ふん／〜ぷん", "-fun/-pun", "noun", "~ phút", "1 phút いっぷん, 3 phút さんぷん, 8 phút はっぷん — biến âm bật hơi.", L),
    v(4,  "はん", "半", "はん", "han", "noun", "Rưỡi, một nửa", "2 giờ rưỡi = にじはん.", L),
    v(5,  "〜じかん", "〜時間", "〜じかん", "-jikan", "noun", "~ tiếng đồng hồ (khoảng thời gian)", "Phân biệt với 〜時 (thời điểm): 2時間 (2 tiếng) khác 2時 (2 giờ).", L),
    v(6,  "なんじ", "何時", "なんじ", "nanji", "noun", "Mấy giờ", "Hỏi thời điểm, không hỏi khoảng thời gian.", L),
    v(7,  "ごぜん", "午前", "ごぜん", "gozen", "noun", "Buổi sáng, giờ AM", "Đứng trước giờ: 午前9時.", L),
    v(8,  "ごご", "午後", "ごご", "gogo", "noun", "Buổi chiều, giờ PM", "午後3時 = 3 giờ chiều.", L),
    v(9,  "あさ", "朝", "あさ", "asa", "noun", "Buổi sáng", "毎朝 = mỗi sáng.", L),
    v(10, "けさ", "今朝", "けさ", "kesa", "noun", "Sáng nay", "Đọc đặc biệt, không theo quy tắc 今+朝.", L),
    v(11, "きょう", "今日", "きょう", "kyou", "noun", "Hôm nay", "Đọc đặc biệt, không phải こんにち trong nghĩa này.", L),
    v(12, "あした", "明日", "あした", "ashita", "noun", "Ngày mai", "Lịch sự hơn: あす.", L),
    v(13, "きのう", "昨日", "きのう", "kinou", "noun", "Hôm qua", "Đọc đặc biệt.", L),
    v(14, "こんばん", "今晩", "こんばん", "konban", "noun", "Tối nay", "今晩は = chào buổi tối (câu chào quen).", L),
    v(15, "げつようび", "月曜日", "げつようび", "getsuyoubi", "noun", "Thứ Hai", "Có thể nói tắt: 月曜.", L),
    v(16, "かようび", "火曜日", "かようび", "kayoubi", "noun", "Thứ Ba", "", L),
    v(17, "きんようび", "金曜日", "きんようび", "kinyoubi", "noun", "Thứ Sáu", "", L),
    v(18, "なんようび", "何曜日", "なんようび", "nan’youbi", "noun", "Thứ mấy", "Hỏi ngày trong tuần.", L),
    v(19, "まいあさ", "毎朝", "まいあさ", "maiasa", "noun", "Mỗi sáng", "毎 + đơn vị thời gian = mỗi ~.", L),
    v(20, "まいばん", "毎晩", "まいばん", "maiban", "noun", "Mỗi tối", "", L),
    v(21, "まいにち", "毎日", "まいにち", "mainichi", "noun", "Mỗi ngày, hằng ngày", "", L),
    v(22, "せんしゅう", "先週", "せんしゅう", "senshuu", "noun", "Tuần trước", "先 = trước, 来 = sau/tới.", L),
    v(23, "らいしゅう", "来週", "らいしゅう", "raishuu", "noun", "Tuần sau", "", L),
    v(24, "ぎんこう", "銀行", "ぎんこう", "ginkou", "noun", "Ngân hàng", "銀行員 = nhân viên ngân hàng (đã học bài 1).", L),
    v(25, "としょかん", "図書館", "としょかん", "toshokan", "noun", "Thư viện", "", L),
    v(26, "えいが", "映画", "えいが", "eiga", "noun", "Phim, điện ảnh", "映画館 = rạp chiếu phim.", L),
    v(27, "やすみ", "休み", "やすみ", "yasumi", "noun", "Ngày nghỉ, kỳ nghỉ", "休みます = nghỉ, vắng mặt.", L),
    v(28, "ばんごう", "番号", "ばんごう", "bangou", "noun", "Số hiệu, số điện thoại", "電話番号 = số điện thoại.", L),
    v(29, "おきます", "起きます", "おきます", "okimasu", "verb", "Thức dậy", "Nhóm 2 (Vて = 起きて).", L),
    v(30, "ねます", "寝ます", "ねます", "nemasu", "verb", "Đi ngủ", "Nhóm 2.", L),
    v(31, "はたらきます", "働きます", "はたらきます", "hatarakimasu", "verb", "Làm việc", "Nhóm 1.", L),
    v(32, "やすみます", "休みます", "やすみます", "yasumimasu", "verb", "Nghỉ ngơi, nghỉ (làm/học)", "Nhóm 1.", L),
    v(33, "べんきょうします", "勉強します", "べんきょうします", "benkyoushimasu", "verb", "Học, học tập", "Nhóm 3 (します).", L),
    v(34, "おわります", "終わります", "おわります", "owarimasu", "verb", "Kết thúc, xong", "Nhóm 1. Trái nghĩa với 始まります.", L),
]

KANJI = [
    k(1, "時", "THỜI", 10, ["ジ (ji)"], ["とき"], "Thời gian, giờ. Đã gặp ở 時計 bài 2 — nay dùng để đếm giờ.",
      [("何時", "なんじ", "Mấy giờ"), ("時間", "じかん", "Khoảng thời gian"), ("時々", "ときどき", "Thỉnh thoảng")], L),
    k(2, "分", "PHÂN", 4, ["フン (fun)", "ブン (bun)"], ["わ(かる)"], "Chia, phần; phút.",
      [("三分", "さんぷん", "3 phút"), ("半分", "はんぶん", "Một nửa"), ("分かります", "わかります", "Hiểu")], L),
    k(3, "曜", "DIỆU", 18, ["ヨウ (you)"], [], "Ngày trong tuần — luôn đi kèm 曜日.",
      [("何曜日", "なんようび", "Thứ mấy"), ("月曜日", "げつようび", "Thứ Hai"), ("日曜日", "にちようび", "Chủ Nhật")], L),
    k(4, "週", "CHU", 11, ["シュウ (shuu)"], [], "Tuần lễ.",
      [("今週", "こんしゅう", "Tuần này"), ("先週", "せんしゅう", "Tuần trước"), ("毎週", "まいしゅう", "Mỗi tuần")], L),
    k(5, "午", "NGỌ", 4, ["ゴ (go)"], [], "Giữa trưa — chỉ dùng ghép trong 午前/午後/正午.",
      [("午前", "ごぜん", "Buổi sáng (AM)"), ("午後", "ごご", "Buổi chiều (PM)"), ("正午", "しょうご", "Giữa trưa")], L),
    k(6, "半", "BÁN", 5, ["ハン (han)"], ["なか(ば)"], "Một nửa.",
      [("半分", "はんぶん", "Một nửa"), ("二時半", "にじはん", "2 giờ rưỡi"), ("半年", "はんとし", "Nửa năm")], L),
]

SLIDES = [
    slide(L, 1,
        "1. Hỏi giờ: 今 何時ですか",
        "今 + 何時 + ですか  →  [số] + 時 + [số] + 分 + です",
        "何時 hỏi THỜI ĐIỂM. Đọc giờ phải nhớ biến âm: 4時 よじ (không phải よんじ), "
        "7時 しちじ (không phải ななじ), 9時 くじ (không phải きゅうじ).",
        [
            ex(L, 1, 1, [t("t-l4s1-1", "いま", "今", "いま"), t("t-l4s1-2", "なんじ", "何時", "なんじ", key=True),
                         t("t-l4s1-3", "ですか")],
               "Bây giờ là mấy giờ vậy?"),
            ex(L, 1, 2, [t("t-l4s1-4", "よじ", "4時", "よじ", key=True), t("t-l4s1-5", "はん", "半", "はん", key=True),
                         t("t-l4s1-6", "です")],
               "4 giờ rưỡi ạ."),
            ex(L, 1, 3, [t("t-l4s1-7", "くじ", "9時", "くじ", key=True), t("t-l4s1-8", "ごじゅっぷん", "50分", "ごじゅっぷん", key=True),
                         t("t-l4s1-9", "です")],
               "9 giờ 50 phút ạ."),
        ],
        tips="Học vẹt 4 số biến âm よじ/しちじ/くじ/よじはん trước — sai bốn số này là lộ ngay người mới học.",
        culture="Người Nhật quen giờ 24h trên tàu xe, nhưng nói chuyện đời thường vẫn dùng 午前/午後 + giờ 12h."),

    slide(L, 2,
        "2. Thời điểm hành động: N[thời gian] + に + V",
        "[Ngày/giờ cụ thể] + に + Vます    (KHÔNG dùng に với hôm nay/mai/hôm qua)",
        "に đánh dấu MỘT THỜI ĐIỂM cụ thể để hành động xảy ra. Ngoại lệ quan trọng: "
        "今日, 明日, 昨日, 今 KHÔNG đi với に — chỉ áp dụng cho ngày trong tuần, giờ, tháng, năm.",
        [
            ex(L, 2, 1, [t("t-l4s2-1", "げつようび", "月曜日", "げつようび", key=True), t("t-l4s2-2", "に", key=True),
                         t("t-l4s2-3", "べんきょうします", "勉強します", "べんきょうします")],
               "Thứ Hai tôi học bài."),
            ex(L, 2, 2, [t("t-l4s2-4", "しちじ", "7時", "しちじ"), t("t-l4s2-5", "に", key=True),
                         t("t-l4s2-6", "おきます", "起きます", "おきます")],
               "7 giờ tôi thức dậy."),
            ex(L, 2, 3, [t("t-l4s2-7", "あした"), t("t-l4s2-8", "はたらきます", "働きます", "はたらきます")],
               "Ngày mai tôi đi làm. (KHÔNG に vì 明日 tự thân đã đủ)"),
        ],
        tips="Học sinh Việt hay thêm nhầm に sau 今日/明日/昨日 — nhớ đây là bốn từ ngoại lệ.",
        culture="銀行 Nhật thường mở 9:00–15:00, đóng cửa cuối tuần — khác giờ hành chính Việt Nam."),

    slide(L, 3,
        "3. Khoảng thời gian から〜まで",
        "[bắt đầu] + から + [kết thúc] + まで",
        "から (từ) và まで (đến) đánh dấu điểm ĐẦU và điểm CUỐI của một khoảng. "
        "Có thể dùng riêng từng cái, hoặc ghép cả hai trong một câu.",
        [
            ex(L, 3, 1, [t("t-l4s3-1", "ぎんこう", "銀行", "ぎんこう"), t("t-l4s3-2", "は"),
                         t("t-l4s3-3", "くじ", "9時", "くじ"), t("t-l4s3-4", "から", key=True),
                         t("t-l4s3-5", "さんじ", "3時", "さんじ"), t("t-l4s3-6", "まで", key=True), t("t-l4s3-7", "です")],
               "Ngân hàng làm việc từ 9 giờ đến 3 giờ."),
            ex(L, 3, 2, [t("t-l4s3-8", "としょかん", "図書館", "としょかん"), t("t-l4s3-9", "は"),
                         t("t-l4s3-10", "げつようび", "月曜日", "げつようび"), t("t-l4s3-11", "から", key=True),
                         t("t-l4s3-12", "きんようび", "金曜日", "きんようび"), t("t-l4s3-13", "まで", key=True), t("t-l4s3-14", "です")],
               "Thư viện mở từ thứ Hai đến thứ Sáu."),
            ex(L, 3, 3, [t("t-l4s3-15", "やすみます", "休みます", "やすみます", key=True), t("t-l4s3-16", "は"),
                         t("t-l4s3-17", "げつようび", "月曜日", "げつようび"), t("t-l4s3-18", "から", key=True), t("t-l4s3-19", "です")],
               "Nghỉ từ thứ Hai. (chỉ dùng から, chưa biết ngày kết thúc)"),
        ],
        tips="から và まで KHÔNG bắt buộc đi cùng nhau — dùng một cái vẫn là câu đúng ngữ pháp.",
        culture="Nhiều cửa hàng nhỏ ở Nhật ghi 定休日 (ngày nghỉ cố định) ngay ngoài cửa, thường là thứ trong tuần chứ không phải cuối tuần."),

    slide(L, 4,
        "4. Động từ ます (hiện tại/tương lai)",
        "V-masu (khẳng định) / V-masen (phủ định)",
        "Thể ます là dạng LỊCH SỰ, trung tính, dùng được với người lạ và trong công việc. "
        "Diễn tả việc THƯỜNG XUYÊN xảy ra hoặc SẼ xảy ra — không phân biệt hiện tại/tương lai bằng động từ.",
        [
            ex(L, 4, 1, [t("t-l4s4-1", "まいあさ", "毎朝", "まいあさ"), t("t-l4s4-2", "しちじ", "7時", "しちじ"),
                         t("t-l4s4-3", "に"), t("t-l4s4-4", "おきます", "起きます", "おきます", key=True)],
               "Mỗi sáng tôi thức dậy lúc 7 giờ."),
            ex(L, 4, 2, [t("t-l4s4-5", "にちようび", "日曜日", "にちようび"), t("t-l4s4-6", "は"),
                         t("t-l4s4-7", "はたらきません", "働きません", "はたらきません", key=True)],
               "Chủ nhật tôi không đi làm."),
            ex(L, 4, 3, [t("t-l4s4-8", "こんばん", "今晩", "こんばん"), t("t-l4s4-9", "じゅういちじ", "11時", "じゅういちじ"),
                         t("t-l4s4-10", "に"), t("t-l4s4-11", "ねます", "寝ます", "ねます", key=True)],
               "Tối nay tôi sẽ đi ngủ lúc 11 giờ."),
        ],
        tips="ません chỉ dùng phủ định VIỆC THÓI QUEN/DỰ ĐỊNH — không nói ai đó 'không thể' làm gì bằng dạng này.",
        culture="働きます nghiêng về 'lao động, đi làm'; nói việc học ở trường dùng 勉強します, không dùng 働きます."),

    slide(L, 5,
        "5. Thì quá khứ: Vました / Vませんでした",
        "V-mashita (đã làm) / V-masen deshita (đã không làm)",
        "Thêm でした vào sau ません để chuyển phủ định sang quá khứ. "
        "Đây là cách chia thì DUY NHẤT cần nhớ ở thể ます — không có biến thể theo chủ ngữ.",
        [
            ex(L, 5, 1, [t("t-l4s5-1", "きのう"), t("t-l4s5-2", "べんきょうしました", "勉強しました", "べんきょうしました", key=True)],
               "Hôm qua tôi đã học bài."),
            ex(L, 5, 2, [t("t-l4s5-3", "せんしゅう", "先週", "せんしゅう"), t("t-l4s5-4", "は"),
                         t("t-l4s5-5", "やすみませんでした", "休みませんでした", "やすみませんでした", key=True)],
               "Tuần trước tôi đã không nghỉ."),
            ex(L, 5, 3, [t("t-l4s5-6", "えいが", "映画", "えいが"), t("t-l4s5-7", "は"),
                         t("t-l4s5-8", "なんじ", "何時", "なんじ", key=True), t("t-l4s5-9", "に"),
                         t("t-l4s5-10", "おわりました", "終わりました", "おわりました", key=True), t("t-l4s5-11", "か")],
               "Phim kết thúc lúc mấy giờ vậy?"),
        ],
        tips="ました/ませんでした luôn giữ nguyên bất kể ngôi thứ mấy — dễ hơn tiếng Việt chia theo chủ ngữ.",
        culture="Người Nhật xem giờ tan làm rất nghiêm — hỏi 何時に終わりますか trước một cuộc hẹn là phép lịch sự thường thấy."),
]

DIALOGUE = [
    line(L, 1, "ミラー", "Nhân viên công ty",
         [t("d-l4-1", "すみません"), t("d-l4-2", "、"), t("d-l4-3", "いま"), t("d-l4-4", "なんじ", "何時", "なんじ", key=True),
          t("d-l4-5", "ですか")],
         "Xin lỗi, bây giờ là mấy giờ vậy ạ?"),
    line(L, 2, "受付", "Lễ tân",
         [t("d-l4-6", "くじ", "9時", "くじ", key=True), t("d-l4-7", "はん", "半", "はん", key=True), t("d-l4-8", "です")],
         "Dạ 9 giờ rưỡi ạ."),
    line(L, 3, "ミラー", "Nhân viên công ty",
         [t("d-l4-9", "ぎんこう", "銀行", "ぎんこう"), t("d-l4-10", "は"), t("d-l4-11", "なんじ", "何時", "なんじ", key=True),
          t("d-l4-12", "から", key=True), t("d-l4-13", "なんじ", "何時", "なんじ", key=True), t("d-l4-14", "まで", key=True),
          t("d-l4-15", "ですか")],
         "Ngân hàng mở cửa từ mấy giờ đến mấy giờ vậy ạ?"),
    line(L, 4, "受付", "Lễ tân",
         [t("d-l4-16", "くじ", "9時", "くじ"), t("d-l4-17", "から", key=True), t("d-l4-18", "さんじ", "3時", "さんじ"),
          t("d-l4-19", "まで", key=True), t("d-l4-20", "です"), t("d-l4-21", "。"), t("d-l4-22", "どようび"), t("d-l4-23", "は"),
          t("d-l4-24", "やすみます", "休みます", "やすみます", key=True)],
         "Từ 9 giờ đến 3 giờ ạ. Thứ Bảy thì nghỉ."),
    line(L, 5, "ミラー", "Nhân viên công ty",
         [t("d-l4-25", "そうですか"), t("d-l4-26", "。"), t("d-l4-27", "ありがとう"), t("d-l4-28", "ございます")],
         "Vậy à. Cảm ơn chị nhiều."),
    line(L, 6, "グプタ", "Đồng nghiệp",
         [t("d-l4-29", "ミラーさん"), t("d-l4-30", "は"), t("d-l4-31", "まいあさ", "毎朝", "まいあさ"),
          t("d-l4-32", "なんじ", "何時", "なんじ", key=True), t("d-l4-33", "に"), t("d-l4-34", "おきます", "起きます", "おきます", key=True),
          t("d-l4-35", "か")],
         "Anh Miller mỗi sáng thức dậy lúc mấy giờ vậy?"),
    line(L, 7, "ミラー", "Nhân viên công ty",
         [t("d-l4-36", "ろくじ", "6時", "ろくじ", key=True), t("d-l4-37", "はん", "半", "はん", key=True), t("d-l4-38", "に"),
          t("d-l4-39", "おきます", "起きます", "おきます")],
         "Tôi thức dậy lúc 6 giờ rưỡi."),
    line(L, 8, "グプタ", "Đồng nghiệp",
         [t("d-l4-40", "きのう"), t("d-l4-41", "も"), t("d-l4-42", "ろくじはん", "6時半", "ろくじはん"), t("d-l4-43", "に"),
          t("d-l4-44", "おきました", "起きました", "おきました", key=True), t("d-l4-45", "か")],
         "Hôm qua cũng thức dậy lúc 6 giờ rưỡi à?"),
    line(L, 9, "ミラー", "Nhân viên công ty",
         [t("d-l4-46", "いいえ"), t("d-l4-47", "、"), t("d-l4-48", "きのう"), t("d-l4-49", "は"),
          t("d-l4-50", "おきませんでした", "起きませんでした", "おきませんでした", key=True), t("d-l4-51", "。"),
          t("d-l4-52", "はちじ", "8時", "はちじ", key=True), t("d-l4-53", "に"), t("d-l4-54", "おきました", "起きました", "おきました")],
         "Không, hôm qua tôi không thức dậy sớm được. Tôi thức dậy lúc 8 giờ."),
    line(L, 10, "グプタ", "Đồng nghiệp",
         [t("d-l4-55", "そうですか"), t("d-l4-56", "。"), t("d-l4-57", "こんばん"), t("d-l4-58", "は"),
          t("d-l4-59", "なんじ", "何時", "なんじ", key=True), t("d-l4-60", "に"), t("d-l4-61", "ねます", "寝ます", "ねます", key=True),
          t("d-l4-62", "か")],
         "Ra vậy. Tối nay anh định ngủ lúc mấy giờ?"),
]

EXERCISES = [
    q(L, 1, "4時 đọc đúng là:",
      ["よじ", "よんじ", "しじ", "よっじ"], 0,
      "4 giờ đọc よじ, biến âm hoàn toàn khác cách đếm số thường (よん).",
      "Đây là một trong bốn số biến âm đặc biệt."),
    q(L, 2, "Câu nào ĐÚNG?",
      ["あした 会社へ 行きます", "あしたに 会社へ 行きます",
       "げつようび 会社へ 行きます", "げつようびは 会社へ 行きます、に"], 0,
      "明日 (ngày mai) là một trong bốn từ ngoại lệ KHÔNG đi với に. Ngày trong tuần thì cần に.",
      "Từ chỉ thời gian tương đối không cần trợ từ に."),
    q(L, 3, "「銀行は 9時から 3時までです」 nghĩa là:",
      ["Ngân hàng mở cửa từ 9 giờ đến 3 giờ", "Ngân hàng mở cửa lúc 9 giờ và 3 giờ",
       "Ngân hàng đóng cửa từ 9 giờ đến 3 giờ", "Ngân hàng mất 9 đến 3 tiếng để mở"], 0,
      "から (từ) đánh dấu điểm bắt đầu, まで (đến) đánh dấu điểm kết thúc của một khoảng thời gian.",
      "Đây là khoảng THỜI GIAN HOẠT ĐỘNG."),
    q(L, 4, "Phủ định quá khứ của 起きます là:",
      ["起きませんでした", "起きませんです", "起きなかったでした", "起きます でした"], 0,
      "Công thức duy nhất: bỏ ます -> thêm ません -> thêm でした. Không có dạng nào khác ở thể lịch sự.",
      "Ghép hai hậu tố lại."),
    q(L, 5, "Từ nào chỉ MỘT TIẾNG ĐỒNG HỒ (khoảng thời gian), không phải một thời điểm?",
      ["2時間", "2時", "2時に", "2時半"], 0,
      "〜時間 là ĐƠN VỊ ĐO độ dài. 〜時 (không có 間) là một ĐIỂM trên đồng hồ.",
      "Có chữ 間 (khoảng) đi kèm."),
    q(L, 6, "「今週」 không cần trợ từ に, nhưng câu nào SAU ĐÂY vẫn cần に?",
      ["月曜日に 勉強します", "今週 勉強します", "今日 勉強します", "毎日 勉強します"], 0,
      "Ngày trong tuần cụ thể (月曜日) cần に. 今週/今日/毎日 là các từ chỉ thời gian tương đối, không cần に.",
      "Ba đáp án còn lại đều là từ tương đối."),
    q(L, 7, "Muốn nói 'nghỉ từ thứ Hai' mà chưa biết ngày kết thúc, dùng:",
      ["月曜日から 休みます", "月曜日まで 休みます",
       "月曜日から月曜日まで 休みます", "月曜日に 休みます"], 0,
      "から dùng độc lập vẫn đúng ngữ pháp khi chỉ biết điểm bắt đầu.",
      "Chỉ cần MỘT trong hai trợ từ."),
    q(L, 8, "8時 đọc là gì (chú ý âm bật hơi)?",
      ["はちじ", "はっじ", "やじ", "はつじ"], 0,
      "8時 đọc bình thường theo quy tắc số đếm là はちじ — không biến âm như 4/7/9時.",
      "8 không nằm trong nhóm 4 số biến âm đặc biệt."),
    q(L, 9, "「今朝」 đọc là gì?",
      ["けさ", "いまあさ", "こんあさ", "きんちょう"], 0,
      "今朝 là một trong các từ đọc ĐẶC BIỆT không theo âm ghép thông thường của 今 + 朝.",
      "Không đọc theo kiểu ghép âm on/kun bình thường."),
    q(L, 10, "Nhà băng Nhật thường đóng cửa ngày nào trong tuần?",
      ["Thứ Bảy và Chủ Nhật", "Chỉ Chủ Nhật", "Không bao giờ đóng cửa", "Thứ Tư"], 0,
      "銀行 Nhật theo giờ hành chính, nghỉ cuối tuần như văn phòng — khác nhiều cửa hàng bán lẻ mở cả tuần.",
      "Giống giờ làm việc công sở."),
]

LESSON = lesson(
    L,
    "Bài 4: Thời gian, giờ giấc & động từ ます",
    "Nói giờ chính xác (kèm 4 số biến âm đặc biệt), chia động từ thể ます ở cả bốn thì "
    "(khẳng định/phủ định × hiện tại/quá khứ), đánh dấu thời điểm bằng に, và khoảng thời gian "
    "bằng から〜まで.",
    VOCAB, KANJI, SLIDES, DIALOGUE, EXERCISES,
)

if __name__ == "__main__":
    pool.mark_used([w["word"] for w in VOCAB if not w["word"].startswith("〜")], lesson=L)
    merge([LESSON])
