# -*- coding: utf-8 -*-
"""N5 — Bài 2 (Minna no Nihongo I): Chỉ thị từ đồ vật & trợ từ の."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from n5_lib import v, k, t, ex, slide, line, q, lesson, merge

L = 2

VOCAB = [
    v(1,  "これ", "", "", "kore", "noun", "Cái này (vật ở gần NGƯỜI NÓI)", "Trong tầm tay mình.", L),
    v(2,  "それ", "", "", "sore", "noun", "Cái đó (vật ở gần NGƯỜI NGHE)", "Trong tầm tay đối phương.", L),
    v(3,  "あれ", "", "", "are", "noun", "Cái kia (vật XA cả hai người)", "Cả hai cùng phải chỉ tay.", L),
    v(4,  "この", "", "", "kono", "particle", "~ này (この + Danh từ)", "この KHÔNG đứng một mình được.", L),
    v(5,  "その", "", "", "sono", "particle", "~ đó (その + Danh từ)", "Luôn dính liền danh từ phía sau.", L),
    v(6,  "あの", "", "", "ano", "particle", "~ kia (あの + Danh từ)", "あの人 = người kia.", L),
    v(7,  "ほん", "本", "ほん", "hon", "noun", "Quyển sách", "Cũng là lượng từ đếm vật dài.", L),
    v(8,  "じしょ", "辞書", "じしょ", "jisho", "noun", "Từ điển", "電子辞書 = từ điển điện tử.", L),
    v(9,  "ざっし", "雑誌", "ざっし", "zasshi", "noun", "Tạp chí", "Âm ngắt っ, bật mạnh.", L),
    v(10, "しんぶん", "新聞", "しんぶん", "shinbun", "noun", "Báo, tờ báo", "Đừng lẫn với ニュース (bản tin).", L),
    v(11, "ノート", "", "", "nooto", "noun", "Quyển vở", "Từ ngoại lai, kéo dài âm ノー.", L),
    v(12, "てちょう", "手帳", "てちょう", "techou", "noun", "Sổ tay", "Dân văn phòng Nhật ai cũng có một quyển.", L),
    v(13, "めいし", "名刺", "めいし", "meishi", "noun", "Danh thiếp", "Trao bằng HAI tay, mặt chữ hướng về người nhận.", L),
    v(14, "カード", "", "", "kaado", "noun", "Thẻ, card", "テレホンカード = thẻ điện thoại.", L),
    v(15, "えんぴつ", "鉛筆", "えんぴつ", "enpitsu", "noun", "Bút chì", "Đếm: 1本 いっぽん, 3本 さんぼん.", L),
    v(16, "ボールペン", "", "", "boorupen", "noun", "Bút bi", "Ghép ball + pen.", L),
    v(17, "シャープペンシル", "", "", "shaapupenshiru", "noun", "Bút chì kim", "Nói tắt hằng ngày: シャーペン.", L),
    v(18, "かぎ", "鍵", "かぎ", "kagi", "noun", "Chìa khóa, ổ khóa", "かぎを かけます = khóa cửa lại.", L),
    v(19, "とけい", "時計", "とけい", "tokei", "noun", "Đồng hồ", "腕時計 うでどけい = đồng hồ đeo tay.", L),
    v(20, "かさ", "傘", "かさ", "kasa", "noun", "Cái ô, cái dù", "Trọng âm phẳng.", L),
    v(21, "かばん", "鞄", "かばん", "kaban", "noun", "Cặp, túi xách", "Thường viết Hiragana.", L),
    v(22, "テープ", "", "", "teepu", "noun", "Băng, cuộn băng", "カセットテープ = băng cát-xét.", L),
    v(23, "テレビ", "", "", "terebi", "noun", "Ti vi", "Nói tắt của テレビジョン.", L),
    v(24, "ラジオ", "", "", "rajio", "noun", "Radio", "Đọc ra-ji-o, không phải 'rây-đi-ô'.", L),
    v(25, "カメラ", "", "", "kamera", "noun", "Máy ảnh", "Nhấn ở âm カ.", L),
    v(26, "コンピューター", "", "", "konpyuutaa", "noun", "Máy vi tính", "Nói tắt: パソコン (máy cá nhân).", L),
    v(27, "つくえ", "机", "つくえ", "tsukue", "noun", "Cái bàn (bàn học, bàn làm việc)", "Bàn ăn thì dùng テーブル.", L),
    v(28, "いす", "椅子", "いす", "isu", "noun", "Cái ghế", "Trọng âm phẳng.", L),
    v(29, "えいご", "英語", "えいご", "eigo", "noun", "Tiếng Anh", "Tên nước + 語 = tiếng nước đó.", L),
    v(30, "にほんご", "日本語", "にほんご", "nihongo", "noun", "Tiếng Nhật", "Riêng tiếng Anh là 英語, không phải イギリス語.", L),
    v(31, "なん", "何", "なん", "nan", "noun", "Cái gì (từ để hỏi vật)", "Trước です đọc なん, đứng riêng đọc なに.", L),
    v(32, "そうです", "", "", "sou desu", "phrase", "Đúng vậy (xác nhận là đúng)", "Đáp cho câu hỏi はい／いいえ.", L),
    v(33, "ちがいます", "違います", "ちがいます", "chigaimasu", "phrase", "Không phải, nhầm rồi", "Nhẹ nhàng hơn いいえ nói trống không.", L),
    v(34, "そうですか", "", "", "sou desu ka", "phrase", "Thế à, ra vậy", "Hạ giọng cuối câu — đây KHÔNG phải câu hỏi.", L),
    v(35, "あのう", "", "", "anou", "phrase", "À, ừm… (đệm trước khi mở lời)", "Kéo dài để xin phép nói xen vào.", L),
    v(36, "どうぞ", "", "", "douzo", "phrase", "Xin mời (khi đưa vật cho ai)", "Đưa bằng hai tay.", L),
    v(37, "どうも", "", "", "doumo", "phrase", "Cảm ơn (ngắn gọn, thân mật)", "Đầy đủ: どうも ありがとう ございます.", L),
    v(38, "ほんのきもちです", "ほんの気持ちです", "ほんのきもちです", "hon no kimochi desu", "phrase", "Chút quà nhỏ gọi là (khi tặng quà)", "Câu khiêm tốn bắt buộc khi biếu quà.", L),
    v(39, "これからおせわになります", "これからお世話になります", "これからおせわになります", "korekara osewa ni narimasu", "phrase", "Từ nay mong được anh/chị giúp đỡ", "Nói khi mới chuyển đến, mới vào làm.", L),
    v(40, "〜ご", "〜語", "〜ご", "-go", "particle", "Tiếng ~ (ベトナム語 = tiếng Việt)", "Gắn sau tên nước.", L),
]

KANJI = [
    k(1, "本", "BẢN", 5, ["ホン (hon)"], ["もと"], "Gốc rễ; quyển sách. Vẽ thân cây có gạch đánh dấu phần gốc.",
      [("本", "ほん", "Quyển sách"), ("日本", "にほん", "Nhật Bản"), ("本当", "ほんとう", "Thật, đúng là")], L),
    k(2, "日", "NHẬT", 4, ["ニチ (nichi)", "ジツ (jitsu)"], ["ひ", "か"], "Mặt trời; ngày. Hình vẽ ông mặt trời.",
      [("日本", "にほん", "Nhật Bản"), ("毎日", "まいにち", "Hằng ngày"), ("今日", "きょう", "Hôm nay")], L),
    k(3, "語", "NGỮ", 14, ["ゴ (go)"], ["かた(る)"], "Ngôn ngữ, lời nói. Bộ 言 (nói) bên trái.",
      [("日本語", "にほんご", "Tiếng Nhật"), ("英語", "えいご", "Tiếng Anh"), ("単語", "たんご", "Từ vựng")], L),
    k(4, "英", "ANH", 8, ["エイ (ei)"], [], "Xuất chúng, tinh hoa; nước Anh.",
      [("英語", "えいご", "Tiếng Anh"), ("英国", "えいこく", "Nước Anh"), ("英会話", "えいかいわ", "Hội thoại tiếng Anh")], L),
    k(5, "時", "THỜI", 10, ["ジ (ji)"], ["とき"], "Thời gian, giờ. Bộ 日 (mặt trời) + 寺.",
      [("時計", "とけい", "Đồng hồ"), ("何時", "なんじ", "Mấy giờ"), ("時々", "ときどき", "Thỉnh thoảng")], L),
    k(6, "計", "KẾ", 9, ["ケイ (kei)"], ["はか(る)"], "Đo đếm, tính toán, kế hoạch.",
      [("時計", "とけい", "Đồng hồ"), ("計画", "けいかく", "Kế hoạch"), ("合計", "ごうけい", "Tổng cộng")], L),
    k(7, "何", "HÀ", 7, ["カ (ka)"], ["なに", "なん"], "Cái gì, bao nhiêu. Từ để hỏi.",
      [("何", "なに", "Cái gì"), ("何時", "なんじ", "Mấy giờ"), ("何人", "なんにん", "Mấy người")], L),
    k(8, "車", "XA", 7, ["シャ (sha)"], ["くるま"], "Xe cộ. Hình vẽ chiếc xe hai bánh nhìn từ trên.",
      [("車", "くるま", "Xe hơi"), ("自動車", "じどうしゃ", "Ô tô"), ("電車", "でんしゃ", "Tàu điện")], L),
]

SLIDES = [
    slide(L, 1,
        "1. これ / それ / あれ は N です",
        "これ / それ / あれ + は + [Danh từ] + です",
        "Ba từ này THAY THẾ luôn tên đồ vật nên đứng một mình được. Chọn từ nào là theo KHOẢNG CÁCH: "
        "これ vật trong tầm tay người nói, それ vật trong tầm tay người nghe, あれ vật xa cả hai.",
        [
            ex(L, 1, 1, [t("t-l2s1-1", "これ", key=True), t("t-l2s1-2", "は"),
                         t("t-l2s1-3", "ほん", "本", "ほん"), t("t-l2s1-4", "です")],
               "Cái này là quyển sách."),
            ex(L, 1, 2, [t("t-l2s1-5", "それ", key=True), t("t-l2s1-6", "は"),
                         t("t-l2s1-7", "じしょ", "辞書", "じしょ"), t("t-l2s1-8", "です")],
               "Cái đó là quyển từ điển."),
            ex(L, 1, 3, [t("t-l2s1-9", "あれ", key=True), t("t-l2s1-10", "は"),
                         t("t-l2s1-11", "なん", "何", "なん", key=True), t("t-l2s1-12", "ですか")],
               "Cái kia là cái gì vậy?"),
        ],
        tips="Vật nằm giữa hai người, ai cũng với tới được thì người nói vẫn chọn これ.",
        culture="Người Nhật ít chỉ tay thẳng vào vật. Họ ngửa bàn tay hướng về phía đó cho lịch sự."),

    slide(L, 2,
        "2. この / その / あの + Danh từ",
        "この / その / あの + [Danh từ] + は + ... です",
        "Khác với これ/それ/あれ, ba từ này KHÔNG đứng một mình — bắt buộc phải dính một danh từ ngay sau. "
        "Dùng khi muốn nói rõ tên vật: cái ô này chứ không chỉ cái này.",
        [
            ex(L, 2, 1, [t("t-l2s2-1", "この", key=True), t("t-l2s2-2", "かさ", "傘", "かさ"),
                         t("t-l2s2-3", "は"), t("t-l2s2-4", "わたし", "私", "わたし"),
                         t("t-l2s2-5", "の"), t("t-l2s2-6", "です")],
               "Cái ô này là của tôi."),
            ex(L, 2, 2, [t("t-l2s2-7", "その", key=True), t("t-l2s2-8", "ざっし", "雑誌", "ざっし"),
                         t("t-l2s2-9", "は"), t("t-l2s2-10", "にほんご", "日本語", "にほんご"),
                         t("t-l2s2-11", "の"), t("t-l2s2-12", "ざっし", "雑誌", "ざっし"), t("t-l2s2-13", "です")],
               "Quyển tạp chí đó là tạp chí tiếng Nhật."),
            ex(L, 2, 3, [t("t-l2s2-14", "あの", key=True), t("t-l2s2-15", "ひと", "人", "ひと"),
                         t("t-l2s2-16", "は"), t("t-l2s2-17", "やまだ", "山田", "やまだ"),
                         t("t-l2s2-18", "さん"), t("t-l2s2-19", "です")],
               "Người kia là anh Yamada."),
        ],
        tips="Nhớ mẹo: これ tự đứng được vì nó ĐÃ là danh từ; この còn thiếu danh từ nên phải mượn một cái.",
        culture="Gọi người thì luôn dùng あの人 hoặc あの方 — đừng bao giờ dùng あれ cho người."),

    slide(L, 3,
        "3. Xác nhận: そうです / ちがいます",
        "はい、そうです。 / いいえ、ちがいます。",
        "Với câu hỏi dạng N ですか chỉ cần đúng-sai, đáp nhanh bằng そうです (đúng vậy) hoặc "
        "ちがいます (không phải). Còn câu hỏi có TỪ ĐỂ HỎI (なん, だれ…) thì KHÔNG được đáp kiểu này.",
        [
            ex(L, 3, 1, [t("t-l2s3-1", "それ"), t("t-l2s3-2", "は"),
                         t("t-l2s3-3", "てちょう", "手帳", "てちょう"), t("t-l2s3-4", "ですか")],
               "Cái đó là quyển sổ tay phải không?"),
            ex(L, 3, 2, [t("t-l2s3-5", "はい"), t("t-l2s3-6", "、"),
                         t("t-l2s3-7", "そうです", key=True)],
               "Vâng, đúng vậy."),
            ex(L, 3, 3, [t("t-l2s3-8", "いいえ"), t("t-l2s3-9", "、"),
                         t("t-l2s3-10", "ちがいます", "違います", "ちがいます", key=True), t("t-l2s3-11", "。"),
                         t("t-l2s3-12", "ノート"), t("t-l2s3-13", "です")],
               "Không phải, đây là quyển vở."),
        ],
        tips="ちがいます nghe mềm hơn いいえ nói trống không rất nhiều — nên tập phản xạ dùng nó.",
        culture="Nghe xong thông tin mới, người Nhật đệm そうですか hạ giọng để báo 'tôi đã nắm được'."),

    slide(L, 4,
        "4. Trợ từ の: sở hữu và thuộc tính",
        "N1 + の + N2   (N1 sở hữu / quy định N2)",
        "の nối hai danh từ theo thứ tự NGƯỢC tiếng Việt: cái sở hữu đứng TRƯỚC. "
        "Ngoài người sở hữu, の còn diễn tả nội dung, chất liệu, nơi sản xuất của vật.",
        [
            ex(L, 4, 1, [t("t-l2s4-1", "わたし", "私", "わたし"), t("t-l2s4-2", "の", key=True),
                         t("t-l2s4-3", "かばん", "鞄", "かばん"), t("t-l2s4-4", "です")],
               "Là cái cặp của tôi."),
            ex(L, 4, 2, [t("t-l2s4-5", "にほんご", "日本語", "にほんご"), t("t-l2s4-6", "の", key=True),
                         t("t-l2s4-7", "ほん", "本", "ほん"), t("t-l2s4-8", "です")],
               "Là quyển sách tiếng Nhật."),
            ex(L, 4, 3, [t("t-l2s4-9", "にほん", "日本", "にほん"), t("t-l2s4-10", "の", key=True),
                         t("t-l2s4-11", "くるま", "車", "くるま"), t("t-l2s4-12", "です")],
               "Là xe hơi của Nhật."),
        ],
        tips="Đọc từ PHẢI sang TRÁI sẽ ra nghĩa tiếng Việt: 日本語の本 → sách ← tiếng Nhật.",
        culture="Người Nhật giới thiệu công ty trước tên mình: IMCの ミラーです — tập thể đứng trên cá nhân."),

    slide(L, 5,
        "5. の thay thế danh từ đã biết",
        "N1 + の  (lược bỏ N2 vì ai cũng hiểu)",
        "Khi danh từ phía sau đã quá rõ trong ngữ cảnh, người Nhật CẮT luôn nó và để の đứng cuối. "
        "わたしの かさ rút thành わたしの. Riêng danh từ chỉ NGƯỜI thì không lược được.",
        [
            ex(L, 5, 1, [t("t-l2s5-1", "この"), t("t-l2s5-2", "かさ", "傘", "かさ"), t("t-l2s5-3", "は"),
                         t("t-l2s5-4", "だれ", "誰", "だれ"), t("t-l2s5-5", "の", key=True), t("t-l2s5-6", "ですか")],
               "Cái ô này là của ai vậy?"),
            ex(L, 5, 2, [t("t-l2s5-7", "わたし", "私", "わたし"), t("t-l2s5-8", "の", key=True),
                         t("t-l2s5-9", "です")],
               "Là của tôi."),
            ex(L, 5, 3, [t("t-l2s5-10", "それ"), t("t-l2s5-11", "は"),
                         t("t-l2s5-12", "サントス"), t("t-l2s5-13", "さん"),
                         t("t-l2s5-14", "の", key=True), t("t-l2s5-15", "じゃ ありません")],
               "Cái đó không phải của anh Santos."),
        ],
        tips="Sai kinh điển: あの人は 先生のです — SAI. Người thì phải nói đủ 先生です.",
        culture="Đồ dùng trong văn phòng Nhật hay dán tên. Hỏi だれのですか là câu cửa miệng."),

    slide(L, 6,
        "6. Hỏi tên vật: N は 何ですか",
        "N + は + 何 (なん) + ですか",
        "何 đọc là なん khi đứng ngay trước です hoặc phụ âm た/だ/な. "
        "Câu hỏi có 何 thì KHÔNG đáp はい／いいえ mà phải trả lời thẳng tên vật.",
        [
            ex(L, 6, 1, [t("t-l2s6-1", "これ"), t("t-l2s6-2", "は"),
                         t("t-l2s6-3", "なん", "何", "なん", key=True), t("t-l2s6-4", "ですか")],
               "Cái này là cái gì vậy?"),
            ex(L, 6, 2, [t("t-l2s6-5", "それ"), t("t-l2s6-6", "は"),
                         t("t-l2s6-7", "めいし", "名刺", "めいし"), t("t-l2s6-8", "です")],
               "Cái đó là danh thiếp."),
            ex(L, 6, 3, [t("t-l2s6-9", "これ"), t("t-l2s6-10", "は"),
                         t("t-l2s6-11", "なん", "何", "なん", key=True), t("t-l2s6-12", "の"),
                         t("t-l2s6-13", "ざっし", "雑誌", "ざっし"), t("t-l2s6-14", "ですか")],
               "Đây là tạp chí về cái gì vậy?"),
        ],
        tips="何の + N hỏi NỘI DUNG (tạp chí về gì), còn だれの + N hỏi CHỦ SỞ HỮU (của ai).",
        culture="Khi chưa rõ vật gì, người Nhật mở lời bằng あのう、これは… rồi bỏ lửng cho đối phương tiếp lời."),
]

DIALOGUE = [
    line(L, 1, "サントス", "Hàng xóm mới chuyển đến",
         [t("d-l2-1", "あのう"), t("d-l2-2", "、"), t("d-l2-3", "これから"),
          t("d-l2-4", "おせわに なります", "お世話に なります", "おせわに なります", key=True), t("d-l2-5", "。")],
         "À, từ nay mong được anh chị giúp đỡ ạ."),
    line(L, 2, "山田一郎", "Hàng xóm",
         [t("d-l2-6", "こちらこそ"), t("d-l2-7", "、"), t("d-l2-8", "よろしく"),
          t("d-l2-9", "おねがいします", "お願いします", "おねがいします"), t("d-l2-10", "。")],
         "Tôi mới là người phải nhờ cậy chứ, rất mong được giúp đỡ."),
    line(L, 3, "サントス", "Hàng xóm mới chuyển đến",
         [t("d-l2-11", "これ"), t("d-l2-12", "、"),
          t("d-l2-13", "ほんのきもちです", "ほんの気持ちです", "ほんのきもちです", key=True),
          t("d-l2-14", "。"), t("d-l2-15", "どうぞ")],
         "Đây, chút quà nhỏ gọi là. Xin mời anh nhận cho."),
    line(L, 4, "山田一郎", "Hàng xóm",
         [t("d-l2-16", "どうも"), t("d-l2-17", "ありがとう"), t("d-l2-18", "ございます"),
          t("d-l2-19", "。"), t("d-l2-20", "これ"), t("d-l2-21", "は"),
          t("d-l2-22", "なん", "何", "なん", key=True), t("d-l2-23", "ですか")],
         "Cảm ơn anh nhiều. Đây là cái gì vậy?"),
    line(L, 5, "サントス", "Hàng xóm mới chuyển đến",
         [t("d-l2-24", "コーヒー"), t("d-l2-25", "です"), t("d-l2-26", "。"),
          t("d-l2-27", "ブラジル"), t("d-l2-28", "の", key=True), t("d-l2-29", "コーヒー"), t("d-l2-30", "です")],
         "Là cà phê ạ. Cà phê của Brazil."),
    line(L, 6, "山田一郎", "Hàng xóm",
         [t("d-l2-31", "そうですか", key=True), t("d-l2-32", "。"),
          t("d-l2-33", "ありがとう"), t("d-l2-34", "ございます")],
         "Thế à. Cảm ơn anh nhiều lắm."),
    line(L, 7, "山田一郎", "Hàng xóm",
         [t("d-l2-35", "あのう"), t("d-l2-36", "、"), t("d-l2-37", "その"),
          t("d-l2-38", "かばん", "鞄", "かばん"), t("d-l2-39", "は"),
          t("d-l2-40", "ブラジル"), t("d-l2-41", "の"), t("d-l2-42", "ですか")],
         "À, cái cặp đó cũng là hàng Brazil à?"),
    line(L, 8, "サントス", "Hàng xóm mới chuyển đến",
         [t("d-l2-43", "いいえ"), t("d-l2-44", "、"),
          t("d-l2-45", "ちがいます", "違います", "ちがいます", key=True), t("d-l2-46", "。"),
          t("d-l2-47", "にほん", "日本", "にほん"), t("d-l2-48", "の"), t("d-l2-49", "です")],
         "Không phải đâu. Là hàng Nhật ạ."),
    line(L, 9, "山田一郎", "Hàng xóm",
         [t("d-l2-50", "あの"), t("d-l2-51", "くるま", "車", "くるま"), t("d-l2-52", "も"),
          t("d-l2-53", "サントス"), t("d-l2-54", "さん"), t("d-l2-55", "の", key=True), t("d-l2-56", "ですか")],
         "Chiếc xe kia cũng là của anh Santos phải không?"),
    line(L, 10, "サントス", "Hàng xóm mới chuyển đến",
         [t("d-l2-57", "はい"), t("d-l2-58", "、"), t("d-l2-59", "そうです", key=True),
          t("d-l2-60", "。"), t("d-l2-61", "わたし", "私", "わたし"), t("d-l2-62", "の"), t("d-l2-63", "です")],
         "Vâng, đúng vậy. Là xe của tôi."),
]

EXERCISES = [
    q(L, 1, "Vật đang nằm trong tay NGƯỜI NGHE, bạn gọi là gì?",
      ["それ", "これ", "あれ", "どれ"], 0,
      "それ chỉ vật ở gần người nghe. これ là gần người nói, あれ là xa cả hai.",
      "Khoảng cách tính từ người nghe."),
    q(L, 2, "Chọn câu ĐÚNG ngữ pháp:",
      ["この かさは わたしのです", "これ かさは わたしのです",
       "この かさは わたしです", "これの かさは わたしのです"], 0,
      "この bắt buộc đi kèm danh từ (かさ). Vế sau dùng わたしの để lược bỏ かさ đã nhắc ở đầu câu.",
      "この đứng một mình được không?"),
    q(L, 3, "「これは 何の 本ですか」 đang hỏi điều gì?",
      ["Sách về nội dung gì", "Sách của ai", "Sách ở đâu", "Sách giá bao nhiêu"], 0,
      "何の + N hỏi NỘI DUNG, chủ đề. Muốn hỏi chủ sở hữu phải dùng だれの + N.",
      "何 nghĩa là 'cái gì'."),
    q(L, 4, "Đáp lại 「それは 辞書ですか」 khi đúng là từ điển:",
      ["はい、そうです。", "はい、辞書の です。", "いいえ、ちがいます。", "はい、そうですか。"], 0,
      "Câu hỏi đúng-sai thì đáp はい、そうです。 Còn そうですか là câu tiếp nhận thông tin, không phải câu đáp.",
      "Xác nhận là ĐÚNG."),
    q(L, 5, "「わたしの 傘」 rút gọn khi đã biết đang nói về cái ô:",
      ["わたしの", "わたしは", "わたしのの", "わたし"], 0,
      "Danh từ phía sau đã rõ thì cắt bỏ, giữ lại の: わたしの です.",
      "Giữ lại trợ từ nối."),
    q(L, 6, "Câu nào SAI?",
      ["あの人は 先生のです", "あの人は 先生です",
       "この本は 先生のです", "その傘は 先生のです"], 0,
      "の chỉ lược được danh từ chỉ VẬT. Danh từ chỉ NGƯỜI không lược được, phải nói đủ 先生です.",
      "Có câu nói về người."),
    q(L, 7, "「日本語の 本」 dịch sang tiếng Việt là:",
      ["Sách tiếng Nhật", "Tiếng Nhật của sách", "Sách và tiếng Nhật", "Sách của người Nhật"], 0,
      "Trong N1のN2, N1 bổ nghĩa cho N2. Dịch ngược từ phải sang trái: 本 ← 日本語.",
      "Danh từ chính đứng sau cùng."),
    q(L, 8, "何 trong 「これは 何ですか」 đọc là:",
      ["なん", "なに", "か", "どう"], 0,
      "何 đọc なん khi đứng trước です và các âm た/だ/な. Đứng riêng hoặc trước を thì đọc なに.",
      "Để ý âm đứng liền sau."),
    q(L, 9, "Khi tặng quà, người Nhật thường nói:",
      ["ほんの 気持ちです", "これは 高いです", "どうぞ よろしく", "お世話に なりました"], 0,
      "ほんの気持ちです = 'chút lòng thành nhỏ mọn', câu khiêm tốn chuẩn mực khi biếu quà.",
      "Nói giảm giá trị món quà."),
    q(L, 10, "「そうですか」 hạ giọng khác với lên giọng ở chỗ nào?",
      ["Hạ giọng là tiếp nhận thông tin, lên giọng là hỏi lại",
       "Hoàn toàn giống nhau",
       "Hạ giọng là câu hỏi",
       "Chỉ dùng được với người trên"], 0,
      "Cùng một chữ nhưng ngữ điệu quyết định: hạ giọng = 'ra vậy', lên giọng = 'thật thế à?' (ngạc nhiên).",
      "Nghe ngữ điệu cuối câu."),
]

LESSON = lesson(
    L,
    "Bài 2: Chỉ thị từ đồ vật (これ / それ / あれ) & trợ từ の",
    "Trỏ đồ vật theo khoảng cách これ / それ / あれ, cụm bổ nghĩa この / その / あの + Danh từ, "
    "xác nhận そうです / ちがいます, trợ từ の nối và thay thế danh từ, hỏi tên vật bằng 何ですか.",
    VOCAB, KANJI, SLIDES, DIALOGUE, EXERCISES,
)

if __name__ == '__main__':
    merge([LESSON])
