# -*- coding: utf-8 -*-
"""N5 — Bài 5: Di chuyển & phương tiện (へ 行きます/来ます/帰ります, で, と, いつ).

Tu vung minh hoa TU CHON tu pool mo data/jlpt-vocab/n5.csv (xem NOTICE.md).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from n5_lib import v, k, t, ex, slide, line, q, lesson, merge
from jlpt_pool import Pool

L = 5
pool = Pool("n5")

VOCAB = [
    v(1,  "いきます", "行きます", "いきます", "ikimasu", "verb", "Đi (đến một nơi)", "Thể từ điển: 行く. Nhóm I.", L),
    v(2,  "きます", "来ます", "きます", "kimasu", "verb", "Đến, tới (về phía người nói)", "Thể từ điển: 来る. Nhóm II bất quy tắc.", L),
    v(3,  "かえります", "帰ります", "かえります", "kaerimasu", "verb", "Về, trở về (nhà, quê)", "Thể từ điển: 帰る. Nhóm I (trông giống nhóm II nhưng chia như nhóm I).", L),
    v(4,  "のります", "乗ります", "のります", "norimasu", "verb", "Lên, đi (phương tiện)", "Đi kèm trợ từ に: 電車に 乗ります.", L),
    v(5,  "おります", "降ります", "おります", "orimasu", "verb", "Xuống (phương tiện)", "Đi kèm trợ từ を: バスを 降ります.", L),
    v(6,  "えき", "駅", "えき", "eki", "noun", "Nhà ga", "駅員 = nhân viên nhà ga.", L),
    v(7,  "でんしゃ", "電車", "でんしゃ", "densha", "noun", "Tàu điện", "Phương tiện phổ biến nhất ở đô thị Nhật.", L),
    v(8,  "じてんしゃ", "自転車", "じてんしゃ", "jitensha", "noun", "Xe đạp", "自転車に 乗ります = đi xe đạp.", L),
    v(9,  "くるま", "車", "くるま", "kuruma", "noun", "Xe hơi, ô tô", "Đã gặp ở bài 2 (đồ vật); nay dùng làm phương tiện.", L),
    v(10, "じどうしゃ", "自動車", "じどうしゃ", "jidousha", "noun", "Ô tô (trang trọng hơn 車)", "Dùng nhiều trong văn viết, biển báo.", L),
    v(11, "バス", "", "", "basu", "noun", "Xe buýt", "バス停 = trạm xe buýt.", L),
    v(12, "タクシー", "", "", "takushii", "noun", "Taxi", "", L),
    v(13, "ひこうき", "飛行機", "ひこうき", "hikouki", "noun", "Máy bay", "空港 = sân bay (chưa học, sẽ gặp ở bài sau).", L),
    v(14, "ともだち", "友達", "ともだち", "tomodachi", "noun", "Bạn bè", "友達と = cùng với bạn bè.", L),
    v(15, "いっしょに", "一緒に", "いっしょに", "issho ni", "phrase", "Cùng nhau, cùng với", "友達と 一緒に 行きます = đi cùng với bạn.", L),
    v(16, "ひとり", "一人", "ひとり", "hitori", "noun", "Một mình, một người", "一人で 行きます = đi một mình.", L),
    v(17, "いつ", "", "", "itsu", "noun", "Khi nào (từ để hỏi thời gian không xác định)", "Khác 何時 (hỏi giờ cụ thể) và 何曜日 (hỏi thứ).", L),
    v(18, "いつも", "", "", "itsumo", "noun", "Luôn luôn, mọi khi", "いつも 電車で 行きます = tôi luôn đi bằng tàu điện.", L),
    v(19, "たんじょうび", "誕生日", "たんじょうび", "tanjoubi", "noun", "Sinh nhật", "お誕生日おめでとうございます = chúc mừng sinh nhật.", L),
    v(20, "りょこう", "旅行", "りょこう", "ryokou", "noun", "Du lịch, chuyến đi", "旅行します = đi du lịch.", L),
    v(21, "らいしゅう", "来週", "らいしゅう", "raishuu", "noun", "Tuần sau", "Đã gặp bài 4.", L),
    v(22, "らいげつ", "来月", "らいげつ", "raigetsu", "noun", "Tháng sau", "", L),
    v(23, "らいねん", "来年", "らいねん", "rainen", "noun", "Năm sau", "", L),
    v(24, "〜がつ", "〜月", "〜がつ", "-gatsu", "noun", "Tháng ~ (trong năm)", "4月 しがつ, 7月 しちがつ, 9月 くがつ — ba số biến âm phải nhớ.", L),
    v(25, "〜にち／〜か", "〜日", "〜にち／〜か", "-nichi/-ka", "noun", "Ngày ~ (trong tháng)", "1日 ついたち là ngoại lệ hoàn toàn không theo quy tắc.", L),
]

KANJI = [
    k(1, "行", "HÀNH", 6, ["コウ (kou)"], ["い(く)", "おこな(う)"], "Đi, thực hiện. Hình vẽ ngã tư đường.",
      [("行きます", "いきます", "Đi"), ("旅行", "りょこう", "Du lịch"), ("銀行", "ぎんこう", "Ngân hàng")], L),
    k(2, "来", "LAI", 7, ["ライ (rai)"], ["く(る)", "き(たる)"], "Đến, tới; sắp tới.",
      [("来ます", "きます", "Đến"), ("来週", "らいしゅう", "Tuần sau"), ("来年", "らいねん", "Năm sau")], L),
    k(3, "駅", "DỊCH", 14, ["エキ (eki)"], [], "Nhà ga. Bộ 馬 (ngựa) bên trái — gốc từ trạm đổi ngựa thời xưa.",
      [("駅", "えき", "Nhà ga"), ("駅前", "えきまえ", "Trước ga"), ("東京駅", "とうきょうえき", "Ga Tokyo")], L),
    k(4, "月", "NGUYỆT", 4, ["ゲツ (getsu)", "ガツ (gatsu)"], ["つき"], "Mặt trăng; tháng.",
      [("来月", "らいげつ", "Tháng sau"), ("四月", "しがつ", "Tháng 4"), ("月曜日", "げつようび", "Thứ Hai")], L),
    k(5, "友", "HỮU", 4, ["ユウ (yuu)"], ["とも"], "Bạn bè. Hai bàn tay nắm nhau.",
      [("友達", "ともだち", "Bạn bè"), ("友情", "ゆうじょう", "Tình bạn"), ("親友", "しんゆう", "Bạn thân")], L),
]

SLIDES = [
    slide(L, 1,
        "1. Điểm đến: N[nơi chốn] + へ + 行きます/来ます/帰ります",
        "[Địa điểm] + へ (đọc \"e\") + 行きます / 来ます / 帰ります",
        "へ đánh dấu HƯỚNG di chuyển, đọc là え chứ không phải へ (he). Ba động từ dùng với へ: "
        "行く (đi xa người nói), 来る (đến gần người nói), 帰る (về nơi thuộc về mình — nhà, quê).",
        [
            ex(L, 1, 1, [t("t-l5s1-1", "らいしゅう", "来週", "らいしゅう"), t("t-l5s1-2", "にほん", "日本", "にほん"),
                         t("t-l5s1-3", "へ", key=True), t("t-l5s1-4", "いきます", "行きます", "いきます", key=True)],
               "Tuần sau tôi sẽ đi Nhật Bản."),
            ex(L, 1, 2, [t("t-l5s1-5", "せんせい", "先生", "せんせい"), t("t-l5s1-6", "は"),
                         t("t-l5s1-7", "きょうしつ", "教室", "きょうしつ"), t("t-l5s1-8", "へ", key=True),
                         t("t-l5s1-9", "きます", "来ます", "きます", key=True)],
               "Thầy giáo đang đến phòng học."),
            ex(L, 1, 3, [t("t-l5s1-10", "なんじ", "何時", "なんじ"), t("t-l5s1-11", "に"),
                         t("t-l5s1-12", "うち", "家", "うち"), t("t-l5s1-13", "へ", key=True),
                         t("t-l5s1-14", "かえります", "帰ります", "かえります", key=True), t("t-l5s1-15", "か")],
               "Mấy giờ anh về nhà vậy?"),
        ],
        tips="へ chỉ là trợ từ, luôn đọc え. Đây là một trong ba chữ đặc biệt (は/へ/を) đọc khác cách viết.",
        culture="帰ります còn dùng cho 'về nước' dù đang ở nước ngoài — vì quê hương luôn là nơi để 帰る."),

    slide(L, 2,
        "2. Phương tiện: N[phương tiện] + で + V",
        "[Phương tiện] + で + 行きます/来ます/帰ります   (đi bộ: 歩いて + V, không dùng で)",
        "で đánh dấu PHƯƠNG TIỆN hoặc CÔNG CỤ thực hiện hành động. Ngoại lệ duy nhất: đi bộ "
        "không dùng で mà dùng 歩いて (dạng て của 歩きます).",
        [
            ex(L, 2, 1, [t("t-l5s2-1", "でんしゃ", "電車", "でんしゃ"), t("t-l5s2-2", "で", key=True),
                         t("t-l5s2-3", "かいしゃ", "会社", "かいしゃ"), t("t-l5s2-4", "へ"),
                         t("t-l5s2-5", "いきます", "行きます", "いきます")],
               "Tôi đi làm bằng tàu điện."),
            ex(L, 2, 2, [t("t-l5s2-6", "じてんしゃ", "自転車", "じてんしゃ"), t("t-l5s2-7", "で", key=True),
                         t("t-l5s2-8", "えき", "駅", "えき"), t("t-l5s2-9", "へ"), t("t-l5s2-10", "きます", "来ます", "きます")],
               "Tôi đến ga bằng xe đạp."),
            ex(L, 2, 3, [t("t-l5s2-11", "あるいて", "歩いて", "あるいて", key=True), t("t-l5s2-12", "うち", "家", "うち"),
                         t("t-l5s2-13", "へ"), t("t-l5s2-14", "かえります", "帰ります", "かえります")],
               "Tôi đi bộ về nhà. (KHÔNG dùng で với đi bộ)"),
        ],
        tips="Lỗi rất hay gặp: 「歩いてで 帰ります」 — SAI. 歩いて đã đủ nghĩa 'bằng cách đi bộ', không thêm で nữa.",
        culture="Ở Tokyo, đi làm bằng 電車 là chuyện bình thường dù mất cả tiếng đồng hồ — khác thói quen đi xe máy ở Việt Nam."),

    slide(L, 3,
        "3. Người cùng đi: N[người] + と + V",
        "[Người] + と + 一緒に + V   /   一人で + V (đi một mình)",
        "と đánh dấu người CÙNG THAM GIA hành động — khác hẳn は (chủ đề) hay を (tân ngữ). "
        "Đi một mình thì không dùng と mà dùng 一人で.",
        [
            ex(L, 3, 1, [t("t-l5s3-1", "ともだち", "友達", "ともだち"), t("t-l5s3-2", "と", key=True),
                         t("t-l5s3-3", "いっしょに", "一緒に", "いっしょに", key=True), t("t-l5s3-4", "りょこう", "旅行", "りょこう"),
                         t("t-l5s3-5", "します")],
               "Tôi đi du lịch cùng với bạn bè."),
            ex(L, 3, 2, [t("t-l5s3-6", "だれ", "誰", "だれ"), t("t-l5s3-7", "と", key=True),
                         t("t-l5s3-8", "にほん", "日本", "にほん"), t("t-l5s3-9", "へ"), t("t-l5s3-10", "いきますか", "行きますか", "いきますか")],
               "Anh đi Nhật với ai vậy?"),
            ex(L, 3, 3, [t("t-l5s3-11", "ひとり", "一人", "ひとり", key=True), t("t-l5s3-12", "で"),
                         t("t-l5s3-13", "いきます", "行きます", "いきます")],
               "Tôi đi một mình."),
        ],
        tips="Hỏi 'với ai' luôn dùng 誰と — không được nói 誰は hay để trống trợ từ.",
        culture="Người Nhật có khái niệm 一人旅 (du lịch một mình) rất phổ biến và được xã hội chấp nhận, không bị coi là cô đơn."),

    slide(L, 4,
        "4. Hỏi thời điểm không xác định: いつ",
        "いつ + V + か   (khác 何時: hỏi GIỜ; khác 何曜日: hỏi THỨ)",
        "いつ hỏi một thời điểm chung chung — có thể trả lời bằng ngày, tháng, năm, hoặc cả một "
        "khoảng như 来週. Đây là điểm khác với 何時 (chỉ hỏi giờ) đã học ở bài 4.",
        [
            ex(L, 4, 1, [t("t-l5s4-1", "いつ", key=True), t("t-l5s4-2", "にほん", "日本", "にほん"),
                         t("t-l5s4-3", "へ"), t("t-l5s4-4", "いきますか", "行きますか", "いきますか")],
               "Khi nào anh đi Nhật vậy?"),
            ex(L, 4, 2, [t("t-l5s4-5", "らいげつ", "来月", "らいげつ"), t("t-l5s4-6", "いきます", "行きます", "いきます")],
               "Tháng sau tôi đi."),
            ex(L, 4, 3, [t("t-l5s4-7", "たんじょうび", "誕生日", "たんじょうび"), t("t-l5s4-8", "は"),
                         t("t-l5s4-9", "いつ", key=True), t("t-l5s4-10", "ですか")],
               "Sinh nhật anh là khi nào vậy?"),
        ],
        tips="いつ không đi kèm trợ từ (không nói いつに, いつは) — đứng trực tiếp trong câu.",
        culture="Người Nhật hỏi sinh nhật khá tự nhiên trong giao tiếp xã giao, không bị coi là riêng tư như hỏi tuổi/lương."),

    slide(L, 5,
        "5. Đọc tháng, ngày: 〜月〜日",
        "[số] + 月 + [số] + 日",
        "月 (tháng) chỉ biến âm ở 4, 7, 9: しがつ、しちがつ、くがつ. "
        "日 (ngày) biến âm phức tạp hơn nhiều — đặc biệt 1日 đọc ついたち, hoàn toàn không theo quy tắc.",
        [
            ex(L, 5, 1, [t("t-l5s5-1", "たんじょうび", "誕生日", "たんじょうび"), t("t-l5s5-2", "は"),
                         t("t-l5s5-3", "しがつ", "4月", "しがつ", key=True), t("t-l5s5-4", "ついたち", "1日", "ついたち", key=True),
                         t("t-l5s5-5", "です")],
               "Sinh nhật tôi là ngày mùng 1 tháng 4."),
            ex(L, 5, 2, [t("t-l5s5-6", "らいねん", "来年", "らいねん"), t("t-l5s5-7", "の"),
                         t("t-l5s5-8", "くがつ", "9月", "くがつ", key=True), t("t-l5s5-9", "に"),
                         t("t-l5s5-10", "りょこう", "旅行", "りょこう"), t("t-l5s5-11", "します")],
               "Tháng 9 năm sau tôi sẽ đi du lịch."),
            ex(L, 5, 3, [t("t-l5s5-12", "なんがつ", "何月", "なんがつ", key=True), t("t-l5s5-13", "なんにち", "何日", "なんにち", key=True),
                         t("t-l5s5-14", "ですか")],
               "Ngày mấy tháng mấy vậy?"),
        ],
        tips="Học riêng bảng 1日〜10日 (ついたち、ふつか、みっか…) như một nhóm từ vựng độc lập — không suy luận được.",
        culture="Năm tài chính và năm học ở Nhật bắt đầu từ tháng 4, không phải tháng 1 như lịch dương thông thường."),
]

DIALOGUE = [
    line(L, 1, "ワン", "Du học sinh",
         [t("d-l5-1", "サントスさん"), t("d-l5-2", "は"), t("d-l5-3", "まいにち", "毎日", "まいにち"),
          t("d-l5-4", "なんで", "何で", "なんで", key=True), t("d-l5-5", "がっこう", "学校", "がっこう"),
          t("d-l5-6", "へ"), t("d-l5-7", "きますか", "来ますか", "きますか")],
         "Anh Santos ngày nào cũng đến trường bằng gì vậy?"),
    line(L, 2, "サントス", "Du học sinh",
         [t("d-l5-8", "でんしゃ", "電車", "でんしゃ", key=True), t("d-l5-9", "で"), t("d-l5-10", "きます", "来ます", "きます"),
          t("d-l5-11", "。"), t("d-l5-12", "ワンさん"), t("d-l5-13", "は")],
         "Tôi đi bằng tàu điện. Còn Wang thì sao?"),
    line(L, 3, "ワン", "Du học sinh",
         [t("d-l5-14", "わたし", "私", "わたし"), t("d-l5-15", "は"), t("d-l5-16", "あるいて", "歩いて", "あるいて", key=True),
          t("d-l5-17", "きます", "来ます", "きます"), t("d-l5-18", "。"), t("d-l5-19", "うち", "家", "うち"),
          t("d-l5-20", "から"), t("d-l5-21", "ちかい", "近い", "ちかい"), t("d-l5-22", "です")],
         "Tôi đi bộ. Vì nhà tôi gần đây."),
    line(L, 4, "サントス", "Du học sinh",
         [t("d-l5-23", "いいですね"), t("d-l5-24", "。"), t("d-l5-25", "らいしゅう", "来週", "らいしゅう"),
          t("d-l5-26", "の"), t("d-l5-27", "どようび", "土曜日", "どようび"), t("d-l5-28", "、"),
          t("d-l5-29", "ひま", "暇", "ひま"), t("d-l5-30", "ですか")],
         "Tốt vậy. Thứ Bảy tuần sau anh có rảnh không?"),
    line(L, 5, "ワン", "Du học sinh",
         [t("d-l5-31", "ええ"), t("d-l5-32", "、"), t("d-l5-33", "ひま", "暇", "ひま"), t("d-l5-34", "です"),
          t("d-l5-35", "。"), t("d-l5-36", "どうしてですか")],
         "Ừ, tôi rảnh. Sao vậy?"),
    line(L, 6, "サントス", "Du học sinh",
         [t("d-l5-37", "ともだち", "友達", "ともだち", key=True), t("d-l5-38", "と", key=True),
          t("d-l5-39", "いっしょに", "一緒に", "いっしょに", key=True), t("d-l5-40", "こうえん", "公園", "こうえん"),
          t("d-l5-41", "へ"), t("d-l5-42", "いきます", "行きます", "いきます"), t("d-l5-43", "。"),
          t("d-l5-44", "いっしょに"), t("d-l5-45", "どうですか")],
         "Tôi định đi công viên cùng bạn bè. Wang đi cùng luôn nhé?"),
    line(L, 7, "ワン", "Du học sinh",
         [t("d-l5-46", "いいですね"), t("d-l5-47", "。"), t("d-l5-48", "なんで", "何で", "なんで", key=True),
          t("d-l5-49", "いきますか", "行きますか", "いきますか")],
         "Được đó. Đi bằng gì vậy?"),
    line(L, 8, "サントス", "Du học sinh",
         [t("d-l5-50", "じてんしゃ", "自転車", "じてんしゃ", key=True), t("d-l5-51", "で"),
          t("d-l5-52", "いきます", "行きます", "いきます")],
         "Đi bằng xe đạp."),
    line(L, 9, "ワン", "Du học sinh",
         [t("d-l5-53", "いいですね"), t("d-l5-54", "。"), t("d-l5-55", "いつ"),
          t("d-l5-56", "、"), t("d-l5-57", "どこ"), t("d-l5-58", "で"), t("d-l5-59", "あいますか", "会いますか", "あいますか")],
         "Tốt. Khi nào, ở đâu thì gặp nhau vậy?"),
    line(L, 10, "サントス", "Du học sinh",
         [t("d-l5-60", "どようび", "土曜日", "どようび"), t("d-l5-61", "の"), t("d-l5-62", "あさ", "朝", "あさ"),
          t("d-l5-63", "くじ", "9時", "くじ"), t("d-l5-64", "に"), t("d-l5-65", "えき", "駅", "えき", key=True),
          t("d-l5-66", "で"), t("d-l5-67", "あいましょう", "会いましょう", "あいましょう")],
         "9 giờ sáng thứ Bảy gặp nhau ở ga nhé."),
]

EXERCISES = [
    q(L, 1, "Trợ từ へ trong 「日本へ 行きます」 đọc là:",
      ["え", "へ", "は", "え、へ đều được"], 0,
      "へ là một trong ba trợ từ đọc khác chữ viết (は=わ, へ=え, を=お). Luôn đọc え khi làm trợ từ chỉ hướng.",
      "Đây là ngoại lệ về cách đọc."),
    q(L, 2, "Câu nào ĐÚNG khi nói 'đi bộ về nhà'?",
      ["歩いて 家へ 帰ります", "歩いてで 家へ 帰ります",
       "歩きます で 家へ 帰ります", "歩いて で 家へ 帰ります"], 0,
      "歩いて (dạng て của 歩きます) đã tự đủ nghĩa 'bằng cách đi bộ' — không được thêm で phía sau.",
      "で chỉ dùng với danh từ phương tiện, không dùng với dạng て."),
    q(L, 3, "「友達と 一緒に 行きます」 và 「一人で 行きます」 khác nhau ở đâu?",
      ["Có bạn đi cùng / đi một mình", "Đi bằng xe / đi bộ",
       "Đi hôm nay / đi mai", "Không khác gì cả"], 0,
      "と…一緒に nói có người cùng đi; 一人で nói đi một mình — hai cấu trúc đối lập nhau.",
      "So sánh nghĩa của と và 一人."),
    q(L, 4, "Muốn hỏi 'khi nào' một cách chung chung (không nhất thiết hỏi giờ), dùng từ nào?",
      ["いつ", "何時", "何曜日", "何日"], 0,
      "いつ hỏi thời điểm chung chung, có thể trả lời bằng ngày/tháng/năm/tuần. 何時 chỉ hỏi GIỜ cụ thể.",
      "Từ này không cần biết đơn vị trả lời trước."),
    q(L, 5, "1日 (ngày mùng 1) đọc là:",
      ["ついたち", "いちにち", "いちじつ", "ひとひ"], 0,
      "1日 là trường hợp đọc HOÀN TOÀN đặc biệt, không theo quy tắc số + 日 thông thường.",
      "Đây là từ phải học thuộc riêng, không suy luận được."),
    q(L, 6, "「電車に 乗ります」 và 「電車を 降ります」 khác nhau ở trợ từ vì:",
      ["に là hướng ĐẾN (lên xe), を là tân ngữ rời khỏi (xuống xe)",
       "に và を hoàn toàn có thể thay cho nhau",
       "を luôn dùng cho phương tiện", "に chỉ dùng cho tàu, を chỉ dùng cho xe buýt"], 0,
      "乗ります dùng に (hướng tới, lên phương tiện); 降ります dùng を (rời khỏi, tân ngữ của hành động xuống).",
      "Hai động từ ngược nghĩa dùng hai trợ từ khác nhau."),
    q(L, 7, "4月 (tháng 4) đọc là:",
      ["しがつ", "よんがつ", "よがつ", "しつき"], 0,
      "月 chỉ biến âm ở ba số: 4月 しがつ, 7月 しちがつ, 9月 くがつ.",
      "Không đọc theo số đếm thông thường よん."),
    q(L, 8, "誰と 日本へ 行きますか — câu này KHÔNG THỂ trả lời bằng:",
      ["はい、そうです", "友達と 行きます", "一人で 行きます", "田中さんと 行きます"], 0,
      "Câu hỏi có từ để hỏi 誰 (ai) không đáp được bằng はい/いいえ, phải trả lời thẳng nội dung.",
      "So sánh với quy tắc đã học ở bài 3."),
    q(L, 9, "Từ nào dùng để chỉ PHƯƠNG TIỆN đi lại?",
      ["で", "へ", "と", "に"], 0,
      "で đánh dấu phương tiện/công cụ. へ chỉ hướng đến, と chỉ người cùng đi, に chỉ thời điểm hoặc điểm đến của một số động từ.",
      "Bốn trợ từ này dễ nhầm nếu không phân biệt rõ chức năng."),
    q(L, 10, "Năm học và năm tài chính ở Nhật thường bắt đầu vào tháng nào?",
      ["Tháng 4", "Tháng 1", "Tháng 9", "Tháng 3"], 0,
      "Khác với lịch dương thông thường bắt đầu tháng 1, Nhật Bản dùng năm tài chính và năm học bắt đầu từ tháng 4.",
      "Trùng thời điểm hoa anh đào nở."),
]

LESSON = lesson(
    L,
    "Bài 5: Di chuyển & Phương tiện (へ 行きます/来ます/帰ります, で, と, いつ)",
    "Nói điểm đến bằng へ, phương tiện di chuyển bằng で (trừ đi bộ dùng 歩いて), người cùng đi "
    "bằng と…一緒に hoặc đi một mình bằng 一人で, hỏi thời điểm chung chung bằng いつ, và cách "
    "đọc ngày tháng 〜月〜日.",
    VOCAB, KANJI, SLIDES, DIALOGUE, EXERCISES,
)

if __name__ == "__main__":
    pool.mark_used([w["word"] for w in VOCAB if not w["word"].startswith("〜")], lesson=L)
    merge([LESSON])
