# -*- coding: utf-8 -*-
"""N5 — Bài 6: Tha động từ (N を V), địa điểm hành động (N で V), lời mời ませんか.

Tu vung minh hoa TU CHON tu pool mo data/jlpt-vocab/n5.csv (xem NOTICE.md).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from n5_lib import v, k, t, ex, slide, line, q, lesson, merge
from jlpt_pool import Pool

L = 6
pool = Pool("n5")

VOCAB = [
    v(1,  "たべます", "食べます", "たべます", "tabemasu", "verb", "Ăn", "Thể từ điển: 食べる. Nhóm II.", L),
    v(2,  "のみます", "飲みます", "のみます", "nomimasu", "verb", "Uống", "Thể từ điển: 飲む. Nhóm I.", L),
    v(3,  "みます", "見ます", "みます", "mimasu", "verb", "Xem, nhìn", "Thể từ điển: 見る. Nhóm II.", L),
    v(4,  "ききます", "聞きます", "ききます", "kikimasu", "verb", "Nghe, hỏi", "Thể từ điển: 聞く. Nhóm I. Vừa nghĩa nghe vừa nghĩa hỏi.", L),
    v(5,  "よみます", "読みます", "よみます", "yomimasu", "verb", "Đọc", "Thể từ điển: 読む. Nhóm I.", L),
    v(6,  "かきます", "書きます", "かきます", "kakimasu", "verb", "Viết, vẽ", "Thể từ điển: 書く. Nhóm I.", L),
    v(7,  "かいます", "買います", "かいます", "kaimasu", "verb", "Mua", "Thể từ điển: 買う. Nhóm I.", L),
    v(8,  "とります", "撮ります", "とります", "torimasu", "verb", "Chụp (ảnh)", "Thể từ điển: 撮る. Nhóm I. Khác 取ります (lấy).", L),
    v(9,  "つくります", "作ります", "つくります", "tsukurimasu", "verb", "Làm, chế tạo, nấu", "Thể từ điển: 作る. Nhóm I.", L),
    v(10, "あいます", "会います", "あいます", "aimasu", "verb", "Gặp", "Thể từ điển: 会う. Đi với person + に, không phải を.", L),
    v(11, "すいます", "吸います", "すいます", "suimasu", "verb", "Hút (thuốc), hít vào", "たばこを 吸います = hút thuốc.", L),
    v(12, "します", "", "", "shimasu", "verb", "Làm (động từ vạn năng)", "Ghép với danh từ hành động: 勉強します, 仕事します.", L),
    v(13, "パン", "", "", "pan", "noun", "Bánh mì", "Từ mượn tiếng Bồ Đào Nha, du nhập từ lâu.", L),
    v(14, "にく", "肉", "にく", "niku", "noun", "Thịt", "豚肉 = thịt heo, 鶏肉 = thịt gà, 牛肉 = thịt bò.", L),
    v(15, "さかな", "魚", "さかな", "sakana", "noun", "Cá", "", L),
    v(16, "やさい", "野菜", "やさい", "yasai", "noun", "Rau", "", L),
    v(17, "くだもの", "果物", "くだもの", "kudamono", "noun", "Trái cây", "", L),
    v(18, "しんぶん", "新聞", "しんぶん", "shinbun", "noun", "Báo, tờ báo", "Đã gặp ở bài 2 (đồ vật); nay dùng làm tân ngữ của 読みます.", L),
    v(19, "てがみ", "手紙", "てがみ", "tegami", "noun", "Lá thư", "手紙を 書きます = viết thư.", L),
    v(20, "しゃしん", "写真", "しゃしん", "shashin", "noun", "Bức ảnh", "写真を 撮ります = chụp ảnh.", L),
    v(21, "おんがく", "音楽", "おんがく", "ongaku", "noun", "Âm nhạc", "音楽を 聞きます = nghe nhạc.", L),
    v(22, "はな", "花", "はな", "hana", "noun", "Hoa", "", L),
    v(23, "こうえん", "公園", "こうえん", "kouen", "noun", "Công viên", "Đã gặp ở exercises N5 trước — nơi chốn hành động.", L),
    v(24, "きっさてん", "喫茶店", "きっさてん", "kissaten", "noun", "Quán cà phê kiểu cổ điển", "Khác カフェ (quán cà phê hiện đại kiểu Tây).", L),
    v(25, "しょくどう", "食堂", "しょくどう", "shokudou", "noun", "Nhà ăn, căng tin", "Đã gặp ở bài 3 (nơi chốn); nay dùng làm nơi hành động で.", L),
    v(26, "だいどころ", "台所", "だいどころ", "daidokoro", "noun", "Nhà bếp", "料理を 作ります + 台所で.", L),
]

KANJI = [
    k(1, "食", "THỰC", 9, ["ショク (shoku)"], ["た(べる)"], "Ăn, thức ăn.",
      [("食べます", "たべます", "Ăn"), ("食堂", "しょくどう", "Nhà ăn"), ("朝食", "ちょうしょく", "Bữa sáng")], L),
    k(2, "飲", "ẨM", 12, ["イン (in)"], ["の(む)"], "Uống.",
      [("飲みます", "のみます", "Uống"), ("飲み物", "のみもの", "Đồ uống"), ("飲食", "いんしょく", "Ăn uống")], L),
    k(3, "見", "KIẾN", 7, ["ケン (ken)"], ["み(る)"], "Nhìn, thấy. Hình con mắt trên đôi chân.",
      [("見ます", "みます", "Xem"), ("見物", "けんぶつ", "Tham quan"), ("意見", "いけん", "Ý kiến")], L),
    k(4, "読", "ĐỘC", 14, ["ドク (doku)"], ["よ(む)"], "Đọc.",
      [("読みます", "よみます", "Đọc"), ("読者", "どくしゃ", "Độc giả"), ("読書", "どくしょ", "Đọc sách")], L),
    k(5, "書", "THƯ", 10, ["ショ (sho)"], ["か(く)"], "Viết; sách, văn bản.",
      [("書きます", "かきます", "Viết"), ("辞書", "じしょ", "Từ điển"), ("図書館", "としょかん", "Thư viện")], L),
    k(6, "買", "MẠI", 12, ["バイ (bai)"], ["か(う)"], "Mua.",
      [("買います", "かいます", "Mua"), ("買い物", "かいもの", "Mua sắm"), ("売買", "ばいばい", "Mua bán")], L),
]

SLIDES = [
    slide(L, 1,
        "1. Tha động từ: N[tân ngữ] + を + V",
        "[Danh từ] + を + Vます",
        "を đánh dấu ĐỐI TƯỢNG chịu tác động trực tiếp của động từ — đọc là お, không phải を(wo) "
        "như chữ viết. Đây là trợ từ RIÊNG cho tha động từ, khác hẳn は (chủ đề) hay が (chủ ngữ).",
        [
            ex(L, 1, 1, [t("t-l6s1-1", "パン"), t("t-l6s1-2", "を", key=True),
                         t("t-l6s1-3", "たべます", "食べます", "たべます", key=True)],
               "Tôi ăn bánh mì."),
            ex(L, 1, 2, [t("t-l6s1-4", "しんぶん", "新聞", "しんぶん"), t("t-l6s1-5", "を", key=True),
                         t("t-l6s1-6", "よみます", "読みます", "よみます", key=True)],
               "Tôi đọc báo."),
            ex(L, 1, 3, [t("t-l6s1-7", "なに", "何", "なに", key=True), t("t-l6s1-8", "を", key=True),
                         t("t-l6s1-9", "かいますか", "買いますか", "かいますか", key=True)],
               "Anh mua gì vậy?"),
        ],
        tips="を luôn đọc お dù viết bằng chữ を — cùng nhóm ngoại lệ đọc với は/へ đã học.",
        culture="会います (gặp) tuy có tân ngữ là người nhưng lại dùng に, không dùng を — đây là ngoại lệ cần nhớ riêng."),

    slide(L, 2,
        "2. Địa điểm xảy ra hành động: N[nơi chốn] + で + V",
        "[Địa điểm] + で + Vます",
        "で ở đây đánh dấu NƠI HÀNH ĐỘNG DIỄN RA — khác で đã học ở bài 5 (phương tiện). "
        "Phân biệt với へ/に (điểm đến của di chuyển): で dùng cho hành động XẢY RA TẠI một chỗ.",
        [
            ex(L, 2, 1, [t("t-l6s2-1", "しょくどう", "食堂", "しょくどう"), t("t-l6s2-2", "で", key=True),
                         t("t-l6s2-3", "ひるごはん", "昼ご飯", "ひるごはん"), t("t-l6s2-4", "を"),
                         t("t-l6s2-5", "たべます", "食べます", "たべます")],
               "Tôi ăn cơm trưa ở căng tin."),
            ex(L, 2, 2, [t("t-l6s2-6", "こうえん", "公園", "こうえん"), t("t-l6s2-7", "で", key=True),
                         t("t-l6s2-8", "しゃしん", "写真", "しゃしん"), t("t-l6s2-9", "を"),
                         t("t-l6s2-10", "とります", "撮ります", "とります")],
               "Tôi chụp ảnh ở công viên."),
            ex(L, 2, 3, [t("t-l6s2-11", "どこ", key=True), t("t-l6s2-12", "で", key=True),
                         t("t-l6s2-13", "あいましょうか", "会いましょうか", "あいましょうか")],
               "Chúng ta gặp nhau ở đâu nhỉ?"),
        ],
        tips="で (nơi hành động) và へ/に (điểm đến) rất dễ lẫn — で trả lời 'làm Ở ĐÂU', へ trả lời 'ĐI ĐÂU'.",
        culture="喫茶店 kiểu Nhật (cổ điển, yên tĩnh, phục vụ cà phê pha phin) khác với カフェ kiểu chuỗi hiện đại như Starbucks."),

    slide(L, 3,
        "3. Lời mời: Vませんか",
        "Vません + か↗   (giọng lên cuối câu, thân thiện hơn ませんか thường)",
        "Thêm か vào thể ません để tạo câu MỜI, không phải câu hỏi phủ định thông thường. "
        "Lịch sự và tự nhiên hơn nhiều so với ra lệnh trực tiếp bằng V.",
        [
            ex(L, 3, 1, [t("t-l6s3-1", "いっしょに", "一緒に", "いっしょに"), t("t-l6s3-2", "えいが", "映画", "えいが"),
                         t("t-l6s3-3", "を"), t("t-l6s3-4", "みませんか", "見ませんか", "みませんか", key=True)],
               "Chúng ta cùng xem phim nhé?"),
            ex(L, 3, 2, [t("t-l6s3-5", "こうえん", "公園", "こうえん"), t("t-l6s3-6", "で"),
                         t("t-l6s3-7", "おんがく", "音楽", "おんがく"), t("t-l6s3-8", "を"),
                         t("t-l6s3-9", "ききませんか", "聞きませんか", "ききませんか", key=True)],
               "Mình ra công viên nghe nhạc không?"),
            ex(L, 3, 3, [t("t-l6s3-10", "コーヒー"), t("t-l6s3-11", "を"),
                         t("t-l6s3-12", "のみませんか", "飲みませんか", "のみませんか", key=True)],
               "Uống cà phê không?"),
        ],
        tips="Đáp lại lời mời: đồng ý nói 「ええ、いいですね」, từ chối nói 「すみません、ちょっと…」 rồi bỏ lửng.",
        culture="Người Nhật hiếm khi từ chối thẳng thừng — câu 「ちょっと…」 bỏ lửng gần như luôn có nghĩa là KHÔNG."),

    slide(L, 4,
        "4. Rủ cùng làm: Vましょう",
        "Vましょう   (đề xuất/rủ, khác ませんか ở chỗ CHỦ ĐỘNG hơn)",
        "ましょう dùng khi người nói đã khá chắc đối phương đồng ý, hoặc chính mình chủ động đề "
        "xuất. ませんか lịch sự, nhường quyền quyết định cho đối phương hơn ましょう.",
        [
            ex(L, 4, 1, [t("t-l6s4-1", "いっしょに", "一緒に", "いっしょに"), t("t-l6s4-2", "たべましょう", "食べましょう", "たべましょう", key=True)],
               "Chúng ta cùng ăn thôi."),
            ex(L, 4, 2, [t("t-l6s4-3", "えき", "駅", "えき"), t("t-l6s4-4", "で"),
                         t("t-l6s4-5", "あいましょう", "会いましょう", "あいましょう", key=True)],
               "Gặp nhau ở ga nhé."),
            ex(L, 4, 3, [t("t-l6s4-6", "ええ"), t("t-l6s4-7", "、"), t("t-l6s4-8", "そうしましょう", key=True)],
               "Ừ, làm vậy đi."),
        ],
        tips="ませんか hỏi ý kiến trước ('bạn có muốn không'), ましょう như đã ngầm hiểu đồng ý ('chúng ta cùng làm nhé').",
        culture="そうしましょう là câu đáp lễ rất tự nhiên khi đồng ý với đề xuất của người khác."),
]

DIALOGUE = [
    line(L, 1, "カリナ", "Sinh viên",
         [t("d-l6-1", "やまださん"), t("d-l6-2", "、"), t("d-l6-3", "いっしょに", "一緒に", "いっしょに"),
          t("d-l6-4", "ひるごはん", "昼ご飯", "ひるごはん"), t("d-l6-5", "を"),
          t("d-l6-6", "たべませんか", "食べませんか", "たべませんか", key=True)],
         "Anh Yamada, cùng ăn trưa không?"),
    line(L, 2, "山田", "Sinh viên",
         [t("d-l6-7", "ええ"), t("d-l6-8", "、"), t("d-l6-9", "いいですね"), t("d-l6-10", "。"),
          t("d-l6-11", "どこ"), t("d-l6-12", "で"), t("d-l6-13", "たべますか", "食べますか", "たべますか")],
         "Ừ, được đó. Ăn ở đâu nhỉ?"),
    line(L, 3, "カリナ", "Sinh viên",
         [t("d-l6-14", "しょくどう", "食堂", "しょくどう", key=True), t("d-l6-15", "で"),
          t("d-l6-16", "たべましょう", "食べましょう", "たべましょう", key=True)],
         "Ăn ở căng tin đi."),
    line(L, 4, "山田", "Sinh viên",
         [t("d-l6-17", "しょくどう", "食堂", "しょくどう"), t("d-l6-18", "で"), t("d-l6-19", "なに", "何", "なに", key=True),
          t("d-l6-20", "を"), t("d-l6-21", "たべますか", "食べますか", "たべますか")],
         "Ở căng tin ăn gì được nhỉ?"),
    line(L, 5, "カリナ", "Sinh viên",
         [t("d-l6-22", "ぎゅうどん", "牛丼", "ぎゅうどん"), t("d-l6-23", "や"), t("d-l6-24", "パン"),
          t("d-l6-25", "が"), t("d-l6-26", "あります", "有ります", "あります")],
         "Có cơm bò và bánh mì."),
    line(L, 6, "山田", "Sinh viên",
         [t("d-l6-27", "じゃ"), t("d-l6-28", "、"), t("d-l6-29", "ぎゅうどん", "牛丼", "ぎゅうどん"),
          t("d-l6-30", "を"), t("d-l6-31", "たべます", "食べます", "たべます")],
         "Vậy thì tôi ăn cơm bò."),
    line(L, 7, "カリナ", "Sinh viên",
         [t("d-l6-32", "たべた", "食べた", "たべた"), t("d-l6-33", "あと"), t("d-l6-34", "、"),
          t("d-l6-35", "こうえん", "公園", "こうえん", key=True), t("d-l6-36", "で"),
          t("d-l6-37", "しゃしん", "写真", "しゃしん", key=True), t("d-l6-38", "を"),
          t("d-l6-39", "とりませんか", "撮りませんか", "とりませんか", key=True)],
         "Ăn xong, ra công viên chụp ảnh không?"),
    line(L, 8, "山田", "Sinh viên",
         [t("d-l6-40", "いいですね"), t("d-l6-41", "。"), t("d-l6-42", "はな", "花", "はな"),
          t("d-l6-43", "が"), t("d-l6-44", "きれい", "綺麗", "きれい"), t("d-l6-45", "ですから")],
         "Được đó. Vì hoa đang đẹp mà."),
    line(L, 9, "カリナ", "Sinh viên",
         [t("d-l6-46", "そのあと"), t("d-l6-47", "、"), t("d-l6-48", "きっさてん", "喫茶店", "きっさてん", key=True),
          t("d-l6-49", "で"), t("d-l6-50", "コーヒー"), t("d-l6-51", "を"),
          t("d-l6-52", "のみましょう", "飲みましょう", "のみましょう", key=True)],
         "Sau đó, mình uống cà phê ở quán nhé."),
    line(L, 10, "山田", "Sinh viên",
         [t("d-l6-53", "ええ"), t("d-l6-54", "、"), t("d-l6-55", "そうしましょう", key=True)],
         "Ừ, làm vậy đi."),
]

EXERCISES = [
    q(L, 1, "Trợ từ を trong 「パンを 食べます」 đọc là:",
      ["お", "を", "うぉ", "either"], 0,
      "を là trợ từ đánh dấu tân ngữ, luôn đọc お bất kể chữ viết. Cùng nhóm ngoại lệ với は/へ.",
      "Đây là quy tắc đọc, không phải viết."),
    q(L, 2, "「会います」 khác các động từ を khác ở chỗ:",
      ["Dùng に để đánh dấu người gặp, không dùng を",
       "Không cần tân ngữ", "Chỉ dùng cho động vật", "Luôn cần で trước nó"], 0,
      "会います là ngoại lệ quan trọng: 友達に 会います (KHÔNG nói 友達を 会います).",
      "So sánh với 食べます, 飲みます, 読みます."),
    q(L, 3, "で trong 「食堂で 食べます」 và で trong 「電車で 行きます」 (bài 5) khác nhau ở:",
      ["Một chỉ NƠI hành động, một chỉ PHƯƠNG TIỆN", "Hoàn toàn giống nhau",
       "Một dùng cho người, một dùng cho vật", "Chỉ khác về ngữ điệu"], 0,
      "で đa chức năng: đánh dấu nơi hành động xảy ra (bài 6) hoặc phương tiện/công cụ (bài 5) tùy ngữ cảnh.",
      "Xem lại bài 5 để so sánh."),
    q(L, 4, "「一緒に映画を見ませんか」 dùng để làm gì?",
      ["Mời ai đó cùng xem phim", "Ra lệnh xem phim",
       "Hỏi đã xem phim chưa", "Cấm xem phim"], 0,
      "Vませんか là cấu trúc MỜI lịch sự, không phải câu hỏi phủ định hay cấm đoán.",
      "Đây là câu rủ rê."),
    q(L, 5, "Khác biệt chính giữa ませんか và ましょう là:",
      ["ませんか nhường quyết định cho đối phương, ましょう chủ động hơn",
       "ませんか là mệnh lệnh", "ましょう là câu hỏi", "Không có khác biệt nào"], 0,
      "ませんか lịch sự, hỏi ý trước; ましょう mang tính chủ động đề xuất, gần như đã ngầm đồng ý.",
      "Xem thứ tự dùng trong hội thoại mẫu."),
    q(L, 6, "Từ chối lời mời một cách lịch sự kiểu Nhật, câu thường dùng là:",
      ["すみません、ちょっと…", "いいえ、絶対だめです", "だめ！", "行きません！"], 0,
      "Người Nhật thường từ chối gián tiếp bằng cách bỏ lửng câu — nói thẳng 'không' bị coi là thô lỗ.",
      "Câu này không nói hết ý."),
    q(L, 7, "「何を 買いますか」 — từ để hỏi 何 ở đây đóng vai trò gì trong câu?",
      ["Tân ngữ của 買います", "Chủ ngữ", "Trạng ngữ chỉ nơi chốn", "Trạng ngữ chỉ thời gian"], 0,
      "何 đứng trước を nên đóng vai trò tân ngữ — hỏi CÁI GÌ bị mua.",
      "Nhìn trợ từ theo sau 何."),
    q(L, 8, "撮ります (chụp ảnh) khác とります (取ります, lấy) ở:",
      ["Cùng đọc とります nhưng nghĩa và chữ Hán khác nhau",
       "Cách đọc khác nhau hoàn toàn", "Không có gì khác nhau",
       "撮ります chỉ dùng cho video"], 0,
      "Đây là cặp đồng âm dị nghĩa (同音異義語) — cùng đọc とります nhưng viết Hán khác, nghĩa khác.",
      "Để ý phần giải thích ở mục từ vựng."),
    q(L, 9, "Muốn rủ 'nghe nhạc ở công viên', câu nào ĐÚNG?",
      ["公園で 音楽を 聞きませんか", "公園に 音楽を 聞きませんか",
       "公園を 音楽で 聞きませんか", "音楽で 公園を 聞きませんか"], 0,
      "公園で (nơi hành động) + 音楽を (tân ngữ của 聞きます) là trật tự trợ từ đúng.",
      "Phân biệt vai trò của で và を."),
    q(L, 10, "喫茶店 khác カフェ ở điểm nào?",
      ["喫茶店 mang phong cách cổ điển, yên tĩnh hơn カフェ hiện đại kiểu chuỗi",
       "喫茶店 chỉ bán trà, カフェ chỉ bán cà phê",
       "Không khác gì, chỉ là hai cách viết", "カフェ đắt hơn nhiều"], 0,
      "喫茶店 là quán kiểu Nhật truyền thống; カフェ là từ mượn, thường chỉ quán theo phong cách phương Tây/chuỗi hiện đại.",
      "Đây là khác biệt văn hóa, không phải ngữ pháp."),
]

LESSON = lesson(
    L,
    "Bài 6: Tha động từ (N を V / N [địa điểm] で V / ませんか)",
    "Đánh dấu tân ngữ bằng を, nơi hành động diễn ra bằng で (phân biệt với で phương tiện ở bài 5), "
    "cách mời lịch sự bằng Vませんか, và cách rủ chủ động bằng Vましょう.",
    VOCAB, KANJI, SLIDES, DIALOGUE, EXERCISES,
)

if __name__ == "__main__":
    pool.mark_used([w["word"] for w in VOCAB if not w["word"].startswith("〜")], lesson=L)
    merge([LESSON])
